const express = require('express');
const supabase = require('../config/supabase');
const router = express.Router();

// Get all reports with filtering and pagination
router.get('/', async (req, res) => {
  try {
    const { 
      study_id, 
      report_type, 
      status, 
      generated_by,
      page = 1, 
      limit = 25,
      search 
    } = req.query;

    let query = supabase
      .from('edc_reports')
      .select(`
        *,
        edc_studies!inner(protocol_number, title),
        generated_by_user:edc_users!generated_by(first_name, last_name)
      `);

    // Apply filters
    if (study_id) query = query.eq('study_id', study_id);
    if (report_type) query = query.eq('report_type', report_type);
    if (status) query = query.eq('status', status);
    if (generated_by) query = query.eq('generated_by', generated_by);
    if (search) {
      query = query.or(`report_name.ilike.%${search}%, description.ilike.%${search}%`);
    }

    // Apply pagination
    const offset = (page - 1) * limit;
    query = query.range(offset, offset + limit - 1);

    const { data: reports, error } = await query
      .order('generated_at', { ascending: false });

    if (error) throw error;

    // Get total count for pagination
    const { count: totalCount } = await supabase
      .from('edc_reports')
      .select('*', { count: 'exact', head: true });

    res.json({
      status: 'success',
      data: reports || [],
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total: totalCount,
        pages: Math.ceil(totalCount / limit)
      }
    });
  } catch (error) {
    console.error('Reports fetch error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to fetch reports',
      error: error.message
    });
  }
});

// Get report by ID
router.get('/:id', async (req, res) => {
  try {
    const { id } = req.params;

    const { data: report, error } = await supabase
      .from('edc_reports')
      .select(`
        *,
        edc_studies!inner(protocol_number, title),
        generated_by_user:edc_users!generated_by(first_name, last_name, email)
      `)
      .eq('id', id)
      .single();

    if (error) throw error;
    if (!report) {
      return res.status(404).json({
        status: 'error',
        message: 'Report not found'
      });
    }

    res.json({
      status: 'success',
      data: report
    });
  } catch (error) {
    console.error('Report fetch error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to fetch report',
      error: error.message
    });
  }
});

// Generate enrollment report
router.post('/enrollment', async (req, res) => {
  try {
    const { study_id, date_from, date_to, generated_by } = req.body;

    if (!study_id || !generated_by) {
      return res.status(400).json({
        status: 'error',
        message: 'Study ID and generated by user are required'
      });
    }

    // Get enrollment data
    let enrollmentQuery = supabase
      .from('edc_subjects')
      .select(`
        *,
        edc_sites!inner(name, site_number),
        edc_studies!inner(protocol_number, title)
      `)
      .eq('study_id', study_id);

    if (date_from) enrollmentQuery = enrollmentQuery.gte('enrollment_date', date_from);
    if (date_to) enrollmentQuery = enrollmentQuery.lte('enrollment_date', date_to);

    const { data: subjects, error: subjectsError } = await enrollmentQuery
      .order('enrollment_date');

    if (subjectsError) throw subjectsError;

    // Calculate enrollment statistics
    const totalEnrolled = subjects.length;
    const activeSubjects = subjects.filter(s => s.status === 'ACTIVE').length;
    const completedSubjects = subjects.filter(s => s.status === 'COMPLETED').length;
    const withdrawnSubjects = subjects.filter(s => s.status === 'WITHDRAWN').length;

    // Enrollment by site
    const enrollmentBySite = subjects.reduce((acc, subject) => {
      const siteName = subject.edc_sites.name;
      if (!acc[siteName]) {
        acc[siteName] = { enrolled: 0, active: 0, completed: 0, withdrawn: 0 };
      }
      acc[siteName].enrolled++;
      acc[siteName][subject.status.toLowerCase()]++;
      return acc;
    }, {});

    // Enrollment by month
    const enrollmentByMonth = subjects.reduce((acc, subject) => {
      if (subject.enrollment_date) {
        const month = subject.enrollment_date.substring(0, 7);
        acc[month] = (acc[month] || 0) + 1;
      }
      return acc;
    }, {});

    const reportData = {
      study_info: subjects[0]?.edc_studies || {},
      summary: {
        total_enrolled: totalEnrolled,
        active_subjects: activeSubjects,
        completed_subjects: completedSubjects,
        withdrawn_subjects: withdrawnSubjects,
        completion_rate: totalEnrolled > 0 ? ((completedSubjects / totalEnrolled) * 100).toFixed(2) : '0.00',
        withdrawal_rate: totalEnrolled > 0 ? ((withdrawnSubjects / totalEnrolled) * 100).toFixed(2) : '0.00'
      },
      enrollment_by_site: enrollmentBySite,
      enrollment_by_month: enrollmentByMonth,
      subjects: subjects
    };

    // Create report record
    const { data: report, error: reportError } = await supabase
      .from('edc_reports')
      .insert([{
        study_id,
        report_type: 'ENROLLMENT',
        report_name: `Enrollment Report - ${subjects[0]?.edc_studies?.protocol_number}`,
        description: `Enrollment report generated for study ${subjects[0]?.edc_studies?.protocol_number}`,
        parameters: { date_from, date_to },
        report_data: reportData,
        generated_by,
        status: 'COMPLETED'
      }])
      .select(`
        *,
        edc_studies!inner(protocol_number, title)
      `)
      .single();

    if (reportError) throw reportError;

    res.status(201).json({
      status: 'success',
      message: 'Enrollment report generated successfully',
      data: report
    });
  } catch (error) {
    console.error('Enrollment report generation error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to generate enrollment report',
      error: error.message
    });
  }
});

// Generate query report
router.post('/queries', async (req, res) => {
  try {
    const { study_id, site_id, severity, status_filter, generated_by } = req.body;

    if (!study_id || !generated_by) {
      return res.status(400).json({
        status: 'error',
        message: 'Study ID and generated by user are required'
      });
    }

    // Get queries data
    let queriesQuery = supabase
      .from('edc_queries_with_age')
      .select(`
        *,
        edc_studies!inner(protocol_number, title),
        edc_sites!inner(name, site_number),
        edc_subjects!inner(subject_number, initials),
        raised_by_user:edc_users!raised_by(first_name, last_name)
      `)
      .eq('study_id', study_id);

    if (site_id) queriesQuery = queriesQuery.eq('site_id', site_id);
    if (severity) queriesQuery = queriesQuery.eq('severity', severity);
    if (status_filter) queriesQuery = queriesQuery.eq('status', status_filter);

    const { data: queries, error: queriesError } = await queriesQuery
      .order('raised_date', { ascending: false });

    if (queriesError) throw queriesError;

    // Calculate query statistics
    const totalQueries = queries.length;
    const openQueries = queries.filter(q => q.status === 'OPEN').length;
    const answeredQueries = queries.filter(q => q.status === 'ANSWERED').length;
    const closedQueries = queries.filter(q => q.status === 'CLOSED').length;

    // Queries by severity
    const queriesBySeverity = queries.reduce((acc, query) => {
      acc[query.severity] = (acc[query.severity] || 0) + 1;
      return acc;
    }, {});

    // Queries by site
    const queriesBySite = queries.reduce((acc, query) => {
      const siteName = query.edc_sites?.name || 'Unknown Site';
      if (!acc[siteName]) {
        acc[siteName] = { total: 0, open: 0, answered: 0, closed: 0 };
      }
      acc[siteName].total++;
      acc[siteName][query.status.toLowerCase()]++;
      return acc;
    }, {});

    // Average age of open queries
    const openQueriesAges = queries.filter(q => q.status === 'OPEN').map(q => q.age_in_days);
    const avgOpenQueryAge = openQueriesAges.length > 0 
      ? (openQueriesAges.reduce((sum, age) => sum + age, 0) / openQueriesAges.length).toFixed(1)
      : '0.0';

    const reportData = {
      study_info: queries[0]?.edc_studies || {},
      summary: {
        total_queries: totalQueries,
        open_queries: openQueries,
        answered_queries: answeredQueries,
        closed_queries: closedQueries,
        resolution_rate: totalQueries > 0 ? (((answeredQueries + closedQueries) / totalQueries) * 100).toFixed(2) : '0.00',
        avg_open_query_age: avgOpenQueryAge
      },
      queries_by_severity: queriesBySeverity,
      queries_by_site: queriesBySite,
      queries: queries
    };

    // Create report record
    const { data: report, error: reportError } = await supabase
      .from('edc_reports')
      .insert([{
        study_id,
        report_type: 'QUERIES',
        report_name: `Query Report - ${queries[0]?.edc_studies?.protocol_number}`,
        description: `Query analysis report generated for study ${queries[0]?.edc_studies?.protocol_number}`,
        parameters: { site_id, severity, status_filter },
        report_data: reportData,
        generated_by,
        status: 'COMPLETED'
      }])
      .select(`
        *,
        edc_studies!inner(protocol_number, title)
      `)
      .single();

    if (reportError) throw reportError;

    res.status(201).json({
      status: 'success',
      message: 'Query report generated successfully',
      data: report
    });
  } catch (error) {
    console.error('Query report generation error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to generate query report',
      error: error.message
    });
  }
});

// Generate data completion report
router.post('/data-completion', async (req, res) => {
  try {
    const { study_id, site_id, generated_by } = req.body;

    if (!study_id || !generated_by) {
      return res.status(400).json({
        status: 'error',
        message: 'Study ID and generated by user are required'
      });
    }

    // Get form data completion
    let formsQuery = supabase
      .from('edc_form_data')
      .select(`
        *,
        edc_studies!inner(protocol_number, title),
        edc_sites!inner(name, site_number),
        edc_subjects!inner(subject_number, initials),
        edc_form_templates!inner(name, category),
        edc_visits(visit_name, visit_number)
      `)
      .eq('study_id', study_id);

    if (site_id) formsQuery = formsQuery.eq('site_id', site_id);

    const { data: forms, error: formsError } = await formsQuery;
    if (formsError) throw formsError;

    // Get visits for completion calculation
    let visitsQuery = supabase
      .from('edc_visits')
      .select(`
        *,
        edc_subjects!inner(subject_number),
        edc_sites!inner(name, site_number)
      `)
      .eq('study_id', study_id);

    if (site_id) visitsQuery = visitsQuery.eq('edc_subjects.site_id', site_id);

    const { data: visits, error: visitsError } = await visitsQuery;
    if (visitsError) throw visitsError;

    // Calculate completion statistics
    const totalForms = forms.length;
    const completedForms = forms.filter(f => f.status === 'COMPLETED').length;
    const draftForms = forms.filter(f => f.status === 'DRAFT').length;
    const lockedForms = forms.filter(f => f.status === 'LOCKED').length;

    const totalVisits = visits.length;
    const completedVisits = visits.filter(v => v.status === 'COMPLETED').length;

    // Completion by site
    const completionBySite = forms.reduce((acc, form) => {
      const siteName = form.edc_sites?.name || 'Unknown Site';
      if (!acc[siteName]) {
        acc[siteName] = { total: 0, completed: 0, draft: 0, locked: 0, percentage: 0 };
      }
      acc[siteName].total++;
      acc[siteName][form.status.toLowerCase()]++;
      acc[siteName].percentage = acc[siteName].total > 0 
        ? ((acc[siteName].completed / acc[siteName].total) * 100).toFixed(2)
        : '0.00';
      return acc;
    }, {});

    // Completion by form type
    const completionByFormType = forms.reduce((acc, form) => {
      const formName = form.edc_form_templates?.name || 'Unknown Form';
      if (!acc[formName]) {
        acc[formName] = { total: 0, completed: 0, percentage: 0 };
      }
      acc[formName].total++;
      if (form.status === 'COMPLETED') acc[formName].completed++;
      acc[formName].percentage = acc[formName].total > 0 
        ? ((acc[formName].completed / acc[formName].total) * 100).toFixed(2)
        : '0.00';
      return acc;
    }, {});

    const reportData = {
      study_info: forms[0]?.edc_studies || {},
      summary: {
        total_forms: totalForms,
        completed_forms: completedForms,
        draft_forms: draftForms,
        locked_forms: lockedForms,
        form_completion_rate: totalForms > 0 ? ((completedForms / totalForms) * 100).toFixed(2) : '0.00',
        total_visits: totalVisits,
        completed_visits: completedVisits,
        visit_completion_rate: totalVisits > 0 ? ((completedVisits / totalVisits) * 100).toFixed(2) : '0.00'
      },
      completion_by_site: completionBySite,
      completion_by_form_type: completionByFormType,
      forms_summary: forms,
      visits_summary: visits
    };

    // Create report record
    const { data: report, error: reportError } = await supabase
      .from('edc_reports')
      .insert([{
        study_id,
        report_type: 'DATA_COMPLETION',
        report_name: `Data Completion Report - ${forms[0]?.edc_studies?.protocol_number}`,
        description: `Data completion analysis report for study ${forms[0]?.edc_studies?.protocol_number}`,
        parameters: { site_id },
        report_data: reportData,
        generated_by,
        status: 'COMPLETED'
      }])
      .select(`
        *,
        edc_studies!inner(protocol_number, title)
      `)
      .single();

    if (reportError) throw reportError;

    res.status(201).json({
      status: 'success',
      message: 'Data completion report generated successfully',
      data: report
    });
  } catch (error) {
    console.error('Data completion report generation error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to generate data completion report',
      error: error.message
    });
  }
});

// Generate audit trail report
router.post('/audit-trail', async (req, res) => {
  try {
    const { study_id, date_from, date_to, user_id, action_type, generated_by } = req.body;

    if (!study_id || !generated_by) {
      return res.status(400).json({
        status: 'error',
        message: 'Study ID and generated by user are required'
      });
    }

    // Get audit trail data
    let auditQuery = supabase
      .from('edc_audit_trail')
      .select(`
        *,
        edc_studies!inner(protocol_number, title),
        edc_users!user_id(first_name, last_name, username)
      `)
      .eq('study_id', study_id);

    if (date_from) auditQuery = auditQuery.gte('created_at', date_from);
    if (date_to) auditQuery = auditQuery.lte('created_at', date_to);
    if (user_id) auditQuery = auditQuery.eq('user_id', user_id);
    if (action_type) auditQuery = auditQuery.eq('action_type', action_type);

    const { data: auditEntries, error: auditError } = await auditQuery
      .order('created_at', { ascending: false });

    if (auditError) throw auditError;

    // Calculate audit statistics
    const totalEntries = auditEntries.length;
    const uniqueUsers = new Set(auditEntries.map(e => e.user_id)).size;

    // Actions by type
    const actionsByType = auditEntries.reduce((acc, entry) => {
      acc[entry.action_type] = (acc[entry.action_type] || 0) + 1;
      return acc;
    }, {});

    // Actions by user
    const actionsByUser = auditEntries.reduce((acc, entry) => {
      const userName = `${entry.edc_users?.first_name} ${entry.edc_users?.last_name}`;
      acc[userName] = (acc[userName] || 0) + 1;
      return acc;
    }, {});

    // Actions by day
    const actionsByDay = auditEntries.reduce((acc, entry) => {
      const day = entry.created_at.split('T')[0];
      acc[day] = (acc[day] || 0) + 1;
      return acc;
    }, {});

    const reportData = {
      study_info: auditEntries[0]?.edc_studies || {},
      summary: {
        total_entries: totalEntries,
        unique_users: uniqueUsers,
        date_range: {
          from: date_from || 'Beginning',
          to: date_to || 'Present'
        }
      },
      actions_by_type: actionsByType,
      actions_by_user: actionsByUser,
      actions_by_day: actionsByDay,
      audit_entries: auditEntries
    };

    // Create report record
    const { data: report, error: reportError } = await supabase
      .from('edc_reports')
      .insert([{
        study_id,
        report_type: 'AUDIT_TRAIL',
        report_name: `Audit Trail Report - ${auditEntries[0]?.edc_studies?.protocol_number}`,
        description: `Audit trail compliance report for study ${auditEntries[0]?.edc_studies?.protocol_number}`,
        parameters: { date_from, date_to, user_id, action_type },
        report_data: reportData,
        generated_by,
        status: 'COMPLETED'
      }])
      .select(`
        *,
        edc_studies!inner(protocol_number, title)
      `)
      .single();

    if (reportError) throw reportError;

    res.status(201).json({
      status: 'success',
      message: 'Audit trail report generated successfully',
      data: report
    });
  } catch (error) {
    console.error('Audit trail report generation error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to generate audit trail report',
      error: error.message
    });
  }
});

// Delete report
router.delete('/:id', async (req, res) => {
  try {
    const { id } = req.params;

    const { data: report, error } = await supabase
      .from('edc_reports')
      .delete()
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    if (!report) {
      return res.status(404).json({
        status: 'error',
        message: 'Report not found'
      });
    }

    res.json({
      status: 'success',
      message: 'Report deleted successfully'
    });
  } catch (error) {
    console.error('Report deletion error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to delete report',
      error: error.message
    });
  }
});

// Get reports by study
router.get('/study/:study_id', async (req, res) => {
  try {
    const { study_id } = req.params;
    const { report_type, status } = req.query;

    let query = supabase
      .from('edc_reports')
      .select(`
        *,
        generated_by_user:edc_users!generated_by(first_name, last_name)
      `)
      .eq('study_id', study_id);

    if (report_type) query = query.eq('report_type', report_type);
    if (status) query = query.eq('status', status);

    const { data: reports, error } = await query
      .order('generated_at', { ascending: false });

    if (error) throw error;

    res.json({
      status: 'success',
      data: reports || []
    });
  } catch (error) {
    console.error('Study reports error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to fetch study reports',
      error: error.message
    });
  }
});

module.exports = router;
