# Databricks notebook source
# MAGIC %md
# MAGIC **Date:** 2025-08-23
# MAGIC """
# MAGIC MODIFICATIONS:
# MAGIC                                                                                                                                                                                                                 DATASTAGE               CODE                           DATE
# MAGIC DEVELOPER             DATE                PROJECT                     DESCRIPTION                                                                                      ENVIRONMENT          REVIEWER                 REVIEW
# MAGIC -----------------------------    ----------------------     ------------------------------        -----------------------------------------------------------------------------------------------------------  ------------------------------    ------------------------------       --------------------
# MAGIC Archana Palivela     09/15/2013          5114                             Original Programming                                                                             IntegrateWrhsDevl       Jag Yelavarthi            2013-12-01

# MAGIC Job Name: IdsDmClmDmClmLoad
# MAGIC Read Load File created in the IdsDmClmDmClmExtr
# MAGIC  Job
# MAGIC Copy Stage for buffer
# MAGIC Update then Insert the CLM_DM_CLMData.
# MAGIC Load rejects are redirected into a Reject file
# MAGIC """
# COMMAND ----------
# MAGIC %run ../../../../../Routine_Functions
# COMMAND ----------
# Using the below functions as UDF(inherited from Routine_Functions notebook) instead of pyspark function
# 1) current_timestamp, current_date - To convert to CST timezone.
# 2) trim - To mimic Datastage behavior in trimming spaces within the string (Not leading or trailing spaces)
# COMMAND ----------
import pyspark.sql.functions as F
from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    TimestampType,
    DecimalType,
    IntegerType
)
# COMMAND ----------
# MAGIC %run ../../../../../Utility_Integrate
# COMMAND ----------


# Retrieve parameters
ClmMartOwner = get_widget_value('ClmMartOwner','')
clmmart_secret_name = get_widget_value('clmmart_secret_name','')
ClmMartArraySize = get_widget_value('ClmMartArraySize','')
ClmMartRecordCount = get_widget_value('ClmMartRecordCount','')

# Define Schema for seq_CLM_DM_CLMcsv_load
schema_seq_CLM_DM_CLMcsv_load = StructType([
    StructField("SRC_SYS_CD", StringType(), False),
    StructField("CLM_ID", StringType(), False),
    StructField("CLM_CAP_CD", StringType(), False),
    StructField("CLM_FINL_DISP_CD", StringType(), False),
    StructField("CLM_INTER_PLN_PGM_CD", StringType(), False),
    StructField("CLM_PAYE_CD", StringType(), False),
    StructField("CLM_STTUS_CD", StringType(), False),
    StructField("CLM_SUBTYP_CD", StringType(), False),
    StructField("CLM_TRNSMSN_STTUS_CD", StringType(), False),
    StructField("CLM_TYP_CD", StringType(), False),
    StructField("FCLTY_CLM_SRC_SYS_GNRT_DRG_CD", StringType(), False),
    StructField("NDC", StringType(), False),
    StructField("CMPL_MBRSH_IN", StringType(), False),
    StructField("CLM_PD_DT", TimestampType(), True),
    StructField("CLM_RCVD_DT", TimestampType(), True),
    StructField("CLM_REMIT_HIST_CHK_PD_DT", TimestampType(), True),
    StructField("CLM_SVC_STRT_DT", TimestampType(), True),
    StructField("CLM_SVC_END_DT", TimestampType(), True),
    StructField("CLM_STTUS_DT", TimestampType(), True),
    StructField("CLM_ACTL_PD_AMT", DecimalType(38,10), False),
    StructField("CLM_ALW_AMT", DecimalType(38,10), False),
    StructField("CLM_CHRG_AMT", DecimalType(38,10), False),
    StructField("CLM_COB_PD_AMT", DecimalType(38,10), False),
    StructField("CLM_COINS_AMT", DecimalType(38,10), False),
    StructField("CLM_CNSD_CHRG_AMT", DecimalType(38,10), False),
    StructField("CLM_COPAY_AMT", DecimalType(38,10), False),
    StructField("CLM_DEDCT_AMT", DecimalType(38,10), False),
    StructField("CLM_DSALW_AMT", DecimalType(38,10), False),
    StructField("CLM_PAYBL_AMT", DecimalType(38,10), False),
    StructField("CLM_REMIT_HIST_CHK_NET_PAY_AMT", DecimalType(38,10), False),
    StructField("CLM_REMIT_HIST_ER_COPAY_AMT", DecimalType(38,10), False),
    StructField("CLM_REMIT_HIST_INTRST_AMT", DecimalType(38,10), False),
    StructField("CLM_REMIT_HIST_NO_RESP_AMT", DecimalType(38,10), False),
    StructField("CLM_REMIT_HIST_PATN_RESP_AMT", DecimalType(38,10), False),
    StructField("CLM_REMIT_HIST_PROV_WRTOFF_AMT", DecimalType(38,10), False),
    StructField("DRUG_CLM_MBR_DIFF_PD_AMT", DecimalType(38,10), False),
    StructField("CLM_REMIT_HIST_CHK_NO", IntegerType(), False),
    StructField("DRUG_CLM_RX_ALW_QTY", DecimalType(38,10), False),
    StructField("DRUG_CLM_RX_SUBMT_QTY", DecimalType(38,10), False),
    StructField("ALPHA_PFX_CD", StringType(), False),
    StructField("CLM_ADJ_FROM_CLM_ID", StringType(), False),
    StructField("CLM_ADJ_TO_CLM_ID", StringType(), False),
    StructField("CLM_PATN_ACCT_NO", StringType(), True),
    StructField("CLM_RFRNG_PROV_TX", StringType(), True),
    StructField("CLM_REMIT_HIST_CHK_PAYE_NM", StringType(), True),
    StructField("CLM_REMIT_HIST_CHK_PAY_REF_ID", StringType(), False),
    StructField("CLM_STTUS_CD_NM", StringType(), False),
    StructField("CLM_SUB_ID", StringType(), False),
    StructField("CMN_PRCT_PRSCRB_CMN_PRCT_ID", StringType(), False),
    StructField("CMN_PRCT_PRSCRB_CMN_PRCT_NM", StringType(), True),
    StructField("CMN_PRCT_SVC_CMN_PRCT_ID", StringType(), False),
    StructField("DRUG_CLM_RX_NO", StringType(), True),
    StructField("GRP_UNIQ_KEY", IntegerType(), False),
    StructField("MBR_UNIQ_KEY", IntegerType(), False),
    StructField("MBR_FIRST_NM", StringType(), True),
    StructField("MBR_MIDINIT", StringType(), True),
    StructField("MBR_LAST_NM", StringType(), True),
    StructField("MBR_SUB_FIRST_NM", StringType(), False),
    StructField("MBR_SUB_MIDINIT", StringType(), False),
    StructField("MBR_SUB_LAST_NM", StringType(), False),
    StructField("NDC_DRUG_LABEL_NM", StringType(), False),
    StructField("PROV_ADDR_PD_REMIT_ADDR_LN_1", StringType(), True),
    StructField("PROV_ADDR_PD_REMIT_ADDR_LN_2", StringType(), False),
    StructField("PROV_ADDR_PD_REMIT_ADDR__LN_3", StringType(), True),
    StructField("PROV_ADDR_PD_REMIT_CITY_NM", StringType(), True),
    StructField("PROV_ADDR_PD_REMIT_ST_CD", StringType(), False),
    StructField("PROV_ADDR_PD_REMIT_POSTAL_CD", StringType(), True),
    StructField("PROV_PD_PROV_ID", StringType(), False),
    StructField("PROV_PD_PROV_NM", StringType(), False),
    StructField("PROV_PCP_PROV_ID", StringType(), False),
    StructField("PROV_PCP_PROV_NM", StringType(), False),
    StructField("PROV_REL_GRP_PROV_ID", StringType(), False),
    StructField("PROV_REL_IPA_PROV_ID", StringType(), False),
    StructField("PROV_SVC_PROV_ID", StringType(), False),
    StructField("PROV_SVC_PROV_NM", StringType(), True),
    StructField("SUB_UNIQ_KEY", IntegerType(), False),
    StructField("SUB_ADDR_LN_1", StringType(), True),
    StructField("SUB_ADDR_LN_2", StringType(), True),
    StructField("SUB_ADDR_CITY_NM", StringType(), True),
    StructField("SUB_ADDR_ST_CD", StringType(), False),
    StructField("SUB_ADDR_POSTAL_CD", StringType(), True),
    StructField("CLM_NTWK_STTUS_CD", StringType(), True),
    StructField("CLM_NTWK_STTUS_NM", StringType(), False),
    StructField("CLM_REMIT_HIST_PAYMT_METH_CD", StringType(), False),
    StructField("CLM_STTUS_CHG_RSN_CD", StringType(), True),
    StructField("CLM_STTUS_CHG_RSN_NM", StringType(), False),
    StructField("FCLTY_CLM_ADMS_TYP_CD", StringType(), True),
    StructField("FCLTY_CLM_ADMS_TYP_NM", StringType(), False),
    StructField("FCLTY_CLM_ADMS_SRC_CD", StringType(), True),
    StructField("FCLTY_CLM_ADMS_SRC_NM", StringType(), False),
    StructField("FCLTY_CLM_BILL_CLS_CD", StringType(), True),
    StructField("FCLTY_CLM_BILL_CLS_NM", StringType(), False),
    StructField("FCLTY_CLM_BILL_FREQ_CD", StringType(), True),
    StructField("FCLTY_CLM_BILL_FREQ_NM", StringType(), False),
    StructField("FCLTY_CLM_BILL_TYP_CD", StringType(), True),
    StructField("FCLTY_CLM_BILL_TYP_NM", StringType(), False),
    StructField("FCLTY_CLM_DSCHG_STTUS_CD", StringType(), True),
    StructField("FCLTY_CLM_DSCHG_STTUS_NM", StringType(), False),
    StructField("MBR_GNDR_CD", StringType(), False),
    StructField("MBR_GNDR_NM", StringType(), False),
    StructField("CLM_HOST_IN", StringType(), False),
    StructField("CLM_PRCS_DT", TimestampType(), True),
    StructField("DM_LAST_UPDT_DT", TimestampType(), False),
    StructField("FCLTY_CLM_ADMS_DT", TimestampType(), True),
    StructField("FCLTY_CLM_DSCHG_DT", TimestampType(), True),
    StructField("MBR_BRTH_DT", TimestampType(), True),
    StructField("CLM_AUTH_NO", StringType(), False),
    StructField("CLS_ID", StringType(), False),
    StructField("CLS_DESC", StringType(), True),
    StructField("CLS_PLN_ID", StringType(), False),
    StructField("CLS_PLN_DESC", StringType(), True),
    StructField("FCLTY_CLM_ADM_PHYS_PROV_ID", StringType(), False),
    StructField("GNRT_DRG_CD", StringType(), False),
    StructField("GRP_ID", StringType(), False),
    StructField("MBR_RELSHP_CD", StringType(), False),
    StructField("MBR_SFX_NO", StringType(), True),
    StructField("NTWK_ID", StringType(), False),
    StructField("NTWK_NM", StringType(), True),
    StructField("PROD_ID", StringType(), False),
    StructField("PROV_AGMNT_ID", StringType(), False),
    StructField("SUBMT_DRG_CD", StringType(), False),
    StructField("SUB_ID", StringType(), False),
    StructField("LAST_UPDT_RUN_CYC_NO", IntegerType(), False),
    StructField("PCA_CLM_CHK_PAYE_TYP_CD", StringType(), True),
    StructField("PCA_CLM_CHK_PAYE_TYP_NM", StringType(), True),
    StructField("PCA_CLM_CHK_PAYMT_METH_CD", StringType(), True),
    StructField("PCA_CLM_CHK_PAYMT_METH_NM", StringType(), True),
    StructField("PCA_TYP_NM", StringType(), True),
    StructField("CLM_HOME_IN", StringType(), True),
    StructField("PCA_CLM_CHK_PD_DT", TimestampType(), True),
    StructField("CLM_PCA_TOT_CNSD_AMT", DecimalType(38,10), True),
    StructField("CLM_PCA_TOT_PD_AMT", DecimalType(38,10), True),
    StructField("CLM_PCA_SUB_TOT_PCA_AVLBL_AMT", DecimalType(38,10), True),
    StructField("CLM_PCA_SUB_TOT_PCA_PDTODT_AMT", DecimalType(38,10), True),
    StructField("PCA_CLM_CHK_NET_PAYMT_AMT", DecimalType(38,10), True),
    StructField("PCA_CLM_CHK_NO", IntegerType(), True),
    StructField("PCA_CLM_CHK_SEQ_NO", IntegerType(), True),
    StructField("CLM_EXTRNL_PROV_NM", StringType(), True),
    StructField("CLM_EXTRNL_REF_PCA_EXTRNL_ID", StringType(), True),
    StructField("PCA_CLM_CHK_PAYE_NM", StringType(), True),
    StructField("PCA_CLM_CHK_PAYMT_REF_ID", StringType(), True),
    StructField("REL_PCA_SRC_SYS_CD", StringType(), False),
    StructField("REL_PCA_CLM_ID", StringType(), True),
    StructField("REL_BASE_SRC_SYS_CD", StringType(), True),
    StructField("REL_BASE_CLM_ID", StringType(), True),
    StructField("PCA_TYP_CD", StringType(), True),
    StructField("CLM_SUB_BCBS_PLN_CD", StringType(), True),
    StructField("ITS_CLM_SCCF_NO", StringType(), True),
    StructField("CLM_REMIT_HIST_ALT_CHRG_IN", StringType(), True),
    StructField("ALT_CHRG_PROV_WRTOFF_AMT", DecimalType(38,10), True)
])

# Read seq_CLM_DM_CLMcsv_load
df_seq_CLM_DM_CLMcsv_load = (
    spark.read
    .option("delimiter", ",")
    .option("quote", "^")
    .option("header", "false")
    .option("nullValue", None)
    .schema(schema_seq_CLM_DM_CLMcsv_load)
    .csv(f"{adls_path}/load/CLM_DM_CLM.dat")
)

# cpy_forBuffer (just pass-through with possible repartition)
df_cpy_forBuffer = df_seq_CLM_DM_CLMcsv_load.repartition("SRC_SYS_CD","CLM_ID")

# Select columns in the order defined by output pins for Odbc_CLM_DM_CLMout
df_Odbc_CLM_DM_CLMout_input = df_cpy_forBuffer.select(
    "SRC_SYS_CD",
    "CLM_ID",
    "CLM_CAP_CD",
    "CLM_FINL_DISP_CD",
    "CLM_INTER_PLN_PGM_CD",
    "CLM_PAYE_CD",
    "CLM_STTUS_CD",
    "CLM_SUBTYP_CD",
    "CLM_TRNSMSN_STTUS_CD",
    "CLM_TYP_CD",
    "FCLTY_CLM_SRC_SYS_GNRT_DRG_CD",
    "NDC",
    "CMPL_MBRSH_IN",
    "CLM_PD_DT",
    "CLM_RCVD_DT",
    "CLM_REMIT_HIST_CHK_PD_DT",
    "CLM_SVC_STRT_DT",
    "CLM_SVC_END_DT",
    "CLM_STTUS_DT",
    "CLM_ACTL_PD_AMT",
    "CLM_ALW_AMT",
    "CLM_CHRG_AMT",
    "CLM_COB_PD_AMT",
    "CLM_COINS_AMT",
    "CLM_CNSD_CHRG_AMT",
    "CLM_COPAY_AMT",
    "CLM_DEDCT_AMT",
    "CLM_DSALW_AMT",
    "CLM_PAYBL_AMT",
    "CLM_REMIT_HIST_CHK_NET_PAY_AMT",
    "CLM_REMIT_HIST_ER_COPAY_AMT",
    "CLM_REMIT_HIST_INTRST_AMT",
    "CLM_REMIT_HIST_NO_RESP_AMT",
    "CLM_REMIT_HIST_PATN_RESP_AMT",
    "CLM_REMIT_HIST_PROV_WRTOFF_AMT",
    "DRUG_CLM_MBR_DIFF_PD_AMT",
    "CLM_REMIT_HIST_CHK_NO",
    "DRUG_CLM_RX_ALW_QTY",
    "DRUG_CLM_RX_SUBMT_QTY",
    "ALPHA_PFX_CD",
    "CLM_ADJ_FROM_CLM_ID",
    "CLM_ADJ_TO_CLM_ID",
    "CLM_PATN_ACCT_NO",
    "CLM_RFRNG_PROV_TX",
    "CLM_REMIT_HIST_CHK_PAYE_NM",
    "CLM_REMIT_HIST_CHK_PAY_REF_ID",
    "CLM_STTUS_CD_NM",
    "CLM_SUB_ID",
    "CMN_PRCT_PRSCRB_CMN_PRCT_ID",
    "CMN_PRCT_PRSCRB_CMN_PRCT_NM",
    "CMN_PRCT_SVC_CMN_PRCT_ID",
    "DRUG_CLM_RX_NO",
    "GRP_UNIQ_KEY",
    "MBR_UNIQ_KEY",
    "MBR_FIRST_NM",
    "MBR_MIDINIT",
    "MBR_LAST_NM",
    "MBR_SUB_FIRST_NM",
    "MBR_SUB_MIDINIT",
    "MBR_SUB_LAST_NM",
    "NDC_DRUG_LABEL_NM",
    "PROV_ADDR_PD_REMIT_ADDR_LN_1",
    "PROV_ADDR_PD_REMIT_ADDR_LN_2",
    "PROV_ADDR_PD_REMIT_ADDR__LN_3",
    "PROV_ADDR_PD_REMIT_CITY_NM",
    "PROV_ADDR_PD_REMIT_ST_CD",
    "PROV_ADDR_PD_REMIT_POSTAL_CD",
    "PROV_PD_PROV_ID",
    "PROV_PD_PROV_NM",
    "PROV_PCP_PROV_ID",
    "PROV_PCP_PROV_NM",
    "PROV_REL_GRP_PROV_ID",
    "PROV_REL_IPA_PROV_ID",
    "PROV_SVC_PROV_ID",
    "PROV_SVC_PROV_NM",
    "SUB_UNIQ_KEY",
    "SUB_ADDR_LN_1",
    "SUB_ADDR_LN_2",
    "SUB_ADDR_CITY_NM",
    "SUB_ADDR_ST_CD",
    "SUB_ADDR_POSTAL_CD",
    "CLM_NTWK_STTUS_CD",
    "CLM_NTWK_STTUS_NM",
    "CLM_REMIT_HIST_PAYMT_METH_CD",
    "CLM_STTUS_CHG_RSN_CD",
    "CLM_STTUS_CHG_RSN_NM",
    "FCLTY_CLM_ADMS_TYP_CD",
    "FCLTY_CLM_ADMS_TYP_NM",
    "FCLTY_CLM_ADMS_SRC_CD",
    "FCLTY_CLM_ADMS_SRC_NM",
    "FCLTY_CLM_BILL_CLS_CD",
    "FCLTY_CLM_BILL_CLS_NM",
    "FCLTY_CLM_BILL_FREQ_CD",
    "FCLTY_CLM_BILL_FREQ_NM",
    "FCLTY_CLM_BILL_TYP_CD",
    "FCLTY_CLM_BILL_TYP_NM",
    "FCLTY_CLM_DSCHG_STTUS_CD",
    "FCLTY_CLM_DSCHG_STTUS_NM",
    "MBR_GNDR_CD",
    "MBR_GNDR_NM",
    "CLM_HOST_IN",
    "CLM_PRCS_DT",
    "DM_LAST_UPDT_DT",
    "FCLTY_CLM_ADMS_DT",
    "FCLTY_CLM_DSCHG_DT",
    "MBR_BRTH_DT",
    "CLM_AUTH_NO",
    "CLS_ID",
    "CLS_DESC",
    "CLS_PLN_ID",
    "CLS_PLN_DESC",
    "FCLTY_CLM_ADM_PHYS_PROV_ID",
    "GNRT_DRG_CD",
    "GRP_ID",
    "MBR_RELSHP_CD",
    "MBR_SFX_NO",
    "NTWK_ID",
    "NTWK_NM",
    "PROD_ID",
    "PROV_AGMNT_ID",
    "SUBMT_DRG_CD",
    "SUB_ID",
    "LAST_UPDT_RUN_CYC_NO",
    "PCA_CLM_CHK_PAYE_TYP_CD",
    "PCA_CLM_CHK_PAYE_TYP_NM",
    "PCA_CLM_CHK_PAYMT_METH_CD",
    "PCA_CLM_CHK_PAYMT_METH_NM",
    "PCA_TYP_NM",
    "CLM_HOME_IN",
    "PCA_CLM_CHK_PD_DT",
    "CLM_PCA_TOT_CNSD_AMT",
    "CLM_PCA_TOT_PD_AMT",
    "CLM_PCA_SUB_TOT_PCA_AVLBL_AMT",
    "CLM_PCA_SUB_TOT_PCA_PDTODT_AMT",
    "PCA_CLM_CHK_NET_PAYMT_AMT",
    "PCA_CLM_CHK_NO",
    "PCA_CLM_CHK_SEQ_NO",
    "CLM_EXTRNL_PROV_NM",
    "CLM_EXTRNL_REF_PCA_EXTRNL_ID",
    "PCA_CLM_CHK_PAYE_NM",
    "PCA_CLM_CHK_PAYMT_REF_ID",
    "REL_PCA_SRC_SYS_CD",
    "REL_PCA_CLM_ID",
    "REL_BASE_SRC_SYS_CD",
    "REL_BASE_CLM_ID",
    "PCA_TYP_CD",
    "CLM_SUB_BCBS_PLN_CD",
    "ITS_CLM_SCCF_NO",
    "CLM_REMIT_HIST_ALT_CHRG_IN",
    "ALT_CHRG_PROV_WRTOFF_AMT"
)

# Prepare for Database Merge
jdbc_url, jdbc_props = get_db_config(clmmart_secret_name)

# Drop temp table if exists
execute_dml(
    f"DROP TABLE IF EXISTS STAGING.IdsDmClmDmClmLoad_Odbc_CLM_DM_CLMout_temp",
    jdbc_url,
    jdbc_props
)

# Write to staging table
df_Odbc_CLM_DM_CLMout_input.write.jdbc(
    url=jdbc_url,
    table="STAGING.IdsDmClmDmClmLoad_Odbc_CLM_DM_CLMout_temp",
    mode="append",
    properties=jdbc_props
)

# Merge statement (converted from DataStage's update/insert SQL)
merge_sql = f"""
MERGE INTO {ClmMartOwner}.CLM_DM_CLM AS T
USING STAGING.IdsDmClmDmClmLoad_Odbc_CLM_DM_CLMout_temp AS S
ON T.SRC_SYS_CD=S.SRC_SYS_CD AND T.CLM_ID=S.CLM_ID
WHEN MATCHED THEN UPDATE SET
 T.CLM_CAP_CD=S.CLM_CAP_CD,
 T.CLM_FINL_DISP_CD=S.CLM_FINL_DISP_CD,
 T.CLM_INTER_PLN_PGM_CD=S.CLM_INTER_PLN_PGM_CD,
 T.CLM_PAYE_CD=S.CLM_PAYE_CD,
 T.CLM_STTUS_CD=S.CLM_STTUS_CD,
 T.CLM_SUBTYP_CD=S.CLM_SUBTYP_CD,
 T.CLM_TRNSMSN_STTUS_CD=S.CLM_TRNSMSN_STTUS_CD,
 T.CLM_TYP_CD=S.CLM_TYP_CD,
 T.FCLTY_CLM_SRC_SYS_GNRT_DRG_CD=S.FCLTY_CLM_SRC_SYS_GNRT_DRG_CD,
 T.NDC=S.NDC,
 T.CMPL_MBRSH_IN=S.CMPL_MBRSH_IN,
 T.CLM_PD_DT=S.CLM_PD_DT,
 T.CLM_RCVD_DT=S.CLM_RCVD_DT,
 T.CLM_REMIT_HIST_CHK_PD_DT=S.CLM_REMIT_HIST_CHK_PD_DT,
 T.CLM_SVC_STRT_DT=S.CLM_SVC_STRT_DT,
 T.CLM_SVC_END_DT=S.CLM_SVC_END_DT,
 T.CLM_STTUS_DT=S.CLM_STTUS_DT,
 T.CLM_ACTL_PD_AMT=S.CLM_ACTL_PD_AMT,
 T.CLM_ALW_AMT=S.CLM_ALW_AMT,
 T.CLM_CHRG_AMT=S.CLM_CHRG_AMT,
 T.CLM_COB_PD_AMT=S.CLM_COB_PD_AMT,
 T.CLM_COINS_AMT=S.CLM_COINS_AMT,
 T.CLM_CNSD_CHRG_AMT=S.CLM_CNSD_CHRG_AMT,
 T.CLM_COPAY_AMT=S.CLM_COPAY_AMT,
 T.CLM_DEDCT_AMT=S.CLM_DEDCT_AMT,
 T.CLM_DSALW_AMT=S.CLM_DSALW_AMT,
 T.CLM_PAYBL_AMT=S.CLM_PAYBL_AMT,
 T.CLM_REMIT_HIST_CHK_NET_PAY_AMT=S.CLM_REMIT_HIST_CHK_NET_PAY_AMT,
 T.CLM_REMIT_HIST_ER_COPAY_AMT=S.CLM_REMIT_HIST_ER_COPAY_AMT,
 T.CLM_REMIT_HIST_INTRST_AMT=S.CLM_REMIT_HIST_INTRST_AMT,
 T.CLM_REMIT_HIST_NO_RESP_AMT=S.CLM_REMIT_HIST_NO_RESP_AMT,
 T.CLM_REMIT_HIST_PATN_RESP_AMT=S.CLM_REMIT_HIST_PATN_RESP_AMT,
 T.CLM_REMIT_HIST_PROV_WRTOFF_AMT=S.CLM_REMIT_HIST_PROV_WRTOFF_AMT,
 T.DRUG_CLM_MBR_DIFF_PD_AMT=S.DRUG_CLM_MBR_DIFF_PD_AMT,
 T.CLM_REMIT_HIST_CHK_NO=S.CLM_REMIT_HIST_CHK_NO,
 T.DRUG_CLM_RX_ALW_QTY=S.DRUG_CLM_RX_ALW_QTY,
 T.DRUG_CLM_RX_SUBMT_QTY=S.DRUG_CLM_RX_SUBMT_QTY,
 T.ALPHA_PFX_CD=S.ALPHA_PFX_CD,
 T.CLM_ADJ_FROM_CLM_ID=S.CLM_ADJ_FROM_CLM_ID,
 T.CLM_ADJ_TO_CLM_ID=S.CLM_ADJ_TO_CLM_ID,
 T.CLM_PATN_ACCT_NO=S.CLM_PATN_ACCT_NO,
 T.CLM_RFRNG_PROV_TX=S.CLM_RFRNG_PROV_TX,
 T.CLM_REMIT_HIST_CHK_PAYE_NM=S.CLM_REMIT_HIST_CHK_PAYE_NM,
 T.CLM_REMIT_HIST_CHK_PAY_REF_ID=S.CLM_REMIT_HIST_CHK_PAY_REF_ID,
 T.CLM_STTUS_CD_NM=S.CLM_STTUS_CD_NM,
 T.CLM_SUB_ID=S.CLM_SUB_ID,
 T.CMN_PRCT_PRSCRB_CMN_PRCT_ID=S.CMN_PRCT_PRSCRB_CMN_PRCT_ID,
 T.CMN_PRCT_PRSCRB_CMN_PRCT_NM=S.CMN_PRCT_PRSCRB_CMN_PRCT_NM,
 T.CMN_PRCT_SVC_CMN_PRCT_ID=S.CMN_PRCT_SVC_CMN_PRCT_ID,
 T.DRUG_CLM_RX_NO=S.DRUG_CLM_RX_NO,
 T.GRP_UNIQ_KEY=S.GRP_UNIQ_KEY,
 T.MBR_UNIQ_KEY=S.MBR_UNIQ_KEY,
 T.MBR_FIRST_NM=S.MBR_FIRST_NM,
 T.MBR_MIDINIT=S.MBR_MIDINIT,
 T.MBR_LAST_NM=S.MBR_LAST_NM,
 T.MBR_SUB_FIRST_NM=S.MBR_SUB_FIRST_NM,
 T.MBR_SUB_MIDINIT=S.MBR_SUB_MIDINIT,
 T.MBR_SUB_LAST_NM=S.MBR_SUB_LAST_NM,
 T.NDC_DRUG_LABEL_NM=S.NDC_DRUG_LABEL_NM,
 T.PROV_ADDR_PD_REMIT_ADDR_LN_1=S.PROV_ADDR_PD_REMIT_ADDR_LN_1,
 T.PROV_ADDR_PD_REMIT_ADDR_LN_2=S.PROV_ADDR_PD_REMIT_ADDR_LN_2,
 T.PROV_ADDR_PD_REMIT_ADDR__LN_3=S.PROV_ADDR_PD_REMIT_ADDR__LN_3,
 T.PROV_ADDR_PD_REMIT_CITY_NM=S.PROV_ADDR_PD_REMIT_CITY_NM,
 T.PROV_ADDR_PD_REMIT_ST_CD=S.PROV_ADDR_PD_REMIT_ST_CD,
 T.PROV_ADDR_PD_REMIT_POSTAL_CD=S.PROV_ADDR_PD_REMIT_POSTAL_CD,
 T.PROV_PD_PROV_ID=S.PROV_PD_PROV_ID,
 T.PROV_PD_PROV_NM=S.PROV_PD_PROV_NM,
 T.PROV_PCP_PROV_ID=S.PROV_PCP_PROV_ID,
 T.PROV_PCP_PROV_NM=S.PROV_PCP_PROV_NM,
 T.PROV_REL_GRP_PROV_ID=S.PROV_REL_GRP_PROV_ID,
 T.PROV_REL_IPA_PROV_ID=S.PROV_REL_IPA_PROV_ID,
 T.PROV_SVC_PROV_ID=S.PROV_SVC_PROV_ID,
 T.PROV_SVC_PROV_NM=S.PROV_SVC_PROV_NM,
 T.SUB_UNIQ_KEY=S.SUB_UNIQ_KEY,
 T.SUB_ADDR_LN_1=S.SUB_ADDR_LN_1,
 T.SUB_ADDR_LN_2=S.SUB_ADDR_LN_2,
 T.SUB_ADDR_CITY_NM=S.SUB_ADDR_CITY_NM,
 T.SUB_ADDR_ST_CD=S.SUB_ADDR_ST_CD,
 T.SUB_ADDR_POSTAL_CD=S.SUB_ADDR_POSTAL_CD,
 T.CLM_NTWK_STTUS_CD=S.CLM_NTWK_STTUS_CD,
 T.CLM_NTWK_STTUS_NM=S.CLM_NTWK_STTUS_NM,
 T.CLM_REMIT_HIST_PAYMT_METH_CD=S.CLM_REMIT_HIST_PAYMT_METH_CD,
 T.CLM_STTUS_CHG_RSN_CD=S.CLM_STTUS_CHG_RSN_CD,
 T.CLM_STTUS_CHG_RSN_NM=S.CLM_STTUS_CHG_RSN_NM,
 T.FCLTY_CLM_ADMS_TYP_CD=S.FCLTY_CLM_ADMS_TYP_CD,
 T.FCLTY_CLM_ADMS_TYP_NM=S.FCLTY_CLM_ADMS_TYP_NM,
 T.FCLTY_CLM_ADMS_SRC_CD=S.FCLTY_CLM_ADMS_SRC_CD,
 T.FCLTY_CLM_ADMS_SRC_NM=S.FCLTY_CLM_ADMS_SRC_NM,
 T.FCLTY_CLM_BILL_CLS_CD=S.FCLTY_CLM_BILL_CLS_CD,
 T.FCLTY_CLM_BILL_CLS_NM=S.FCLTY_CLM_BILL_CLS_NM,
 T.FCLTY_CLM_BILL_FREQ_CD=S.FCLTY_CLM_BILL_FREQ_CD,
 T.FCLTY_CLM_BILL_FREQ_NM=S.FCLTY_CLM_BILL_FREQ_NM,
 T.FCLTY_CLM_BILL_TYP_CD=S.FCLTY_CLM_BILL_TYP_CD,
 T.FCLTY_CLM_BILL_TYP_NM=S.FCLTY_CLM_BILL_TYP_NM,
 T.FCLTY_CLM_DSCHG_STTUS_CD=S.FCLTY_CLM_DSCHG_STTUS_CD,
 T.FCLTY_CLM_DSCHG_STTUS_NM=S.FCLTY_CLM_DSCHG_STTUS_NM,
 T.MBR_GNDR_CD=S.MBR_GNDR_CD,
 T.MBR_GNDR_NM=S.MBR_GNDR_NM,
 T.CLM_HOST_IN=S.CLM_HOST_IN,
 T.CLM_PRCS_DT=S.CLM_PRCS_DT,
 T.DM_LAST_UPDT_DT=S.DM_LAST_UPDT_DT,
 T.FCLTY_CLM_ADMS_DT=S.FCLTY_CLM_ADMS_DT,
 T.FCLTY_CLM_DSCHG_DT=S.FCLTY_CLM_DSCHG_DT,
 T.MBR_BRTH_DT=S.MBR_BRTH_DT,
 T.CLM_AUTH_NO=S.CLM_AUTH_NO,
 T.CLS_ID=S.CLS_ID,
 T.CLS_DESC=S.CLS_DESC,
 T.CLS_PLN_ID=S.CLS_PLN_ID,
 T.CLS_PLN_DESC=S.CLS_PLN_DESC,
 T.FCLTY_CLM_ADM_PHYS_PROV_ID=S.FCLTY_CLM_ADM_PHYS_PROV_ID,
 T.GNRT_DRG_CD=S.GNRT_DRG_CD,
 T.GRP_ID=S.GRP_ID,
 T.MBR_RELSHP_CD=S.MBR_RELSHP_CD,
 T.MBR_SFX_NO=S.MBR_SFX_NO,
 T.NTWK_ID=S.NTWK_ID,
 T.NTWK_NM=S.NTWK_NM,
 T.PROD_ID=S.PROD_ID,
 T.PROV_AGMNT_ID=S.PROV_AGMNT_ID,
 T.SUBMT_DRG_CD=S.SUBMT_DRG_CD,
 T.SUB_ID=S.SUB_ID,
 T.LAST_UPDT_RUN_CYC_NO=S.LAST_UPDT_RUN_CYC_NO,
 T.PCA_CLM_CHK_PAYE_TYP_CD=S.PCA_CLM_CHK_PAYE_TYP_CD,
 T.PCA_CLM_CHK_PAYE_TYP_NM=S.PCA_CLM_CHK_PAYE_TYP_NM,
 T.PCA_CLM_CHK_PAYMT_METH_CD=S.PCA_CLM_CHK_PAYMT_METH_CD,
 T.PCA_CLM_CHK_PAYMT_METH_NM=S.PCA_CLM_CHK_PAYMT_METH_NM,
 T.PCA_TYP_NM=S.PCA_TYP_NM,
 T.CLM_HOME_IN=S.CLM_HOME_IN,
 T.PCA_CLM_CHK_PD_DT=S.PCA_CLM_CHK_PD_DT,
 T.CLM_PCA_TOT_CNSD_AMT=S.CLM_PCA_TOT_CNSD_AMT,
 T.CLM_PCA_TOT_PD_AMT=S.CLM_PCA_TOT_PD_AMT,
 T.CLM_PCA_SUB_TOT_PCA_AVLBL_AMT=S.CLM_PCA_SUB_TOT_PCA_AVLBL_AMT,
 T.CLM_PCA_SUB_TOT_PCA_PDTODT_AMT=S.CLM_PCA_SUB_TOT_PCA_PDTODT_AMT,
 T.PCA_CLM_CHK_NET_PAYMT_AMT=S.PCA_CLM_CHK_NET_PAYMT_AMT,
 T.PCA_CLM_CHK_NO=S.PCA_CLM_CHK_NO,
 T.PCA_CLM_CHK_SEQ_NO=S.PCA_CLM_CHK_SEQ_NO,
 T.CLM_EXTRNL_PROV_NM=S.CLM_EXTRNL_PROV_NM,
 T.CLM_EXTRNL_REF_PCA_EXTRNL_ID=S.CLM_EXTRNL_REF_PCA_EXTRNL_ID,
 T.PCA_CLM_CHK_PAYE_NM=S.PCA_CLM_CHK_PAYE_NM,
 T.PCA_CLM_CHK_PAYMT_REF_ID=S.PCA_CLM_CHK_PAYMT_REF_ID,
 T.REL_PCA_SRC_SYS_CD=S.REL_PCA_SRC_SYS_CD,
 T.REL_PCA_CLM_ID=S.REL_PCA_CLM_ID,
 T.REL_BASE_SRC_SYS_CD=S.REL_BASE_SRC_SYS_CD,
 T.REL_BASE_CLM_ID=S.REL_BASE_CLM_ID,
 T.PCA_TYP_CD=S.PCA_TYP_CD,
 T.CLM_SUB_BCBS_PLN_CD=S.CLM_SUB_BCBS_PLN_CD,
 T.ITS_CLM_SCCF_NO=S.ITS_CLM_SCCF_NO,
 T.CLM_REMIT_HIST_ALT_CHRG_IN=S.CLM_REMIT_HIST_ALT_CHRG_IN,
 T.ALT_CHRG_PROV_WRTOFF_AMT=S.ALT_CHRG_PROV_WRTOFF_AMT
WHEN NOT MATCHED THEN INSERT (
 SRC_SYS_CD,
 CLM_ID,
 CLM_CAP_CD,
 CLM_FINL_DISP_CD,
 CLM_INTER_PLN_PGM_CD,
 CLM_PAYE_CD,
 CLM_STTUS_CD,
 CLM_SUBTYP_CD,
 CLM_TRNSMSN_STTUS_CD,
 CLM_TYP_CD,
 FCLTY_CLM_SRC_SYS_GNRT_DRG_CD,
 NDC,
 CMPL_MBRSH_IN,
 CLM_PD_DT,
 CLM_RCVD_DT,
 CLM_REMIT_HIST_CHK_PD_DT,
 CLM_SVC_STRT_DT,
 CLM_SVC_END_DT,
 CLM_STTUS_DT,
 CLM_ACTL_PD_AMT,
 CLM_ALW_AMT,
 CLM_CHRG_AMT,
 CLM_COB_PD_AMT,
 CLM_COINS_AMT,
 CLM_CNSD_CHRG_AMT,
 CLM_COPAY_AMT,
 CLM_DEDCT_AMT,
 CLM_DSALW_AMT,
 CLM_PAYBL_AMT,
 CLM_REMIT_HIST_CHK_NET_PAY_AMT,
 CLM_REMIT_HIST_ER_COPAY_AMT,
 CLM_REMIT_HIST_INTRST_AMT,
 CLM_REMIT_HIST_NO_RESP_AMT,
 CLM_REMIT_HIST_PATN_RESP_AMT,
 CLM_REMIT_HIST_PROV_WRTOFF_AMT,
 DRUG_CLM_MBR_DIFF_PD_AMT,
 CLM_REMIT_HIST_CHK_NO,
 DRUG_CLM_RX_ALW_QTY,
 DRUG_CLM_RX_SUBMT_QTY,
 ALPHA_PFX_CD,
 CLM_ADJ_FROM_CLM_ID,
 CLM_ADJ_TO_CLM_ID,
 CLM_PATN_ACCT_NO,
 CLM_RFRNG_PROV_TX,
 CLM_REMIT_HIST_CHK_PAYE_NM,
 CLM_REMIT_HIST_CHK_PAY_REF_ID,
 CLM_STTUS_CD_NM,
 CLM_SUB_ID,
 CMN_PRCT_PRSCRB_CMN_PRCT_ID,
 CMN_PRCT_PRSCRB_CMN_PRCT_NM,
 CMN_PRCT_SVC_CMN_PRCT_ID,
 DRUG_CLM_RX_NO,
 GRP_UNIQ_KEY,
 MBR_UNIQ_KEY,
 MBR_FIRST_NM,
 MBR_MIDINIT,
 MBR_LAST_NM,
 MBR_SUB_FIRST_NM,
 MBR_SUB_MIDINIT,
 MBR_SUB_LAST_NM,
 NDC_DRUG_LABEL_NM,
 PROV_ADDR_PD_REMIT_ADDR_LN_1,
 PROV_ADDR_PD_REMIT_ADDR_LN_2,
 PROV_ADDR_PD_REMIT_ADDR__LN_3,
 PROV_ADDR_PD_REMIT_CITY_NM,
 PROV_ADDR_PD_REMIT_ST_CD,
 PROV_ADDR_PD_REMIT_POSTAL_CD,
 PROV_PD_PROV_ID,
 PROV_PD_PROV_NM,
 PROV_PCP_PROV_ID,
 PROV_PCP_PROV_NM,
 PROV_REL_GRP_PROV_ID,
 PROV_REL_IPA_PROV_ID,
 PROV_SVC_PROV_ID,
 PROV_SVC_PROV_NM,
 SUB_UNIQ_KEY,
 SUB_ADDR_LN_1,
 SUB_ADDR_LN_2,
 SUB_ADDR_CITY_NM,
 SUB_ADDR_ST_CD,
 SUB_ADDR_POSTAL_CD,
 CLM_NTWK_STTUS_CD,
 CLM_NTWK_STTUS_NM,
 CLM_REMIT_HIST_PAYMT_METH_CD,
 CLM_STTUS_CHG_RSN_CD,
 CLM_STTUS_CHG_RSN_NM,
 FCLTY_CLM_ADMS_TYP_CD,
 FCLTY_CLM_ADMS_TYP_NM,
 FCLTY_CLM_ADMS_SRC_CD,
 FCLTY_CLM_ADMS_SRC_NM,
 FCLTY_CLM_BILL_CLS_CD,
 FCLTY_CLM_BILL_CLS_NM,
 FCLTY_CLM_BILL_FREQ_CD,
 FCLTY_CLM_BILL_FREQ_NM,
 FCLTY_CLM_BILL_TYP_CD,
 FCLTY_CLM_BILL_TYP_NM,
 FCLTY_CLM_DSCHG_STTUS_CD,
 FCLTY_CLM_DSCHG_STTUS_NM,
 MBR_GNDR_CD,
 MBR_GNDR_NM,
 CLM_HOST_IN,
 CLM_PRCS_DT,
 DM_LAST_UPDT_DT,
 FCLTY_CLM_ADMS_DT,
 FCLTY_CLM_DSCHG_DT,
 MBR_BRTH_DT,
 CLM_AUTH_NO,
 CLS_ID,
 CLS_DESC,
 CLS_PLN_ID,
 CLS_PLN_DESC,
 FCLTY_CLM_ADM_PHYS_PROV_ID,
 GNRT_DRG_CD,
 GRP_ID,
 MBR_RELSHP_CD,
 MBR_SFX_NO,
 NTWK_ID,
 NTWK_NM,
 PROD_ID,
 PROV_AGMNT_ID,
 SUBMT_DRG_CD,
 SUB_ID,
 LAST_UPDT_RUN_CYC_NO,
 PCA_CLM_CHK_PAYE_TYP_CD,
 PCA_CLM_CHK_PAYE_TYP_NM,
 PCA_CLM_CHK_PAYMT_METH_CD,
 PCA_CLM_CHK_PAYMT_METH_NM,
 PCA_TYP_NM,
 CLM_HOME_IN,
 PCA_CLM_CHK_PD_DT,
 CLM_PCA_TOT_CNSD_AMT,
 CLM_PCA_TOT_PD_AMT,
 CLM_PCA_SUB_TOT_PCA_AVLBL_AMT,
 CLM_PCA_SUB_TOT_PCA_PDTODT_AMT,
 PCA_CLM_CHK_NET_PAYMT_AMT,
 PCA_CLM_CHK_NO,
 PCA_CLM_CHK_SEQ_NO,
 CLM_EXTRNL_PROV_NM,
 CLM_EXTRNL_REF_PCA_EXTRNL_ID,
 PCA_CLM_CHK_PAYE_NM,
 PCA_CLM_CHK_PAYMT_REF_ID,
 REL_PCA_SRC_SYS_CD,
 REL_PCA_CLM_ID,
 REL_BASE_SRC_SYS_CD,
 REL_BASE_CLM_ID,
 PCA_TYP_CD,
 CLM_SUB_BCBS_PLN_CD,
 ITS_CLM_SCCF_NO,
 CLM_REMIT_HIST_ALT_CHRG_IN,
 ALT_CHRG_PROV_WRTOFF_AMT
)
VALUES (
 S.SRC_SYS_CD,
 S.CLM_ID,
 S.CLM_CAP_CD,
 S.CLM_FINL_DISP_CD,
 S.CLM_INTER_PLN_PGM_CD,
 S.CLM_PAYE_CD,
 S.CLM_STTUS_CD,
 S.CLM_SUBTYP_CD,
 S.CLM_TRNSMSN_STTUS_CD,
 S.CLM_TYP_CD,
 S.FCLTY_CLM_SRC_SYS_GNRT_DRG_CD,
 S.NDC,
 S.CMPL_MBRSH_IN,
 S.CLM_PD_DT,
 S.CLM_RCVD_DT,
 S.CLM_REMIT_HIST_CHK_PD_DT,
 S.CLM_SVC_STRT_DT,
 S.CLM_SVC_END_DT,
 S.CLM_STTUS_DT,
 S.CLM_ACTL_PD_AMT,
 S.CLM_ALW_AMT,
 S.CLM_CHRG_AMT,
 S.CLM_COB_PD_AMT,
 S.CLM_COINS_AMT,
 S.CLM_CNSD_CHRG_AMT,
 S.CLM_COPAY_AMT,
 S.CLM_DEDCT_AMT,
 S.CLM_DSALW_AMT,
 S.CLM_PAYBL_AMT,
 S.CLM_REMIT_HIST_CHK_NET_PAY_AMT,
 S.CLM_REMIT_HIST_ER_COPAY_AMT,
 S.CLM_REMIT_HIST_INTRST_AMT,
 S.CLM_REMIT_HIST_NO_RESP_AMT,
 S.CLM_REMIT_HIST_PATN_RESP_AMT,
 S.CLM_REMIT_HIST_PROV_WRTOFF_AMT,
 S.DRUG_CLM_MBR_DIFF_PD_AMT,
 S.CLM_REMIT_HIST_CHK_NO,
 S.DRUG_CLM_RX_ALW_QTY,
 S.DRUG_CLM_RX_SUBMT_QTY,
 S.ALPHA_PFX_CD,
 S.CLM_ADJ_FROM_CLM_ID,
 S.CLM_ADJ_TO_CLM_ID,
 S.CLM_PATN_ACCT_NO,
 S.CLM_RFRNG_PROV_TX,
 S.CLM_REMIT_HIST_CHK_PAYE_NM,
 S.CLM_REMIT_HIST_CHK_PAY_REF_ID,
 S.CLM_STTUS_CD_NM,
 S.CLM_SUB_ID,
 S.CMN_PRCT_PRSCRB_CMN_PRCT_ID,
 S.CMN_PRCT_PRSCRB_CMN_PRCT_NM,
 S.CMN_PRCT_SVC_CMN_PRCT_ID,
 S.DRUG_CLM_RX_NO,
 S.GRP_UNIQ_KEY,
 S.MBR_UNIQ_KEY,
 S.MBR_FIRST_NM,
 S.MBR_MIDINIT,
 S.MBR_LAST_NM,
 S.MBR_SUB_FIRST_NM,
 S.MBR_SUB_MIDINIT,
 S.MBR_SUB_LAST_NM,
 S.NDC_DRUG_LABEL_NM,
 S.PROV_ADDR_PD_REMIT_ADDR_LN_1,
 S.PROV_ADDR_PD_REMIT_ADDR_LN_2,
 S.PROV_ADDR_PD_REMIT_ADDR__LN_3,
 S.PROV_ADDR_PD_REMIT_CITY_NM,
 S.PROV_ADDR_PD_REMIT_ST_CD,
 S.PROV_ADDR_PD_REMIT_POSTAL_CD,
 S.PROV_PD_PROV_ID,
 S.PROV_PD_PROV_NM,
 S.PROV_PCP_PROV_ID,
 S.PROV_PCP_PROV_NM,
 S.PROV_REL_GRP_PROV_ID,
 S.PROV_REL_IPA_PROV_ID,
 S.PROV_SVC_PROV_ID,
 S.PROV_SVC_PROV_NM,
 S.SUB_UNIQ_KEY,
 S.SUB_ADDR_LN_1,
 S.SUB_ADDR_LN_2,
 S.SUB_ADDR_CITY_NM,
 S.SUB_ADDR_ST_CD,
 S.SUB_ADDR_POSTAL_CD,
 S.CLM_NTWK_STTUS_CD,
 S.CLM_NTWK_STTUS_NM,
 S.CLM_REMIT_HIST_PAYMT_METH_CD,
 S.CLM_STTUS_CHG_RSN_CD,
 S.CLM_STTUS_CHG_RSN_NM,
 S.FCLTY_CLM_ADMS_TYP_CD,
 S.FCLTY_CLM_ADMS_TYP_NM,
 S.FCLTY_CLM_ADMS_SRC_CD,
 S.FCLTY_CLM_ADMS_SRC_NM,
 S.FCLTY_CLM_BILL_CLS_CD,
 S.FCLTY_CLM_BILL_CLS_NM,
 S.FCLTY_CLM_BILL_FREQ_CD,
 S.FCLTY_CLM_BILL_FREQ_NM,
 S.FCLTY_CLM_BILL_TYP_CD,
 S.FCLTY_CLM_BILL_TYP_NM,
 S.FCLTY_CLM_DSCHG_STTUS_CD,
 S.FCLTY_CLM_DSCHG_STTUS_NM,
 S.MBR_GNDR_CD,
 S.MBR_GNDR_NM,
 S.CLM_HOST_IN,
 S.CLM_PRCS_DT,
 S.DM_LAST_UPDT_DT,
 S.FCLTY_CLM_ADMS_DT,
 S.FCLTY_CLM_DSCHG_DT,
 S.MBR_BRTH_DT,
 S.CLM_AUTH_NO,
 S.CLS_ID,
 S.CLS_DESC,
 S.CLS_PLN_ID,
 S.CLS_PLN_DESC,
 S.FCLTY_CLM_ADM_PHYS_PROV_ID,
 S.GNRT_DRG_CD,
 S.GRP_ID,
 S.MBR_RELSHP_CD,
 S.MBR_SFX_NO,
 S.NTWK_ID,
 S.NTWK_NM,
 S.PROD_ID,
 S.PROV_AGMNT_ID,
 S.SUBMT_DRG_CD,
 S.SUB_ID,
 S.LAST_UPDT_RUN_CYC_NO,
 S.PCA_CLM_CHK_PAYE_TYP_CD,
 S.PCA_CLM_CHK_PAYE_TYP_NM,
 S.PCA_CLM_CHK_PAYMT_METH_CD,
 S.PCA_CLM_CHK_PAYMT_METH_NM,
 S.PCA_TYP_NM,
 S.CLM_HOME_IN,
 S.PCA_CLM_CHK_PD_DT,
 S.CLM_PCA_TOT_CNSD_AMT,
 S.CLM_PCA_TOT_PD_AMT,
 S.CLM_PCA_SUB_TOT_PCA_AVLBL_AMT,
 S.CLM_PCA_SUB_TOT_PCA_PDTODT_AMT,
 S.PCA_CLM_CHK_NET_PAYMT_AMT,
 S.PCA_CLM_CHK_NO,
 S.PCA_CLM_CHK_SEQ_NO,
 S.CLM_EXTRNL_PROV_NM,
 S.CLM_EXTRNL_REF_PCA_EXTRNL_ID,
 S.PCA_CLM_CHK_PAYE_NM,
 S.PCA_CLM_CHK_PAYMT_REF_ID,
 S.REL_PCA_SRC_SYS_CD,
 S.REL_PCA_CLM_ID,
 S.REL_BASE_SRC_SYS_CD,
 S.REL_BASE_CLM_ID,
 S.PCA_TYP_CD,
 S.CLM_SUB_BCBS_PLN_CD,
 S.ITS_CLM_SCCF_NO,
 S.CLM_REMIT_HIST_ALT_CHRG_IN,
 S.ALT_CHRG_PROV_WRTOFF_AMT
);
"""

# Execute merge
execute_dml(merge_sql, jdbc_url, jdbc_props)

# Create a placeholder DataFrame for rejects (row-level DB errors not captured by Spark)
df_rejects_schema = StructType([
    StructField("ERRORCODE", StringType(), True),
    StructField("ERRORTEXT", StringType(), True)
])
df_rejects = spark.createDataFrame([], df_rejects_schema)

# Write rejects to CLM_DM_CLM_Rej.dat
# No length known for ERRORCODE/ERRORTEXT, so no rpad needed
write_files(
    df_rejects,
    f"{adls_path}/load/CLM_DM_CLM_Rej.dat",
    delimiter=",",
    mode="append",
    is_pqruet=False,
    header=False,
    quote="^",
    nullValue=None
)