import { Octokit } from "@octokit/rest";

function getOctokit() {
  return new Octokit({ auth: process.env.GITHUB_TOKEN });
}

function getOwner() {
  return process.env.GITHUB_USERNAME!;
}

export async function createRepoAndPush(
  repoName: string,
  htmlContent: string
): Promise<{ repoUrl: string }> {
  const octokit = getOctokit();
  const owner = getOwner();

  // Create the repository
  let repoUrl: string;
  try {
    const { data: repo } = await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description:
        "Investor landing page generated by Yajur Knowledge Solutions",
      private: false,
      auto_init: true,
    });
    repoUrl = repo.html_url;
  } catch (error: unknown) {
    const err = error as { status?: number };
    if (err.status === 422) {
      // Repo already exists, use it
      repoUrl = `https://github.com/${owner}/${repoName}`;
    } else {
      throw error;
    }
  }

  // Wait briefly for repo initialization
  await new Promise((resolve) => setTimeout(resolve, 2000));

  // Get the reference to main branch
  const { data: ref } = await octokit.git.getRef({
    owner,
    repo: repoName,
    ref: "heads/main",
  });
  const latestCommitSha = ref.object.sha;

  // Get the commit to find the tree
  const { data: commit } = await octokit.git.getCommit({
    owner,
    repo: repoName,
    commit_sha: latestCommitSha,
  });

  // Create blob for index.html
  const { data: htmlBlob } = await octokit.git.createBlob({
    owner,
    repo: repoName,
    content: Buffer.from(htmlContent).toString("base64"),
    encoding: "base64",
  });

  // Create tree with index.html
  const { data: tree } = await octokit.git.createTree({
    owner,
    repo: repoName,
    base_tree: commit.tree.sha,
    tree: [
      {
        path: "index.html",
        mode: "100644",
        type: "blob",
        sha: htmlBlob.sha,
      },
    ],
  });

  // Create commit
  const { data: newCommit } = await octokit.git.createCommit({
    owner,
    repo: repoName,
    message: "Deploy investor landing page",
    tree: tree.sha,
    parents: [latestCommitSha],
  });

  // Update main branch reference
  await octokit.git.updateRef({
    owner,
    repo: repoName,
    ref: "heads/main",
    sha: newCommit.sha,
  });

  return { repoUrl };
}

export async function updateRepoFile(
  repoName: string,
  htmlContent: string
): Promise<void> {
  const octokit = getOctokit();
  const owner = getOwner();

  const { data: existingFile } = await octokit.repos.getContent({
    owner,
    repo: repoName,
    path: "index.html",
  });

  const fileSha = Array.isArray(existingFile) ? undefined : existingFile.sha;

  await octokit.repos.createOrUpdateFileContents({
    owner,
    repo: repoName,
    path: "index.html",
    message: "Update investor landing page",
    content: Buffer.from(htmlContent).toString("base64"),
    sha: fileSha,
  });
}
