# Databricks notebook source
# MAGIC %md
# MAGIC **Date:** 2025-08-24
# MAGIC """
# MAGIC Â© Copyright 2013 Blue Cross/Blue Shield of Kansas City
# MAGIC 
# MAGIC JOB NAME:  
# MAGIC 
# MAGIC 
# MAGIC DESCRIPTION:  This Job FTP's std_inp_claim_headers file
# MAGIC 
# MAGIC 
# MAGIC CALLED BY:  
# MAGIC 
# MAGIC HASH FILES:  
# MAGIC 
# MAGIC 
# MAGIC RERUN INFORMATION: 
# MAGIC 
# MAGIC              PREVIOUS RUN SUCCESSFUL:   Nothing to reset. 
# MAGIC              PREVIOUS RUN ABORTED:         Nothing to reset, just restart.
# MAGIC 
# MAGIC 
# MAGIC MODIFICATIONS:
# MAGIC 
# MAGIC Developer                          Date                    Project/Ticket #\(9)           Change Description\(9)\(9)\(9)              Development Project\(9)      Code Reviewer\(9)        Date Reviewed       
# MAGIC ------------------                    -------------------            ---------------------------\(9)           -----------------------------------------------------------------------            --------------------------------\(9)      -------------------------         -------------------------    
# MAGIC Praveen  Annam             2014-07-14              5115 BHI                                       Original programming                                                  EnterpriseNewDevl        Bhoomi Dasari           7/15/2014  
# MAGIC Bhoomi Dasari               10/7/2014                 5115-BHI                                   Changes to FTP stage to remove extra bytes                EnterpriseNewDevl         Kalyan Neelam           2014-10-08
# MAGIC 
# MAGIC Madhavan B                 2018-04-16                 5726                                        Added 3 new fields (BILL_PROV_TXNMY_CD,              EnterpriseDev2               Jaideep Mankala      04/18/2018
# MAGIC                                                                                                                         ATND_PROV_TXNMY_CD and
# MAGIC                                                                                                                         REND_PROV_TXNMY_CD) at the end of the extract file
# MAGIC 
# MAGIC Madhu Sudhan Thera    2019-08-13            99156                                   Added substance use flag and taxonomy code fields         EnterpriseDev2              Kalyan Nelam               2019-08-14
# MAGIC                                                                                                                                in source file

# MAGIC Job Name: std_inp_claim_headers File FTP
# MAGIC """
# COMMAND ----------
# MAGIC %run ../../../../Routine_Functions
# COMMAND ----------
# Using the below functions as UDF(inherited from Routine_Functions notebook) instead of pyspark function
# 1) current_timestamp, current_date - To convert to CST timezone.
# 2) trim - To mimic Datastage behavior in trimming spaces within the string (Not leading or trailing spaces)
# COMMAND ----------
from pyspark.sql.types import StringType
from pyspark.sql.functions import rpad, col
# COMMAND ----------
# MAGIC %run ../../../../Utility_Enterprise
# COMMAND ----------


ProdIn = get_widget_value('ProdIn','')

col_details = {
    "BHI_HOME_PLN_ID": {"len": 3, "type": StringType()},
    "CLM_ID": {"len": 25, "type": StringType()},
    "TRACEABILITY_FLD": {"len": 5, "type": StringType()},
    "ADJ_SEQ_NO": {"len": 8, "type": StringType()},
    "HOST_PLN_ID": {"len": 3, "type": StringType()},
    "HOME_PLN_PROD_ID": {"len": 15, "type": StringType()},
    "ACCT": {"len": 14, "type": StringType()},
    "GRP_ID": {"len": 14, "type": StringType()},
    "SUB_GRP_ID": {"len": 10, "type": StringType()},
    "MBR_ID": {"len": 22, "type": StringType()},
    "MBR_ZIP_CD_ON_CLM": {"len": 5, "type": StringType()},
    "MBR_CTRY_ON_CLM": {"len": 2, "type": StringType()},
    "ATND_PROV_IDENTFIER": {"len": 27, "type": StringType()},
    "ATND_PROV_SPEC": {"len": 2, "type": StringType()},
    "ATND_PROV_ZIP": {"len": 5, "type": StringType()},
    "ATND_PROV_CTRY": {"len": 2, "type": StringType()},
    "BILL_PROV_ID": {"len": 27, "type": StringType()},
    "BILL_PROV_SPEC": {"len": 2, "type": StringType()},
    "BILL_PROV_ZIP_CD": {"len": 5, "type": StringType()},
    "BILL_PROV_CTRY": {"len": 2, "type": StringType()},
    "BILL_PROV_TAX_ID": {"len": 12, "type": StringType()},
    "BILL_PROV_MCARE_ID": {"len": 20, "type": StringType()},
    "BILL_PROV_LAST_NM": {"len": 50, "type": StringType()},
    "BILL_PROV_FRIST_NM": {"len": 30, "type": StringType()},
    "BILL_PROV_NTWK": {"len": 10, "type": StringType()},
    "PCP_PROV_ID": {"len": 27, "type": StringType()},
    "PCP_PROV_SPEC": {"len": 2, "type": StringType()},
    "PCP_PROV_ZIP_CD": {"len": 5, "type": StringType()},
    "PCP_PROV_CTRY": {"len": 2, "type": StringType()},
    "REND_PROV_ID": {"len": 27, "type": StringType()},
    "REND_PROV_SPEC": {"len": 2, "type": StringType()},
    "REND_PROV_ZIP_CD": {"len": 5, "type": StringType()},
    "REND_PROV_CTRY": {"len": 2, "type": StringType()},
    "REND_PROV_TYP": {"len": 2, "type": StringType()},
    "REND_PROV_MCARE_ID": {"len": 20, "type": StringType()},
    "REND_PROV_LAST_NM": {"len": 50, "type": StringType()},
    "REND_PROV_FIRST_NM": {"len": 30, "type": StringType()},
    "REND_PROV_NTWK": {"len": 10, "type": StringType()},
    "ADM_DIAG": {"len": 7, "type": StringType()},
    "ICD_9_DIAG_CD_PRNCPL": {"len": 7, "type": StringType()},
    "ICD_9_DIAG_CD_SECAY_1": {"len": 7, "type": StringType()},
    "ICD_9_DIAG_CD_SECAY_2": {"len": 7, "type": StringType()},
    "ICD_9_DIAG_CD_SECAY_3": {"len": 7, "type": StringType()},
    "ICD_9_DIAG_CD_SECAY_4": {"len": 7, "type": StringType()},
    "ICD_9_DIAG_CD_SECAY_5": {"len": 7, "type": StringType()},
    "ICD_9_DIAG_CD_SECAY_6": {"len": 7, "type": StringType()},
    "ICD_9_DIAG_CD_SECAY_7": {"len": 7, "type": StringType()},
    "ICD_9_DIAG_CD_SECAY_8": {"len": 7, "type": StringType()},
    "ICD_9_DIAG_CD_SECAY_9": {"len": 7, "type": StringType()},
    "ICD_9_DIAG_CD_SECAY_10": {"len": 7, "type": StringType()},
    "PROC_CD_PRNCPL": {"len": 6, "type": StringType()},
    "PROC_DT_PRNCPL": {"len": 8, "type": StringType()},
    "PROC_CD_SEC_1": {"len": 6, "type": StringType()},
    "PROC_DT_1": {"len": 8, "type": StringType()},
    "PROC_CD_SEC_2": {"len": 6, "type": StringType()},
    "PROC_DT_2": {"len": 8, "type": StringType()},
    "PROC_CD_SEC_3": {"len": 6, "type": StringType()},
    "PROC_DT_3": {"len": 8, "type": StringType()},
    "PROC_CD_SEC_4": {"len": 6, "type": StringType()},
    "PROC_CD_DT_4": {"len": 8, "type": StringType()},
    "PROC_CD_SEC_5": {"len": 6, "type": StringType()},
    "PROC_DT_5": {"len": 8, "type": StringType()},
    "ADM_SRC_CD": {"len": 2, "type": StringType()},
    "ADM_TYP_CD": {"len": 2, "type": StringType()},
    "AUTH_ID": {"len": 15, "type": StringType()},
    "BNF_PAYMT_STTUS_CD": {"len": 1, "type": StringType()},
    "BILL_STTUS_CD": {"len": 1, "type": StringType()},
    "BRTHWT_CD": {"len": 3, "type": StringType()},
    "CAT_OF_SVC": {"len": 14, "type": StringType()},
    "CLM_SYS_DRG_CD": {"len": 4, "type": StringType()},
    "CLM_SYS_DRG_MDC_CD": {"len": 2, "type": StringType()},
    "CLM_SYS_APDRG_CD": {"len": 4, "type": StringType()},
    "CLM_SYS_APDRG_MDC_CD": {"len": 2, "type": StringType()},
    "CLM_PAYMT_STTUS": {"len": 1, "type": StringType()},
    "CLM_TYP": {"len": 2, "type": StringType()},
    "DSCHG_STTUS_CD": {"len": 2, "type": StringType()},
    "ITS_CLM_IN": {"len": 1, "type": StringType()},
    "NON_COV_RSN_CD_PRI": {"len": 2, "type": StringType()},
    "NON_COV_RSN_CD_2": {"len": 2, "type": StringType()},
    "NON_COV_RSN_CD_3": {"len": 2, "type": StringType()},
    "NON_COV_RSN_CD_4": {"len": 2, "type": StringType()},
    "POS": {"len": 2, "type": StringType()},
    "RMBRMT_TYP_CD": {"len": 5, "type": StringType()},
    "SUBMSN_TYP": {"len": 2, "type": StringType()},
    "TYP_OF_BILL_CD": {"len": 3, "type": StringType()},
    "ADJDCT_DT": {"len": 8, "type": StringType()},
    "CLM_ENTER_DT": {"len": 8, "type": StringType()},
    "CLM_PD_DT": {"len": 8, "type": StringType()},
    "CLM_RCVD_DT": {"len": 8, "type": StringType()},
    "FIRST_DT_OF_SVC": {"len": 8, "type": StringType()},
    "LAST_DT_OF_SVC": {"len": 8, "type": StringType()},
    "STMNT_FROM_DT": {"len": 8, "type": StringType()},
    "STMNT_THRU_DT": {"len": 8, "type": StringType()},
    "COV_DAYS_FOR_PAYMT": {"len": 3, "type": StringType()},
    "NON_COV_DAYS_FOR_PAYMT": {"len": 3, "type": StringType()},
    "SUBMT_AMT": {"len": 11, "type": StringType()},
    "NON_COV_AMT": {"len": 11, "type": StringType()},
    "ALW_AMT": {"len": 11, "type": StringType()},
    "PAYMT_AMT": {"len": 11, "type": StringType()},
    "COB_TPL_AMT": {"len": 11, "type": StringType()},
    "COINS": {"len": 11, "type": StringType()},
    "COPAY": {"len": 11, "type": StringType()},
    "DEDCT": {"len": 11, "type": StringType()},
    "NPI_ATND_PROV_ID": {"len": 10, "type": StringType()},
    "NPI_BILL_PROV_ID": {"len": 10, "type": StringType()},
    "NPI_PCP_PROV_ID": {"len": 10, "type": StringType()},
    "NPI_REND_PROV_ID": {"len": 10, "type": StringType()},
    "NON_CNTRED_HOLD_HRMLS_NGTNS_IN": {"len": 1, "type": StringType()},
    "BILL_PROV_CNTRING_STTUS_IN": {"len": 1, "type": StringType()},
    "REND_PROV_CNTRING_STTUS_IN": {"len": 1, "type": StringType()},
    "SCCF": {"len": 17, "type": StringType()},
    "ICD_10_ADM_DIAG": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_PRNCPL": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_1": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_2": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_3": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_4": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_5": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_6": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_7": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_8": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_9": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_10": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_PRNCPL": {"len": 7, "type": StringType()},
    "ICD_10_PROC_CD_SEC_1": {"len": 7, "type": StringType()},
    "ICD_10_PROC_CD_SEC_2": {"len": 7, "type": StringType()},
    "ICD_10_PROC_CD_SEC_3": {"len": 7, "type": StringType()},
    "ICD_10_PROC_CD_SEC_4": {"len": 7, "type": StringType()},
    "ICD_10_PROC_CD_SEC_5": {"len": 7, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_11": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_12": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_13": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_14": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_15": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_16": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_17": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_18": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_19": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_20": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_21": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_22": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_23": {"len": 8, "type": StringType()},
    "ICD_10_DIAG_CD_SEC_24": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_6": {"len": 7, "type": StringType()},
    "PROC_DT_6": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_7": {"len": 7, "type": StringType()},
    "PROC_DT_7": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_8": {"len": 7, "type": StringType()},
    "PROC_DT_8": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_9": {"len": 7, "type": StringType()},
    "PROC_DT_9": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_10": {"len": 7, "type": StringType()},
    "PROC_DT_10": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_11": {"len": 7, "type": StringType()},
    "PROC_DT_11": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_12": {"len": 7, "type": StringType()},
    "PROC_DT_12": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_13": {"len": 7, "type": StringType()},
    "PROC_DT_13": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_14": {"len": 7, "type": StringType()},
    "PROC_DT_14": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_15": {"len": 7, "type": StringType()},
    "PROC_DT_15": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_16": {"len": 7, "type": StringType()},
    "PROC_DT_16": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_17": {"len": 7, "type": StringType()},
    "PROC_DT_17": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_18": {"len": 7, "type": StringType()},
    "PROC_DT_18": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_19": {"len": 7, "type": StringType()},
    "PROC_DT_19": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_20": {"len": 7, "type": StringType()},
    "PROC_DT_20": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_21": {"len": 7, "type": StringType()},
    "PROC_DT_21": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_22": {"len": 7, "type": StringType()},
    "PROC_DT_22": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_23": {"len": 7, "type": StringType()},
    "PROC_DT_23": {"len": 8, "type": StringType()},
    "ICD_10_PROC_CD_SEC_24": {"len": 7, "type": StringType()},
    "PROC_DT_24": {"len": 8, "type": StringType()},
    "POA_CD_PRINCIPLE": {"len": 1, "type": StringType()},
    "POA_CD_SEC_1": {"len": 1, "type": StringType()},
    "POA_CD_SEC_2": {"len": 1, "type": StringType()},
    "POA_CD_SEC_3": {"len": 1, "type": StringType()},
    "POA_CD_SEC_4": {"len": 1, "type": StringType()},
    "POA_CD_SEC_5": {"len": 1, "type": StringType()},
    "POA_CD_SEC_6": {"len": 1, "type": StringType()},
    "POA_CD_SEC_7": {"len": 1, "type": StringType()},
    "POA_CD_SEC_8": {"len": 1, "type": StringType()},
    "POA_CD_SEC_9": {"len": 1, "type": StringType()},
    "POA_CD_SEC_10": {"len": 1, "type": StringType()},
    "POA_CD_SEC_11": {"len": 1, "type": StringType()},
    "POA_CD_SEC_12": {"len": 1, "type": StringType()},
    "POA_CD_SEC_13": {"len": 1, "type": StringType()},
    "POA_CD_SEC_14": {"len": 1, "type": StringType()},
    "POA_CD_SEC_15": {"len": 1, "type": StringType()},
    "POA_CD_SEC_16": {"len": 1, "type": StringType()},
    "POA_CD_SEC_17": {"len": 1, "type": StringType()},
    "POA_CD_SEC_18": {"len": 1, "type": StringType()},
    "POA_CD_SEC_19": {"len": 1, "type": StringType()},
    "POA_CD_SEC_20": {"len": 1, "type": StringType()},
    "POA_CD_SEC_21": {"len": 1, "type": StringType()},
    "POA_CD_SEC_22": {"len": 1, "type": StringType()},
    "POA_CD_SEC_23": {"len": 1, "type": StringType()},
    "POA_CD_SEC_24": {"len": 1, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_1": {"len": 8, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_2": {"len": 8, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_3": {"len": 8, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_4": {"len": 8, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_5": {"len": 8, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_6": {"len": 8, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_7": {"len": 8, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_8": {"len": 8, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_9": {"len": 8, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_10": {"len": 8, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_11": {"len": 8, "type": StringType()},
    "EXTRNL_CAUSE_OF_INJRY_CD_12": {"len": 8, "type": StringType()},
    "PATN_RSN_FOR_VST_CD_1": {"len": 8, "type": StringType()},
    "PATN_RSN_FOR_VST_CD_2": {"len": 8, "type": StringType()},
    "PATN_RSN_FOR_VST_CD_3": {"len": 8, "type": StringType()},
    "BILL_PROV_TXNMY_CD": {"len": 15, "type": StringType()},
    "ATND_PROV_TXNMY_CD": {"len": 15, "type": StringType()},
    "REND_PROV_TXNMY_CD": {"len": 15, "type": StringType()},
    "SBSTNC_USE_RCRD_IN": {"len": 1, "type": StringType()}
}

df_std_inp_claim_headers = fixed_file_read_write(
    f"{adls_path_publish}/external/std_inp_claim_headers",
    col_details,
    "read"
)

df_FTP_std_inp_claim_headers = df_std_inp_claim_headers

df_FTP_std_inp_claim_headers_final = df_FTP_std_inp_claim_headers.select(
    rpad(col("BHI_HOME_PLN_ID"), 3, " ").alias("BHI_HOME_PLN_ID"),
    rpad(col("CLM_ID"), 25, " ").alias("CLM_ID"),
    rpad(col("TRACEABILITY_FLD"), 5, " ").alias("TRACEABILITY_FLD"),
    rpad(col("ADJ_SEQ_NO"), 8, " ").alias("ADJ_SEQ_NO"),
    rpad(col("HOST_PLN_ID"), 3, " ").alias("HOST_PLN_ID"),
    rpad(col("HOME_PLN_PROD_ID"), 15, " ").alias("HOME_PLN_PROD_ID"),
    rpad(col("ACCT"), 14, " ").alias("ACCT"),
    rpad(col("GRP_ID"), 14, " ").alias("GRP_ID"),
    rpad(col("SUB_GRP_ID"), 10, " ").alias("SUB_GRP_ID"),
    rpad(col("MBR_ID"), 22, " ").alias("MBR_ID"),
    rpad(col("MBR_ZIP_CD_ON_CLM"), 5, " ").alias("MBR_ZIP_CD_ON_CLM"),
    rpad(col("MBR_CTRY_ON_CLM"), 2, " ").alias("MBR_CTRY_ON_CLM"),
    rpad(col("ATND_PROV_IDENTFIER"), 27, " ").alias("ATND_PROV_IDENTFIER"),
    rpad(col("ATND_PROV_SPEC"), 2, " ").alias("ATND_PROV_SPEC"),
    rpad(col("ATND_PROV_ZIP"), 5, " ").alias("ATND_PROV_ZIP"),
    rpad(col("ATND_PROV_CTRY"), 2, " ").alias("ATND_PROV_CTRY"),
    rpad(col("BILL_PROV_ID"), 27, " ").alias("BILL_PROV_ID"),
    rpad(col("BILL_PROV_SPEC"), 2, " ").alias("BILL_PROV_SPEC"),
    rpad(col("BILL_PROV_ZIP_CD"), 5, " ").alias("BILL_PROV_ZIP_CD"),
    rpad(col("BILL_PROV_CTRY"), 2, " ").alias("BILL_PROV_CTRY"),
    rpad(col("BILL_PROV_TAX_ID"), 12, " ").alias("BILL_PROV_TAX_ID"),
    rpad(col("BILL_PROV_MCARE_ID"), 20, " ").alias("BILL_PROV_MCARE_ID"),
    rpad(col("BILL_PROV_LAST_NM"), 50, " ").alias("BILL_PROV_LAST_NM"),
    rpad(col("BILL_PROV_FRIST_NM"), 30, " ").alias("BILL_PROV_FRIST_NM"),
    rpad(col("BILL_PROV_NTWK"), 10, " ").alias("BILL_PROV_NTWK"),
    rpad(col("PCP_PROV_ID"), 27, " ").alias("PCP_PROV_ID"),
    rpad(col("PCP_PROV_SPEC"), 2, " ").alias("PCP_PROV_SPEC"),
    rpad(col("PCP_PROV_ZIP_CD"), 5, " ").alias("PCP_PROV_ZIP_CD"),
    rpad(col("PCP_PROV_CTRY"), 2, " ").alias("PCP_PROV_CTRY"),
    rpad(col("REND_PROV_ID"), 27, " ").alias("REND_PROV_ID"),
    rpad(col("REND_PROV_SPEC"), 2, " ").alias("REND_PROV_SPEC"),
    rpad(col("REND_PROV_ZIP_CD"), 5, " ").alias("REND_PROV_ZIP_CD"),
    rpad(col("REND_PROV_CTRY"), 2, " ").alias("REND_PROV_CTRY"),
    rpad(col("REND_PROV_TYP"), 2, " ").alias("REND_PROV_TYP"),
    rpad(col("REND_PROV_MCARE_ID"), 20, " ").alias("REND_PROV_MCARE_ID"),
    rpad(col("REND_PROV_LAST_NM"), 50, " ").alias("REND_PROV_LAST_NM"),
    rpad(col("REND_PROV_FIRST_NM"), 30, " ").alias("REND_PROV_FIRST_NM"),
    rpad(col("REND_PROV_NTWK"), 10, " ").alias("REND_PROV_NTWK"),
    rpad(col("ADM_DIAG"), 7, " ").alias("ADM_DIAG"),
    rpad(col("ICD_9_DIAG_CD_PRNCPL"), 7, " ").alias("ICD_9_DIAG_CD_PRNCPL"),
    rpad(col("ICD_9_DIAG_CD_SECAY_1"), 7, " ").alias("ICD_9_DIAG_CD_SECAY_1"),
    rpad(col("ICD_9_DIAG_CD_SECAY_2"), 7, " ").alias("ICD_9_DIAG_CD_SECAY_2"),
    rpad(col("ICD_9_DIAG_CD_SECAY_3"), 7, " ").alias("ICD_9_DIAG_CD_SECAY_3"),
    rpad(col("ICD_9_DIAG_CD_SECAY_4"), 7, " ").alias("ICD_9_DIAG_CD_SECAY_4"),
    rpad(col("ICD_9_DIAG_CD_SECAY_5"), 7, " ").alias("ICD_9_DIAG_CD_SECAY_5"),
    rpad(col("ICD_9_DIAG_CD_SECAY_6"), 7, " ").alias("ICD_9_DIAG_CD_SECAY_6"),
    rpad(col("ICD_9_DIAG_CD_SECAY_7"), 7, " ").alias("ICD_9_DIAG_CD_SECAY_7"),
    rpad(col("ICD_9_DIAG_CD_SECAY_8"), 7, " ").alias("ICD_9_DIAG_CD_SECAY_8"),
    rpad(col("ICD_9_DIAG_CD_SECAY_9"), 7, " ").alias("ICD_9_DIAG_CD_SECAY_9"),
    rpad(col("ICD_9_DIAG_CD_SECAY_10"), 7, " ").alias("ICD_9_DIAG_CD_SECAY_10"),
    rpad(col("PROC_CD_PRNCPL"), 6, " ").alias("PROC_CD_PRNCPL"),
    rpad(col("PROC_DT_PRNCPL"), 8, " ").alias("PROC_DT_PRNCPL"),
    rpad(col("PROC_CD_SEC_1"), 6, " ").alias("PROC_CD_SEC_1"),
    rpad(col("PROC_DT_1"), 8, " ").alias("PROC_DT_1"),
    rpad(col("PROC_CD_SEC_2"), 6, " ").alias("PROC_CD_SEC_2"),
    rpad(col("PROC_DT_2"), 8, " ").alias("PROC_DT_2"),
    rpad(col("PROC_CD_SEC_3"), 6, " ").alias("PROC_CD_SEC_3"),
    rpad(col("PROC_DT_3"), 8, " ").alias("PROC_DT_3"),
    rpad(col("PROC_CD_SEC_4"), 6, " ").alias("PROC_CD_SEC_4"),
    rpad(col("PROC_CD_DT_4"), 8, " ").alias("PROC_CD_DT_4"),
    rpad(col("PROC_CD_SEC_5"), 6, " ").alias("PROC_CD_SEC_5"),
    rpad(col("PROC_DT_5"), 8, " ").alias("PROC_DT_5"),
    rpad(col("ADM_SRC_CD"), 2, " ").alias("ADM_SRC_CD"),
    rpad(col("ADM_TYP_CD"), 2, " ").alias("ADM_TYP_CD"),
    rpad(col("AUTH_ID"), 15, " ").alias("AUTH_ID"),
    rpad(col("BNF_PAYMT_STTUS_CD"), 1, " ").alias("BNF_PAYMT_STTUS_CD"),
    rpad(col("BILL_STTUS_CD"), 1, " ").alias("BILL_STTUS_CD"),
    rpad(col("BRTHWT_CD"), 3, " ").alias("BRTHWT_CD"),
    rpad(col("CAT_OF_SVC"), 14, " ").alias("CAT_OF_SVC"),
    rpad(col("CLM_SYS_DRG_CD"), 4, " ").alias("CLM_SYS_DRG_CD"),
    rpad(col("CLM_SYS_DRG_MDC_CD"), 2, " ").alias("CLM_SYS_DRG_MDC_CD"),
    rpad(col("CLM_SYS_APDRG_CD"), 4, " ").alias("CLM_SYS_APDRG_CD"),
    rpad(col("CLM_SYS_APDRG_MDC_CD"), 2, " ").alias("CLM_SYS_APDRG_MDC_CD"),
    rpad(col("CLM_PAYMT_STTUS"), 1, " ").alias("CLM_PAYMT_STTUS"),
    rpad(col("CLM_TYP"), 2, " ").alias("CLM_TYP"),
    rpad(col("DSCHG_STTUS_CD"), 2, " ").alias("DSCHG_STTUS_CD"),
    rpad(col("ITS_CLM_IN"), 1, " ").alias("ITS_CLM_IN"),
    rpad(col("NON_COV_RSN_CD_PRI"), 2, " ").alias("NON_COV_RSN_CD_PRI"),
    rpad(col("NON_COV_RSN_CD_2"), 2, " ").alias("NON_COV_RSN_CD_2"),
    rpad(col("NON_COV_RSN_CD_3"), 2, " ").alias("NON_COV_RSN_CD_3"),
    rpad(col("NON_COV_RSN_CD_4"), 2, " ").alias("NON_COV_RSN_CD_4"),
    rpad(col("POS"), 2, " ").alias("POS"),
    rpad(col("RMBRMT_TYP_CD"), 5, " ").alias("RMBRMT_TYP_CD"),
    rpad(col("SUBMSN_TYP"), 2, " ").alias("SUBMSN_TYP"),
    rpad(col("TYP_OF_BILL_CD"), 3, " ").alias("TYP_OF_BILL_CD"),
    rpad(col("ADJDCT_DT"), 8, " ").alias("ADJDCT_DT"),
    rpad(col("CLM_ENTER_DT"), 8, " ").alias("CLM_ENTER_DT"),
    rpad(col("CLM_PD_DT"), 8, " ").alias("CLM_PD_DT"),
    rpad(col("CLM_RCVD_DT"), 8, " ").alias("CLM_RCVD_DT"),
    rpad(col("FIRST_DT_OF_SVC"), 8, " ").alias("FIRST_DT_OF_SVC"),
    rpad(col("LAST_DT_OF_SVC"), 8, " ").alias("LAST_DT_OF_SVC"),
    rpad(col("STMNT_FROM_DT"), 8, " ").alias("STMNT_FROM_DT"),
    rpad(col("STMNT_THRU_DT"), 8, " ").alias("STMNT_THRU_DT"),
    rpad(col("COV_DAYS_FOR_PAYMT"), 3, " ").alias("COV_DAYS_FOR_PAYMT"),
    rpad(col("NON_COV_DAYS_FOR_PAYMT"), 3, " ").alias("NON_COV_DAYS_FOR_PAYMT"),
    rpad(col("SUBMT_AMT"), 11, " ").alias("SUBMT_AMT"),
    rpad(col("NON_COV_AMT"), 11, " ").alias("NON_COV_AMT"),
    rpad(col("ALW_AMT"), 11, " ").alias("ALW_AMT"),
    rpad(col("PAYMT_AMT"), 11, " ").alias("PAYMT_AMT"),
    rpad(col("COB_TPL_AMT"), 11, " ").alias("COB_TPL_AMT"),
    rpad(col("COINS"), 11, " ").alias("COINS"),
    rpad(col("COPAY"), 11, " ").alias("COPAY"),
    rpad(col("DEDCT"), 11, " ").alias("DEDCT"),
    rpad(col("NPI_ATND_PROV_ID"), 10, " ").alias("NPI_ATND_PROV_ID"),
    rpad(col("NPI_BILL_PROV_ID"), 10, " ").alias("NPI_BILL_PROV_ID"),
    rpad(col("NPI_PCP_PROV_ID"), 10, " ").alias("NPI_PCP_PROV_ID"),
    rpad(col("NPI_REND_PROV_ID"), 10, " ").alias("NPI_REND_PROV_ID"),
    rpad(col("NON_CNTRED_HOLD_HRMLS_NGTNS_IN"), 1, " ").alias("NON_CNTRED_HOLD_HRMLS_NGTNS_IN"),
    rpad(col("BILL_PROV_CNTRING_STTUS_IN"), 1, " ").alias("BILL_PROV_CNTRING_STTUS_IN"),
    rpad(col("REND_PROV_CNTRING_STTUS_IN"), 1, " ").alias("REND_PROV_CNTRING_STTUS_IN"),
    rpad(col("SCCF"), 17, " ").alias("SCCF"),
    rpad(col("ICD_10_ADM_DIAG"), 8, " ").alias("ICD_10_ADM_DIAG"),
    rpad(col("ICD_10_DIAG_CD_PRNCPL"), 8, " ").alias("ICD_10_DIAG_CD_PRNCPL"),
    rpad(col("ICD_10_DIAG_CD_SEC_1"), 8, " ").alias("ICD_10_DIAG_CD_SEC_1"),
    rpad(col("ICD_10_DIAG_CD_SEC_2"), 8, " ").alias("ICD_10_DIAG_CD_SEC_2"),
    rpad(col("ICD_10_DIAG_CD_SEC_3"), 8, " ").alias("ICD_10_DIAG_CD_SEC_3"),
    rpad(col("ICD_10_DIAG_CD_SEC_4"), 8, " ").alias("ICD_10_DIAG_CD_SEC_4"),
    rpad(col("ICD_10_DIAG_CD_SEC_5"), 8, " ").alias("ICD_10_DIAG_CD_SEC_5"),
    rpad(col("ICD_10_DIAG_CD_SEC_6"), 8, " ").alias("ICD_10_DIAG_CD_SEC_6"),
    rpad(col("ICD_10_DIAG_CD_SEC_7"), 8, " ").alias("ICD_10_DIAG_CD_SEC_7"),
    rpad(col("ICD_10_DIAG_CD_SEC_8"), 8, " ").alias("ICD_10_DIAG_CD_SEC_8"),
    rpad(col("ICD_10_DIAG_CD_SEC_9"), 8, " ").alias("ICD_10_DIAG_CD_SEC_9"),
    rpad(col("ICD_10_DIAG_CD_SEC_10"), 8, " ").alias("ICD_10_DIAG_CD_SEC_10"),
    rpad(col("ICD_10_PROC_CD_PRNCPL"), 7, " ").alias("ICD_10_PROC_CD_PRNCPL"),
    rpad(col("ICD_10_PROC_CD_SEC_1"), 7, " ").alias("ICD_10_PROC_CD_SEC_1"),
    rpad(col("ICD_10_PROC_CD_SEC_2"), 7, " ").alias("ICD_10_PROC_CD_SEC_2"),
    rpad(col("ICD_10_PROC_CD_SEC_3"), 7, " ").alias("ICD_10_PROC_CD_SEC_3"),
    rpad(col("ICD_10_PROC_CD_SEC_4"), 7, " ").alias("ICD_10_PROC_CD_SEC_4"),
    rpad(col("ICD_10_PROC_CD_SEC_5"), 7, " ").alias("ICD_10_PROC_CD_SEC_5"),
    rpad(col("ICD_10_DIAG_CD_SEC_11"), 8, " ").alias("ICD_10_DIAG_CD_SEC_11"),
    rpad(col("ICD_10_DIAG_CD_SEC_12"), 8, " ").alias("ICD_10_DIAG_CD_SEC_12"),
    rpad(col("ICD_10_DIAG_CD_SEC_13"), 8, " ").alias("ICD_10_DIAG_CD_SEC_13"),
    rpad(col("ICD_10_DIAG_CD_SEC_14"), 8, " ").alias("ICD_10_DIAG_CD_SEC_14"),
    rpad(col("ICD_10_DIAG_CD_SEC_15"), 8, " ").alias("ICD_10_DIAG_CD_SEC_15"),
    rpad(col("ICD_10_DIAG_CD_SEC_16"), 8, " ").alias("ICD_10_DIAG_CD_SEC_16"),
    rpad(col("ICD_10_DIAG_CD_SEC_17"), 8, " ").alias("ICD_10_DIAG_CD_SEC_17"),
    rpad(col("ICD_10_DIAG_CD_SEC_18"), 8, " ").alias("ICD_10_DIAG_CD_SEC_18"),
    rpad(col("ICD_10_DIAG_CD_SEC_19"), 8, " ").alias("ICD_10_DIAG_CD_SEC_19"),
    rpad(col("ICD_10_DIAG_CD_SEC_20"), 8, " ").alias("ICD_10_DIAG_CD_SEC_20"),
    rpad(col("ICD_10_DIAG_CD_SEC_21"), 8, " ").alias("ICD_10_DIAG_CD_SEC_21"),
    rpad(col("ICD_10_DIAG_CD_SEC_22"), 8, " ").alias("ICD_10_DIAG_CD_SEC_22"),
    rpad(col("ICD_10_DIAG_CD_SEC_23"), 8, " ").alias("ICD_10_DIAG_CD_SEC_23"),
    rpad(col("ICD_10_DIAG_CD_SEC_24"), 8, " ").alias("ICD_10_DIAG_CD_SEC_24"),
    rpad(col("ICD_10_PROC_CD_SEC_6"), 7, " ").alias("ICD_10_PROC_CD_SEC_6"),
    rpad(col("PROC_DT_6"), 8, " ").alias("PROC_DT_6"),
    rpad(col("ICD_10_PROC_CD_SEC_7"), 7, " ").alias("ICD_10_PROC_CD_SEC_7"),
    rpad(col("PROC_DT_7"), 8, " ").alias("PROC_DT_7"),
    rpad(col("ICD_10_PROC_CD_SEC_8"), 7, " ").alias("ICD_10_PROC_CD_SEC_8"),
    rpad(col("PROC_DT_8"), 8, " ").alias("PROC_DT_8"),
    rpad(col("ICD_10_PROC_CD_SEC_9"), 7, " ").alias("ICD_10_PROC_CD_SEC_9"),
    rpad(col("PROC_DT_9"), 8, " ").alias("PROC_DT_9"),
    rpad(col("ICD_10_PROC_CD_SEC_10"), 7, " ").alias("ICD_10_PROC_CD_SEC_10"),
    rpad(col("PROC_DT_10"), 8, " ").alias("PROC_DT_10"),
    rpad(col("ICD_10_PROC_CD_SEC_11"), 7, " ").alias("ICD_10_PROC_CD_SEC_11"),
    rpad(col("PROC_DT_11"), 8, " ").alias("PROC_DT_11"),
    rpad(col("ICD_10_PROC_CD_SEC_12"), 7, " ").alias("ICD_10_PROC_CD_SEC_12"),
    rpad(col("PROC_DT_12"), 8, " ").alias("PROC_DT_12"),
    rpad(col("ICD_10_PROC_CD_SEC_13"), 7, " ").alias("ICD_10_PROC_CD_SEC_13"),
    rpad(col("PROC_DT_13"), 8, " ").alias("PROC_DT_13"),
    rpad(col("ICD_10_PROC_CD_SEC_14"), 7, " ").alias("ICD_10_PROC_CD_SEC_14"),
    rpad(col("PROC_DT_14"), 8, " ").alias("PROC_DT_14"),
    rpad(col("ICD_10_PROC_CD_SEC_15"), 7, " ").alias("ICD_10_PROC_CD_SEC_15"),
    rpad(col("PROC_DT_15"), 8, " ").alias("PROC_DT_15"),
    rpad(col("ICD_10_PROC_CD_SEC_16"), 7, " ").alias("ICD_10_PROC_CD_SEC_16"),
    rpad(col("PROC_DT_16"), 8, " ").alias("PROC_DT_16"),
    rpad(col("ICD_10_PROC_CD_SEC_17"), 7, " ").alias("ICD_10_PROC_CD_SEC_17"),
    rpad(col("PROC_DT_17"), 8, " ").alias("PROC_DT_17"),
    rpad(col("ICD_10_PROC_CD_SEC_18"), 7, " ").alias("ICD_10_PROC_CD_SEC_18"),
    rpad(col("PROC_DT_18"), 8, " ").alias("PROC_DT_18"),
    rpad(col("ICD_10_PROC_CD_SEC_19"), 7, " ").alias("ICD_10_PROC_CD_SEC_19"),
    rpad(col("PROC_DT_19"), 8, " ").alias("PROC_DT_19"),
    rpad(col("ICD_10_PROC_CD_SEC_20"), 7, " ").alias("ICD_10_PROC_CD_SEC_20"),
    rpad(col("PROC_DT_20"), 8, " ").alias("PROC_DT_20"),
    rpad(col("ICD_10_PROC_CD_SEC_21"), 7, " ").alias("ICD_10_PROC_CD_SEC_21"),
    rpad(col("PROC_DT_21"), 8, " ").alias("PROC_DT_21"),
    rpad(col("ICD_10_PROC_CD_SEC_22"), 7, " ").alias("ICD_10_PROC_CD_SEC_22"),
    rpad(col("PROC_DT_22"), 8, " ").alias("PROC_DT_22"),
    rpad(col("ICD_10_PROC_CD_SEC_23"), 7, " ").alias("ICD_10_PROC_CD_SEC_23"),
    rpad(col("PROC_DT_23"), 8, " ").alias("PROC_DT_23"),
    rpad(col("ICD_10_PROC_CD_SEC_24"), 7, " ").alias("ICD_10_PROC_CD_SEC_24"),
    rpad(col("PROC_DT_24"), 8, " ").alias("PROC_DT_24"),
    rpad(col("POA_CD_PRINCIPLE"), 1, " ").alias("POA_CD_PRINCIPLE"),
    rpad(col("POA_CD_SEC_1"), 1, " ").alias("POA_CD_SEC_1"),
    rpad(col("POA_CD_SEC_2"), 1, " ").alias("POA_CD_SEC_2"),
    rpad(col("POA_CD_SEC_3"), 1, " ").alias("POA_CD_SEC_3"),
    rpad(col("POA_CD_SEC_4"), 1, " ").alias("POA_CD_SEC_4"),
    rpad(col("POA_CD_SEC_5"), 1, " ").alias("POA_CD_SEC_5"),
    rpad(col("POA_CD_SEC_6"), 1, " ").alias("POA_CD_SEC_6"),
    rpad(col("POA_CD_SEC_7"), 1, " ").alias("POA_CD_SEC_7"),
    rpad(col("POA_CD_SEC_8"), 1, " ").alias("POA_CD_SEC_8"),
    rpad(col("POA_CD_SEC_9"), 1, " ").alias("POA_CD_SEC_9"),
    rpad(col("POA_CD_SEC_10"), 1, " ").alias("POA_CD_SEC_10"),
    rpad(col("POA_CD_SEC_11"), 1, " ").alias("POA_CD_SEC_11"),
    rpad(col("POA_CD_SEC_12"), 1, " ").alias("POA_CD_SEC_12"),
    rpad(col("POA_CD_SEC_13"), 1, " ").alias("POA_CD_SEC_13"),
    rpad(col("POA_CD_SEC_14"), 1, " ").alias("POA_CD_SEC_14"),
    rpad(col("POA_CD_SEC_15"), 1, " ").alias("POA_CD_SEC_15"),
    rpad(col("POA_CD_SEC_16"), 1, " ").alias("POA_CD_SEC_16"),
    rpad(col("POA_CD_SEC_17"), 1, " ").alias("POA_CD_SEC_17"),
    rpad(col("POA_CD_SEC_18"), 1, " ").alias("POA_CD_SEC_18"),
    rpad(col("POA_CD_SEC_19"), 1, " ").alias("POA_CD_SEC_19"),
    rpad(col("POA_CD_SEC_20"), 1, " ").alias("POA_CD_SEC_20"),
    rpad(col("POA_CD_SEC_21"), 1, " ").alias("POA_CD_SEC_21"),
    rpad(col("POA_CD_SEC_22"), 1, " ").alias("POA_CD_SEC_22"),
    rpad(col("POA_CD_SEC_23"), 1, " ").alias("POA_CD_SEC_23"),
    rpad(col("POA_CD_SEC_24"), 1, " ").alias("POA_CD_SEC_24"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_1"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_1"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_2"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_2"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_3"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_3"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_4"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_4"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_5"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_5"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_6"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_6"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_7"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_7"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_8"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_8"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_9"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_9"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_10"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_10"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_11"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_11"),
    rpad(col("EXTRNL_CAUSE_OF_INJRY_CD_12"), 8, " ").alias("EXTRNL_CAUSE_OF_INJRY_CD_12"),
    rpad(col("PATN_RSN_FOR_VST_CD_1"), 8, " ").alias("PATN_RSN_FOR_VST_CD_1"),
    rpad(col("PATN_RSN_FOR_VST_CD_2"), 8, " ").alias("PATN_RSN_FOR_VST_CD_2"),
    rpad(col("PATN_RSN_FOR_VST_CD_3"), 8, " ").alias("PATN_RSN_FOR_VST_CD_3"),
    rpad(col("BILL_PROV_TXNMY_CD"), 15, " ").alias("BILL_PROV_TXNMY_CD"),
    rpad(col("ATND_PROV_TXNMY_CD"), 15, " ").alias("ATND_PROV_TXNMY_CD"),
    rpad(col("REND_PROV_TXNMY_CD"), 15, " ").alias("REND_PROV_TXNMY_CD"),
    rpad(col("SBSTNC_USE_RCRD_IN"), 1, " ").alias("SBSTNC_USE_RCRD_IN")
)

# The final DataFrame after FTP stage is df_FTP_std_inp_claim_headers_final.
# No additional write operation is specified in the job.