module.exports = {
  ROLES: {
    STUDY_ADMIN: 'STUDY_ADMIN',
    STUDY_DESIGNER: 'STUDY_DESIGNER',
    CRC: 'CRC',
    PI: 'PI',
    DATA_MANAGER: 'DATA_MANAGER',
    CRA_MONITOR: 'CRA_MONITOR',
    READ_ONLY: 'READ_ONLY',
    AUDITOR: 'AUDITOR'
  },

  STUDY_PHASES: {
    STARTUP: 'STARTUP',
    CONDUCT: 'CONDUCT',
    CLOSEOUT: 'CLOSEOUT'
  },

  FORM_STATUS: {
    DRAFT: 'DRAFT',
    UAT: 'UAT',
    PRODUCTION: 'PRODUCTION',
    DEPRECATED: 'DEPRECATED'
  },

  DATA_ENTRY_STATUS: {
    IN_PROGRESS: 'IN_PROGRESS',
    SUBMITTED: 'SUBMITTED',
    VERIFIED: 'VERIFIED',
    LOCKED: 'LOCKED'
  },

  QUERY_STATUS: {
    OPEN: 'OPEN',
    ASSIGNED: 'ASSIGNED',
    SITE_ANSWERED: 'SITE_ANSWERED',
    DM_REVIEWED: 'DM_REVIEWED',
    RESOLVED: 'RESOLVED',
    CLOSED: 'CLOSED',
    ACCEPTED_AS_VALID: 'ACCEPTED_AS_VALID'
  },

  QUERY_SEVERITY: {
    HARD_ERROR: 'HARD_ERROR',
    WARNING: 'WARNING',
    NOTE: 'NOTE'
  },

  SUBJECT_STATUS: {
    SCREENED: 'SCREENED',
    ENROLLED: 'ENROLLED',
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED',
    WITHDRAWN: 'WITHDRAWN',
    DISCONTINUED: 'DISCONTINUED'
  },

  VISIT_STATUS: {
    PLANNED: 'PLANNED',
    SCHEDULED: 'SCHEDULED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    MISSED: 'MISSED',
    UNSCHEDULED: 'UNSCHEDULED'
  },

  FIELD_TYPES: {
    TEXT: 'TEXT',
    INTEGER: 'INTEGER',
    DECIMAL: 'DECIMAL',
    DATE: 'DATE',
    DATETIME: 'DATETIME',
    DROPDOWN: 'DROPDOWN',
    RADIO: 'RADIO',
    CHECKBOX: 'CHECKBOX',
    MULTI_SELECT: 'MULTI_SELECT',
    FILE_UPLOAD: 'FILE_UPLOAD',
    CALCULATED: 'CALCULATED',
    TEXTAREA: 'TEXTAREA'
  },

  UAT_DEFECT_STATUS: {
    OPEN: 'OPEN',
    IN_PROGRESS: 'IN_PROGRESS',
    FIXED: 'FIXED',
    RE_TESTED: 'RE_TESTED',
    CLOSED: 'CLOSED'
  },

  AUDIT_ACTIONS: {
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    VIEW: 'VIEW',
    EXPORT: 'EXPORT',
    LOCK: 'LOCK',
    UNLOCK: 'UNLOCK',
    SIGN: 'SIGN',
    APPROVE: 'APPROVE',
    REJECT: 'REJECT',
    QUERY_RAISED: 'QUERY_RAISED',
    QUERY_ANSWERED: 'QUERY_ANSWERED',
    QUERY_CLOSED: 'QUERY_CLOSED'
  },

  EXPORT_FORMATS: {
    CSV: 'CSV',
    XLSX: 'XLSX',
    XML: 'XML',
    JSON: 'JSON',
    CDISC_SDTM: 'CDISC_SDTM',
    CDISC_ADAM: 'CDISC_ADAM',
    PDF: 'PDF'
  },

  PERMISSIONS: {
    // Study Management
    CREATE_STUDY: 'CREATE_STUDY',
    VIEW_STUDY: 'VIEW_STUDY',
    UPDATE_STUDY: 'UPDATE_STUDY',
    DELETE_STUDY: 'DELETE_STUDY',
    LOCK_STUDY: 'LOCK_STUDY',
    
    // Form Management
    CREATE_FORM: 'CREATE_FORM',
    VIEW_FORM: 'VIEW_FORM',
    UPDATE_FORM: 'UPDATE_FORM',
    DELETE_FORM: 'DELETE_FORM',
    PROMOTE_FORM: 'PROMOTE_FORM',
    
    // Data Entry
    ENTER_DATA: 'ENTER_DATA',
    VIEW_DATA: 'VIEW_DATA',
    UPDATE_DATA: 'UPDATE_DATA',
    DELETE_DATA: 'DELETE_DATA',
    LOCK_DATA: 'LOCK_DATA',
    
    // Query Management
    RAISE_QUERY: 'RAISE_QUERY',
    VIEW_QUERY: 'VIEW_QUERY',
    ANSWER_QUERY: 'ANSWER_QUERY',
    CLOSE_QUERY: 'CLOSE_QUERY',
    
    // Export
    EXPORT_DATA: 'EXPORT_DATA',
    EXPORT_AUDIT: 'EXPORT_AUDIT',
    
    // User Management
    CREATE_USER: 'CREATE_USER',
    VIEW_USER: 'VIEW_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    
    // System Administration
    SYSTEM_CONFIG: 'SYSTEM_CONFIG',
    VIEW_AUDIT: 'VIEW_AUDIT'
  }
};