# Databricks notebook source
# MAGIC %md
# MAGIC **Date:** 2025-08-24
# MAGIC """
# MAGIC Â© Copyright 2011, 2013, 2022 Blue Cross and Blue Shield of Kansas City
# MAGIC 
# MAGIC JOB NAME:  IdsProviderMbrBioMesrRsltExtr
# MAGIC CALLED BY: IdsProvMbrBioMesrRsltExtrSeq
# MAGIC 
# MAGIC Processing: This job reads the "FORMAT" file generated by the job ProviderMbrBioMesrSecondaryMbrMatch, applies some transformations to massage that data, and get it into the format to be loaded into the MBR_BIO_MESR_RSLT table.
# MAGIC 
# MAGIC Control Job Rerun Information: 
# MAGIC                     Previous Run Successful:    Restart, no other steps necessary
# MAGIC                     Previous Run Aborted:         Restart, no other steps necessary
# MAGIC 
# MAGIC Modifications:                        
# MAGIC =============================================================================================================================================================================================
# MAGIC Developer\(9)\(9)Date\(9)\(9)Project/Altiris #\(9)Change Description\(9)\(9)\(9)\(9)\(9)\(9)Development Project\(9)\(9)Code Reviewer\(9)\(9)Date Reviewed
# MAGIC =============================================================================================================================================================================================
# MAGIC Naveen Nallamothu      \(9)2021-02-18       \(9)US_311874\(9)Original Programming\(9)\(9)\(9)    \(9)\(9)IntegrateDev2\(9)               \(9)\(9)Manasa Andru    \(9)\(9)2021-02-26
# MAGIC Lakshmi Devagiri          \(9)2021-03-29        \(9)US364108\(9)Updated input file format to exclude double quotes     \(9)\(9)IntegrateDev2\(9)\(9)\(9)Kalyan Neelam                 \(9)2021-03-31
# MAGIC Lakshmi Devagiri    \(9)     \(9)2021-04-26       \(9)US373622      \(9)Updated Member query to Ignore Case                      \(9)\(9)IntegrateDev2                  \(9)\(9)Jaideep Mankala              \(9)04/27/2021
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)on First Name and Last Name                                           
# MAGIC Abhishek Pulluri           \(9)2021-06-21       \(9)379170\(9)\(9)Updated Upcase to Columns Pol_No and Mtrc  \(9)\(9)\(9)IntegrateDev2               \(9)\(9)Manasa Andru       \(9)\(9)2021-06-23
# MAGIC Ken Bradmon\(9)\(9)2022-08-29\(9)us542424\(9)\(9)Removed the check for NULL Gender values, so those              \(9)IntegrateDev2                         \(9)\(9)Goutham Kalidindi                    2022-09-13
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)records won't get sent to the error file.
# MAGIC Ken Bradmon\(9)\(9)2024-02-16\(9)us611146\(9)\(9)A new column was added to the "format" file created by the\(9)\(9)IntegrateDev2                         \(9)\(9)Goutham Kalidindi                    2024-03-01
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)ProviderMbrBioMesrSecondaryMbrMatch job.  We don't need 
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)this column for anything in THIS job, but added that column anyway,
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)so the file format of this job matches the member match job.

# MAGIC JOB NAME:  IdsProviderMbrBioMesrRsltExtr
# MAGIC CALLED BY: IdsProvMbrBioMesrRsltExtrSeq
# MAGIC 
# MAGIC Processing: This job reads the "FORMAT" file generated by the job ProviderMbrBioMesrSecondaryMbrMatch, applies some transformations to massage that data, and get it into the format to be loaded into the MBR_BIO_MESR_RSLT table.
# MAGIC These are individual records that error out, because a value was NULL that should not be NULL, according to the business rules.  The transformation for this is in BOTH the \"Transfm1\" stage and in the \"BusinessRules\" stage.  So if something must get updated, you need to change BOTH stages.
# MAGIC If the lookup to the CD_MPPNG table for the Gender fails to find a decode record, the value for MBR_GNDR_CD_SK in the MBR_BIO_MESR_RSLT target table will get set to zero, and the business has confirmed that is OKAY.
# MAGIC Values where the lookup to CD_MPPNG fails get set to zero, and that is done in the \"Transfm2\" stage.
# MAGIC Primary Keying
# MAGIC """
# COMMAND ----------
# MAGIC %run ../../../../../Routine_Functions
# COMMAND ----------
# Using the below functions as UDF(inherited from Routine_Functions notebook) instead of pyspark function
# 1) current_timestamp, current_date - To convert to CST timezone.
# 2) trim - To mimic Datastage behavior in trimming spaces within the string (Not leading or trailing spaces)
# COMMAND ----------
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, BinaryType
from pyspark.sql.functions import col, lit, when
# COMMAND ----------
# MAGIC %run ../../../../../Utility_Integrate
# COMMAND ----------


# Parameter retrieval
IDSOwner = get_widget_value("IDSOwner","")
ids_secret_name = get_widget_value("ids_secret_name","")
CurRunCycle = get_widget_value("CurRunCycle","")
RunID = get_widget_value("RunID","")
CurrDate = get_widget_value("CurrDate","")
InputFile = get_widget_value("InputFile","")
ErrorFile = get_widget_value("ErrorFile","")

# MAGIC %run ../../../../../shared_containers/PrimaryKey/<shared_container_name>
# COMMAND ----------

# Read from hf_mbr_bio_mesr_rslt_lkup (Scenario C -> read parquet)
df_hf_mbr_bio_mesr_rslt_lkup = spark.read.parquet(f"{adls_path}/hf_mbr_bio_mesr_rslt.parquet")

# DB2Connector: CD_MPPNG (IDS)
jdbc_url_ids, jdbc_props_ids = get_db_config(ids_secret_name)

df_CD_MPPNG_BioMesr_BioMesrTypCd = (
    spark.read.format("jdbc")
    .option("url", jdbc_url_ids)
    .options(**jdbc_props_ids)
    .option("query", f"SELECT SRC_CD,TRGT_CD,CD_MPPNG_SK,SRC_SYS_CD,SRC_CLCTN_CD FROM {IDSOwner}.CD_MPPNG WHERE TRGT_DOMAIN_NM='BIO MEASURE TYPE' AND SRC_DOMAIN_NM = 'BIO MEASURE TYPE'  AND TRGT_CLCTN_CD='IDS'")
    .load()
)

df_CD_MPPNG_BioMesrSrcSubTypCdSk = (
    spark.read.format("jdbc")
    .option("url", jdbc_url_ids)
    .options(**jdbc_props_ids)
    .option("query", f"SELECT CD_MPPNG.SRC_CD as SRC_CD,CD_MPPNG.CD_MPPNG_SK as CD_MPPNG_SK ,SRC_SYS_CD SRC_SYS_CD, SRC_CLCTN_CD SRC_CLCTN_CD FROM {IDSOwner}.CD_MPPNG CD_MPPNG WHERE SRC_CD='ONSITE'  AND TRGT_CLCTN_CD='IDS' AND TRGT_DOMAIN_NM='BIO MEASURE SOURCE SUBTYPE' and SRC_DOMAIN_NM='BIO MEASURE SOURCE SUBTYPE'")
    .load()
)

df_CD_MPPNG_BioMesrSrcTypCdSk = (
    spark.read.format("jdbc")
    .option("url", jdbc_url_ids)
    .options(**jdbc_props_ids)
    .option("query", f"SELECT CD_MPPNG.SRC_CD as SRC_CD,CD_MPPNG.CD_MPPNG_SK as CD_MPPNG_SK ,SRC_SYS_CD SRC_SYS_CD,SRC_CLCTN_CD SRC_CLCTN_CD FROM {IDSOwner}.CD_MPPNG CD_MPPNG WHERE SRC_CD='OFFVISIT'   AND TRGT_SRC_SYS_CD='IDS'  AND TRGT_CLCTN_CD='IDS' AND TRGT_DOMAIN_NM='BIO MEASURE SOURCE TYPE' AND SRC_DOMAIN_NM = 'BIO MEASURE SOURCE TYPE'")
    .load()
)

df_CD_MPPNG_Src_Cd_Sk = (
    spark.read.format("jdbc")
    .option("url", jdbc_url_ids)
    .options(**jdbc_props_ids)
    .option("query", f"SELECT CD_MPPNG.SRC_CD as SRC_CD,CD_MPPNG.CD_MPPNG_SK as CD_MPPNG_SK FROM {IDSOwner}.CD_MPPNG CD_MPPNG WHERE CD_MPPNG.SRC_DOMAIN_NM = 'SOURCE SYSTEM' AND CD_MPPNG.TRGT_DOMAIN_NM = 'SOURCE SYSTEM'")
    .load()
)

df_CD_MPPNG_Mbr_Gndr_Cd_Sk = (
    spark.read.format("jdbc")
    .option("url", jdbc_url_ids)
    .options(**jdbc_props_ids)
    .option("query", f"SELECT SRC_CD,TRGT_CD,CD_MPPNG_SK,SRC_SYS_CD,SRC_CLCTN_CD FROM {IDSOwner}.CD_MPPNG WHERE SRC_DOMAIN_NM = 'GENDER' AND TRGT_CLCTN_CD = 'IDS' AND TRGT_DOMAIN_NM = 'GENDER'")
    .load()
)

df_CD_MPPNG_UnitofMeasureCdSk = (
    spark.read.format("jdbc")
    .option("url", jdbc_url_ids)
    .options(**jdbc_props_ids)
    .option("query", f"SELECT SRC_CD,CD_MPPNG_SK,SRC_CD_NM,SRC_SYS_CD,SRC_CLCTN_CD FROM {IDSOwner}.CD_MPPNG WHERE SRC_DOMAIN_NM = 'BIO MEASURE UNIT' AND TRGT_CLCTN_CD='IDS' AND TRGT_DOMAIN_NM='BIO MEASURE UNIT'")
    .load()
)

# hf_Provsrcsyscdsk (Scenario A: intermediate hashed file). Key columns = ["SRC_CD"]
df_hf_Provsrcsyscdsk = df_CD_MPPNG_Src_Cd_Sk.dropDuplicates(["SRC_CD"])
df_LkpSrcSysCdSk = df_hf_Provsrcsyscdsk

# hf_ProvBioMesrSrcSubTypCdSk (Scenario A). Key columns = ["SRC_CD","SRC_SYS_CD"]
df_hf_ProvBioMesrSrcSubTypCdSk = df_CD_MPPNG_BioMesrSrcSubTypCdSk.dropDuplicates(["SRC_CD","SRC_SYS_CD"])
df_LkpBioMesrSrcSubTypCdSk = df_hf_ProvBioMesrSrcSubTypCdSk

# hf_ProvBioMesrSrcTypCdSk (Scenario A). Key columns = ["SRC_CD","SRC_SYS_CD"]
df_hf_ProvBioMesrSrcTypCdSk = df_CD_MPPNG_BioMesrSrcTypCdSk.dropDuplicates(["SRC_CD","SRC_SYS_CD"])
df_LkpBioMesrSrcTypCdSk = df_hf_ProvBioMesrSrcTypCdSk

# hf_ProvBioMesrTypCd (Scenario A). Key columns = ["SRC_CD","SRC_SYS_CD"]
df_hf_ProvBioMesrTypCd = df_CD_MPPNG_BioMesr_BioMesrTypCd.dropDuplicates(["SRC_CD","SRC_SYS_CD"])
df_LkpBioMesrTypCd = df_hf_ProvBioMesrTypCd

# hf_ProvMbrBioGndrCdSk (Scenario A). Key columns = ["SRC_CD","SRC_SYS_CD"]
df_hf_ProvMbrBioGndrCdSk = df_CD_MPPNG_Mbr_Gndr_Cd_Sk.dropDuplicates(["SRC_CD","SRC_SYS_CD"])
df_LkkpMbrbioGndrCdSk = df_hf_ProvMbrBioGndrCdSk

# hf_ProvMbrUnitofMeasurecdSk (Scenario A). Key columns = ["SRC_CD","SRC_SYS_CD"]
df_hf_ProvMbrUnitofMeasurecdSk = df_CD_MPPNG_UnitofMeasureCdSk.dropDuplicates(["SRC_CD","SRC_SYS_CD"])
df_LkpMbrUnitofMeasurecdSk = df_hf_ProvMbrUnitofMeasurecdSk
df_SrcUOM = df_hf_ProvMbrUnitofMeasurecdSk

# MBRLUNIQ_LKP (IDS)
df_MBRLUNIQ_LKP = (
    spark.read.format("jdbc")
    .option("url", jdbc_url_ids)
    .options(**jdbc_props_ids)
    .option("query", f"""
SELECT DISTINCT 
UPPER(SUB.SUB_ID) SUB_ID,
FIRST_VALUE(MBR.MBR_UNIQ_KEY) OVER (PARTITION BY SUB.SUB_ID,UPPER(MBR.LAST_NM),UPPER(MBR.FIRST_NM),REPLACE(MBR.BRTH_DT_SK,'-') ORDER BY ENR.TERM_DT_SK DESC) MBR_UNIQ_KEY,
FIRST_VALUE(MBR.MBR_SK) OVER (PARTITION BY SUB.SUB_ID,UPPER(MBR.LAST_NM),UPPER(MBR.FIRST_NM),REPLACE(MBR.BRTH_DT_SK,'-') ORDER BY ENR.TERM_DT_SK DESC) MBR_SK,
UPPER(MBR.LAST_NM) LAST_NM,
UPPER(MBR.FIRST_NM) FIRST_NM,
REPLACE(MBR.BRTH_DT_SK,'-') BRTH_DT_SK,
FIRST_VALUE(SUB.GRP_SK) OVER (PARTITION BY SUB.SUB_ID,UPPER(MBR.LAST_NM),UPPER(MBR.FIRST_NM),REPLACE(MBR.BRTH_DT_SK,'-') ORDER BY ENR.TERM_DT_SK DESC) GRP_SK
FROM {IDSOwner}.MBR MBR
JOIN {IDSOwner}.SUB SUB ON MBR.SUB_SK = SUB.SUB_SK
LEFT OUTER JOIN {IDSOwner}.MBR_ENR ENR
ON MBR.MBR_UNIQ_KEY = ENR.MBR_UNIQ_KEY
AND MBR.SRC_SYS_CD_SK = ENR.SRC_SYS_CD_SK
AND ENR.ELIG_IN = 'Y'
LEFT OUTER JOIN {IDSOwner}.CD_MPPNG CD_ENR_MED
ON ENR.MBR_ENR_CLS_PLN_PROD_CAT_CD_SK = CD_ENR_MED.CD_MPPNG_SK
AND CD_ENR_MED.SRC_CD = 'M' 
AND CD_ENR_MED.SRC_DOMAIN_NM = 'CLASS PLAN PRODUCT CATEGORY'
""")
    .load()
)

# hf_ProvMbrUniqKey (Scenario A). Key columns = ["SUB_ID","LAST_NM","FIRST_NM","BRTH_DT_SK"]
df_hf_ProvMbrUniqKey = df_MBRLUNIQ_LKP.dropDuplicates(["SUB_ID","LAST_NM","FIRST_NM","BRTH_DT_SK"])

# PROV_BIOMETRIC (CSeqFileStage) - read a CSV
schema_PROV_BIOMETRIC = StructType([
    StructField("POL_NO", StringType(), True),
    StructField("PATN_LAST_NM", StringType(), True),
    StructField("PATN_FIRST_NM", StringType(), True),
    StructField("PATN_MID_NM", StringType(), True),
    StructField("MBI", StringType(), True),
    StructField("DOB", StringType(), False),
    StructField("GNDR", StringType(), True),
    StructField("DT_OF_SVC", StringType(), True),
    StructField("MTRC", StringType(), True),
    StructField("RSLT_VAL", StringType(), True),
    StructField("UOM", StringType(), True),
    StructField("SOURCE_ID", StringType(), True),
    StructField("MemberMatchLevel", StringType(), False)
])

df_PROV_BIOMETRIC = (
    spark.read.format("csv")
    .option("header", "false")
    .option("sep", ",")
    .option("quote", "\u0000")
    .schema(schema_PROV_BIOMETRIC)
    .load(f"{adls_path}/verified/{InputFile}")
)

# Xfm1
df_Xfm1 = (
    df_PROV_BIOMETRIC
    .withColumn("POL_NO", Upcase(trim(col("POL_NO"))))
    .withColumn("PATN_LAST_NM", col("PATN_LAST_NM"))
    .withColumn("PATN_FIRST_NM", col("PATN_FIRST_NM"))
    .withColumn("PATN_MID_NM", col("PATN_MID_NM"))
    .withColumn("MBI", col("MBI"))
    .withColumn("DOB", col("DOB"))
    .withColumn("GNDR", col("GNDR"))
    .withColumn("DT_OF_SVC", col("DT_OF_SVC"))
    .withColumn("MTRC", Upcase(trim(col("MTRC"))))
    .withColumn("RSLT_VAL", col("RSLT_VAL"))
    .withColumn("UOM", col("UOM"))
    .withColumn("SOURCE_ID", col("SOURCE_ID"))
    .withColumn("UPPER_PATN_LAST_NM", Upcase(trim(col("PATN_LAST_NM"))))
    .withColumn("UPPER_PATN_FIRST_NM", Upcase(trim(col("PATN_FIRST_NM"))))
)

# Transfm1: Left join with df_hf_ProvMbrUniqKey on 4 conditions
df_Transfm1_join = (
    df_Xfm1.alias("inputfile")
    .join(
       df_hf_ProvMbrUniqKey.alias("Transfm1b"),
       on=[
           col("inputfile.POL_NO") == col("Transfm1b.SUB_ID"),
           col("inputfile.UPPER_PATN_LAST_NM") == col("Transfm1b.LAST_NM"),
           col("inputfile.UPPER_PATN_FIRST_NM") == col("Transfm1b.FIRST_NM"),
           col("inputfile.DOB") == col("Transfm1b.BRTH_DT_SK")
       ],
       how="left"
    )
)

df_Transfm1_vars = (
    df_Transfm1_join
    .withColumn(
        "svDtOfSvc",
        when(
           (col("inputfile.DT_OF_SVC").isNull()) | (length(trim(col("inputfile.DT_OF_SVC"))) == 0),
           lit("1753-01-01")
        ).otherwise(
           FORMAT.DATE(col("inputfile.DT_OF_SVC"), lit("CHAR"), lit("CCYYMMDD"), lit("CCYY-MM-DD"))
        )
    )
    .withColumn(
        "svLoadDt",
        when(
           (col("inputfile.DT_OF_SVC").isNull()) | (length(trim(col("inputfile.DT_OF_SVC"))) == 0),
           lit("1753-01-01")
        ).otherwise(
           FORMAT.DATE(col("inputfile.DT_OF_SVC"), lit("ACCESS"), lit("TIMESTAMP"), lit("CCYY-MM-DD"))
        )
    )
    .withColumn(
        "svPolNoNullChk",
        when((col("inputfile.POL_NO").isNull()) | (length(trim(col("inputfile.POL_NO"))) == 0), lit("POL_NO Do Not Found")).otherwise(lit("1"))
    )
    .withColumn(
        "svDtOfSvcNullChk",
        when((col("inputfile.DT_OF_SVC").isNull()) | (length(trim(col("inputfile.DT_OF_SVC"))) == 0), lit("DT_OF_SVC Do Not Found")).otherwise(lit("1"))
    )
    .withColumn(
        "svMtrcNullChk",
        when((col("inputfile.MTRC").isNull()) | (length(trim(col("inputfile.MTRC"))) == 0), lit("MTRC Do Not Found")).otherwise(lit("1"))
    )
    .withColumn(
        "svSourceIdNullChk",
        when((col("inputfile.SOURCE_ID").isNull()) | (length(trim(col("inputfile.SOURCE_ID"))) == 0), lit("SOURCE_ID Do Not Found")).otherwise(lit("1"))
    )
    .withColumn(
        "svRsltValNullChk",
        when((col("inputfile.RSLT_VAL").isNull()) | (length(trim(col("inputfile.RSLT_VAL"))) == 0), lit("RSLT_VAL Do Not Found")).otherwise(lit("1"))
    )
    .withColumn(
        "svUomNullChk",
        when((col("inputfile.UOM").isNull()) | (length(trim(col("inputfile.UOM"))) == 0), lit("UOM Do Not Found")).otherwise(lit("1"))
    )
    .withColumn(
        "svNullchkFlg",
        when(
            (col("svPolNoNullChk") != lit("1")) |
            (col("svDtOfSvcNullChk") != lit("1")) |
            (col("svMtrcNullChk") != lit("1")) |
            (col("svSourceIdNullChk") != lit("1")) |
            (col("svRsltValNullChk") != lit("1")) |
            (col("svUomNullChk") != lit("1")),
            lit("Y")
        ).otherwise(lit("N"))
    )
    .withColumn(
        "svErrReason",
        when((col("inputfile.POL_NO").isNull()) | (length(trim(col("inputfile.POL_NO"))) == 0), lit("POL_NO Do Not Found"))
        .otherwise(
          when((col("inputfile.DT_OF_SVC").isNull()) | (length(trim(col("inputfile.DT_OF_SVC"))) == 0), lit("DT_OF_SVC Do Not Found"))
          .otherwise(
            when((col("inputfile.MTRC").isNull()) | (length(trim(col("inputfile.MTRC"))) == 0), lit("MTRC Do Not Found"))
            .otherwise(
              when((col("inputfile.SOURCE_ID").isNull()) | (length(trim(col("inputfile.SOURCE_ID"))) == 0), lit("SOURCE_ID Do Not Found"))
              .otherwise(
                when((col("inputfile.RSLT_VAL").isNull()) | (length(trim(col("inputfile.RSLT_VAL"))) == 0), lit("RSLT_VAL Do Not Found"))
                .otherwise(
                  when((col("inputfile.UOM").isNull()) | (length(trim(col("inputfile.UOM"))) == 0), lit("UOM Do Not Found"))
                  .otherwise(lit("1"))
                )
              )
            )
          )
        )
    )
)

df_Transfm1_for_Transfm2 = df_Transfm1_vars.select(
    col("inputfile.POL_NO").alias("POL_NO"),
    col("Transfm1b.MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY"),
    lit("OFFVISIT").alias("BIO_MESR_SRC_TYP_CD"),
    lit("ONSITE").alias("BIO_MESR_SRC_SUBTYP_CD"),
    col("svDtOfSvc").alias("APPT_DT"),
    col("inputfile.MTRC").alias("BIO_TP_CD"),
    trim(col("inputfile.SOURCE_ID")).alias("VENDOR"),
    col("inputfile.RSLT_VAL").alias("METRIC"),
    Upcase(col("inputfile.UOM")).alias("UOM"),
    col("Transfm1b.GRP_SK").alias("GRP_SK"),
    col("Transfm1b.MBR_SK").alias("MBR_SK"),
    col("inputfile.GNDR").alias("GNDR"),
    when(
       (Upcase(col("inputfile.UOM")) == lit("KG")), lit("LB")
    ).otherwise(
       when(
         (Upcase(col("inputfile.UOM")) == lit("M")), lit("IN")
       ).otherwise(
         when(
           (Upcase(col("inputfile.UOM")) == lit("KG/M2")), lit("LB/IN2")
         ).otherwise(Upcase(col("inputfile.UOM")))
       )
    ).alias("UOM_CONVERT"),
    expr("@INROWNUM").alias("Dummy"),
    col("svDtOfSvcNullChk"),
    col("svPolNoNullChk"),
    col("svMtrcNullChk"),
    col("svSourceIdNullChk"),
    col("svRsltValNullChk"),
    col("svUomNullChk"),
    col("svNullchkFlg"),
    col("svErrReason")
)

df_Transfm1_for_Error = df_Transfm1_vars.select(
    expr("@INROWNUM").alias("Dummy"),
    col("inputfile.POL_NO").alias("POL_NO"),
    col("inputfile.PATN_LAST_NM").alias("PATN_LAST_NM"),
    col("inputfile.PATN_FIRST_NM").alias("PATN_FIRST_NM"),
    col("inputfile.PATN_MID_NM").alias("PATN_MID_NM"),
    col("inputfile.MBI").alias("MBI"),
    col("inputfile.DOB").alias("DOB"),
    col("inputfile.GNDR").alias("GNDR"),
    col("inputfile.DT_OF_SVC").alias("DT_OF_SVC"),
    col("inputfile.MTRC").alias("MTRC"),
    col("inputfile.RSLT_VAL").alias("RSLT_VAL"),
    col("inputfile.UOM").alias("UOM"),
    col("inputfile.SOURCE_ID").alias("SOURCE_ID"),
    col("svErrReason").alias("ERROR_REASON"),
    col("svNullchkFlg").alias("NULL_CHECK_FLAG")
)

# hf_prov_ErrorCapture (Scenario A). Key columns = ["Dummy"]
df_hf_prov_ErrorCapture = df_Transfm1_for_Error.dropDuplicates(["Dummy"])
df_LnkErr1 = df_hf_prov_ErrorCapture

# Transfm2: multiple left joins
df_Transfm2_joined = (
    df_Transfm1_for_Transfm2.alias("Transfm2")
    .join(
       df_LkpSrcSysCdSk.alias("LkpSrcSysCdSk"),
       on=[col("Transfm2.VENDOR") == col("LkpSrcSysCdSk.SRC_CD")],
       how="left"
    )
    .join(
       df_LkpBioMesrSrcSubTypCdSk.alias("LkpBioMesrSrcSubTypCdSk"),
       on=[
         col("Transfm2.BIO_MESR_SRC_SUBTYP_CD") == col("LkpBioMesrSrcSubTypCdSk.SRC_CD"),
         col("Transfm2.VENDOR") == col("LkpBioMesrSrcSubTypCdSk.SRC_SYS_CD")
       ],
       how="left"
    )
    .join(
       df_LkpBioMesrSrcTypCdSk.alias("LkpBioMesrSrcTypCdSk"),
       on=[
         col("Transfm2.BIO_MESR_SRC_TYP_CD") == col("LkpBioMesrSrcTypCdSk.SRC_CD"),
         col("Transfm2.VENDOR") == col("LkpBioMesrSrcTypCdSk.SRC_SYS_CD")
       ],
       how="left"
    )
    .join(
       df_LkpBioMesrTypCd.alias("LkpBioMesrTypCd"),
       on=[
         col("Transfm2.BIO_TP_CD") == col("LkpBioMesrTypCd.SRC_CD"),
         col("Transfm2.VENDOR") == col("LkpBioMesrTypCd.SRC_SYS_CD")
       ],
       how="left"
    )
    .join(
       df_LkkpMbrbioGndrCdSk.alias("LkkpMbrbioGndrCdSk"),
       on=[
         col("Transfm2.GNDR") == col("LkkpMbrbioGndrCdSk.SRC_CD"),
         col("Transfm2.VENDOR") == col("LkkpMbrbioGndrCdSk.SRC_SYS_CD")
       ],
       how="left"
    )
    .join(
       df_LkpMbrUnitofMeasurecdSk.alias("LkpMbrUnitofMeasurecdSk"),
       on=[
         col("Transfm2.UOM_CONVERT") == col("LkpMbrUnitofMeasurecdSk.SRC_CD"),
         col("Transfm2.VENDOR") == col("LkpMbrUnitofMeasurecdSk.SRC_SYS_CD")
       ],
       how="left"
    )
    .join(
       df_SrcUOM.alias("SrcUOM"),
       on=[
         col("Transfm2.UOM") == col("SrcUOM.SRC_CD"),
         col("Transfm2.VENDOR") == col("SrcUOM.SRC_SYS_CD")
       ],
       how="left"
    )
)

df_Transfm2_Check = df_Transfm2_joined.select(
    col("Transfm2.MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY"),
    col("Transfm2.BIO_MESR_SRC_TYP_CD").alias("BIO_MESR_SRC_TYP_CD"),
    col("Transfm2.BIO_MESR_SRC_SUBTYP_CD").alias("BIO_MESR_SRC_SUBTYP_CD"),
    col("Transfm2.APPT_DT").alias("BIO_MESR_SRC_DT_SK"),
    col("Transfm2.BIO_TP_CD").alias("BIO_MESR_TYP_CD"),
    when(col("LkpSrcSysCdSk.CD_MPPNG_SK").isNull(), lit(0)).otherwise(col("LkpSrcSysCdSk.CD_MPPNG_SK")).alias("SRC_SYS_CD_SK"),
    col("Transfm2.VENDOR").alias("SRC_SYS_CD"),
    col("Transfm2.GRP_SK").alias("GRP_SK"),
    col("Transfm2.MBR_SK").alias("MBR_SK"),
    when(col("LkpBioMesrSrcSubTypCdSk.CD_MPPNG_SK").isNull(), lit(0)).otherwise(col("LkpBioMesrSrcSubTypCdSk.CD_MPPNG_SK")).alias("BIO_MESR_SRC_SUBTYP_CD_SK"),
    when(col("LkpBioMesrSrcTypCdSk.CD_MPPNG_SK").isNull(), lit(0)).otherwise(col("LkpBioMesrSrcTypCdSk.CD_MPPNG_SK")).alias("BIO_MESR_SRC_TYP_CD_SK"),
    when(col("LkpBioMesrTypCd.CD_MPPNG_SK").isNull(), lit(0)).otherwise(col("LkpBioMesrTypCd.CD_MPPNG_SK")).alias("BIO_MESR_TYP_CD_SK"),
    when(col("LkkpMbrbioGndrCdSk.CD_MPPNG_SK").isNull(), lit(0)).otherwise(col("LkkpMbrbioGndrCdSk.CD_MPPNG_SK")).alias("MBR_GNDR_CD_SK"),
    when(
       (Upcase(col("Transfm2.UOM")) == lit("KG")), col("Transfm2.METRIC") * 2.20462
    ).otherwise(
       when(
         (Upcase(col("Transfm2.UOM")) == lit("M")), col("Transfm2.METRIC") * 39.3701
       ).otherwise(
         when(
           (Upcase(col("Transfm2.UOM")) == lit("KG/M2")), col("Transfm2.METRIC") * 0.00142233
         ).otherwise(
           when(
             ( (Upcase(col("Transfm2.UOM")) == lit("IN")) | (Upcase(col("Transfm2.UOM")) == lit("LB")) | (Upcase(col("Transfm2.UOM")) == lit("LB/IN2")) ),
             col("Transfm2.METRIC")
           ).otherwise(col("Transfm2.METRIC"))
         )
       )
    ).alias("BIO_MESR_RSLT_NO"),
    when(col("LkpMbrUnitofMeasurecdSk.CD_MPPNG_SK").isNull(), lit(0)).otherwise(col("LkpMbrUnitofMeasurecdSk.CD_MPPNG_SK")).alias("BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK"),
    col("Transfm2.METRIC").alias("SRC_BIO_MESR_RSLT_NO"),
    when(col("SrcUOM.CD_MPPNG_SK").isNull(), lit(0)).otherwise(col("SrcUOM.CD_MPPNG_SK")).alias("SRC_BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK"),
    col("Transfm2.Dummy").alias("Dummy")
)

# BussinessRules
df_BussinesRules_vars = (
    df_Transfm2_Check
    .withColumn(
      "svKeyFields",
      when(
         (col("MBR_UNIQ_KEY").isNull()) | (length(trim(col("MBR_UNIQ_KEY"))) == 0) |
         (col("BIO_MESR_SRC_TYP_CD").isNull()) | (length(trim(col("BIO_MESR_SRC_TYP_CD"))) == 0) |
         (col("BIO_MESR_SRC_SUBTYP_CD").isNull()) | (length(trim(col("BIO_MESR_SRC_SUBTYP_CD"))) == 0) |
         (col("BIO_MESR_SRC_DT_SK").isNull()) | (length(trim(col("BIO_MESR_SRC_DT_SK"))) == 0) |
         (col("BIO_MESR_TYP_CD").isNull()) | (length(trim(col("BIO_MESR_TYP_CD"))) == 0) |
         (col("SRC_SYS_CD_SK").isNull()) | (length(trim(col("SRC_SYS_CD_SK"))) == 0) |
         (trim(col("MBR_UNIQ_KEY")) == lit("0")) | (trim(col("MBR_UNIQ_KEY")) == lit("1")) |
         (trim(col("BIO_MESR_SRC_TYP_CD")) == lit("0")) | (trim(col("BIO_MESR_SRC_TYP_CD")) == lit("1")) |
         (trim(col("BIO_MESR_SRC_SUBTYP_CD")) == lit("0")) | (trim(col("BIO_MESR_SRC_SUBTYP_CD")) == lit("1")) |
         (trim(col("BIO_MESR_SRC_DT_SK")) == lit("0")) | (trim(col("BIO_MESR_SRC_DT_SK")) == lit("1")) |
         (trim(col("BIO_MESR_TYP_CD")) == lit("0")) | (trim(col("BIO_MESR_TYP_CD")) == lit("1")) |
         (trim(col("SRC_SYS_CD_SK")) == lit("0")) | (trim(col("SRC_SYS_CD_SK")) == lit("1")),
         lit("Y")
      ).otherwise(lit("N"))
    )
    .withColumn(
      "svSrcDt",
      when(
        (col("BIO_MESR_SRC_DT_SK") == lit("UNK")) |
        (col("BIO_MESR_SRC_DT_SK") == lit("NA")) |
        (col("BIO_MESR_SRC_DT_SK") == lit("1753-01-01")) |
        (col("BIO_MESR_SRC_DT_SK") == lit("2199-12-31")),
        lit("Y")
      ).otherwise(lit("N"))
    )
    .withColumn(
      "svCdMppngLkpChk",
      when((col("MBR_UNIQ_KEY") == lit("0")) | (length(trim(col("MBR_UNIQ_KEY"))) == 0), lit("Member Match Not Found"))
      .otherwise(
        when((col("BIO_MESR_SRC_DT_SK") == lit("0")) | (length(trim(col("BIO_MESR_SRC_DT_SK"))) == 0), lit("DATE OF SERVICE (DT_OF_SVC) Not Found"))
        .otherwise(
          when((col("BIO_MESR_TYP_CD") == lit("0")) | (length(trim(col("BIO_MESR_TYP_CD"))) == 0), lit("METRIC (MTRC) Not Found"))
          .otherwise(
            when((col("SRC_SYS_CD_SK") == lit("0")) | (length(trim(col("SRC_SYS_CD_SK"))) == 0), lit("SOURCE ID (SOURCE_ID) Not Found"))
            .otherwise(
              when((col("GRP_SK") == lit("0")) | (length(trim(col("GRP_SK"))) == 0), lit("Member Match Not Found"))
              .otherwise(
                when((col("MBR_SK") == lit("0")) | (length(trim(col("MBR_SK"))) == 0), lit("Member Match Not Found"))
                .otherwise(
                  when((col("BIO_MESR_TYP_CD_SK") == lit("0")) | (length(trim(col("BIO_MESR_TYP_CD_SK"))) == 0), lit("METRIC (MTRC) Not Found"))
                  .otherwise(
                    when((col("BIO_MESR_RSLT_NO") == lit("0")) | (length(trim(col("BIO_MESR_RSLT_NO"))) == 0), lit("RESULT VALUE (RSLT_VAL) Not Found"))
                    .otherwise(
                      when((col("BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK") == lit("0")) | (length(trim(col("BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK"))) == 0), lit("UNIT OF MEASURE (UOM) Not Found or Invalid"))
                      .otherwise(
                        when((col("SRC_BIO_MESR_RSLT_NO") == lit("0")) | (length(trim(col("SRC_BIO_MESR_RSLT_NO"))) == 0), lit("RESULT VALUE (RSLT_VAL) Not Found"))
                        .otherwise(
                          when((col("SRC_BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK") == lit("0")) | (length(trim(col("SRC_BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK"))) == 0), lit("UNIT OF MEASURE (UOM) Not Found"))
                          .otherwise(lit("1"))
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
)

df_BussinessRules_PrimaryKey = df_BussinesRules_vars.where(
    (col("svKeyFields") == lit("N")) & 
    (col("svSrcDt") == lit("N")) & 
    (col("svCdMppngLkpChk") == lit("1"))
).select(
    lit(0).alias("JOB_EXCTN_RCRD_ERR_SK"),
    rpad(lit("I"),10," ").alias("INSRT_UPDT_CD"),
    rpad(lit("N"),1," ").alias("DISCARD_IN"),
    rpad(lit("Y"),1," ").alias("PASS_THRU_IN"),
    col("CurrDate").alias("FIRST_RECYC_DT"),  
    lit(0).alias("ERR_CT"),
    lit(0).alias("RECYCLE_CT"),
    col("SRC_SYS_CD").alias("SRC_SYS_CD"),
    (col("MBR_UNIQ_KEY").cast("string") 
     + lit(";") 
     + col("BIO_MESR_SRC_TYP_CD").cast("string") 
     + lit(";") 
     + col("BIO_MESR_SRC_SUBTYP_CD").cast("string") 
     + lit(";") 
     + col("BIO_MESR_SRC_DT_SK").cast("string") 
     + lit(";") 
     + col("BIO_MESR_TYP_CD").cast("string") 
     + lit(";") 
     + col("SRC_SYS_CD_SK").cast("string")
    ).alias("PRI_KEY_STRING"),
    col("MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY"),
    col("BIO_MESR_SRC_TYP_CD").alias("BIO_MESR_SRC_TYP_CD"),
    col("BIO_MESR_SRC_SUBTYP_CD").alias("BIO_MESR_SRC_SUBTYP_CD"),
    col("BIO_MESR_SRC_DT_SK").alias("BIO_MESR_SRC_DT_SK"),
    col("BIO_MESR_TYP_CD").alias("BIO_MESR_TYP_CD"),
    col("SRC_SYS_CD_SK").alias("SRC_SYS_CD_SK"),
    col("GRP_SK").alias("GRP_SK"),
    col("MBR_SK").alias("MBR_SK"),
    col("BIO_MESR_SRC_SUBTYP_CD_SK").alias("BIO_MESR_SRC_SUBTYP_CD_SK"),
    col("BIO_MESR_SRC_TYP_CD_SK").alias("BIO_MESR_SRC_TYP_CD_SK"),
    col("BIO_MESR_TYP_CD_SK").alias("BIO_MESR_TYP_CD_SK"),
    col("MBR_GNDR_CD_SK").alias("MBR_GNDR_CD_SK"),
    col("BIO_MESR_RSLT_NO").alias("BIO_MESR_RSLT_NO"),
    col("BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK").alias("BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK"),
    col("SRC_BIO_MESR_RSLT_NO").alias("SRC_BIO_MESR_RSLT_NO"),
    col("SRC_BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK").alias("SRC_BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK")
)

df_BussinessRules_LnkErrorCdMppngLkpFailure = df_BussinesRules_vars.where(
    (col("svKeyFields") != lit("N")) | 
    (col("svSrcDt") != lit("N")) | 
    (col("svCdMppngLkpChk") != lit("1"))
).select(
    expr("Dummy").alias("Dummy"),
    col("svCdMppngLkpChk").alias("ERROR_REASON")
)

# hf_CdMppngError1 (Scenario A). Key columns = ["Dummy"]
df_hf_CdMppngError1 = df_BussinessRules_LnkErrorCdMppngLkpFailure.dropDuplicates(["Dummy"])
df_LnkRejectFile = df_hf_CdMppngError1

# PrimaryKey: left join with df_hf_mbr_bio_mesr_rslt_lkup
df_PrimaryKey_join = (
    df_BussinessRules_PrimaryKey.alias("PrimaryKey")
    .join(
        df_hf_mbr_bio_mesr_rslt_lkup.alias("lkup"),
        on=[
          col("PrimaryKey.SRC_SYS_CD") == col("lkup.SRC_SYS_CD"),
          col("PrimaryKey.MBR_UNIQ_KEY") == col("lkup.MBR_UNIQ_KEY"),
          col("PrimaryKey.BIO_MESR_SRC_TYP_CD") == col("lkup.BIO_MESR_SRC_TYP_CD"),
          col("PrimaryKey.BIO_MESR_SRC_SUBTYP_CD") == col("lkup.BIO_MESR_SRC_SUBTYP_CD"),
          col("PrimaryKey.BIO_MESR_SRC_DT_SK") == col("lkup.BIO_MESR_SRC_DT_SK"),
          col("PrimaryKey.BIO_MESR_TYP_CD") == col("lkup.BIO_MESR_TYP_CD")
        ],
        how="left"
    )
)

df_PrimaryKey_calcs = (
    df_PrimaryKey_join
    .withColumn(
       "SK",
       when(col("lkup.MBR_BIO_MESR_RSLT_SK").isNull(), SurrogateKeyGen(col("PrimaryKey"),<DB sequence name>,lit("key_col"),<schema>,<secret_name>)).otherwise(col("lkup.MBR_BIO_MESR_RSLT_SK"))
    )
    .withColumn(
       "NewCrtRunCycExtcnSk",
       when(col("lkup.MBR_BIO_MESR_RSLT_SK").isNull(), col("CurRunCycle")).otherwise(col("lkup.CRT_RUN_CYC_EXCTN_SK"))
    )
)

df_PrimaryKey_Key = df_PrimaryKey_calcs.where("true").select(
    col("PrimaryKey.JOB_EXCTN_RCRD_ERR_SK").alias("JOB_EXCTN_RCRD_ERR_SK"),
    rpad(col("PrimaryKey.INSRT_UPDT_CD"), 10, " ").alias("INSRT_UPDT_CD"),
    rpad(col("PrimaryKey.DISCARD_IN"), 1, " ").alias("DISCARD_IN"),
    rpad(col("PrimaryKey.PASS_THRU_IN"), 1, " ").alias("PASS_THRU_IN"),
    col("PrimaryKey.FIRST_RECYC_DT").alias("FIRST_RECYC_DT"),
    col("PrimaryKey.ERR_CT").alias("ERR_CT"),
    col("PrimaryKey.RECYCLE_CT").alias("RECYCLE_CT"),
    col("PrimaryKey.SRC_SYS_CD").alias("SRC_SYS_CD"),
    col("PrimaryKey.PRI_KEY_STRING").alias("PRI_KEY_STRING"),
    col("SK").alias("MBR_BIO_MESR_RSLT_SK"),
    col("PrimaryKey.MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY"),
    col("PrimaryKey.BIO_MESR_SRC_TYP_CD").alias("BIO_MESR_SRC_TYP_CD"),
    col("PrimaryKey.BIO_MESR_SRC_SUBTYP_CD").alias("BIO_MESR_SRC_SUBTYP_CD"),
    rpad(col("PrimaryKey.BIO_MESR_SRC_DT_SK"), 10, " ").alias("BIO_MESR_SRC_DT_SK"),
    col("PrimaryKey.BIO_MESR_TYP_CD").alias("BIO_MESR_TYP_CD"),
    col("PrimaryKey.SRC_SYS_CD_SK").alias("SRC_SYS_CD_SK"),
    col("NewCrtRunCycExtcnSk").alias("CRT_RUN_CYC_EXCTN_SK"),
    col("CurRunCycle").alias("LAST_UPDT_RUN_CYC_EXCTN_SK"),
    col("PrimaryKey.GRP_SK").alias("GRP_SK"),
    col("PrimaryKey.MBR_SK").alias("MBR_SK"),
    col("PrimaryKey.BIO_MESR_SRC_SUBTYP_CD_SK").alias("BIO_MESR_SRC_SUBTYP_CD_SK"),
    col("PrimaryKey.BIO_MESR_SRC_TYP_CD_SK").alias("BIO_MESR_SRC_TYP_CD_SK"),
    col("PrimaryKey.BIO_MESR_TYP_CD_SK").alias("BIO_MESR_TYP_CD_SK"),
    col("PrimaryKey.MBR_GNDR_CD_SK").alias("MBR_GNDR_CD_SK"),
    col("PrimaryKey.BIO_MESR_RSLT_NO").alias("BIO_MESR_RSLT_NO"),
    col("PrimaryKey.BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK").alias("BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK"),
    col("PrimaryKey.SRC_BIO_MESR_RSLT_NO").alias("SRC_BIO_MESR_RSLT_NO"),
    col("PrimaryKey.SRC_BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK").alias("SRC_BIO_MESR_RSLT_UNIT_OF_MESR_CD_SK")
)

df_PrimaryKey_updt = df_PrimaryKey_calcs.where(col("lkup.MBR_BIO_MESR_RSLT_SK").isNull()).select(
    col("PrimaryKey.SRC_SYS_CD").alias("SRC_SYS_CD"),
    col("PrimaryKey.MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY"),
    col("PrimaryKey.BIO_MESR_SRC_TYP_CD").alias("BIO_MESR_SRC_TYP_CD"),
    col("PrimaryKey.BIO_MESR_SRC_SUBTYP_CD").alias("BIO_MESR_SRC_SUBTYP_CD"),
    rpad(col("PrimaryKey.BIO_MESR_SRC_DT_SK"), 10, " ").alias("BIO_MESR_SRC_DT_SK"),
    col("PrimaryKey.BIO_MESR_TYP_CD").alias("BIO_MESR_TYP_CD"),
    col("NewCrtRunCycExtcnSk").alias("CRT_RUN_CYC_EXCTN_SK"),
    col("SK").alias("MBR_BIO_MESR_RSLT_SK")
)

# MbrBioMesrRsltFileOut (CSeqFileStage)
df_MbrBioMesrRsltFileOut = df_PrimaryKey_Key
write_files(
    df_MbrBioMesrRsltFileOut,
    f"{adls_path}/key/IdsProviderMbrBioMesrRsltExtr.MbrBioMesrRslt.dat.{RunID}",
    delimiter=",",
    mode="overwrite",
    is_pqruet=False,
    header=False,
    quote="\"",
    nullValue=None
)

# hf_mbr_bio_mesr_rslt (Scenario C -> writing the df_PrimaryKey_updt to parquet)
# but this is an output hashed file, so we must write it to hf_mbr_bio_mesr_rslt.parquet
# first reorder columns as defined in the link
df_hf_mbr_bio_mesr_rslt_out = df_PrimaryKey_updt.select(
    col("SRC_SYS_CD"),
    col("MBR_UNIQ_KEY"),
    col("BIO_MESR_SRC_TYP_CD"),
    col("BIO_MESR_SRC_SUBTYP_CD"),
    col("BIO_MESR_SRC_DT_SK"),
    col("BIO_MESR_TYP_CD"),
    col("CRT_RUN_CYC_EXCTN_SK"),
    col("MBR_BIO_MESR_RSLT_SK")
)
write_files(
    df_hf_mbr_bio_mesr_rslt_out,
    f"{adls_path}/hf_mbr_bio_mesr_rslt.parquet",
    delimiter=",",
    mode="overwrite",
    is_pqruet=True,
    header=True,
    quote="\"",
    nullValue=None
)

# hf_CdMppngError1 => df_LnkRejectFile is already defined
# Xmf4: left join df_LnkErr1 with df_LnkRejectFile
df_Xmf4_join = (
    df_LnkErr1.alias("LnkErr1")
    .join(
       df_LnkRejectFile.alias("LnkRejectFile"),
       on=[col("LnkErr1.Dummy") == col("LnkRejectFile.Dummy")],
       how="left"
    )
)

df_Xmf4_out = df_Xmf4_join.where(
    (col("LnkErr1.NULL_CHECK_FLAG") == lit("Y")) |
    (col("LnkErr1.ERROR_REASON") != lit("1")) |
    (col("LnkRejectFile.ERROR_REASON") != lit("1"))
).select(
    col("LnkErr1.POL_NO").alias("POL_NO"),
    col("LnkErr1.PATN_LAST_NM").alias("PATN_LAST_NM"),
    col("LnkErr1.PATN_FIRST_NM").alias("PATN_FIRST_NM"),
    col("LnkErr1.PATN_MID_NM").alias("PATN_MID_NM"),
    col("LnkErr1.MBI").alias("MBI"),
    col("LnkErr1.DOB").alias("DOB"),
    col("LnkErr1.GNDR").alias("GNDR"),
    col("LnkErr1.DT_OF_SVC").alias("DT_OF_SVC"),
    col("LnkErr1.MTRC").alias("MTRC"),
    col("LnkErr1.RSLT_VAL").alias("RSLT_VAL"),
    col("LnkErr1.UOM").alias("UOM"),
    col("LnkErr1.SOURCE_ID").alias("SOURCE_ID"),
    when(col("LnkRejectFile.ERROR_REASON") != lit("1"), col("LnkRejectFile.ERROR_REASON")).otherwise(col("LnkErr1.ERROR_REASON")).alias("ERROR_REASON")
)

# ErrorOutFile (CSeqFileStage)
write_files(
    df_Xmf4_out,
    f"{adls_path}/verified/{ErrorFile}",
    delimiter="|",
    mode="overwrite",
    is_pqruet=False,
    header=True,
    quote="\u0000",
    nullValue=None
)