# Databricks notebook source
# MAGIC %run ./Utility
# COMMAND ----------
# MAGIC %run ./Routine_Functions
# COMMAND ----------

"""
Shared-Container: CustSvcTaskCstmDtlPK
Folder Path    : Shared Containers/PrimaryKey
Job Type       : Server Job
Job Category   : DS_Integrate

Description
------------
* VC LOGS *
^1_1 10/21/08 10:37:16 Batch  14905_38245 PROMOTE bckcetl ids20 dsadm rc for brent 
^1_1 10/21/08 10:33:47 Batch  14905_38033 INIT bckcett testIDS dsadm rc for brent
^1_1 10/20/08 12:44:46 Batch  14904_45890 PROMOTE bckcett testIDS u08717 Brent
^1_1 10/20/08 12:41:40 Batch  14904_45702 INIT bckcett devlIDS u08717 Brent
^1_1 08/01/08 11:02:29 Batch  14824_39756 PROMOTE bckcett testIDS u03651 steph for Brent
^1_1 08/01/08 10:50:09 Batch  14824_39011 INIT bckcett devlIDS u03651 steffy
^1_2 07/23/08 15:42:49 Batch  14815_56575 PROMOTE bckcett devlIDS u08717 Brent
^1_2 07/23/08 15:08:26 Batch  14815_54510 INIT bckcett devlIDScur u08717 Brent
^1_1 05/12/08 08:17:54 Batch  14743_29878 INIT bckcett devlIDScur u08717 Brent

Copyright 2008 Blue Cross/Blue Shield of Kansas City

CALLED BY : FctsCustSvcTaskCstmDtlExtr

PROCESSING
-----------
Assign primary surrogate key to input records.

MODIFICATIONS
-------------
Developer        Date        Altiris #  Description
Brent Leland     2008-02-26  3567       Original Programming.  Change counter IDS_SK to CUST_SVC_TASK_CSTM_DTL_SK

Annotations
-----------
join primary key info with table info
update primary key table (K_CUST_SVC_TASK_CSTM_DTL) with new keys created today
Assign primary surrogate key
primary key hash file only contains current run keys
Temp table is truncated before load and runstat done after load
SQL joins temp table with key table to assign known keys
Load IDS temp. table
IDS Primary Key Container for Customer Service
Used by FctsCustSvcTaskCstmDtlExtr
Hash file cleared in calling job
"""

from pyspark.sql import DataFrame
from pyspark.sql import functions as F


def run_CustSvcTaskCstmDtlPK(
    df_AllCol: DataFrame,
    df_Transform: DataFrame,
    params: dict,
) -> DataFrame:
    """
    Executes the CustSvcTaskCstmDtlPK shared-container logic.

    Parameters
    ----------
    df_AllCol   : DataFrame
        Stream that carries all customer-service task custom-detail columns.
    df_Transform: DataFrame
        Stream that feeds the K_CUST_SVC_TASK_CSTM_DTL_TEMP table.
    params      : dict
        Runtime parameters and environmental objects (JDBC URLs, secrets, ADLS paths, etc.).

    Returns
    -------
    DataFrame
        Output stream “Key” generated by the Merge stage.
    """

    # --------------------------------------------------
    # Unpack runtime parameters – do this exactly once
    # --------------------------------------------------
    CurrRunCycle         = params["CurrRunCycle"]
    SrcSysCd             = params["SrcSysCd"]
    IDSOwner             = params["IDSOwner"]
    ids_jdbc_url         = params["ids_jdbc_url"]
    ids_jdbc_props       = params["ids_jdbc_props"]
    ids_secret_name      = params["ids_secret_name"]
    adls_path            = params["adls_path"]
    adls_path_raw        = params["adls_path_raw"]
    adls_path_publish    = params["adls_path_publish"]

    # --------------------------------------------------
    # Stage: K_CUST_SVC_TASK_CSTM_DTL_TEMP  (load)
    # --------------------------------------------------
    temp_table_name = f"{IDSOwner}.K_CUST_SVC_TASK_CSTM_DTL_TEMP"
    (
        df_Transform.write.format("jdbc")
        .option("url", ids_jdbc_url)
        .options(**ids_jdbc_props)
        .option("dbtable", temp_table_name)
        .mode("append")
        .save()
    )

    # --------------------------------------------------
    # Stage: K_CUST_SVC_TASK_CSTM_DTL_TEMP  (extract)
    # --------------------------------------------------
    extract_query = f"""
        SELECT k.CUST_SVC_TASK_CSTM_DTL_SK,
               w.SRC_SYS_CD_SK,
               w.CUST_SVC_ID,
               w.TASK_SEQ_NO,
               w.CUST_SVC_TASK_CSTM_DTL_CD,
               w.CSTM_DTL_UNIQ_ID,
               w.CSTM_DTL_SEQ_NO,
               k.CRT_RUN_CYC_EXCTN_SK
        FROM   {IDSOwner}.K_CUST_SVC_TASK_CSTM_DTL_TEMP w,
               {IDSOwner}.K_CUST_SVC_TASK_CSTM_DTL       k
        WHERE  w.SRC_SYS_CD_SK              = k.SRC_SYS_CD_SK
           AND w.CUST_SVC_ID                = k.CUST_SVC_ID
           AND w.TASK_SEQ_NO                = k.TASK_SEQ_NO
           AND w.CUST_SVC_TASK_CSTM_DTL_CD  = k.CUST_SVC_TASK_CSTM_DTL_CD
           AND w.CSTM_DTL_UNIQ_ID           = k.CSTM_DTL_UNIQ_ID
           AND w.CSTM_DTL_SEQ_NO            = k.CSTM_DTL_SEQ_NO
        UNION
        SELECT -1,
               w2.SRC_SYS_CD_SK,
               w2.CUST_SVC_ID,
               w2.TASK_SEQ_NO,
               w2.CUST_SVC_TASK_CSTM_DTL_CD,
               w2.CSTM_DTL_UNIQ_ID,
               w2.CSTM_DTL_SEQ_NO,
               {CurrRunCycle}
        FROM   {IDSOwner}.K_CUST_SVC_TASK_CSTM_DTL_TEMP w2
        WHERE  NOT EXISTS (
                 SELECT 1
                 FROM   {IDSOwner}.K_CUST_SVC_TASK_CSTM_DTL k2
                 WHERE  w2.SRC_SYS_CD_SK              = k2.SRC_SYS_CD_SK
                   AND  w2.CUST_SVC_ID                = k2.CUST_SVC_ID
                   AND  w2.TASK_SEQ_NO                = k2.TASK_SEQ_NO
                   AND  w2.CUST_SVC_TASK_CSTM_DTL_CD  = k2.CUST_SVC_TASK_CSTM_DTL_CD
                   AND  w2.CSTM_DTL_UNIQ_ID           = k2.CSTM_DTL_UNIQ_ID
                   AND  w2.CSTM_DTL_SEQ_NO            = k2.CSTM_DTL_SEQ_NO
              )
    """

    df_W_Extract = (
        spark.read.format("jdbc")
        .option("url", ids_jdbc_url)
        .options(**ids_jdbc_props)
        .option("query", extract_query)
        .load()
    )

    # --------------------------------------------------
    # Transformer: PrimaryKey
    # --------------------------------------------------
    df_enriched = (
        df_W_Extract
        .withColumn(
            "INSRT_UPDT_CD",
            F.when(F.col("CUST_SVC_TASK_CSTM_DTL_SK") == F.lit(-1), F.lit("I")).otherwise(F.lit("U")),
        )
        .withColumn("SRC_SYS_CD", F.lit(SrcSysCd))
        .withColumn(
            "CUST_SVC_TASK_CSTM_DTL_SK",
            F.when(F.col("INSRT_UPDT_CD") == F.lit("I"), F.lit(None)).otherwise(F.col("CUST_SVC_TASK_CSTM_DTL_SK")),
        )
        .withColumn(
            "CRT_RUN_CYC_EXCTN_SK",
            F.when(F.col("INSRT_UPDT_CD") == F.lit("I"), F.lit(CurrRunCycle)).otherwise(F.col("CRT_RUN_CYC_EXCTN_SK")),
        )
    )

    # Surrogate-key generation (MANDATORY placeholder call)
    df_enriched = SurrogateKeyGen(
        df_enriched,
        <DB sequence name>,
        "CUST_SVC_TASK_CSTM_DTL_SK",
        <schema>,
        <secret_name>,
        stg_owner="staging",
    )

    # --------------------------------------------------
    # Links out of PrimaryKey
    # --------------------------------------------------
    #   NewKeys  (constraint INSRT_UPDT_CD = 'I')
    df_NewKeys = (
        df_enriched.filter(F.col("INSRT_UPDT_CD") == F.lit("I"))
        .select(
            "SRC_SYS_CD_SK",
            "CUST_SVC_ID",
            "TASK_SEQ_NO",
            "CUST_SVC_TASK_CSTM_DTL_CD",
            "CSTM_DTL_UNIQ_ID",
            "CSTM_DTL_SEQ_NO",
            "CRT_RUN_CYC_EXCTN_SK",
            "CUST_SVC_TASK_CSTM_DTL_SK",
        )
    )

    #   Keys (all rows)
    df_Keys = (
        df_enriched.select(
            "CUST_SVC_TASK_CSTM_DTL_SK",
            "SRC_SYS_CD_SK",
            "SRC_SYS_CD",
            "CUST_SVC_ID",
            "TASK_SEQ_NO",
            "CUST_SVC_TASK_CSTM_DTL_CD",
            "CSTM_DTL_UNIQ_ID",
            "CSTM_DTL_SEQ_NO",
            "INSRT_UPDT_CD",
            "CRT_RUN_CYC_EXCTN_SK",
        )
    )

    #   updt (all rows, keyed structure)
    df_updt = (
        df_enriched.select(
            "SRC_SYS_CD",
            "CUST_SVC_ID",
            "TASK_SEQ_NO",
            F.col("CUST_SVC_TASK_CSTM_DTL_CD").alias("CUST_SVC_TASK_CSTM_DTL_STYLE_C"),
            "CSTM_DTL_UNIQ_ID",
            "CSTM_DTL_SEQ_NO",
            "CRT_RUN_CYC_EXCTN_SK",
            "CUST_SVC_TASK_CSTM_DTL_SK",
        )
    )

    # --------------------------------------------------
    # Write sequential file for NewKeys
    # --------------------------------------------------
    file_path_seq = f"{adls_path}/load/K_CUST_SVC_TASK_CSTM_DTL.dat"
    write_files(
        df_NewKeys,
        file_path_seq,
        delimiter=",",
        mode="overwrite",
        is_pqruet=False,
        header=False,
        quote='"',
        nullValue=None,
    )

    # --------------------------------------------------
    # Hash-file hf_cust_task_cstm_dtl_updt  (scenario-c → parquet)
    # --------------------------------------------------
    parquet_path_updt = f"{adls_path}/CustSvcTaskCstmDtlPK_updt.parquet"
    write_files(
        df_updt,
        parquet_path_updt,
        delimiter=",",
        mode="overwrite",
        is_pqruet=True,
        header=True,
        quote='"',
        nullValue=None,
    )

    # --------------------------------------------------
    # Hash-file hf_cust_svc_task_cstm_dtl_allcol  (scenario-a → dedup)
    # --------------------------------------------------
    partition_cols = [
        "SRC_SYS_CD_SK",
        "CUST_SVC_ID",
        "TASK_SEQ_NO",
        "CUST_SVC_TASK_CSTM_DTL_CD",
        "CSTM_DTL_UNIQ_ID",
        "CSTM_DTL_SEQ_NO",
    ]
    sort_cols = [(c, "A") for c in partition_cols]

    df_AllCol_clean = dedup_sort(df_AllCol, partition_cols, sort_cols)

    # --------------------------------------------------
    # Transformer: Merge
    # --------------------------------------------------
    join_expr = (
        (F.col("all.SRC_SYS_CD_SK") == F.col("k.SRC_SYS_CD_SK"))
        & (F.col("all.CUST_SVC_ID") == F.col("k.CUST_SVC_ID"))
        & (F.col("all.TASK_SEQ_NO") == F.col("k.TASK_SEQ_NO"))
        & (F.col("all.CUST_SVC_TASK_CSTM_DTL_CD") == F.col("k.CUST_SVC_TASK_CSTM_DTL_CD"))
        & (F.col("all.CSTM_DTL_UNIQ_ID") == F.col("k.CSTM_DTL_UNIQ_ID"))
        & (F.col("all.CSTM_DTL_SEQ_NO") == F.col("k.CSTM_DTL_SEQ_NO"))
    )

    df_Key = (
        df_AllCol_clean.alias("all")
        .join(df_Keys.alias("k"), join_expr, "left")
        .select(
            F.col("all.JOB_EXCTN_RCRD_ERR_SK").alias("JOB_EXCTN_RCRD_ERR_SK"),
            F.col("k.INSRT_UPDT_CD").alias("INSRT_UPDT_CD"),
            F.col("all.DISCARD_IN").alias("DISCARD_IN"),
            F.col("all.PASS_THRU_IN").alias("PASS_THRU_IN"),
            F.col("all.FIRST_RECYC_DT").alias("FIRST_RECYC_DT"),
            F.col("all.ERR_CT").alias("ERR_CT"),
            F.col("all.RECYCLE_CT").alias("RECYCLE_CT"),
            F.col("k.SRC_SYS_CD").alias("SRC_SYS_CD"),
            F.col("all.PRI_KEY_STRING").alias("PRI_KEY_STRING"),
            F.col("k.CUST_SVC_TASK_CSTM_DTL_SK").alias("CUST_SVC_TASK_CSTM_DTL_SK"),
            F.col("all.CUST_SVC_ID").alias("CUST_SVC_ID"),
            F.col("all.TASK_SEQ_NO").alias("TASK_SEQ_NO"),
            F.col("all.CUST_SVC_TASK_CSTM_DTL_CD").alias("CUST_SVC_TASK_CSTM_DTL_CD"),
            F.col("all.CSTM_DTL_UNIQ_ID").alias("CSTM_DTL_UNIQ_ID"),
            F.col("all.CSTM_DTL_SEQ_NO").alias("CSTM_DTL_SEQ_NO"),
            F.col("k.CRT_RUN_CYC_EXCTN_SK").alias("CRT_RUN_CYC_EXCTN_SK"),
            F.lit(CurrRunCycle).alias("LAST_UPDT_RUN_CYC_EXCTN_SK"),
            F.col("all.CRT_BY_USER").alias("CRT_BY_USER"),
            F.col("all.CUST_SVC_TASK").alias("CUST_SVC_TASK"),
            F.col("all.LAST_UPDT_USER").alias("LAST_UPDT_USER"),
            F.col("all.CRT_DTM").alias("CRT_DTM"),
            F.col("all.CSTM_DTL_DT_1").alias("CSTM_DTL_DT_1"),
            F.col("all.CSTM_DTL_DT_2").alias("CSTM_DTL_DT_2"),
            F.col("all.LAST_UPDT_DTM").alias("LAST_UPDT_DTM"),
            F.col("all.CSTM_DTL_MNY_1").alias("CSTM_DTL_MNY_1"),
            F.col("all.CSTM_DTL_NO_1").alias("CSTM_DTL_NO_1"),
            F.col("all.CSTM_DTL_DESC").alias("CSTM_DTL_DESC"),
            F.col("all.CSTM_DTL_TX_1").alias("CSTM_DTL_TX_1"),
            F.col("all.CSTM_DTL_TX_2").alias("CSTM_DTL_TX_2"),
            F.col("all.CSTM_DTL_TX_3").alias("CSTM_DTL_TX_3"),
        )
    )

    # Return the single output stream
    return df_Key