import 'package:flutter/material.dart';
import 'package:shifthour/worker/const/Standard_Appbar.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: StandardAppBar(title: 'Privacy Policy', centerTitle: false),
      body: Padding(
        padding: const EdgeInsets.only(bottom: 16.0),
        child: ListView(
          padding: const EdgeInsets.all(16.0),
          children: [
            const Text(
              'Privacy Policy for ShiftHour',
              style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 8),
            const Text(
              'Last updated: April 04, 2025',
              style: TextStyle(
                fontSize: 14,
                fontStyle: FontStyle.italic,
                color: Colors.grey,
              ),
            ),
            const SizedBox(height: 16),
            const Text(
              'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 16),
            const Text(
              'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 24),

            _buildSectionHeader('Interpretation and Definitions'),
            const SizedBox(height: 8),
            _buildSubsectionHeader('Interpretation'),
            const Text(
              'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 16),

            _buildSubsectionHeader('Definitions'),
            const Text(
              'For the purposes of this Privacy Policy:',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 8),
            _buildDefinitionItem(
              'Account',
              'means a unique account created for You to access our Service or parts of our Service.',
            ),
            _buildDefinitionItem(
              'Affiliate',
              'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
            ),
            _buildDefinitionItem(
              'Application',
              'refers to ShiftHour, the software program provided by the Company.',
            ),
            _buildDefinitionItem(
              'Company',
              '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to ShiftHour, Neil Rao Towers, I, Rd Number 3, Vijayanagar, EPIP Zone, Whitefield, Bengaluru, Karnataka 560066.',
            ),
            _buildDefinitionItem('Country', 'refers to: Karnataka, India'),
            _buildDefinitionItem(
              'Device',
              'means any device that can access the Service such as a computer, a cellphone or a digital tablet.',
            ),
            _buildDefinitionItem(
              'Personal Data',
              'is any information that relates to an identified or identifiable individual.',
            ),
            _buildDefinitionItem('Service', 'refers to the Application.'),
            _buildDefinitionItem(
              'Service Provider',
              'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.',
            ),
            _buildDefinitionItem(
              'Third-party Social Media Service',
              'refers to any website or any social network website through which a User can log in or create an account to use the Service.',
            ),
            _buildDefinitionItem(
              'Usage Data',
              'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).',
            ),
            _buildDefinitionItem(
              'You',
              'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
            ),
            const SizedBox(height: 24),

            _buildSectionHeader('Collecting and Using Your Personal Data'),
            const SizedBox(height: 8),
            _buildSubsectionHeader('Types of Data Collected'),
            const SizedBox(height: 8),
            _buildSubsectionHeader('Personal Data', fontSize: 16),
            const Text(
              'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 8),
            _buildBulletPoint('Email address'),
            _buildBulletPoint('First name and last name'),
            _buildBulletPoint('Phone number'),
            _buildBulletPoint(
              'Address, State, Province, ZIP/Postal code, City',
            ),
            _buildBulletPoint('Usage Data'),
            const SizedBox(height: 16),

            _buildSubsectionHeader('Usage Data', fontSize: 16),
            const Text(
              'Usage Data is collected automatically when using the Service.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 8),
            const Text(
              'Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 8),
            const Text(
              'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 8),
            const Text(
              'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 16),

            _buildSubsectionHeader(
              'Information from Third-Party Social Media Services',
              fontSize: 16,
            ),
            const Text(
              'The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 8),
            _buildBulletPoint('Google'),
            _buildBulletPoint('Facebook'),
            _buildBulletPoint('Instagram'),
            _buildBulletPoint('Twitter'),
            _buildBulletPoint('LinkedIn'),
            const SizedBox(height: 8),
            const Text(
              'If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service\'s account, such as Your name, Your email address, Your activities or Your contact list associated with that account.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 8),
            const Text(
              'You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service\'s account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 16),

            // Continue with the rest of the sections...
            _buildSubsectionHeader(
              'Information Collected while Using the Application',
              fontSize: 16,
            ),
            const Text(
              'While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 8),
            _buildBulletPoint('Information regarding your location'),
            const SizedBox(height: 8),
            const Text(
              'We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company\'s servers and/or a Service Provider\'s server or it may be simply stored on Your device.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 8),
            const Text(
              'You can enable or disable access to this information at any time, through Your Device settings.',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 24),

            _buildSectionHeader('Use of Your Personal Data'),
            const Text(
              'The Company may use Personal Data for the following purposes:',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 8),
            _buildBulletPoint(
              'To provide and maintain our Service, including to monitor the usage of our Service.',
            ),
            _buildBulletPoint(
              'To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.',
            ),
            _buildBulletPoint(
              'For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.',
            ),
            _buildBulletPoint(
              'To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application\'s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.',
            ),
            _buildBulletPoint(
              'To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.',
            ),
            _buildBulletPoint(
              'To manage Your requests: To attend and manage Your requests to Us.',
            ),
            _buildBulletPoint(
              'For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.',
            ),
            _buildBulletPoint(
              'For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.',
            ),
            const SizedBox(height: 24),

            // Continue with more sections...
            // Add more sections as needed, following the same pattern
            _buildSectionHeader('Contact Us'),
            const Text(
              'If you have any questions about this Privacy Policy, You can contact us:',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 8),
            const Text(
              'By email: shifthour.jobs@gmail.com',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 4),
            const Text(
              'By phone number: 8088848484',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 16),
            const Text(
              'Generated using Free Privacy Policy Generator',
              style: TextStyle(
                fontSize: 14,
                color: Colors.grey,
                fontStyle: FontStyle.italic,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionHeader(String title) {
    return Text(
      title,
      style: const TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.bold,
        color: Color(0xFF3461FD),
      ),
    );
  }

  Widget _buildSubsectionHeader(String title, {double fontSize = 18}) {
    return Text(
      title,
      style: TextStyle(fontSize: fontSize, fontWeight: FontWeight.bold),
    );
  }

  Widget _buildDefinitionItem(String term, String definition) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: RichText(
        text: TextSpan(
          style: const TextStyle(fontSize: 16, color: Colors.black),
          children: [
            TextSpan(
              text: '$term ',
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            TextSpan(text: definition),
          ],
        ),
      ),
    );
  }

  Widget _buildBulletPoint(String text) {
    return Padding(
      padding: const EdgeInsets.only(left: 16.0, bottom: 4.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('• ', style: TextStyle(fontSize: 16)),
          Expanded(child: Text(text, style: const TextStyle(fontSize: 16))),
        ],
      ),
    );
  }
}
