#!/usr/bin/python3

from npadf import *

def OptumIdsMbrPdxDeniedClmXfmActivities(ctx):
  def dfOptumIdsMbrPdxDeniedClmXfm():
    def db2MBR():
       ds_ls_db = LinkedServiceReference(type='LinkedServiceReference',reference_name=ctx.sqldb_linked_service)
       df_sources_inline = DataFlowSource(name='db2MBR',linked_service=ds_ls_db)
       return DataflowSegment([df_sources_inline])
    def OptumRxDeniedInputFile():
       ds_ls_blob = LinkedServiceReference(type='LinkedServiceReference',reference_name=ctx.file_linked_service)
       df_sources_inline = DataFlowSource(name='OptumRxDeniedInputFile', linked_service=ds_ls_blob)
       return DataflowSegment([df_sources_inline])
    def xfmDataClean():
       return DataflowSegment([
         Transformation(name='xfmDataCleanDerived'),
         Transformation(name='xfmDataClean')])
    def xfmoptumrxV0S26P5map():
       return DataflowSegment([
         Transformation(name='xfmoptumrxV0S26P5mapDerived'),
         Transformation(name='xfmoptumrxV0S26P5map')])
    def xfmoptumrxV0S26P5():
       return DataflowSegment([
         Transformation(name='xfmoptumrxV0S26P5')])
    def JnMbr():
       return DataflowSegment([Transformation(name='JnMbr'),
         Transformation(name="JnMbrJoin1"),Transformation(name="JnMbrDerived1")])
    def xfmoptumrxV0S26P6map():
       return DataflowSegment([
         Transformation(name='xfmoptumrxV0S26P6mapDerived'),
         Transformation(name='xfmoptumrxV0S26P6map')])
    def xfmoptumrxV0S26P6():
       return DataflowSegment([
         Transformation(name='xfmoptumrxV0S26P6')])
    def Seqerror():
       ds_ls_blob = LinkedServiceReference(type='LinkedServiceReference',reference_name=ctx.file_linked_service)
       df_sinks_inline = DataFlowSink(name='Seqerror', linked_service=ds_ls_blob)
       return DataflowSegment([df_sinks_inline])
    def db2PROV():
       ds_ls_db = LinkedServiceReference(type='LinkedServiceReference',reference_name=ctx.sqldb_linked_service)
       df_sources_inline = DataFlowSource(name='db2PROV',linked_service=ds_ls_db)
       return DataflowSegment([df_sources_inline])
    def db2provdea():
       ds_ls_db = LinkedServiceReference(type='LinkedServiceReference',reference_name=ctx.sqldb_linked_service)
       df_sources_inline = DataFlowSource(name='db2provdea',linked_service=ds_ls_db)
       return DataflowSegment([df_sources_inline])
    def Lkpprov():
       return DataflowSegment([
         Transformation(name="Lkpprov"),
         Transformation(name="LkpprovJoin1"),Transformation(name="LkpprovDerived1")])
    def JnNABP():
       return DataflowSegment([Transformation(name='JnNABP'),
         Transformation(name="JnNABPJoin1"),Transformation(name="JnNABPDerived1")])
    def xfmOptumRxpdx():
       return DataflowSegment([
         Transformation(name='xfmOptumRxpdxDerived'),
         Transformation(name='xfmOptumRxpdx')])
    def RvNaturalKeys():
       return DataflowSegment([
         Transformation(name='RvNaturalKeysAggregate'),
         Transformation(name='RvNaturalKeys')
         ])
    def dsMBRPDXDENIEDTRANSxfm():
       ds_ls_blob = LinkedServiceReference(type='LinkedServiceReference',reference_name=ctx.file_linked_service)
       df_sinks_dataset = DataFlowSink(name='dsMBRPDXDENIEDTRANSxfm', linked_service=ds_ls_blob)
       return DataflowSegment([df_sinks_dataset])
    dataflowName = "OptumIdsMbrPdxDeniedClmXfm"
    buffer = DataflowBuffer()
    buffer.append(db2MBR())
    buffer.append(OptumRxDeniedInputFile())
    buffer.append(xfmDataClean())
    buffer.append(xfmoptumrxV0S26P5map())
    buffer.append(xfmoptumrxV0S26P5())
    buffer.append(JnMbr())
    buffer.append(xfmoptumrxV0S26P6map())
    buffer.append(xfmoptumrxV0S26P6())
    buffer.append(Seqerror())
    buffer.append(db2PROV())
    buffer.append(db2provdea())
    buffer.append(Lkpprov())
    buffer.append(JnNABP())
    buffer.append(xfmOptumRxpdx())
    buffer.append(RvNaturalKeys())
    buffer.append(dsMBRPDXDENIEDTRANSxfm())
    dataflow = MappingDataFlow(
      folder = DataFlowFolder(name="DataWarehouse/Claim/DeniedPDXClaims"),
      sources = buffer.sources,
      sinks = buffer.sinks,
      transformations = buffer.transformations,
      script = f"""parameters{{
        IDSAcct as string ,
        IDSDB as string ("{ctx.IDSDB}"),
        IDSPW as string ,
        APT_CONFIG_FILE as string ("{ctx.APT_CONFIG_FILE}"),
        FilePath as string ("{ctx.FilePath}"),
        IDSOwner as string ("{ctx.IDSOwner}"),
        IDSDB2ArraySize as string ("{ctx.IDSDB2ArraySize}"),
        IDSDB2RecordCount as string ("{ctx.IDSDB2RecordCount}"),
        IDSRunCycle as integer ,
        SrcSysCd as string ,
        RunID as string ,
        CurrDate as string 
      }}
    source(output(
        MBR_ID as string,
        MBR_SK as integer,
        SUB_FIRST_NM as string,
        SUB_LAST_NM as string,
        GRP_SK as integer,
        SUB_SK as integer,
        MBR_GNDR_CD_SK as integer,
        MBR_RELSHP_CD_SK as integer,
        ACCOUNTID as string,
        SUB_BRTH_DT as string),
      allowSchemaDrift: true,
      validateSchema: false,
      format: 'query',
      store: 'sqlserver',
      query: ("SELECT\\nS.SUB_ID||M.MBR_SFX_NO AS MBR_ID,\\nM.MBR_SK AS MBR_SK,\\nM.FIRST_NM AS SUB_FIRST_NM,\\nM.LAST_NM AS SUB_LAST_NM,\\nM.BRTH_DT_SK AS SUB_BRTH_DT,\\nS.GRP_SK AS GRP_SK,\\nS.SUB_SK AS SUB_SK,\\nG.GRP_ID as ACCOUNTID,\\nM.MBR_GNDR_CD_SK MBR_GNDR_CD_SK,\\nM.MBR_RELSHP_CD_SK MBR_RELSHP_CD_SK\\n----M.MBR_SFX_NO MBR_SFX_NO \\nFROM " + toString($IDSOwner) + ".MBR M, " + toString($IDSOwner) + ".SUB S, " + toString($IDSOwner) + ".GRP G\\n\\nWHERE\\nS.SUB_SK = M.SUB_SK\\nAND \\nS.GRP_SK = G.GRP_SK\\n\\nORDER BY  S.SUB_ID||M.MBR_SFX_NO, G.GRP_ID\\n "),
      schemaName: '',
      tableName: '',
      isolationLevel: 'READ_UNCOMMITTED') ~> db2MBR
    source(output(
        MEMBERID as string,
        ACCOUNTID as string,
        NPIPROV as string,
        DENIALDTE as string,
        RXNUMBER as string,
        DATESBM as date,
        TIMESBM as string,
        SRC_SYS_CD as string,
        MBRSEX as string,
        MBRRELCDE as string,
        REJCDE1 as string,
        REJCDE2 as string,
        RXNETWRKQL as string,
        MBRBIRTH as date,
        PHRDISPFEE as decimal(11, 2),
        CLTDUEAMT as decimal(11, 2),
        CLT2DUEAMT as decimal(11, 2),
        CLTPATPAY as decimal(11, 2),
        CLTINGRCST as decimal(11, 2),
        MBRFSTNME as string,
        MBRLSTNME as string,
        SOCSECNBR as string,
        SRVPROVNME as string,
        PRESCDEAID as string,
        NPIPRESCR as string,
        PPRSFSTNME as string,
        PPRSLSTNME as string,
        PPRSTATE as string,
        LABELNAME as string,
        SRVPROVID as string,
        CARID as string,
        GROUPID as string,
        CLMORIGIN as string,
        RXCLMNBR as decimal(15, 0),
        PRODUCTID as string,
        MBR_UNIQ_KEY as integer,
        GRP_ID as string,
        LOB_IN as string),
      allowSchemaDrift: true,
      validateSchema: false,
      ignoreNoFilesFound: false,
      format: 'delimited',
      fileSystem: '{ctx.file_container}',
      folderPath: ({ctx.getFolderPath("$FilePath + '/verified/' + $SrcSysCd + '_DeniedClaims_Landing.dat.' + $RunID")}),
      fileName: ({ctx.getFileName("$FilePath + '/verified/' + $SrcSysCd + '_DeniedClaims_Landing.dat.' + $RunID")}) ,
      columnDelimiter: ',',
      rowDelimiter: '\\n',
      quoteChar: '',
      columnNamesAsHeader:false) ~> OptumRxDeniedInputFile
    OptumRxDeniedInputFile
        derive(
              MBR_PDX_DENIED_TRANS_SK = "",
              MBR_UNIQ_KEY = npw_DS_TRIM_1(MBR_UNIQ_KEY),
              ACCOUNTID = npw_DS_TRIM_1(ACCOUNTID),
              PDX_NTNL_PROV_ID = NPIPROV,
              TRANS_TYP_CD = "31",
              TRANS_DENIED_DT = DATESBM,
              RX_NO = RXNUMBER,
              PRCS_DT = $CurrDate,
              SRC_SYS_CLM_RCVD_DT = DATESBM,
              SRC_SYS_CLM_RCVD_TM = substring(TIMESBM, 1, 2) + ":" + substring(TIMESBM, 3, 2) + ":" + substring(TIMESBM, 5, 2),
              SRC_SYS_CD = SRC_SYS_CD,
              CRT_RUN_CYC_EXCTN_SK = 0,
              LAST_UPDT_RUN_CYC_EXCTN_SK = 0,
              GRP_SK = 0,
              MBR_SK = 0,
              NDC_SK = 0,
              PRSCRB_PROV_SK = 0,
              PROV_SPEC_CD_SK = 0,
              SRV_PROV_SK = 0,
              SUB_SK = 0,
              MEDIA_TYP_CD_SK = 0,
              MBR_GNDR_CD_SK = MBRSEX,
              MBR_RELSHP_CD_SK = MBRRELCDE,
              PDX_RSPN_RSN_CD_SK = REJCDE1,
              PDX_RSPN_TYP_CD_SK = 0,
              TRANS_TYP_CD_SK = "",
              MAIL_ORDER_IN = RXNETWRKQL,
              MBR_BRTH_DT = MBRBIRTH,
              BILL_RX_DISPENSE_FEE_AMT = PHRDISPFEE,
              BILL_RX_GROS_APRV_AMT = CLTDUEAMT,
              BILL_RX_NET_CHK_AMT = CLT2DUEAMT,
              BILL_RX_PATN_PAY_AMT = CLTPATPAY,
              INGR_CST_ALW_AMT = CLTINGRCST,
              TRANS_MO_NO = 0,
              TRANS_YR_NO = 0,
              MBR_ID =  case(npw_DS_TRIM_1(LOB_IN) == "MCARE", npw_DS_TRIM_1(substring(MEMBERID, 4, length(MEMBERID))) + "00", npw_DS_TRIM_1(MEMBERID)),
              MBR_SFX_NO =  case(LOB_IN == "MCARE", "00", npw_DS_TRIM_1(substring(MEMBERID, 10, 2))),
              MBR_FIRST_NM = MBRFSTNME,
              MBR_LAST_NM = MBRLSTNME,
              MBR_SSN = SOCSECNBR,
              PDX_NM = SRVPROVNME,
              PDX_PHN_NO = "UNK",
              PHYS_DEA_NO =  case(PRESCDEAID == "UNK", "NA", PRESCDEAID),
              PHYS_NTNL_PROV_ID = NPIPRESCR,
              PHYS_FIRST_NM = PPRSFSTNME,
              PHYS_LAST_NM = PPRSLSTNME,
              PHYS_ST_ADDR_LN = "UNK",
              PHYS_CITY_NM = "UNK",
              PHYS_ST_CD = PPRSTATE,
              PHYS_POSTAL_CD = "UNK",
              RX_LABEL_TX = LABELNAME,
              SVC_PROV_NABP_NM = npw_DS_TRIM_1(SRVPROVID),
              SRC_SYS_CAR_ID = CARID,
              SRC_SYS_CLNT_ORG_ID = "20165",
              SRC_SYS_CLNT_ORG_NM = "BCBS OF KANSAS CITY",
              SRC_SYS_CNTR_ID = MEMBERID,
              SRC_SYS_GRP_ID = ACCOUNTID,
              SUB_ID =  case(npw_DS_TRIM_1(LOB_IN) == "MCARE", npw_DS_TRIM_1(substring(MEMBERID, 4, length(MEMBERID))), npw_DS_TRIM_1(MEMBERID)),
              SUB_FIRST_NM = "",
              SUB_LAST_NM = "",
              NDC = npw_DS_TRIM_1(PRODUCTID),
              MEMBERID = MEMBERID,
              GRP_ID = GRP_ID,
              CLMORIGIN = CLMORIGIN,
              LOB_IN = LOB_IN) ~> xfmDataCleanDerived
        xfmDataCleanDerived
        select(mapColumn(
            MBR_PDX_DENIED_TRANS_SK,
            MBR_UNIQ_KEY,
            ACCOUNTID,
            PDX_NTNL_PROV_ID,
            TRANS_TYP_CD,
            TRANS_DENIED_DT,
            RX_NO,
            PRCS_DT,
            SRC_SYS_CLM_RCVD_DT,
            SRC_SYS_CLM_RCVD_TM,
            SRC_SYS_CD,
            CRT_RUN_CYC_EXCTN_SK,
            LAST_UPDT_RUN_CYC_EXCTN_SK,
            GRP_SK,
            MBR_SK,
            NDC_SK,
            PRSCRB_PROV_SK,
            PROV_SPEC_CD_SK,
            SRV_PROV_SK,
            SUB_SK,
            MEDIA_TYP_CD_SK,
            MBR_GNDR_CD_SK,
            MBR_RELSHP_CD_SK,
            PDX_RSPN_RSN_CD_SK,
            PDX_RSPN_TYP_CD_SK,
            TRANS_TYP_CD_SK,
            MAIL_ORDER_IN,
            MBR_BRTH_DT,
            BILL_RX_DISPENSE_FEE_AMT,
            BILL_RX_GROS_APRV_AMT,
            BILL_RX_NET_CHK_AMT,
            BILL_RX_PATN_PAY_AMT,
            INGR_CST_ALW_AMT,
            TRANS_MO_NO,
            TRANS_YR_NO,
            MBR_ID,
            MBR_SFX_NO,
            MBR_FIRST_NM,
            MBR_LAST_NM,
            MBR_SSN,
            PDX_NM,
            PDX_PHN_NO,
            PHYS_DEA_NO,
            PHYS_NTNL_PROV_ID,
            PHYS_FIRST_NM,
            PHYS_LAST_NM,
            PHYS_ST_ADDR_LN,
            PHYS_CITY_NM,
            PHYS_ST_CD,
            PHYS_POSTAL_CD,
            RX_LABEL_TX,
            SVC_PROV_NABP_NM,
            SRC_SYS_CAR_ID,
            SRC_SYS_CLNT_ORG_ID,
            SRC_SYS_CLNT_ORG_NM,
            SRC_SYS_CNTR_ID,
            SRC_SYS_GRP_ID,
            SUB_ID,
            SUB_FIRST_NM,
            SUB_LAST_NM,
            NDC,
            MEMBERID,
            GRP_ID,
            CLMORIGIN,
            LOB_IN
        ),
        skipDuplicateMapInputs: true,
        skipDuplicateMapOutputs: true) ~> xfmDataClean
    xfmDataClean
        derive(
              MBR_PDX_DENIED_TRANS_SK = MBR_PDX_DENIED_TRANS_SK,
              MBR_UNIQ_KEY = npw_DS_TRIM_1(MBR_UNIQ_KEY),
              ACCOUNTID = ACCOUNTID,
              PDX_NTNL_PROV_ID = PDX_NTNL_PROV_ID,
              TRANS_TYP_CD = TRANS_TYP_CD,
              TRANS_DENIED_DT = TRANS_DENIED_DT,
              RX_NO = RX_NO,
              PRCS_DT = PRCS_DT,
              SRC_SYS_CLM_RCVD_DT = SRC_SYS_CLM_RCVD_DT,
              SRC_SYS_CLM_RCVD_TM = SRC_SYS_CLM_RCVD_TM,
              SRC_SYS_CD = SRC_SYS_CD,
              CRT_RUN_CYC_EXCTN_SK = CRT_RUN_CYC_EXCTN_SK,
              LAST_UPDT_RUN_CYC_EXCTN_SK = LAST_UPDT_RUN_CYC_EXCTN_SK,
              GRP_SK = GRP_SK,
              MBR_SK = MBR_SK,
              NDC_SK = NDC_SK,
              PRSCRB_PROV_SK = PRSCRB_PROV_SK,
              PROV_SPEC_CD_SK = PROV_SPEC_CD_SK,
              SRV_PROV_SK = SRV_PROV_SK,
              SUB_SK = SUB_SK,
              MEDIA_TYP_CD_SK = MEDIA_TYP_CD_SK,
              MBR_GNDR_CD_SK = MBR_GNDR_CD_SK,
              MBR_RELSHP_CD_SK = MBR_RELSHP_CD_SK,
              PDX_RSPN_RSN_CD_SK = PDX_RSPN_RSN_CD_SK,
              PDX_RSPN_TYP_CD_SK = PDX_RSPN_TYP_CD_SK,
              TRANS_TYP_CD_SK = TRANS_TYP_CD_SK,
              MAIL_ORDER_IN = MAIL_ORDER_IN,
              MBR_BRTH_DT = MBR_BRTH_DT,
              BILL_RX_DISPENSE_FEE_AMT = BILL_RX_DISPENSE_FEE_AMT,
              BILL_RX_GROS_APRV_AMT = BILL_RX_GROS_APRV_AMT,
              BILL_RX_NET_CHK_AMT = BILL_RX_NET_CHK_AMT,
              BILL_RX_PATN_PAY_AMT = BILL_RX_PATN_PAY_AMT,
              INGR_CST_ALW_AMT = INGR_CST_ALW_AMT,
              TRANS_MO_NO = TRANS_MO_NO,
              TRANS_YR_NO = TRANS_YR_NO,
              MBR_ID = MBR_ID,
              MBR_SFX_NO = MBR_SFX_NO,
              MBR_FIRST_NM = MBR_FIRST_NM,
              MBR_LAST_NM = MBR_LAST_NM,
              MBR_SSN = MBR_SSN,
              PDX_NM = PDX_NM,
              PDX_PHN_NO = PDX_PHN_NO,
              PHYS_DEA_NO = PHYS_DEA_NO,
              PHYS_NTNL_PROV_ID = PHYS_NTNL_PROV_ID,
              PHYS_FIRST_NM = PHYS_FIRST_NM,
              PHYS_LAST_NM = PHYS_LAST_NM,
              PHYS_ST_ADDR_LN = PHYS_ST_ADDR_LN,
              PHYS_CITY_NM = PHYS_CITY_NM,
              PHYS_ST_CD = PHYS_ST_CD,
              PHYS_POSTAL_CD = PHYS_POSTAL_CD,
              RX_LABEL_TX =  case(isNull(RX_LABEL_TX) || length(RX_LABEL_TX) == 0, "UNK", upper(npw_DS_TRIM_1(RX_LABEL_TX))),
              SVC_PROV_NABP_NM = npw_DS_TRIM_1(SVC_PROV_NABP_NM),
              SRC_SYS_CAR_ID = SRC_SYS_CAR_ID,
              SRC_SYS_CLNT_ORG_ID = SRC_SYS_CLNT_ORG_ID,
              SRC_SYS_CLNT_ORG_NM = SRC_SYS_CLNT_ORG_NM,
              SRC_SYS_CNTR_ID = SRC_SYS_CNTR_ID,
              SRC_SYS_GRP_ID = SRC_SYS_GRP_ID,
              SUB_ID = SUB_ID,
              SUB_FIRST_NM = SUB_FIRST_NM,
              SUB_LAST_NM = SUB_LAST_NM,
              NDC = NDC,
              MEMBERID = MEMBERID,
              GRP_ID = npw_DS_TRIM_1(GRP_ID),
              CLMORIGIN = npw_DS_TRIM_1(CLMORIGIN),
              LOB_IN = LOB_IN,
              CLNT_ORG_OPTRNAL_ID = SRC_SYS_CLNT_ORG_ID,
              CLNT_ORG_NM = npw_DS_TRIM_1(SRC_SYS_CLNT_ORG_NM),
              CLNT_MBRSH_ID = "",
              PATN_ID = MEMBERID,
              CLNT_ID =  case(LOB_IN == "MCARE", SUB_ID, substring(SUB_ID, 1, 9)),
              CLNT_ELIG_MBRSH_ID = "",
              PRSN_NO = "",
              RELSHP_CD = MBR_RELSHP_CD_SK,
              GNDR_CD = MBR_GNDR_CD_SK,
              SVC_DT = TRANS_DENIED_DT,
              MSG_TYP_CD = TRANS_TYP_CD_SK,
              MSG_TYP = "",
              MSG_TX = "",
              MEDIA_TYP_CD = MEDIA_TYP_CD_SK,
              RSPN_CD = "",
              DESC = "",
              CHAPTER_ID = "",
              CHAPTER_DESC = "",
              svPdxNtnlProvId = :svPdxNtnlProvId,
              svTransDeniedDt = :svTransDeniedDt,
              svRxNo = :svRxNo,
              svMbrUniqKey = :svMbrUniqKey,
              svSrcSysClmRcdDt = :svSrcSysClmRcdDt,
              svSrcSysClmRcdTm = :svSrcSysClmRcdTm,
              svPdxNtnlProvId := {' case((isNull(PDX_NTNL_PROV_ID) || length(npw_DS_TRIM_1(PDX_NTNL_PROV_ID)) == 0), "Y", "N")'.replace("toOptumxfm.","")},
              svTransDeniedDt := {' case(TRANS_DENIED_DT == "1753-01-01", "Y", "N")'.replace("toOptumxfm.","")},
              svRxNo := {' case((isNull(RX_NO) || length(npw_DS_TRIM_1(RX_NO)) == 0), "Y", "N")'.replace("toOptumxfm.","")},
              svMbrUniqKey := {' case((isNull(MBR_UNIQ_KEY) || length(npw_DS_TRIM_1(MBR_UNIQ_KEY)) == 0) || npw_DS_TRIM_1(MBR_UNIQ_KEY) == 0, "Y", "N")'.replace("toOptumxfm.","")},
              svSrcSysClmRcdDt := {' case(TRANS_DENIED_DT == "1753-01-01", "Y", "N")'.replace("toOptumxfm.","")},
              svSrcSysClmRcdTm := {' case((isNull(SRC_SYS_CLM_RCVD_TM) || length(npw_DS_TRIM_1(SRC_SYS_CLM_RCVD_TM)) == 0), "Y", "N")'.replace("toOptumxfm.","")}) ~> xfmoptumrxV0S26P5mapDerived
        xfmoptumrxV0S26P5mapDerived
        select(mapColumn(
            MBR_PDX_DENIED_TRANS_SK,
            MBR_UNIQ_KEY,
            ACCOUNTID,
            PDX_NTNL_PROV_ID,
            TRANS_TYP_CD,
            TRANS_DENIED_DT,
            RX_NO,
            PRCS_DT,
            SRC_SYS_CLM_RCVD_DT,
            SRC_SYS_CLM_RCVD_TM,
            SRC_SYS_CD,
            CRT_RUN_CYC_EXCTN_SK,
            LAST_UPDT_RUN_CYC_EXCTN_SK,
            GRP_SK,
            MBR_SK,
            NDC_SK,
            PRSCRB_PROV_SK,
            PROV_SPEC_CD_SK,
            SRV_PROV_SK,
            SUB_SK,
            MEDIA_TYP_CD_SK,
            MBR_GNDR_CD_SK,
            MBR_RELSHP_CD_SK,
            PDX_RSPN_RSN_CD_SK,
            PDX_RSPN_TYP_CD_SK,
            TRANS_TYP_CD_SK,
            MAIL_ORDER_IN,
            MBR_BRTH_DT,
            BILL_RX_DISPENSE_FEE_AMT,
            BILL_RX_GROS_APRV_AMT,
            BILL_RX_NET_CHK_AMT,
            BILL_RX_PATN_PAY_AMT,
            INGR_CST_ALW_AMT,
            TRANS_MO_NO,
            TRANS_YR_NO,
            MBR_ID,
            MBR_SFX_NO,
            MBR_FIRST_NM,
            MBR_LAST_NM,
            MBR_SSN,
            PDX_NM,
            PDX_PHN_NO,
            PHYS_DEA_NO,
            PHYS_NTNL_PROV_ID,
            PHYS_FIRST_NM,
            PHYS_LAST_NM,
            PHYS_ST_ADDR_LN,
            PHYS_CITY_NM,
            PHYS_ST_CD,
            PHYS_POSTAL_CD,
            RX_LABEL_TX,
            SVC_PROV_NABP_NM,
            SRC_SYS_CAR_ID,
            SRC_SYS_CLNT_ORG_ID,
            SRC_SYS_CLNT_ORG_NM,
            SRC_SYS_CNTR_ID,
            SRC_SYS_GRP_ID,
            SUB_ID,
            SUB_FIRST_NM,
            SUB_LAST_NM,
            NDC,
            MEMBERID,
            GRP_ID,
            CLMORIGIN,
            LOB_IN,
            CLNT_ORG_OPTRNAL_ID,
            CLNT_ORG_NM,
            CLNT_MBRSH_ID,
            PATN_ID,
            CLNT_ID,
            CLNT_ELIG_MBRSH_ID,
            PRSN_NO,
            RELSHP_CD,
            GNDR_CD,
            SVC_DT,
            MSG_TYP_CD,
            MSG_TYP,
            MSG_TX,
            MEDIA_TYP_CD,
            RSPN_CD,
            DESC,
            CHAPTER_ID,
            CHAPTER_DESC,
            svPdxNtnlProvId,
            svTransDeniedDt,
            svRxNo,
            svMbrUniqKey,
            svSrcSysClmRcdDt,
            svSrcSysClmRcdTm
        ),
        skipDuplicateMapInputs: true,
        skipDuplicateMapOutputs: true) ~> xfmoptumrxV0S26P5map
    xfmoptumrxV0S26P5map
        filter(
            svPdxNtnlProvId == "N" && svTransDeniedDt == "N" && svRxNo == "N" && svMbrUniqKey == "N" && svSrcSysClmRcdDt == "N" && svSrcSysClmRcdTm == "N"
        ) ~> xfmoptumrxV0S26P5
    {ctx.joinScript(joinType='inner', 
      master=['xfmoptumrxV0S26P5', 'CLNT_ORG_OPTRNAL_ID,MBR_UNIQ_KEY,ACCOUNTID,CLNT_ORG_NM,MAIL_ORDER_IN,SRC_SYS_CAR_ID,RX_NO,TRANS_TYP_CD,CLNT_MBRSH_ID,PATN_ID,CLNT_ID,CLNT_ELIG_MBRSH_ID,SRC_SYS_CD,MBR_SSN,PRSN_NO,RELSHP_CD,GNDR_CD,MBR_BRTH_DT,MBR_FIRST_NM,MBR_LAST_NM,RX_LABEL_TX,SVC_DT,SRC_SYS_GRP_ID,SRC_SYS_CLM_RCVD_DT,SRC_SYS_CLM_RCVD_TM,MSG_TYP_CD,MSG_TYP,MSG_TX,INGR_CST_ALW_AMT,BILL_RX_GROS_APRV_AMT,BILL_RX_NET_CHK_AMT,BILL_RX_PATN_PAY_AMT,BILL_RX_DISPENSE_FEE_AMT,MEDIA_TYP_CD,RSPN_CD,DESC,CHAPTER_ID,CHAPTER_DESC,PHYS_DEA_NO,PHYS_NTNL_PROV_ID,PHYS_FIRST_NM,PHYS_LAST_NM,PHYS_ST_ADDR_LN,PHYS_CITY_NM,PHYS_ST_CD,PHYS_POSTAL_CD,PDX_NTNL_PROV_ID,SVC_PROV_NABP_NM,PDX_NM,PDX_PHN_NO,NDC,MBR_SFX_NO,MBR_ID,SRC_SYS_CNTR_ID,GRP_ID,CLMORIGIN,PDX_RSPN_RSN_CD_SK,PRCS_DT,LOB_IN'],
      transformationName='JnMbr', 
      references=[['db2MBR', ctx.joinConditionAndFixDataTypeMismatch(masterName='xfmoptumrxV0S26P5', masterDataTypes={'CLNT_ORG_OPTRNAL_ID':'string','MBR_UNIQ_KEY':'integer','ACCOUNTID':'string','CLNT_ORG_NM':'string','MAIL_ORDER_IN':'string','SRC_SYS_CAR_ID':'string','RX_NO':'string','TRANS_TYP_CD':'string','CLNT_MBRSH_ID':'string','PATN_ID':'string','CLNT_ID':'string','CLNT_ELIG_MBRSH_ID':'string','SRC_SYS_CD':'string','MBR_SSN':'string','PRSN_NO':'string','RELSHP_CD':'string','GNDR_CD':'string','MBR_BRTH_DT':'string','MBR_FIRST_NM':'string','MBR_LAST_NM':'string','RX_LABEL_TX':'string','SVC_DT':'date','SRC_SYS_GRP_ID':'string','SRC_SYS_CLM_RCVD_DT':'date','SRC_SYS_CLM_RCVD_TM':'timestamp','MSG_TYP_CD':'string','MSG_TYP':'string','MSG_TX':'string','INGR_CST_ALW_AMT':'decimal(13, 2)','BILL_RX_GROS_APRV_AMT':'decimal(13, 2)','BILL_RX_NET_CHK_AMT':'decimal(13, 2)','BILL_RX_PATN_PAY_AMT':'decimal(13, 2)','BILL_RX_DISPENSE_FEE_AMT':'decimal(13, 2)','MEDIA_TYP_CD':'string','RSPN_CD':'string','DESC':'string','CHAPTER_ID':'string','CHAPTER_DESC':'string','PHYS_DEA_NO':'string','PHYS_NTNL_PROV_ID':'string','PHYS_FIRST_NM':'string','PHYS_LAST_NM':'string','PHYS_ST_ADDR_LN':'string','PHYS_CITY_NM':'string','PHYS_ST_CD':'string','PHYS_POSTAL_CD':'string','PDX_NTNL_PROV_ID':'string','SVC_PROV_NABP_NM':'string','PDX_NM':'string','PDX_PHN_NO':'string','NDC':'string','MBR_SFX_NO':'string','MBR_ID':'string','SRC_SYS_CNTR_ID':'string','GRP_ID':'string','CLMORIGIN':'string','PDX_RSPN_RSN_CD_SK':'string','PRCS_DT':'date','LOB_IN':'string'}, refName='db2MBR', refDataTypes={'MBR_ID':'string','MBR_SK':'integer','SUB_FIRST_NM':'string','SUB_LAST_NM':'string','GRP_SK':'integer','SUB_SK':'integer','MBR_GNDR_CD_SK':'integer','MBR_RELSHP_CD_SK':'integer','ACCOUNTID':'string','SUB_BRTH_DT':'string'}, joinFields='MBR_ID,ACCOUNTID'), 'MBR_ID,MBR_SK,SUB_FIRST_NM,SUB_LAST_NM,GRP_SK,SUB_SK,MBR_GNDR_CD_SK,MBR_RELSHP_CD_SK,ACCOUNTID,SUB_BRTH_DT']],
      schema="CLNT_ORG_OPTRNAL_ID,CLNT_ORG_NM,MAIL_ORDER_IN,SRC_SYS_CAR_ID,TRANS_TYP_CD,CLNT_MBRSH_ID,PATN_ID,CLNT_ID,CLNT_ELIG_MBRSH_ID,MBR_SSN,PRSN_NO,RELSHP_CD,GNDR_CD,SUB_BRTH_DT,MBR_BRTH_DT,MBR_FIRST_NM,MBR_LAST_NM,SUBMT_SUB_FIRST_NM,SUBMT_SUB_LAST_NM,RX_LABEL_TX,SVC_DT,SRC_SYS_GRP_ID,SRC_SYS_CLM_RCVD_DT,SRC_SYS_CLM_RCVD_TM,MSG_TYP_CD,MSG_TYP,MSG_TX,INGR_CST_ALW_AMT,BILL_RX_GROS_APRV_AMT,BILL_RX_NET_CHK_AMT,BILL_RX_PATN_PAY_AMT,BILL_RX_DISPENSE_FEE_AMT,MEDIA_TYP_CD,RSPN_CD,DESC,CHAPTER_ID,CHAPTER_DESC,PHYS_DEA_NO,PHYS_NTNL_PROV_ID,PHYS_FIRST_NM,PHYS_LAST_NM,PHYS_ST_ADDR_LN,PHYS_CITY_NM,PHYS_ST_CD,PHYS_POSTAL_CD,PDX_NTNL_PROV_ID,SVC_PROV_NABP_NM,PDX_NM,PDX_PHN_NO,NDC,MBR_UNIQ_KEY,MBR_SK,GRP_SK,SUB_SK,MBR_GNDR_CD_SK,MBR_RELSHP_CD_SK,MBR_SFX_NO,SRC_SYS_CD,RX_NO,MBR_ID,SRC_SYS_CNTR_ID,GRP_ID,CLMORIGIN,PDX_RSPN_RSN_CD_SK,PRCS_DT,LOB_IN",
      map=['Lnk_OptumRx_mbr_denied.CLNT_ORG_OPTRNAL_ID','Lnk_OptumRx_mbr_denied.CLNT_ORG_NM','Lnk_OptumRx_mbr_denied.MAIL_ORDER_IN','Lnk_OptumRx_mbr_denied.SRC_SYS_CAR_ID','Lnk_OptumRx_mbr_denied.TRANS_TYP_CD','Lnk_OptumRx_mbr_denied.CLNT_MBRSH_ID','Lnk_OptumRx_mbr_denied.PATN_ID','Lnk_OptumRx_mbr_denied.CLNT_ID','Lnk_OptumRx_mbr_denied.CLNT_ELIG_MBRSH_ID','Lnk_OptumRx_mbr_denied.MBR_SSN','Lnk_OptumRx_mbr_denied.PRSN_NO','Lnk_OptumRx_mbr_denied.RELSHP_CD','Lnk_OptumRx_mbr_denied.GNDR_CD','lnk_mbr_extr.SUB_BRTH_DT','Lnk_OptumRx_mbr_denied.MBR_BRTH_DT','Lnk_OptumRx_mbr_denied.MBR_FIRST_NM','Lnk_OptumRx_mbr_denied.MBR_LAST_NM','lnk_mbr_extr.SUB_FIRST_NM','lnk_mbr_extr.SUB_LAST_NM','Lnk_OptumRx_mbr_denied.RX_LABEL_TX','Lnk_OptumRx_mbr_denied.SVC_DT','Lnk_OptumRx_mbr_denied.SRC_SYS_GRP_ID','Lnk_OptumRx_mbr_denied.SRC_SYS_CLM_RCVD_DT','Lnk_OptumRx_mbr_denied.SRC_SYS_CLM_RCVD_TM','Lnk_OptumRx_mbr_denied.MSG_TYP_CD','Lnk_OptumRx_mbr_denied.MSG_TYP','Lnk_OptumRx_mbr_denied.MSG_TX','Lnk_OptumRx_mbr_denied.INGR_CST_ALW_AMT','Lnk_OptumRx_mbr_denied.BILL_RX_GROS_APRV_AMT','Lnk_OptumRx_mbr_denied.BILL_RX_NET_CHK_AMT','Lnk_OptumRx_mbr_denied.BILL_RX_PATN_PAY_AMT','Lnk_OptumRx_mbr_denied.BILL_RX_DISPENSE_FEE_AMT','Lnk_OptumRx_mbr_denied.MEDIA_TYP_CD','Lnk_OptumRx_mbr_denied.RSPN_CD','Lnk_OptumRx_mbr_denied.DESC','Lnk_OptumRx_mbr_denied.CHAPTER_ID','Lnk_OptumRx_mbr_denied.CHAPTER_DESC','Lnk_OptumRx_mbr_denied.PHYS_DEA_NO','Lnk_OptumRx_mbr_denied.PHYS_NTNL_PROV_ID','Lnk_OptumRx_mbr_denied.PHYS_FIRST_NM','Lnk_OptumRx_mbr_denied.PHYS_LAST_NM','Lnk_OptumRx_mbr_denied.PHYS_ST_ADDR_LN','Lnk_OptumRx_mbr_denied.PHYS_CITY_NM','Lnk_OptumRx_mbr_denied.PHYS_ST_CD','Lnk_OptumRx_mbr_denied.PHYS_POSTAL_CD','Lnk_OptumRx_mbr_denied.PDX_NTNL_PROV_ID','Lnk_OptumRx_mbr_denied.SVC_PROV_NABP_NM','Lnk_OptumRx_mbr_denied.PDX_NM','Lnk_OptumRx_mbr_denied.PDX_PHN_NO','Lnk_OptumRx_mbr_denied.NDC','Lnk_OptumRx_mbr_denied.MBR_UNIQ_KEY','lnk_mbr_extr.MBR_SK','lnk_mbr_extr.GRP_SK','lnk_mbr_extr.SUB_SK','lnk_mbr_extr.MBR_GNDR_CD_SK','lnk_mbr_extr.MBR_RELSHP_CD_SK','Lnk_OptumRx_mbr_denied.MBR_SFX_NO','Lnk_OptumRx_mbr_denied.SRC_SYS_CD','Lnk_OptumRx_mbr_denied.RX_NO','Lnk_OptumRx_mbr_denied.MBR_ID','Lnk_OptumRx_mbr_denied.SRC_SYS_CNTR_ID','Lnk_OptumRx_mbr_denied.GRP_ID','Lnk_OptumRx_mbr_denied.CLMORIGIN','Lnk_OptumRx_mbr_denied.PDX_RSPN_RSN_CD_SK','Lnk_OptumRx_mbr_denied.PRCS_DT','Lnk_OptumRx_mbr_denied.LOB_IN'],
      aliasFrom="Lnk_OptumRx_mbr_denied,lnk_mbr_extr", 
      aliasTo="xfmoptumrxV0S26P5,db2MBR")}
    xfmDataClean
        derive(
              MBR_PDX_DENIED_TRANS_SK = MBR_PDX_DENIED_TRANS_SK,
              MBR_UNIQ_KEY = MBR_UNIQ_KEY,
              ACCOUNTID = ACCOUNTID,
              PDX_NTNL_PROV_ID = npw_DS_TRIM_1(PDX_NTNL_PROV_ID),
              TRANS_TYP_CD = npw_DS_TRIM_1(TRANS_TYP_CD),
              TRANS_DENIED_DT = TRANS_DENIED_DT,
              RX_NO = npw_DS_TRIM_1(RX_NO),
              PRCS_DT = PRCS_DT,
              SRC_SYS_CLM_RCVD_DT = SRC_SYS_CLM_RCVD_DT,
              SRC_SYS_CLM_RCVD_TM = SRC_SYS_CLM_RCVD_TM,
              SRC_SYS_CD = SRC_SYS_CD,
              CRT_RUN_CYC_EXCTN_SK = CRT_RUN_CYC_EXCTN_SK,
              LAST_UPDT_RUN_CYC_EXCTN_SK = LAST_UPDT_RUN_CYC_EXCTN_SK,
              GRP_SK = GRP_SK,
              MBR_SK = MBR_SK,
              NDC_SK = NDC_SK,
              PRSCRB_PROV_SK = PRSCRB_PROV_SK,
              PROV_SPEC_CD_SK = PROV_SPEC_CD_SK,
              SRV_PROV_SK = SRV_PROV_SK,
              SUB_SK = SUB_SK,
              MEDIA_TYP_CD_SK = MEDIA_TYP_CD_SK,
              MBR_GNDR_CD_SK = MBR_GNDR_CD_SK,
              MBR_RELSHP_CD_SK = MBR_RELSHP_CD_SK,
              PDX_RSPN_RSN_CD_SK = PDX_RSPN_RSN_CD_SK,
              PDX_RSPN_TYP_CD_SK = PDX_RSPN_TYP_CD_SK,
              TRANS_TYP_CD_SK = TRANS_TYP_CD_SK,
              MAIL_ORDER_IN = MAIL_ORDER_IN,
              MBR_BRTH_DT = MBR_BRTH_DT,
              BILL_RX_DISPENSE_FEE_AMT = BILL_RX_DISPENSE_FEE_AMT,
              BILL_RX_GROS_APRV_AMT = BILL_RX_GROS_APRV_AMT,
              BILL_RX_NET_CHK_AMT = BILL_RX_NET_CHK_AMT,
              BILL_RX_PATN_PAY_AMT = BILL_RX_PATN_PAY_AMT,
              INGR_CST_ALW_AMT = INGR_CST_ALW_AMT,
              TRANS_MO_NO = TRANS_MO_NO,
              TRANS_YR_NO = TRANS_YR_NO,
              MBR_ID = MBR_ID,
              MBR_SFX_NO = MBR_SFX_NO,
              MBR_FIRST_NM = MBR_FIRST_NM,
              MBR_LAST_NM = MBR_LAST_NM,
              MBR_SSN = MBR_SSN,
              PDX_NM = PDX_NM,
              PDX_PHN_NO = PDX_PHN_NO,
              PHYS_DEA_NO = PHYS_DEA_NO,
              PHYS_NTNL_PROV_ID = PHYS_NTNL_PROV_ID,
              PHYS_FIRST_NM = PHYS_FIRST_NM,
              PHYS_LAST_NM = PHYS_LAST_NM,
              PHYS_ST_ADDR_LN = PHYS_ST_ADDR_LN,
              PHYS_CITY_NM = PHYS_CITY_NM,
              PHYS_ST_CD = PHYS_ST_CD,
              PHYS_POSTAL_CD = PHYS_POSTAL_CD,
              RX_LABEL_TX = RX_LABEL_TX,
              SVC_PROV_NABP_NM = SVC_PROV_NABP_NM,
              SRC_SYS_CAR_ID = SRC_SYS_CAR_ID,
              SRC_SYS_CLNT_ORG_ID = SRC_SYS_CLNT_ORG_ID,
              SRC_SYS_CLNT_ORG_NM = SRC_SYS_CLNT_ORG_NM,
              SRC_SYS_CNTR_ID = SRC_SYS_CNTR_ID,
              SRC_SYS_GRP_ID = SRC_SYS_GRP_ID,
              SUB_ID = SUB_ID,
              SUB_FIRST_NM = SUB_FIRST_NM,
              SUB_LAST_NM = SUB_LAST_NM,
              NDC = NDC,
              MEMBERID = MEMBERID,
              GRP_ID = GRP_ID,
              CLMORIGIN = CLMORIGIN,
              LOB_IN = LOB_IN,
              CLNT_ID = npw_DS_TRIM_1(MBR_ID),
              DEA_NO = npw_DS_TRIM_1(PHYS_DEA_NO),
              NPI_NO = npw_DS_TRIM_1(PHYS_NTNL_PROV_ID),
              svPdxNtnlProvId = :svPdxNtnlProvId,
              svTransDeniedDt = :svTransDeniedDt,
              svRxNo = :svRxNo,
              svMbrUniqKey = :svMbrUniqKey,
              svSrcSysClmRcdDt = :svSrcSysClmRcdDt,
              svSrcSysClmRcdTm = :svSrcSysClmRcdTm,
              svPdxNtnlProvId := {' case((isNull(PDX_NTNL_PROV_ID) || length(npw_DS_TRIM_1(PDX_NTNL_PROV_ID)) == 0), "Y", "N")'.replace("toOptumxfm.","")},
              svTransDeniedDt := {' case(TRANS_DENIED_DT == "1753-01-01", "Y", "N")'.replace("toOptumxfm.","")},
              svRxNo := {' case((isNull(RX_NO) || length(npw_DS_TRIM_1(RX_NO)) == 0), "Y", "N")'.replace("toOptumxfm.","")},
              svMbrUniqKey := {' case((isNull(MBR_UNIQ_KEY) || length(npw_DS_TRIM_1(MBR_UNIQ_KEY)) == 0) || npw_DS_TRIM_1(MBR_UNIQ_KEY) == 0, "Y", "N")'.replace("toOptumxfm.","")},
              svSrcSysClmRcdDt := {' case(TRANS_DENIED_DT == "1753-01-01", "Y", "N")'.replace("toOptumxfm.","")},
              svSrcSysClmRcdTm := {' case((isNull(SRC_SYS_CLM_RCVD_TM) || length(npw_DS_TRIM_1(SRC_SYS_CLM_RCVD_TM)) == 0), "Y", "N")'.replace("toOptumxfm.","")}) ~> xfmoptumrxV0S26P6mapDerived
        xfmoptumrxV0S26P6mapDerived
        select(mapColumn(
            MBR_PDX_DENIED_TRANS_SK,
            MBR_UNIQ_KEY,
            ACCOUNTID,
            PDX_NTNL_PROV_ID,
            TRANS_TYP_CD,
            TRANS_DENIED_DT,
            RX_NO,
            PRCS_DT,
            SRC_SYS_CLM_RCVD_DT,
            SRC_SYS_CLM_RCVD_TM,
            SRC_SYS_CD,
            CRT_RUN_CYC_EXCTN_SK,
            LAST_UPDT_RUN_CYC_EXCTN_SK,
            GRP_SK,
            MBR_SK,
            NDC_SK,
            PRSCRB_PROV_SK,
            PROV_SPEC_CD_SK,
            SRV_PROV_SK,
            SUB_SK,
            MEDIA_TYP_CD_SK,
            MBR_GNDR_CD_SK,
            MBR_RELSHP_CD_SK,
            PDX_RSPN_RSN_CD_SK,
            PDX_RSPN_TYP_CD_SK,
            TRANS_TYP_CD_SK,
            MAIL_ORDER_IN,
            MBR_BRTH_DT,
            BILL_RX_DISPENSE_FEE_AMT,
            BILL_RX_GROS_APRV_AMT,
            BILL_RX_NET_CHK_AMT,
            BILL_RX_PATN_PAY_AMT,
            INGR_CST_ALW_AMT,
            TRANS_MO_NO,
            TRANS_YR_NO,
            MBR_ID,
            MBR_SFX_NO,
            MBR_FIRST_NM,
            MBR_LAST_NM,
            MBR_SSN,
            PDX_NM,
            PDX_PHN_NO,
            PHYS_DEA_NO,
            PHYS_NTNL_PROV_ID,
            PHYS_FIRST_NM,
            PHYS_LAST_NM,
            PHYS_ST_ADDR_LN,
            PHYS_CITY_NM,
            PHYS_ST_CD,
            PHYS_POSTAL_CD,
            RX_LABEL_TX,
            SVC_PROV_NABP_NM,
            SRC_SYS_CAR_ID,
            SRC_SYS_CLNT_ORG_ID,
            SRC_SYS_CLNT_ORG_NM,
            SRC_SYS_CNTR_ID,
            SRC_SYS_GRP_ID,
            SUB_ID,
            SUB_FIRST_NM,
            SUB_LAST_NM,
            NDC,
            MEMBERID,
            GRP_ID,
            CLMORIGIN,
            LOB_IN,
            CLNT_ID,
            DEA_NO,
            NPI_NO,
            svPdxNtnlProvId,
            svTransDeniedDt,
            svRxNo,
            svMbrUniqKey,
            svSrcSysClmRcdDt,
            svSrcSysClmRcdTm
        ),
        skipDuplicateMapInputs: true,
        skipDuplicateMapOutputs: true) ~> xfmoptumrxV0S26P6map
    xfmoptumrxV0S26P6map
        filter(
            svPdxNtnlProvId == "Y" || svTransDeniedDt == "Y" || svRxNo == "Y" || svMbrUniqKey == "Y" || svSrcSysClmRcdDt == "Y" || svSrcSysClmRcdTm == "Y"
        ) ~> xfmoptumrxV0S26P6
    xfmoptumrxV0S26P6 sink(
      allowSchemaDrift: true,
      validateSchema: false,
      partitionFileNames:[(""" + ctx.getFileName("""$FilePath + '/load/MBR_PDX_DENIED_TRANS_ERROR.' + $CurrDate + '.dat'""") + f""")],
      partitionBy('hash', 1),
      skipDuplicateMapInputs: true,
      skipDuplicateMapOutputs: true,
      format: 'delimited',
      fileSystem: '{ctx.file_container}',
      folderPath: (""" + ctx.getFolderPath("""$FilePath + '/load/MBR_PDX_DENIED_TRANS_ERROR.' + $CurrDate + '.dat'""") + f""") ,
      columnDelimiter: ',',
      escapeChar:""" + '\\\\' + f""",
      rowDelimiter: '\\n',
      quoteChar: '\\"',
      columnNamesAsHeader:true) ~> Seqerror
    source(output(
        PROV_SK_SRV_PROV_SK as integer,
        SRC_SYS_CD_SK_SRV_PROV_SK as integer,
        SVC_PROV_NABP_NM as string),
      allowSchemaDrift: true,
      validateSchema: false,
      format: 'query',
      store: 'sqlserver',
      query: ("    SELECT \\n               PROV.PROV_SK AS PROV_SK_SRV_PROV_SK,\\n               PROV.SRC_SYS_CD_SK AS SRC_SYS_CD_SK_SRV_PROV_SK,\\n               PROV.PROV_ID AS SVC_PROV_NABP_NM        \\n               \\n               FROM " + toString($IDSOwner) + ".PROV PROV               \\n               INNER JOIN " + toString($IDSOwner) + ".CD_MPPNG CD_MPPNG\\n               ON PROV.SRC_SYS_CD_SK=CD_MPPNG.CD_MPPNG_SK \\n               WHERE   CD_MPPNG.TRGT_CD = 'NABP'\\n\\nORDER BY  PROV_ID ASC "),
      schemaName: '',
      tableName: '',
      isolationLevel: 'READ_UNCOMMITTED') ~> db2PROV
    source(output(
        PROV_SK as integer,
        PROV_SPEC_CD_SK as integer,
        PROV_DEA_SK as integer,
        NPI_NO as string,
        EFF_DT_SK as string,
        TERM_DT_SK as string),
      allowSchemaDrift: true,
      validateSchema: false,
      format: 'query',
      store: 'sqlserver',
      query: ("SELECT   \\n         MAX(PROV.PROV_SK) AS PROV_SK,      \\n         PROV_DEA.PROV_DEA_SK,        \\n         PROV.PROV_SPEC_CD_SK AS PROV_SPEC_CD_SK,	\\n         ----PROV_DEA.DEA_NO AS PHYS_DEA_NO,\\n         PROV_DEA.NTNL_PROV_ID AS NPI_NO,\\n         PROV_DEA.EFF_DT_SK AS EFF_DT_SK,\\n         PROV_DEA.TERM_DT_SK AS TERM_DT_SK\\nFROM     \\n         " + toString($IDSOwner) + ".PROV_DEA PROV_DEA \\n      INNER JOIN " + toString($IDSOwner) + ".PROV PROV \\n      ON PROV_DEA.CMN_PRCT_SK=PROV.CMN_PRCT_SK AND\\n      PROV_DEA.NTNL_PROV_ID=PROV.NTNL_PROV_ID \\n      INNER JOIN (SELECT\\n --                  MAX(PROV.PROV_SK) PROV_SK\\n                   PROV.CMN_PRCT_SK\\n                  , PROV.NTNL_PROV_ID\\n                  , MAX(PROV.TERM_DT_SK) AS TERM_DT_SK \\n               FROM\\n                  " + toString($IDSOwner) + ".PROV PROV \\n               GROUP BY\\n                 PROV.CMN_PRCT_SK\\n                  , PROV.NTNL_PROV_ID ) A \\n      ON PROV.CMN_PRCT_SK = A.CMN_PRCT_SK AND\\n--      PROV.PROV_SK = A.PROV_SK AND\\n      PROV.NTNL_PROV_ID = A.NTNL_PROV_ID AND\\n      PROV.TERM_DT_SK = A.TERM_DT_SK\\n	  \\nWHERE  PROV_DEA.CMN_PRCT_SK  NOT IN ('0','1')\\nAND PROV.TERM_DT_SK >= ORCHESTRATE.SVC_DT\\nAND PROV_DEA.EFF_DT_SK <= ORCHESTRATE.SVC_DT\\nAND PROV_DEA.TERM_DT_SK >= ORCHESTRATE.SVC_DT\\nAND PROV_DEA.DEA_NO= ORCHESTRATE.PHYS_DEA_NO\\nAND PROV_DEA.NTNL_PROV_ID = ORCHESTRATE.PHYS_NTNL_PROV_ID\\n\\nGROUP BY \\n         PROV_DEA.PROV_DEA_SK, \\n         PROV.PROV_SPEC_CD_SK, \\n         PROV_DEA.DEA_NO, \\n         PROV_DEA.NTNL_PROV_ID, \\n         PROV_DEA.EFF_DT_SK, \\n         PROV_DEA.TERM_DT_SK "),
      schemaName: '',
      tableName: '',
      isolationLevel: 'READ_UNCOMMITTED') ~> db2provdea
    {ctx.joinScript(joinType='left',
      master=['JnMbr', 'CLNT_ORG_OPTRNAL_ID,CLNT_ORG_NM,MAIL_ORDER_IN,SRC_SYS_CAR_ID,TRANS_TYP_CD,CLNT_MBRSH_ID,PATN_ID,CLNT_ID,CLNT_ELIG_MBRSH_ID,MBR_SSN,PRSN_NO,RELSHP_CD,GNDR_CD,SUB_BRTH_DT,MBR_BRTH_DT,MBR_FIRST_NM,MBR_LAST_NM,SUBMT_SUB_FIRST_NM,SUBMT_SUB_LAST_NM,RX_LABEL_TX,SVC_DT,SRC_SYS_GRP_ID,SRC_SYS_CLM_RCVD_DT,SRC_SYS_CLM_RCVD_TM,MSG_TYP_CD,MSG_TYP,MSG_TX,INGR_CST_ALW_AMT,BILL_RX_GROS_APRV_AMT,BILL_RX_NET_CHK_AMT,BILL_RX_PATN_PAY_AMT,BILL_RX_DISPENSE_FEE_AMT,MEDIA_TYP_CD,RSPN_CD,DESC,CHAPTER_ID,CHAPTER_DESC,PHYS_DEA_NO,PHYS_NTNL_PROV_ID,PHYS_FIRST_NM,PHYS_LAST_NM,PHYS_ST_ADDR_LN,PHYS_CITY_NM,PHYS_ST_CD,PHYS_POSTAL_CD,PDX_NTNL_PROV_ID,SVC_PROV_NABP_NM,PDX_NM,PDX_PHN_NO,NDC,MBR_UNIQ_KEY,MBR_SK,GRP_SK,SUB_SK,MBR_GNDR_CD_SK,MBR_RELSHP_CD_SK,MBR_SFX_NO,SRC_SYS_CD,RX_NO,MBR_ID,SRC_SYS_CNTR_ID,GRP_ID,CLMORIGIN,PDX_RSPN_RSN_CD_SK,PRCS_DT,LOB_IN'],
      transformationName='Lkpprov',
      references=[['db2provdea', ctx.joinConditionForLookup(master={'name':'JnMbr','alias':'Lnk_mbr','types':{'CLNT_ORG_OPTRNAL_ID':'string','CLNT_ORG_NM':'string','MAIL_ORDER_IN':'string','SRC_SYS_CAR_ID':'string','TRANS_TYP_CD':'string','CLNT_MBRSH_ID':'string','PATN_ID':'string','CLNT_ID':'string','CLNT_ELIG_MBRSH_ID':'string','MBR_SSN':'string','PRSN_NO':'string','RELSHP_CD':'string','GNDR_CD':'string','SUB_BRTH_DT':'string','MBR_BRTH_DT':'string','MBR_FIRST_NM':'string','MBR_LAST_NM':'string','SUBMT_SUB_FIRST_NM':'string','SUBMT_SUB_LAST_NM':'string','RX_LABEL_TX':'string','SVC_DT':'date','SRC_SYS_GRP_ID':'string','SRC_SYS_CLM_RCVD_DT':'date','SRC_SYS_CLM_RCVD_TM':'timestamp','MSG_TYP_CD':'string','MSG_TYP':'string','MSG_TX':'string','INGR_CST_ALW_AMT':'decimal(13, 2)','BILL_RX_GROS_APRV_AMT':'decimal(13, 2)','BILL_RX_NET_CHK_AMT':'decimal(13, 2)','BILL_RX_PATN_PAY_AMT':'decimal(13, 2)','BILL_RX_DISPENSE_FEE_AMT':'decimal(13, 2)','MEDIA_TYP_CD':'string','RSPN_CD':'string','DESC':'string','CHAPTER_ID':'string','CHAPTER_DESC':'string','PHYS_DEA_NO':'string','PHYS_NTNL_PROV_ID':'string','PHYS_FIRST_NM':'string','PHYS_LAST_NM':'string','PHYS_ST_ADDR_LN':'string','PHYS_CITY_NM':'string','PHYS_ST_CD':'string','PHYS_POSTAL_CD':'string','PDX_NTNL_PROV_ID':'string','SVC_PROV_NABP_NM':'string','PDX_NM':'string','PDX_PHN_NO':'string','NDC':'string','MBR_UNIQ_KEY':'integer','MBR_SK':'integer','GRP_SK':'integer','SUB_SK':'integer','MBR_GNDR_CD_SK':'integer','MBR_RELSHP_CD_SK':'integer','MBR_SFX_NO':'string','SRC_SYS_CD':'string','RX_NO':'string','MBR_ID':'string','SRC_SYS_CNTR_ID':'string','GRP_ID':'string','CLMORIGIN':'string','PDX_RSPN_RSN_CD_SK':'string','PRCS_DT':'date','LOB_IN':'string'}}, reference={'name':'db2provdea','alias':'lnk_prov_extr','types':{'PROV_SK':'integer','PROV_SPEC_CD_SK':'integer','PROV_DEA_SK':'integer','NPI_NO':'string','EFF_DT_SK':'string','TERM_DT_SK':'string'}}, joinFields=[]), 'PROV_SK,PROV_SPEC_CD_SK,PROV_DEA_SK,NPI_NO,EFF_DT_SK,TERM_DT_SK']],
      schema="CLNT_ORG_OPTRNAL_ID,CLNT_ORG_NM,MAIL_ORDER_IN,SRC_SYS_CAR_ID,TRANS_TYP_CD,CLNT_MBRSH_ID,PATN_ID,CLNT_ID,CLNT_ELIG_MBRSH_ID,MBR_SSN,PRSN_NO,RELSHP_CD,GNDR_CD,SUB_BRTH_DT,MBR_BRTH_DT,MBR_FIRST_NM,MBR_LAST_NM,SUBMT_SUB_FIRST_NM,SUBMT_SUB_LAST_NM,RX_LABEL_TX,SVC_DT,SRC_SYS_GRP_ID,SRC_SYS_CLM_RCVD_DT,SRC_SYS_CLM_RCVD_TM,MSG_TYP_CD,MSG_TYP,MSG_TX,INGR_CST_ALW_AMT,BILL_RX_GROS_APRV_AMT,BILL_RX_NET_CHK_AMT,BILL_RX_PATN_PAY_AMT,BILL_RX_DISPENSE_FEE_AMT,MEDIA_TYP_CD,RSPN_CD,DESC,CHAPTER_ID,CHAPTER_DESC,PHYS_DEA_NO,PHYS_NTNL_PROV_ID,PHYS_FIRST_NM,PHYS_LAST_NM,PHYS_ST_ADDR_LN,PHYS_CITY_NM,PHYS_ST_CD,PHYS_POSTAL_CD,PDX_NTNL_PROV_ID,SVC_PROV_NABP_NM,PDX_NM,PDX_PHN_NO,NDC,MBR_UNIQ_KEY,MBR_SK,GRP_SK,SUB_SK,MBR_GNDR_CD_SK,MBR_RELSHP_CD_SK,MBR_SFX_NO,PROV_SK,PROV_SPEC_CD_SK,PROV_DEA_SK,EFF_DT_SK,TERM_DT_SK,SRC_SYS_CD,CLMORIGIN,RX_NO,MBR_ID,SRC_SYS_CNTR_ID,GRP_ID,PDX_RSPN_RSN_CD_SK,PRCS_DT,LOB_IN",
      map=['Lnk_mbr.CLNT_ORG_OPTRNAL_ID','Lnk_mbr.CLNT_ORG_NM','Lnk_mbr.MAIL_ORDER_IN','Lnk_mbr.SRC_SYS_CAR_ID','Lnk_mbr.TRANS_TYP_CD','Lnk_mbr.CLNT_MBRSH_ID','Lnk_mbr.PATN_ID','Lnk_mbr.CLNT_ID','Lnk_mbr.CLNT_ELIG_MBRSH_ID','Lnk_mbr.MBR_SSN','Lnk_mbr.PRSN_NO','Lnk_mbr.RELSHP_CD','Lnk_mbr.GNDR_CD','Lnk_mbr.SUB_BRTH_DT','Lnk_mbr.MBR_BRTH_DT','Lnk_mbr.MBR_FIRST_NM','Lnk_mbr.MBR_LAST_NM','Lnk_mbr.SUBMT_SUB_FIRST_NM','Lnk_mbr.SUBMT_SUB_LAST_NM','Lnk_mbr.RX_LABEL_TX','Lnk_mbr.SVC_DT','Lnk_mbr.SRC_SYS_GRP_ID','Lnk_mbr.SRC_SYS_CLM_RCVD_DT','Lnk_mbr.SRC_SYS_CLM_RCVD_TM','Lnk_mbr.MSG_TYP_CD','Lnk_mbr.MSG_TYP','Lnk_mbr.MSG_TX','Lnk_mbr.INGR_CST_ALW_AMT','Lnk_mbr.BILL_RX_GROS_APRV_AMT','Lnk_mbr.BILL_RX_NET_CHK_AMT','Lnk_mbr.BILL_RX_PATN_PAY_AMT','Lnk_mbr.BILL_RX_DISPENSE_FEE_AMT','Lnk_mbr.MEDIA_TYP_CD','Lnk_mbr.RSPN_CD','Lnk_mbr.DESC','Lnk_mbr.CHAPTER_ID','Lnk_mbr.CHAPTER_DESC','Lnk_mbr.PHYS_DEA_NO','Lnk_mbr.PHYS_NTNL_PROV_ID','Lnk_mbr.PHYS_FIRST_NM','Lnk_mbr.PHYS_LAST_NM','Lnk_mbr.PHYS_ST_ADDR_LN','Lnk_mbr.PHYS_CITY_NM','Lnk_mbr.PHYS_ST_CD','Lnk_mbr.PHYS_POSTAL_CD','Lnk_mbr.PDX_NTNL_PROV_ID','Lnk_mbr.SVC_PROV_NABP_NM','Lnk_mbr.PDX_NM','Lnk_mbr.PDX_PHN_NO','Lnk_mbr.NDC','Lnk_mbr.MBR_UNIQ_KEY','Lnk_mbr.MBR_SK','Lnk_mbr.GRP_SK','Lnk_mbr.SUB_SK','Lnk_mbr.MBR_GNDR_CD_SK','Lnk_mbr.MBR_RELSHP_CD_SK','Lnk_mbr.MBR_SFX_NO','lnk_prov_extr.PROV_SK','lnk_prov_extr.PROV_SPEC_CD_SK','lnk_prov_extr.PROV_DEA_SK','lnk_prov_extr.EFF_DT_SK','lnk_prov_extr.TERM_DT_SK','Lnk_mbr.SRC_SYS_CD','Lnk_mbr.CLMORIGIN','Lnk_mbr.RX_NO','Lnk_mbr.MBR_ID','Lnk_mbr.SRC_SYS_CNTR_ID','Lnk_mbr.GRP_ID','Lnk_mbr.PDX_RSPN_RSN_CD_SK','Lnk_mbr.PRCS_DT','Lnk_mbr.LOB_IN'],
      aliasFrom="Lnk_mbr,lnk_prov_extr",
      aliasTo="JnMbr,db2provdea")}
    {ctx.joinScript(joinType='left', 
      master=['Lkpprov', 'CLNT_ORG_OPTRNAL_ID,CLNT_ORG_NM,MAIL_ORDER_IN,SRC_SYS_CAR_ID,TRANS_TYP_CD,CLNT_MBRSH_ID,PATN_ID,CLNT_ID,CLNT_ELIG_MBRSH_ID,MBR_SSN,PRSN_NO,RELSHP_CD,GNDR_CD,SUB_BRTH_DT,MBR_BRTH_DT,MBR_FIRST_NM,MBR_LAST_NM,SUBMT_SUB_FIRST_NM,SUBMT_SUB_LAST_NM,RX_LABEL_TX,SVC_DT,SRC_SYS_GRP_ID,SRC_SYS_CLM_RCVD_DT,SRC_SYS_CLM_RCVD_TM,MSG_TYP_CD,MSG_TYP,MSG_TX,INGR_CST_ALW_AMT,BILL_RX_GROS_APRV_AMT,BILL_RX_NET_CHK_AMT,BILL_RX_PATN_PAY_AMT,BILL_RX_DISPENSE_FEE_AMT,MEDIA_TYP_CD,RSPN_CD,DESC,CHAPTER_ID,CHAPTER_DESC,PHYS_DEA_NO,PHYS_NTNL_PROV_ID,PHYS_FIRST_NM,PHYS_LAST_NM,PHYS_ST_ADDR_LN,PHYS_CITY_NM,PHYS_ST_CD,PHYS_POSTAL_CD,PDX_NTNL_PROV_ID,SVC_PROV_NABP_NM,PDX_NM,PDX_PHN_NO,NDC,MBR_UNIQ_KEY,MBR_SK,GRP_SK,SUB_SK,MBR_GNDR_CD_SK,MBR_RELSHP_CD_SK,MBR_SFX_NO,PROV_SK,PROV_SPEC_CD_SK,PROV_DEA_SK,EFF_DT_SK,TERM_DT_SK,SRC_SYS_CD,CLMORIGIN,RX_NO,MBR_ID,SRC_SYS_CNTR_ID,GRP_ID,PDX_RSPN_RSN_CD_SK,PRCS_DT,LOB_IN'],
      transformationName='JnNABP', 
      references=[['db2PROV', ctx.joinConditionAndFixDataTypeMismatch(masterName='Lkpprov', masterDataTypes={'CLNT_ORG_OPTRNAL_ID':'string','CLNT_ORG_NM':'string','MAIL_ORDER_IN':'string','SRC_SYS_CAR_ID':'string','TRANS_TYP_CD':'string','CLNT_MBRSH_ID':'string','PATN_ID':'string','CLNT_ID':'string','CLNT_ELIG_MBRSH_ID':'string','MBR_SSN':'string','PRSN_NO':'string','RELSHP_CD':'string','GNDR_CD':'string','SUB_BRTH_DT':'string','MBR_BRTH_DT':'string','MBR_FIRST_NM':'string','MBR_LAST_NM':'string','SUBMT_SUB_FIRST_NM':'string','SUBMT_SUB_LAST_NM':'string','RX_LABEL_TX':'string','SVC_DT':'date','SRC_SYS_GRP_ID':'string','SRC_SYS_CLM_RCVD_DT':'date','SRC_SYS_CLM_RCVD_TM':'timestamp','MSG_TYP_CD':'string','MSG_TYP':'string','MSG_TX':'string','INGR_CST_ALW_AMT':'decimal(13, 2)','BILL_RX_GROS_APRV_AMT':'decimal(13, 2)','BILL_RX_NET_CHK_AMT':'decimal(13, 2)','BILL_RX_PATN_PAY_AMT':'decimal(13, 2)','BILL_RX_DISPENSE_FEE_AMT':'decimal(13, 2)','MEDIA_TYP_CD':'string','RSPN_CD':'string','DESC':'string','CHAPTER_ID':'string','CHAPTER_DESC':'string','PHYS_DEA_NO':'string','PHYS_NTNL_PROV_ID':'string','PHYS_FIRST_NM':'string','PHYS_LAST_NM':'string','PHYS_ST_ADDR_LN':'string','PHYS_CITY_NM':'string','PHYS_ST_CD':'string','PHYS_POSTAL_CD':'string','PDX_NTNL_PROV_ID':'string','SVC_PROV_NABP_NM':'string','PDX_NM':'string','PDX_PHN_NO':'string','NDC':'string','MBR_UNIQ_KEY':'integer','MBR_SK':'integer','GRP_SK':'integer','SUB_SK':'integer','MBR_GNDR_CD_SK':'integer','MBR_RELSHP_CD_SK':'integer','MBR_SFX_NO':'string','PROV_SK':'integer','PROV_SPEC_CD_SK':'integer','PROV_DEA_SK':'integer','EFF_DT_SK':'string','TERM_DT_SK':'string','SRC_SYS_CD':'string','CLMORIGIN':'string','RX_NO':'string','MBR_ID':'string','SRC_SYS_CNTR_ID':'string','GRP_ID':'string','PDX_RSPN_RSN_CD_SK':'string','PRCS_DT':'date','LOB_IN':'string'}, refName='db2PROV', refDataTypes={'PROV_SK_SRV_PROV_SK':'integer','SRC_SYS_CD_SK_SRV_PROV_SK':'integer','SVC_PROV_NABP_NM':'string'}, joinFields='SVC_PROV_NABP_NM'), 'PROV_SK_SRV_PROV_SK,SRC_SYS_CD_SK_SRV_PROV_SK,SVC_PROV_NABP_NM']],
      schema="CLNT_ORG_OPTRNAL_ID,CLNT_ORG_NM,MAIL_ORDER_IN,SRC_SYS_CAR_ID,TRANS_TYP_CD,CLNT_MBRSH_ID,PATN_ID,CLNT_ID,CLNT_ELIG_MBRSH_ID,MBR_SSN,PRSN_NO,RELSHP_CD,GNDR_CD,SUB_BRTH_DT,MBR_BRTH_DT,MBR_FIRST_NM,MBR_LAST_NM,SUBMT_SUB_FIRST_NM,SUBMT_SUB_LAST_NM,RX_LABEL_TX,SVC_DT,SRC_SYS_GRP_ID,SRC_SYS_CLM_RCVD_DT,SRC_SYS_CLM_RCVD_TM,MSG_TYP_CD,MSG_TYP,MSG_TX,INGR_CST_ALW_AMT,BILL_RX_GROS_APRV_AMT,BILL_RX_NET_CHK_AMT,BILL_RX_PATN_PAY_AMT,BILL_RX_DISPENSE_FEE_AMT,MEDIA_TYP_CD,RSPN_CD,DESC,CHAPTER_ID,CHAPTER_DESC,PHYS_DEA_NO,PHYS_NTNL_PROV_ID,PHYS_FIRST_NM,PHYS_LAST_NM,PHYS_ST_ADDR_LN,PHYS_CITY_NM,PHYS_ST_CD,PHYS_POSTAL_CD,PDX_NTNL_PROV_ID,SVC_PROV_NABP_NM,PDX_NM,PDX_PHN_NO,NDC,MBR_UNIQ_KEY,MBR_SK,GRP_SK,SUB_SK,MBR_GNDR_CD_SK,MBR_RELSHP_CD_SK,MBR_SFX_NO,PROV_SK,PROV_SPEC_CD_SK,PROV_DEA_SK,EFF_DT_SK,TERM_DT_SK,SRV_PROV_SK,SRC_SYS_CD_SK_SRV_PROV_SK,SRC_SYS_CD,RX_NO,MBR_ID,SRC_SYS_CNTR_ID,GRP_ID,CLMORIGIN,PDX_RSPN_RSN_CD_SK,PRCS_DT,LOB_IN",
      map=['Jn_ndc.CLNT_ORG_OPTRNAL_ID','Jn_ndc.CLNT_ORG_NM','Jn_ndc.MAIL_ORDER_IN','Jn_ndc.SRC_SYS_CAR_ID','Jn_ndc.TRANS_TYP_CD','Jn_ndc.CLNT_MBRSH_ID','Jn_ndc.PATN_ID','Jn_ndc.CLNT_ID','Jn_ndc.CLNT_ELIG_MBRSH_ID','Jn_ndc.MBR_SSN','Jn_ndc.PRSN_NO','Jn_ndc.RELSHP_CD','Jn_ndc.GNDR_CD','Jn_ndc.SUB_BRTH_DT','Jn_ndc.MBR_BRTH_DT','Jn_ndc.MBR_FIRST_NM','Jn_ndc.MBR_LAST_NM','Jn_ndc.SUBMT_SUB_FIRST_NM','Jn_ndc.SUBMT_SUB_LAST_NM','Jn_ndc.RX_LABEL_TX','Jn_ndc.SVC_DT','Jn_ndc.SRC_SYS_GRP_ID','Jn_ndc.SRC_SYS_CLM_RCVD_DT','Jn_ndc.SRC_SYS_CLM_RCVD_TM','Jn_ndc.MSG_TYP_CD','Jn_ndc.MSG_TYP','Jn_ndc.MSG_TX','iifNull(Jn_ndc.INGR_CST_ALW_AMT, 0, Jn_ndc.INGR_CST_ALW_AMT)','iifNull(Jn_ndc.BILL_RX_GROS_APRV_AMT, 0, Jn_ndc.BILL_RX_GROS_APRV_AMT)','iifNull(Jn_ndc.BILL_RX_NET_CHK_AMT, 0, Jn_ndc.BILL_RX_NET_CHK_AMT)','iifNull(Jn_ndc.BILL_RX_PATN_PAY_AMT, 0, Jn_ndc.BILL_RX_PATN_PAY_AMT)','iifNull(Jn_ndc.BILL_RX_DISPENSE_FEE_AMT, 0, Jn_ndc.BILL_RX_DISPENSE_FEE_AMT)','Jn_ndc.MEDIA_TYP_CD','Jn_ndc.RSPN_CD','Jn_ndc.DESC','Jn_ndc.CHAPTER_ID','Jn_ndc.CHAPTER_DESC','Jn_ndc.PHYS_DEA_NO','Jn_ndc.PHYS_NTNL_PROV_ID','Jn_ndc.PHYS_FIRST_NM','Jn_ndc.PHYS_LAST_NM','Jn_ndc.PHYS_ST_ADDR_LN','Jn_ndc.PHYS_CITY_NM','Jn_ndc.PHYS_ST_CD','Jn_ndc.PHYS_POSTAL_CD','Jn_ndc.PDX_NTNL_PROV_ID','Jn_ndc.SVC_PROV_NABP_NM','Jn_ndc.PDX_NM','Jn_ndc.PDX_PHN_NO','Jn_ndc.NDC','iifNull(Jn_ndc.MBR_UNIQ_KEY, 0, Jn_ndc.MBR_UNIQ_KEY)','iifNull(Jn_ndc.MBR_SK, 0, Jn_ndc.MBR_SK)','iifNull(Jn_ndc.GRP_SK, 0, Jn_ndc.GRP_SK)','iifNull(Jn_ndc.SUB_SK, 0, Jn_ndc.SUB_SK)','iifNull(Jn_ndc.MBR_GNDR_CD_SK, 0, Jn_ndc.MBR_GNDR_CD_SK)','iifNull(Jn_ndc.MBR_RELSHP_CD_SK, 0, Jn_ndc.MBR_RELSHP_CD_SK)','Jn_ndc.MBR_SFX_NO','iifNull(Jn_ndc.PROV_SK, 0, Jn_ndc.PROV_SK)','iifNull(Jn_ndc.PROV_SPEC_CD_SK, 0, Jn_ndc.PROV_SPEC_CD_SK)','iifNull(Jn_ndc.PROV_DEA_SK, 0, Jn_ndc.PROV_DEA_SK)','Jn_ndc.EFF_DT_SK','Jn_ndc.TERM_DT_SK','iifNull(lnk_SRV_PROV_SK.PROV_SK_SRV_PROV_SK, 0, lnk_SRV_PROV_SK.PROV_SK_SRV_PROV_SK)','iifNull(lnk_SRV_PROV_SK.SRC_SYS_CD_SK_SRV_PROV_SK, 0, lnk_SRV_PROV_SK.SRC_SYS_CD_SK_SRV_PROV_SK)','Jn_ndc.SRC_SYS_CD','Jn_ndc.RX_NO','Jn_ndc.MBR_ID','Jn_ndc.SRC_SYS_CNTR_ID','Jn_ndc.GRP_ID','Jn_ndc.CLMORIGIN','Jn_ndc.PDX_RSPN_RSN_CD_SK','Jn_ndc.PRCS_DT','Jn_ndc.LOB_IN'],
      aliasFrom="Jn_ndc,lnk_SRV_PROV_SK", 
      aliasTo="Lkpprov,db2PROV",
      fillNull="True")}
    JnNABP
        derive(
              MBR_PDX_DENIED_TRANS_SK = 0,
              MBR_UNIQ_KEY = MBR_UNIQ_KEY,
              PDX_NTNL_PROV_ID = PDX_NTNL_PROV_ID,
              TRANS_TYP_CD = trim(upper(TRANS_TYP_CD)),
              TRANS_DENIED_DT = SVC_DT,
              RX_NO = RX_NO,
              PRCS_DT = currentDate(),
              SRC_SYS_CD = trim(SRC_SYS_CD),
              CRT_RUN_CYC_EXCTN_SK = $IDSRunCycle,
              LAST_UPDT_RUN_CYC_EXCTN_SK = $IDSRunCycle,
              GRP_SK =  case(isNull(GRP_SK) || length(GRP_SK) == 0, 0, GRP_SK),
              MBR_SK =  case(isNull(MBR_SK) || length(MBR_SK) == 0, 0, MBR_SK),
              NDC_SK = "0",
              PRSCRB_PROV_SK =  case(isNull(PROV_SK) || length(PROV_SK) == 0, 0, PROV_SK),
              PROV_SPEC_CD_SK =  case(isNull(PROV_SPEC_CD_SK) || length(PROV_SPEC_CD_SK) == 0, 0, PROV_SPEC_CD_SK),
              SRV_PROV_SK =  case(isNull(SRV_PROV_SK) || length(SRV_PROV_SK) == 0, 0, SRV_PROV_SK),
              SUB_SK =  case(isNull(SUB_SK) || length(SUB_SK) == 0, 0, SUB_SK),
              MEDIA_TYP_CD_SK = CLMORIGIN,
              MBR_GNDR_CD_SK =  case(isNull(MBR_GNDR_CD_SK) || length(MBR_GNDR_CD_SK) == 0, 0, MBR_GNDR_CD_SK),
              MBR_RELSHP_CD_SK =  case(isNull(MBR_RELSHP_CD_SK) || length(MBR_RELSHP_CD_SK) == 0, 0, MBR_RELSHP_CD_SK),
              PDX_RSPN_RSN_CD_SK = npw_DS_TRIM_1(PDX_RSPN_RSN_CD_SK),
              PDX_RSPN_TYP_CD_SK = 0,
              TRANS_TYP_CD_SK = 0,
              MAIL_ORDER_IN =  case((isNull(MAIL_ORDER_IN) || length(trim(MAIL_ORDER_IN)) == 0), "R", MAIL_ORDER_IN),
              MBR_BRTH_DT =  case((isNull(MBR_BRTH_DT) || length(trim(MBR_BRTH_DT)) == 0), "1753-01-01", MBR_BRTH_DT),
              SRC_SYS_CLM_RCVD_DT = SRC_SYS_CLM_RCVD_DT,
              SRC_SYS_CLM_RCVD_TM = SRC_SYS_CLM_RCVD_TM,
              SUB_BRTH_DT =  case((isNull(SUB_BRTH_DT) || length(trim(SUB_BRTH_DT)) == 0), "1753-01-01", SUB_BRTH_DT),
              BILL_RX_DISPENSE_FEE_AMT =  case((isNull(BILL_RX_DISPENSE_FEE_AMT) || length(trim(BILL_RX_DISPENSE_FEE_AMT)) == 0), "0.00 ", BILL_RX_DISPENSE_FEE_AMT),
              BILL_RX_GROS_APRV_AMT =  case((isNull(BILL_RX_GROS_APRV_AMT) || length(trim(BILL_RX_GROS_APRV_AMT)) == 0), "0.00 ", BILL_RX_GROS_APRV_AMT),
              BILL_RX_NET_CHK_AMT =  case((isNull(BILL_RX_NET_CHK_AMT) || length(trim(BILL_RX_NET_CHK_AMT)) == 0), "0.00 ", BILL_RX_NET_CHK_AMT),
              BILL_RX_PATN_PAY_AMT =  case((isNull(BILL_RX_PATN_PAY_AMT) || length(trim(BILL_RX_PATN_PAY_AMT)) == 0), "0.00 ", BILL_RX_PATN_PAY_AMT),
              INGR_CST_ALW_AMT =  case((isNull(INGR_CST_ALW_AMT) || length(trim(INGR_CST_ALW_AMT)) == 0), "0.00 ", INGR_CST_ALW_AMT),
              TRANS_MO_NO =  case(length(month(currentDate())) == 1, "0" + month(currentDate()), month(currentDate())),
              TRANS_YR_NO = year(currentDate()),
              MBR_ID =  case(LOB_IN == "MCARE", SRC_SYS_CNTR_ID, substring(MBR_ID, 1, 20)),
              MBR_SFX_NO =  case(isNull(MBR_SFX_NO) || length(npw_DS_TRIM_1(MBR_SFX_NO)) == 0, "00", trim(MBR_SFX_NO)),
              MBR_FIRST_NM =  case((isNull(MBR_FIRST_NM) || length(npw_DS_TRIM_1(MBR_FIRST_NM)) == 0), "UNK", npw_DS_TRIM_1(upper(MBR_FIRST_NM))),
              MBR_LAST_NM =  case((isNull(MBR_LAST_NM) || length(npw_DS_TRIM_1(MBR_LAST_NM)) == 0), "UNK", npw_DS_TRIM_1(upper(MBR_LAST_NM))),
              MBR_SSN =  case(isNull(MBR_SSN) || length(MBR_SSN) == 0, "UNK", MBR_SSN),
              PDX_NM =  case((isNull(PDX_NM) || length(trim(PDX_NM)) == 0), "", trim(upper(PDX_NM))),
              PDX_PHN_NO = PDX_PHN_NO,
              PHYS_DEA_NO = PHYS_DEA_NO,
              PHYS_NTNL_PROV_ID =  case((isNull(PHYS_NTNL_PROV_ID) || length(trim(PHYS_NTNL_PROV_ID)) == 0 || PHYS_NTNL_PROV_ID == "0") || (PHYS_NTNL_PROV_ID == "NA"), "UNK", trim(upper(PHYS_NTNL_PROV_ID))),
              PHYS_FIRST_NM =  case((isNull(PHYS_FIRST_NM) || length(trim(PHYS_FIRST_NM)) == 0), "UNK", trim(upper(PHYS_FIRST_NM))),
              PHYS_LAST_NM =  case((isNull(PHYS_LAST_NM) || length(npw_DS_TRIM_1(PHYS_LAST_NM)) == 0), "UNK", trim(upper(PHYS_LAST_NM))),
              PHYS_ST_ADDR_LN = PHYS_ST_ADDR_LN,
              PHYS_CITY_NM = PHYS_CITY_NM,
              PHYS_ST_CD =  case((isNull(PHYS_ST_CD) || length(npw_DS_TRIM_1(PHYS_ST_CD)) == 0), "UNK", trim(upper(PHYS_ST_CD))),
              PHYS_POSTAL_CD = PHYS_POSTAL_CD,
              RX_LABEL_TX =  case((isNull(RX_LABEL_TX) || length(trim(RX_LABEL_TX)) == 0), "UNK", trim(upper(RX_LABEL_TX))),
              SVC_PROV_NABP_NM =  case((isNull(SVC_PROV_NABP_NM) || length(npw_DS_TRIM_1(SVC_PROV_NABP_NM)) == 0), "UNK", trim(upper(SVC_PROV_NABP_NM))),
              SRC_SYS_CAR_ID =  case((isNull(SRC_SYS_CAR_ID) || length(npw_DS_TRIM_1(SRC_SYS_CAR_ID)) == 0), "UNK", trim(upper(SRC_SYS_CAR_ID))),
              SRC_SYS_CLNT_ORG_ID = "BCBSKC",
              SRC_SYS_CLNT_ORG_NM = "BCBS OF KANSAS CITY",
              SRC_SYS_CNTR_ID =  case((isNull(SRC_SYS_CNTR_ID) || length(npw_DS_TRIM_1(SRC_SYS_CNTR_ID)) == 0), "UNK", trim(upper(SRC_SYS_CNTR_ID))),
              SRC_SYS_GRP_ID =  case((isNull(SRC_SYS_GRP_ID) || length(npw_DS_TRIM_1(SRC_SYS_GRP_ID)) == 0), "UNK", trim(upper(SRC_SYS_GRP_ID))),
              SUB_ID =  case((isNull(CLNT_ID) || length(trim(CLNT_ID)) == 0), "UNK", trim(upper(CLNT_ID))),
              SUB_FIRST_NM = npw_DS_TRIM_1(upper(SUBMT_SUB_FIRST_NM)),
              SUB_LAST_NM = npw_DS_TRIM_1(upper(SUBMT_SUB_LAST_NM)),
              CLNT_ELIG_MBRSH_ID = CLNT_ELIG_MBRSH_ID,
              PRSN_NO = npw_DS_TRIM_1(upper(PRSN_NO)),
              RELSHP_CD = npw_DS_TRIM_1(upper(RELSHP_CD)),
              GNDR_CD = npw_DS_TRIM_1(upper(GNDR_CD)),
              CLM_RCVD_TM = SRC_SYS_CLM_RCVD_TM,
              MSG_TYP_CD = npw_DS_TRIM_1(upper(MSG_TYP_CD)),
              MSG_TYP = npw_DS_TRIM_1(upper(MSG_TYP)),
              MSG_TX = npw_DS_TRIM_1(upper(MSG_TX)),
              CLNT_MBRSH_ID = npw_DS_TRIM_1(upper(CLNT_MBRSH_ID)),
              MEDIA_TYP_CD = npw_DS_TRIM_1(upper(MEDIA_TYP_CD)),
              RSPN_CD = npw_DS_TRIM_1(upper(RSPN_CD)),
              DESC = npw_DS_TRIM_1(upper(DESC)),
              CHAPTER_ID = npw_DS_TRIM_1(upper(CHAPTER_ID)),
              CHAPTER_DESC = trim(upper(CHAPTER_DESC)),
              PDX_NPI = PDX_NTNL_PROV_ID,
              NDC = NDC) ~> xfmOptumRxpdxDerived
        xfmOptumRxpdxDerived
        select(mapColumn(
            MBR_PDX_DENIED_TRANS_SK,
            MBR_UNIQ_KEY,
            PDX_NTNL_PROV_ID,
            TRANS_TYP_CD,
            TRANS_DENIED_DT,
            RX_NO,
            PRCS_DT,
            SRC_SYS_CD,
            CRT_RUN_CYC_EXCTN_SK,
            LAST_UPDT_RUN_CYC_EXCTN_SK,
            GRP_SK,
            MBR_SK,
            NDC_SK,
            PRSCRB_PROV_SK,
            PROV_SPEC_CD_SK,
            SRV_PROV_SK,
            SUB_SK,
            MEDIA_TYP_CD_SK,
            MBR_GNDR_CD_SK,
            MBR_RELSHP_CD_SK,
            PDX_RSPN_RSN_CD_SK,
            PDX_RSPN_TYP_CD_SK,
            TRANS_TYP_CD_SK,
            MAIL_ORDER_IN,
            MBR_BRTH_DT,
            SRC_SYS_CLM_RCVD_DT,
            SRC_SYS_CLM_RCVD_TM,
            SUB_BRTH_DT,
            BILL_RX_DISPENSE_FEE_AMT,
            BILL_RX_GROS_APRV_AMT,
            BILL_RX_NET_CHK_AMT,
            BILL_RX_PATN_PAY_AMT,
            INGR_CST_ALW_AMT,
            TRANS_MO_NO,
            TRANS_YR_NO,
            MBR_ID,
            MBR_SFX_NO,
            MBR_FIRST_NM,
            MBR_LAST_NM,
            MBR_SSN,
            PDX_NM,
            PDX_PHN_NO,
            PHYS_DEA_NO,
            PHYS_NTNL_PROV_ID,
            PHYS_FIRST_NM,
            PHYS_LAST_NM,
            PHYS_ST_ADDR_LN,
            PHYS_CITY_NM,
            PHYS_ST_CD,
            PHYS_POSTAL_CD,
            RX_LABEL_TX,
            SVC_PROV_NABP_NM,
            SRC_SYS_CAR_ID,
            SRC_SYS_CLNT_ORG_ID,
            SRC_SYS_CLNT_ORG_NM,
            SRC_SYS_CNTR_ID,
            SRC_SYS_GRP_ID,
            SUB_ID,
            SUB_FIRST_NM,
            SUB_LAST_NM,
            CLNT_ELIG_MBRSH_ID,
            PRSN_NO,
            RELSHP_CD,
            GNDR_CD,
            CLM_RCVD_TM,
            MSG_TYP_CD,
            MSG_TYP,
            MSG_TX,
            CLNT_MBRSH_ID,
            MEDIA_TYP_CD,
            RSPN_CD,
            DESC,
            CHAPTER_ID,
            CHAPTER_DESC,
            PDX_NPI,
            NDC
        ),
        skipDuplicateMapInputs: true,
        skipDuplicateMapOutputs: true) ~> xfmOptumRxpdx
    xfmOptumRxpdx aggregate(groupBy(mycols = sha2(256, 'MBR_UNIQ_KEY', 'PDX_NTNL_PROV_ID', 'TRANS_TYP_CD', 'TRANS_DENIED_DT', 'RX_NO', 'PRCS_DT', 'SRC_SYS_CLM_RCVD_DT', 'SRC_SYS_CLM_RCVD_TM', 'SRC_SYS_CD')),
    	each(match(true()), $$ = first($$))) ~> RvNaturalKeysAggregate
    RvNaturalKeysAggregate
        select(mapColumn(
            {ctx.formatSelectMap("MBR_PDX_DENIED_TRANS_SK", "Lnk_OptumRx_mbr_denied_tgt.MBR_PDX_DENIED_TRANS_SK")},
            {ctx.formatSelectMap("MBR_UNIQ_KEY", "Lnk_OptumRx_mbr_denied_tgt.MBR_UNIQ_KEY")},
            {ctx.formatSelectMap("PDX_NTNL_PROV_ID", "Lnk_OptumRx_mbr_denied_tgt.PDX_NTNL_PROV_ID")},
            {ctx.formatSelectMap("TRANS_TYP_CD", "Lnk_OptumRx_mbr_denied_tgt.TRANS_TYP_CD")},
            {ctx.formatSelectMap("TRANS_DENIED_DT", "Lnk_OptumRx_mbr_denied_tgt.TRANS_DENIED_DT")},
            {ctx.formatSelectMap("RX_NO", "Lnk_OptumRx_mbr_denied_tgt.RX_NO")},
            {ctx.formatSelectMap("PRCS_DT", "Lnk_OptumRx_mbr_denied_tgt.PRCS_DT")},
            {ctx.formatSelectMap("SRC_SYS_CD", "Lnk_OptumRx_mbr_denied_tgt.SRC_SYS_CD")},
            {ctx.formatSelectMap("CRT_RUN_CYC_EXCTN_SK", "Lnk_OptumRx_mbr_denied_tgt.CRT_RUN_CYC_EXCTN_SK")},
            {ctx.formatSelectMap("LAST_UPDT_RUN_CYC_EXCTN_SK", "Lnk_OptumRx_mbr_denied_tgt.LAST_UPDT_RUN_CYC_EXCTN_SK")},
            {ctx.formatSelectMap("GRP_SK", "Lnk_OptumRx_mbr_denied_tgt.GRP_SK")},
            {ctx.formatSelectMap("MBR_SK", "Lnk_OptumRx_mbr_denied_tgt.MBR_SK")},
            {ctx.formatSelectMap("NDC_SK", "Lnk_OptumRx_mbr_denied_tgt.NDC_SK")},
            {ctx.formatSelectMap("PRSCRB_PROV_SK", "Lnk_OptumRx_mbr_denied_tgt.PRSCRB_PROV_SK")},
            {ctx.formatSelectMap("PROV_SPEC_CD_SK", "Lnk_OptumRx_mbr_denied_tgt.PROV_SPEC_CD_SK")},
            {ctx.formatSelectMap("SRV_PROV_SK", "Lnk_OptumRx_mbr_denied_tgt.SRV_PROV_SK")},
            {ctx.formatSelectMap("SUB_SK", "Lnk_OptumRx_mbr_denied_tgt.SUB_SK")},
            {ctx.formatSelectMap("MEDIA_TYP_CD_SK", "Lnk_OptumRx_mbr_denied_tgt.MEDIA_TYP_CD_SK")},
            {ctx.formatSelectMap("MBR_GNDR_CD_SK", "Lnk_OptumRx_mbr_denied_tgt.MBR_GNDR_CD_SK")},
            {ctx.formatSelectMap("MBR_RELSHP_CD_SK", "Lnk_OptumRx_mbr_denied_tgt.MBR_RELSHP_CD_SK")},
            {ctx.formatSelectMap("PDX_RSPN_RSN_CD_SK", "Lnk_OptumRx_mbr_denied_tgt.PDX_RSPN_RSN_CD_SK")},
            {ctx.formatSelectMap("PDX_RSPN_TYP_CD_SK", "Lnk_OptumRx_mbr_denied_tgt.PDX_RSPN_TYP_CD_SK")},
            {ctx.formatSelectMap("TRANS_TYP_CD_SK", "Lnk_OptumRx_mbr_denied_tgt.TRANS_TYP_CD_SK")},
            {ctx.formatSelectMap("MAIL_ORDER_IN", "Lnk_OptumRx_mbr_denied_tgt.MAIL_ORDER_IN")},
            {ctx.formatSelectMap("MBR_BRTH_DT", "Lnk_OptumRx_mbr_denied_tgt.MBR_BRTH_DT")},
            {ctx.formatSelectMap("SRC_SYS_CLM_RCVD_DT", "Lnk_OptumRx_mbr_denied_tgt.SRC_SYS_CLM_RCVD_DT")},
            {ctx.formatSelectMap("SRC_SYS_CLM_RCVD_TM", "Lnk_OptumRx_mbr_denied_tgt.SRC_SYS_CLM_RCVD_TM")},
            {ctx.formatSelectMap("SUB_BRTH_DT", "Lnk_OptumRx_mbr_denied_tgt.SUB_BRTH_DT")},
            {ctx.formatSelectMap("BILL_RX_DISPENSE_FEE_AMT", "Lnk_OptumRx_mbr_denied_tgt.BILL_RX_DISPENSE_FEE_AMT")},
            {ctx.formatSelectMap("BILL_RX_GROS_APRV_AMT", "Lnk_OptumRx_mbr_denied_tgt.BILL_RX_GROS_APRV_AMT")},
            {ctx.formatSelectMap("BILL_RX_NET_CHK_AMT", "Lnk_OptumRx_mbr_denied_tgt.BILL_RX_NET_CHK_AMT")},
            {ctx.formatSelectMap("BILL_RX_PATN_PAY_AMT", "Lnk_OptumRx_mbr_denied_tgt.BILL_RX_PATN_PAY_AMT")},
            {ctx.formatSelectMap("INGR_CST_ALW_AMT", "Lnk_OptumRx_mbr_denied_tgt.INGR_CST_ALW_AMT")},
            {ctx.formatSelectMap("TRANS_MO_NO", "Lnk_OptumRx_mbr_denied_tgt.TRANS_MO_NO")},
            {ctx.formatSelectMap("TRANS_YR_NO", "Lnk_OptumRx_mbr_denied_tgt.TRANS_YR_NO")},
            {ctx.formatSelectMap("MBR_ID", "Lnk_OptumRx_mbr_denied_tgt.MBR_ID")},
            {ctx.formatSelectMap("MBR_SFX_NO", "Lnk_OptumRx_mbr_denied_tgt.MBR_SFX_NO")},
            {ctx.formatSelectMap("MBR_FIRST_NM", "Lnk_OptumRx_mbr_denied_tgt.MBR_FIRST_NM")},
            {ctx.formatSelectMap("MBR_LAST_NM", "Lnk_OptumRx_mbr_denied_tgt.MBR_LAST_NM")},
            {ctx.formatSelectMap("MBR_SSN", "Lnk_OptumRx_mbr_denied_tgt.MBR_SSN")},
            {ctx.formatSelectMap("PDX_NM", "Lnk_OptumRx_mbr_denied_tgt.PDX_NM")},
            {ctx.formatSelectMap("PDX_PHN_NO", "Lnk_OptumRx_mbr_denied_tgt.PDX_PHN_NO")},
            {ctx.formatSelectMap("PHYS_DEA_NO", "Lnk_OptumRx_mbr_denied_tgt.PHYS_DEA_NO")},
            {ctx.formatSelectMap("PHYS_NTNL_PROV_ID", "Lnk_OptumRx_mbr_denied_tgt.PHYS_NTNL_PROV_ID")},
            {ctx.formatSelectMap("PHYS_FIRST_NM", "Lnk_OptumRx_mbr_denied_tgt.PHYS_FIRST_NM")},
            {ctx.formatSelectMap("PHYS_LAST_NM", "Lnk_OptumRx_mbr_denied_tgt.PHYS_LAST_NM")},
            {ctx.formatSelectMap("PHYS_ST_ADDR_LN", "Lnk_OptumRx_mbr_denied_tgt.PHYS_ST_ADDR_LN")},
            {ctx.formatSelectMap("PHYS_CITY_NM", "Lnk_OptumRx_mbr_denied_tgt.PHYS_CITY_NM")},
            {ctx.formatSelectMap("PHYS_ST_CD", "Lnk_OptumRx_mbr_denied_tgt.PHYS_ST_CD")},
            {ctx.formatSelectMap("PHYS_POSTAL_CD", "Lnk_OptumRx_mbr_denied_tgt.PHYS_POSTAL_CD")},
            {ctx.formatSelectMap("RX_LABEL_TX", "Lnk_OptumRx_mbr_denied_tgt.RX_LABEL_TX")},
            {ctx.formatSelectMap("SVC_PROV_NABP_NM", "Lnk_OptumRx_mbr_denied_tgt.SVC_PROV_NABP_NM")},
            {ctx.formatSelectMap("SRC_SYS_CAR_ID", "Lnk_OptumRx_mbr_denied_tgt.SRC_SYS_CAR_ID")},
            {ctx.formatSelectMap("SRC_SYS_CLNT_ORG_ID", "Lnk_OptumRx_mbr_denied_tgt.SRC_SYS_CLNT_ORG_ID")},
            {ctx.formatSelectMap("SRC_SYS_CLNT_ORG_NM", "Lnk_OptumRx_mbr_denied_tgt.SRC_SYS_CLNT_ORG_NM")},
            {ctx.formatSelectMap("SRC_SYS_CNTR_ID", "Lnk_OptumRx_mbr_denied_tgt.SRC_SYS_CNTR_ID")},
            {ctx.formatSelectMap("SRC_SYS_GRP_ID", "Lnk_OptumRx_mbr_denied_tgt.SRC_SYS_GRP_ID")},
            {ctx.formatSelectMap("SUB_ID", "Lnk_OptumRx_mbr_denied_tgt.SUB_ID")},
            {ctx.formatSelectMap("SUB_FIRST_NM", "Lnk_OptumRx_mbr_denied_tgt.SUB_FIRST_NM")},
            {ctx.formatSelectMap("SUB_LAST_NM", "Lnk_OptumRx_mbr_denied_tgt.SUB_LAST_NM")},
            {ctx.formatSelectMap("CLNT_ELIG_MBRSH_ID", "Lnk_OptumRx_mbr_denied_tgt.CLNT_ELIG_MBRSH_ID")},
            {ctx.formatSelectMap("PRSN_NO", "Lnk_OptumRx_mbr_denied_tgt.PRSN_NO")},
            {ctx.formatSelectMap("RELSHP_CD", "Lnk_OptumRx_mbr_denied_tgt.RELSHP_CD")},
            {ctx.formatSelectMap("GNDR_CD", "Lnk_OptumRx_mbr_denied_tgt.GNDR_CD")},
            {ctx.formatSelectMap("CLM_RCVD_TM", "Lnk_OptumRx_mbr_denied_tgt.CLM_RCVD_TM")},
            {ctx.formatSelectMap("MSG_TYP_CD", "Lnk_OptumRx_mbr_denied_tgt.MSG_TYP_CD")},
            {ctx.formatSelectMap("MSG_TYP", "Lnk_OptumRx_mbr_denied_tgt.MSG_TYP")},
            {ctx.formatSelectMap("MSG_TX", "Lnk_OptumRx_mbr_denied_tgt.MSG_TX")},
            {ctx.formatSelectMap("CLNT_MBRSH_ID", "Lnk_OptumRx_mbr_denied_tgt.CLNT_MBRSH_ID")},
            {ctx.formatSelectMap("MEDIA_TYP_CD", "Lnk_OptumRx_mbr_denied_tgt.MEDIA_TYP_CD")},
            {ctx.formatSelectMap("RSPN_CD", "Lnk_OptumRx_mbr_denied_tgt.RSPN_CD")},
            {ctx.formatSelectMap("DESC", "Lnk_OptumRx_mbr_denied_tgt.DESC")},
            {ctx.formatSelectMap("CHAPTER_ID", "Lnk_OptumRx_mbr_denied_tgt.CHAPTER_ID")},
            {ctx.formatSelectMap("CHAPTER_DESC", "Lnk_OptumRx_mbr_denied_tgt.CHAPTER_DESC")},
            {ctx.formatSelectMap("PDX_NPI", "Lnk_OptumRx_mbr_denied_tgt.PDX_NPI")},
            {ctx.formatSelectMap("NDC", "Lnk_OptumRx_mbr_denied_tgt.NDC")}
        ),
        skipDuplicateMapInputs: true,
        skipDuplicateMapOutputs: true) ~> RvNaturalKeys
    RvNaturalKeys sink(
      allowSchemaDrift: true,
      validateSchema: false,
      format: 'parquet',
      fileSystem: '{ctx.file_container}',
      folderPath: (toString($FilePath) + '/ds/MBR_PDX_DENIED_TRANS.' + toString($SrcSysCd) + '.xfrm.' + toString($RunID) + '.ds'),
      truncate: true,
      compressionCodec: 'none',
      umask: 0022,
      preCommands: [],
      postCommands: [],
      skipDuplicateMapInputs: true,
      skipDuplicateMapOutputs: true) ~> dsMBRPDXDENIEDTRANSxfm""", type='MappingDataFlow')
    artifacts = buffer.artifacts + [(dataflowName, dataflow)]
    return artifacts, dataflowName
  artifacts, dataflowName = dfOptumIdsMbrPdxDeniedClmXfm()
  activityName = "OptumIdsMbrPdxDeniedClmXfm"
  activityParameters = {"IDSAcct":  {"value": "'@{pipeline().parameters.IDSAcct}'","type": "Expression"},
  "IDSDB":  {"value": "'@{pipeline().parameters.IDSDB}'","type": "Expression"},
  "IDSPW":  {"value": "'@{pipeline().parameters.IDSPW}'","type": "Expression"},
  "APT_CONFIG_FILE":  {"value": "'@{pipeline().parameters.APT_CONFIG_FILE}'","type": "Expression"},
  "FilePath":  {"value": "'@{pipeline().parameters.FilePath}'","type": "Expression"},
  "IDSOwner":  {"value": "'@{pipeline().parameters.IDSOwner}'","type": "Expression"},
  "IDSDB2ArraySize":  {"value": "'@{pipeline().parameters.IDSDB2ArraySize}'","type": "Expression"},
  "IDSDB2RecordCount":  {"value": "'@{pipeline().parameters.IDSDB2RecordCount}'","type": "Expression"},
  "IDSRunCycle":  {"value": "'@{pipeline().parameters.IDSRunCycle}'","type": "Expression"},
  "SrcSysCd":  {"value": "'@{pipeline().parameters.SrcSysCd}'","type": "Expression"},
  "RunID":  {"value": "'@{pipeline().parameters.RunID}'","type": "Expression"},
  "CurrDate":  {"value": "'@{pipeline().parameters.CurrDate}'","type": "Expression"}}
  activity = ExecuteDataFlowActivity(
    name = activityName,
    data_flow = DataFlowReference(reference_name=dataflowName,
      parameters=activityParameters, type='DataFlowReference'))
  return artifacts, [activity]

def OptumIdsMbrPdxDeniedClmXfm(ctx):
  name = "OptumIdsMbrPdxDeniedClmXfm"
  artifacts, activities = OptumIdsMbrPdxDeniedClmXfmActivities(ctx)
  pipeline = PipelineResource(
    folder = PipelineFolder(name="DataWarehouse/Claim/DeniedPDXClaims"),
    activities = activities,
    description = """
      Extract OPTUMRX  Claims denied data, do Member and provider matching details
      *****************************************************************************************************************************************************************************
      COPYRIGHT 2019 BLUE CROSS/BLUE SHIELD OF KANSAS CITY 


      DESCRIPTION:  OPTUMRX  Claims denied data is extracted from source file and loaded into the  MBR_PDX_DENIED_TRANS Table


      Called By: OptumIdsMbrPdxDeniedTransLoadSeq

      MODIFICATIONS:
      Developer                 Date                  Project/Altiris #                                                     Change Description                                                      Development Project           Code Reviewer                
      ------------------              --------------------     ------------------------                                                    --------------------------------------------------------------                      --------------------------------------         --------------------------------
      Peter Gichiri              2019-10-27      6131 - PBM REPLACEMENT  to OPTUMRX     Original Devlopment Integrate                                       IntegrateDev2                         Kalyan Neelam        2019-11-21

      Rekha Radhakrishna 2020-10-12  Phase II Government Programs                             TRANS_MO_NO derivation changed                           IntegrateDev2
                                                                                                                                            to show two digit month
      Rekha Radhakrishna 2020-11-05 Phase II Government Programs                               Changed Member Matching logic for Med-D                IntegrateDev2                        Kalyan Neelam         2020-12-10
      Parameters:
      -----------
      IDSAcct:
        IDS Account
      IDSDB:
        IDS Database
      IDSPW:
        IDS Password
      APT_CONFIG_FILE:
        Configuration file
        The Parallel job configuration file.
      FilePath:
        File Path
      IDSOwner:
        IDS Table Owner
      IDSDB2ArraySize:
        IDS DB2 Array Size for Load
      IDSDB2RecordCount:
        IDS DB2 Record Count for Load
      IDSRunCycle:
        IDSRunCycle
      SrcSysCd:
        SrcSysCd
      RunID:
        RunID
      CurrDate:
        CurrDate""",
    parameters = {
      "IDSAcct": ParameterSpecification(type="String"),
      "IDSDB": ParameterSpecification(type="String", default_value=ctx.IDSDB),
      "IDSPW": ParameterSpecification(type="String"),
      "APT_CONFIG_FILE": ParameterSpecification(type="String", default_value=ctx.APT_CONFIG_FILE),
      "FilePath": ParameterSpecification(type="String", default_value=ctx.FilePath),
      "IDSOwner": ParameterSpecification(type="String", default_value=ctx.IDSOwner),
      "IDSDB2ArraySize": ParameterSpecification(type="String", default_value=ctx.IDSDB2ArraySize),
      "IDSDB2RecordCount": ParameterSpecification(type="String", default_value=ctx.IDSDB2RecordCount),
      "IDSRunCycle": ParameterSpecification(type="Int"),
      "SrcSysCd": ParameterSpecification(type="String"),
      "RunID": ParameterSpecification(type="String"),
      "CurrDate": ParameterSpecification(type="String")})
  return artifacts + [(name, pipeline)]

def main():
  ctx = TranslationContext()
  artifacts = (OptumIdsMbrPdxDeniedClmXfm(ctx))
  if ctx.validateArtifacts(artifacts):
    ctx.deployArtifacts(artifacts)

if __name__ == '__main__':
  main()
