# Databricks notebook source
# MAGIC %md
# MAGIC **Date:** 2025-08-24
# MAGIC """
# MAGIC COPYRIGHT 2009 - 2011 BLUE CROSS/BLUE SHIELD OF KANSAS CITY 
# MAGIC 
# MAGIC 
# MAGIC DESCRIPTION:  Extracts latest run cycle data and updates the LFSTYL_RATE_FCTR_SK field with the appropriate value
# MAGIC       
# MAGIC 
# MAGIC MODIFICATIONS:
# MAGIC Developer	Date		Project/Altiris #		Change Description				Development Project	Code Reviewer	Date Reviewed
# MAGIC =====================================================================================================================================================
# MAGIC Kishore goud	2019-09-18	MVP -141541			Original Devlopment			IntegrateDev2	Kalyan Neelam             2019-09-20


# MAGIC """
# COMMAND ----------
# MAGIC %run ../../../../../Routine_Functions
# COMMAND ----------
# Using the below functions as UDF(inherited from Routine_Functions notebook) instead of pyspark function
# 1) current_timestamp, current_date - To convert to CST timezone.
# 2) trim - To mimic Datastage behavior in trimming spaces within the string (Not leading or trailing spaces)
# COMMAND ----------
from pyspark.sql.types import StructType, StructField, StringType, DecimalType, LongType, IntegerType
from pyspark.sql.functions import col, lit, when
# COMMAND ----------
# MAGIC %run ../../../../../Utility_Integrate
# COMMAND ----------


IDSOwner = get_widget_value('IDSOwner','')
ids_secret_name = get_widget_value('ids_secret_name','')
PrcsYrMo = get_widget_value('PrcsYrMo','')
PrcsYrMoDt = get_widget_value('PrcsYrMoDt','')

jdbc_url, jdbc_props = get_db_config(ids_secret_name)

extract_query_Db2_InterPlanBill_dtl = f"""
SELECT DISTINCT
INTER_PLN_BILL_DTL.INTER_PLN_BILL_DTL_SK,
INTER_PLN_BILL_DTL.INTER_PLN_BILL_DTL_ID,
INTER_PLN_BILL_DTL.BUS_OWNER_ID,
INTER_PLN_BILL_DTL.SRC_SYS_CD_SK,
INTER_PLN_BILL_DTL.CRT_RUN_CYC_EXCTN_SK,
INTER_PLN_BILL_DTL.LAST_UPDT_RUN_CYC_EXCTN_SK,
INTER_PLN_BILL_DTL.MBR_SK,
INTER_PLN_BILL_DTL.ATTRBTN_PGM_CD_SK,
INTER_PLN_BILL_DTL.CFA_RMBRMT_TYP_CD_SK,
INTER_PLN_BILL_DTL.CFA_TRANS_TYP_CD_SK,
INTER_PLN_BILL_DTL.CTL_PLN_CD_SK,
INTER_PLN_BILL_DTL.EPSD_TYP_CD_SK,
INTER_PLN_BILL_DTL.HOME_CORP_PLN_CD_SK,
INTER_PLN_BILL_DTL.HOME_PLN_CD_SK,
INTER_PLN_BILL_DTL.HOST_CORP_PLN_CD_SK,
INTER_PLN_BILL_DTL.HOST_PLN_CD_SK,
INTER_PLN_BILL_DTL.LOCAL_PLN_CD_SK,
INTER_PLN_BILL_DTL.VAL_BASED_PGM_CD_SK,
INTER_PLN_BILL_DTL.VAL_BASED_PGM_PAYMT_TYP_CD_SK,
INTER_PLN_BILL_DTL.BTCH_CRT_DT_SK,
INTER_PLN_BILL_DTL.CBF_SETL_STRT_DT_SK,
INTER_PLN_BILL_DTL.CBF_SETL_BILL_END_DT_SK,
INTER_PLN_BILL_DTL.CFA_DISP_DT_SK,
INTER_PLN_BILL_DTL.CFA_PRCS_DT_SK,
INTER_PLN_BILL_DTL.HOME_AUTH_DENIAL_DT_SK,
INTER_PLN_BILL_DTL.INCUR_PERD_STRT_DT_SK,
INTER_PLN_BILL_DTL.INCUR_PERD_END_DT_SK,
INTER_PLN_BILL_DTL.MSRMNT_PERD_STRT_DT_SK,
INTER_PLN_BILL_DTL.MSRMNT_PERD_END_DT_SK,
INTER_PLN_BILL_DTL.MBR_ELIG_STRT_DT_SK,
INTER_PLN_BILL_DTL.MBR_ELIG_END_DT_SK,
INTER_PLN_BILL_DTL.PRCS_CYC_YR_MO_SK,
INTER_PLN_BILL_DTL.SETL_DT_SK,
INTER_PLN_BILL_DTL.ACES_FEE_ADJ_AMT,
INTER_PLN_BILL_DTL.CBF_SETL_RATE_AMT,
INTER_PLN_BILL_DTL.MBR_LVL_CHRG_AMT,
INTER_PLN_BILL_DTL.ATRBD_PROV_ID,
INTER_PLN_BILL_DTL.ATRBD_PROV_NTNL_PROV_ID,
INTER_PLN_BILL_DTL.ATTRBTN_PROV_PGM_NM,
INTER_PLN_BILL_DTL.BCBSA_MMI_ID,
INTER_PLN_BILL_DTL.CONSIS_MBR_ID,
INTER_PLN_BILL_DTL.CBF_SCCF_NO,
INTER_PLN_BILL_DTL.GRP_ID,
INTER_PLN_BILL_DTL.HOME_PLN_MBR_ID,
INTER_PLN_BILL_DTL.ITS_SUB_ID,
INTER_PLN_BILL_DTL.ORIG_INTER_PLN_BILL_DTL_SRL_NO,
INTER_PLN_BILL_DTL.ORIG_ITS_CLM_SCCF_NO,
INTER_PLN_BILL_DTL.PROV_GRP_NM,
INTER_PLN_BILL_DTL.VRNC_ACCT_ID,
INTER_PLN_BILL_DTL.BTCH_STTUS_CD_TX,
INTER_PLN_BILL_DTL.STTUS_CD_TX,
INTER_PLN_BILL_DTL.ERR_CD_TX,
INTER_PLN_BILL_DTL.POST_AS_EXP_IN,
INTER_PLN_BILL_DTL.PRCS_CYC_DT_SK,
INTER_PLN_BILL_DTL.VAL_BASED_PGM_ID,
INTER_PLN_BILL_DTL.DSPTD_RCRD_CD,
INTER_PLN_BILL_DTL.HOME_PLN_DSPT_ACTN_CD,
INTER_PLN_BILL_DTL.CMNT_TX,
INTER_PLN_BILL_DTL.HOST_PLN_DSPT_ACTN_CD,
INTER_PLN_BILL_DTL.LOCAL_PLN_CTL_NO,
INTER_PLN_BILL_DTL.PRCS_SITE_CTL_NO,
INTER_PLN_BILL_DTL.BILL_DTL_FMT_RCRD_TYP_CD,
ROW_NUMBER() OVER (PARTITION BY CONSIS_MBR_ID, INCUR_PERD_STRT_DT_SK, VAL_BASED_PGM_PAYMT_TYP_CD_SK ORDER BY CONSIS_MBR_ID, INCUR_PERD_STRT_DT_SK, VAL_BASED_PGM_PAYMT_TYP_CD_SK asc) AS ROWNUM
FROM
{IDSOwner}.INTER_PLN_BILL_DTL INTER_PLN_BILL_DTL
WHERE
INTER_PLN_BILL_DTL.PRCS_CYC_YR_MO_SK='{PrcsYrMo}'
"""

df_Db2_InterPlanBill_dtl = (
    spark.read.format("jdbc")
    .option("url", jdbc_url)
    .options(**jdbc_props)
    .option("query", extract_query_Db2_InterPlanBill_dtl)
    .load()
)

df_Trans_dup_DSLink6 = (
    df_Db2_InterPlanBill_dtl.filter(col("ROWNUM") == 1)
    .select(
        col("VAL_BASED_PGM_PAYMT_TYP_CD_SK").alias("VAL_BASED_PGM_PAYMT_TYP_CD_SK"),
        col("INCUR_PERD_STRT_DT_SK").alias("INCUR_PERD_STRT_DT_SK"),
        col("CONSIS_MBR_ID").alias("CONSIS_MBR_ID"),
        col("INTER_PLN_BILL_DTL_SK").alias("INTER_PLN_BILL_DTL_SK"),
        col("INTER_PLN_BILL_DTL_ID").alias("INTER_PLN_BILL_DTL_ID"),
        col("BUS_OWNER_ID").alias("BUS_OWNER_ID"),
        col("SRC_SYS_CD_SK").alias("SRC_SYS_CD_SK"),
        col("CRT_RUN_CYC_EXCTN_SK").alias("CRT_RUN_CYC_EXCTN_SK"),
        col("LAST_UPDT_RUN_CYC_EXCTN_SK").alias("LAST_UPDT_RUN_CYC_EXCTN_SK"),
        col("MBR_SK").alias("MBR_SK"),
        col("ATTRBTN_PGM_CD_SK").alias("ATTRBTN_PGM_CD_SK"),
        col("CFA_RMBRMT_TYP_CD_SK").alias("CFA_RMBRMT_TYP_CD_SK"),
        col("CFA_TRANS_TYP_CD_SK").alias("CFA_TRANS_TYP_CD_SK"),
        col("CTL_PLN_CD_SK").alias("CTL_PLN_CD_SK"),
        col("EPSD_TYP_CD_SK").alias("EPSD_TYP_CD_SK"),
        col("HOME_CORP_PLN_CD_SK").alias("HOME_CORP_PLN_CD_SK"),
        col("HOME_PLN_CD_SK").alias("HOME_PLN_CD_SK"),
        col("HOST_CORP_PLN_CD_SK").alias("HOST_CORP_PLN_CD_SK"),
        col("HOST_PLN_CD_SK").alias("HOST_PLN_CD_SK"),
        col("LOCAL_PLN_CD_SK").alias("LOCAL_PLN_CD_SK"),
        col("VAL_BASED_PGM_CD_SK").alias("VAL_BASED_PGM_CD_SK"),
        col("BTCH_CRT_DT_SK").alias("BTCH_CRT_DT_SK"),
        col("CBF_SETL_STRT_DT_SK").alias("CBF_SETL_STRT_DT_SK"),
        col("CBF_SETL_BILL_END_DT_SK").alias("CBF_SETL_BILL_END_DT_SK"),
        col("CFA_DISP_DT_SK").alias("CFA_DISP_DT_SK"),
        col("CFA_PRCS_DT_SK").alias("CFA_PRCS_DT_SK"),
        col("HOME_AUTH_DENIAL_DT_SK").alias("HOME_AUTH_DENIAL_DT_SK"),
        col("INCUR_PERD_END_DT_SK").alias("INCUR_PERD_END_DT_SK"),
        col("MSRMNT_PERD_STRT_DT_SK").alias("MSRMNT_PERD_STRT_DT_SK"),
        col("MSRMNT_PERD_END_DT_SK").alias("MSRMNT_PERD_END_DT_SK"),
        col("MBR_ELIG_STRT_DT_SK").alias("MBR_ELIG_STRT_DT_SK"),
        col("MBR_ELIG_END_DT_SK").alias("MBR_ELIG_END_DT_SK"),
        col("PRCS_CYC_YR_MO_SK").alias("PRCS_CYC_YR_MO_SK"),
        col("SETL_DT_SK").alias("SETL_DT_SK"),
        col("ACES_FEE_ADJ_AMT").alias("ACES_FEE_ADJ_AMT"),
        col("CBF_SETL_RATE_AMT").alias("CBF_SETL_RATE_AMT"),
        col("MBR_LVL_CHRG_AMT").alias("MBR_LVL_CHRG_AMT"),
        col("ATRBD_PROV_ID").alias("ATRBD_PROV_ID"),
        col("ATRBD_PROV_NTNL_PROV_ID").alias("ATRBD_PROV_NTNL_PROV_ID"),
        col("ATTRBTN_PROV_PGM_NM").alias("ATTRBTN_PROV_PGM_NM"),
        col("BCBSA_MMI_ID").alias("BCBSA_MMI_ID"),
        col("CBF_SCCF_NO").alias("CBF_SCCF_NO"),
        col("GRP_ID").alias("GRP_ID"),
        col("HOME_PLN_MBR_ID").alias("HOME_PLN_MBR_ID"),
        col("ITS_SUB_ID").alias("ITS_SUB_ID"),
        col("ORIG_INTER_PLN_BILL_DTL_SRL_NO").alias("ORIG_INTER_PLN_BILL_DTL_SRL_NO"),
        col("ORIG_ITS_CLM_SCCF_NO").alias("ORIG_ITS_CLM_SCCF_NO"),
        col("PROV_GRP_NM").alias("PROV_GRP_NM"),
        col("VRNC_ACCT_ID").alias("VRNC_ACCT_ID"),
        col("BTCH_STTUS_CD_TX").alias("BTCH_STTUS_CD_TX"),
        col("STTUS_CD_TX").alias("STTUS_CD_TX"),
        col("ERR_CD_TX").alias("ERR_CD_TX"),
        col("POST_AS_EXP_IN").alias("POST_AS_EXP_IN"),
        col("PRCS_CYC_DT_SK").alias("PRCS_CYC_DT_SK"),
        col("VAL_BASED_PGM_ID").alias("VAL_BASED_PGM_ID"),
        col("DSPTD_RCRD_CD").alias("DSPTD_RCRD_CD"),
        col("HOME_PLN_DSPT_ACTN_CD").alias("HOME_PLN_DSPT_ACTN_CD"),
        col("CMNT_TX").alias("CMNT_TX"),
        col("HOST_PLN_DSPT_ACTN_CD").alias("HOST_PLN_DSPT_ACTN_CD"),
        col("LOCAL_PLN_CTL_NO").alias("LOCAL_PLN_CTL_NO"),
        col("PRCS_SITE_CTL_NO").alias("PRCS_SITE_CTL_NO"),
        col("BILL_DTL_FMT_RCRD_TYP_CD").alias("BILL_DTL_FMT_RCRD_TYP_CD"),
        col("ROWNUM").alias("ROWNUM")
    )
)

df_Trans_dup_DSLink9 = (
    df_Db2_InterPlanBill_dtl.filter(col("ROWNUM") == 2)
    .select(
        col("INTER_PLN_BILL_DTL_SK").alias("INTER_PLN_BILL_DTL_SK"),
        col("INTER_PLN_BILL_DTL_ID").alias("INTER_PLN_BILL_DTL_ID"),
        col("BUS_OWNER_ID").alias("BUS_OWNER_ID"),
        col("SRC_SYS_CD_SK").alias("SRC_SYS_CD_SK"),
        col("CRT_RUN_CYC_EXCTN_SK").alias("CRT_RUN_CYC_EXCTN_SK"),
        col("LAST_UPDT_RUN_CYC_EXCTN_SK").alias("LAST_UPDT_RUN_CYC_EXCTN_SK"),
        col("MBR_SK").alias("MBR_SK"),
        col("ATTRBTN_PGM_CD_SK").alias("ATTRBTN_PGM_CD_SK"),
        col("CFA_RMBRMT_TYP_CD_SK").alias("CFA_RMBRMT_TYP_CD_SK"),
        col("CFA_TRANS_TYP_CD_SK").alias("CFA_TRANS_TYP_CD_SK"),
        col("CTL_PLN_CD_SK").alias("CTL_PLN_CD_SK"),
        col("EPSD_TYP_CD_SK").alias("EPSD_TYP_CD_SK"),
        col("HOME_CORP_PLN_CD_SK").alias("HOME_CORP_PLN_CD_SK"),
        col("HOME_PLN_CD_SK").alias("HOME_PLN_CD_SK"),
        col("HOST_CORP_PLN_CD_SK").alias("HOST_CORP_PLN_CD_SK"),
        col("HOST_PLN_CD_SK").alias("HOST_PLN_CD_SK"),
        col("LOCAL_PLN_CD_SK").alias("LOCAL_PLN_CD_SK"),
        col("VAL_BASED_PGM_CD_SK").alias("VAL_BASED_PGM_CD_SK"),
        col("VAL_BASED_PGM_PAYMT_TYP_CD_SK").alias("VAL_BASED_PGM_PAYMT_TYP_CD_SK"),
        col("BTCH_CRT_DT_SK").alias("BTCH_CRT_DT_SK"),
        col("CBF_SETL_STRT_DT_SK").alias("CBF_SETL_STRT_DT_SK"),
        col("CBF_SETL_BILL_END_DT_SK").alias("CBF_SETL_BILL_END_DT_SK"),
        col("CFA_DISP_DT_SK").alias("CFA_DISP_DT_SK"),
        col("CFA_PRCS_DT_SK").alias("CFA_PRCS_DT_SK"),
        col("HOME_AUTH_DENIAL_DT_SK").alias("HOME_AUTH_DENIAL_DT_SK"),
        col("INCUR_PERD_STRT_DT_SK").alias("INCUR_PERD_STRT_DT_SK"),
        col("INCUR_PERD_END_DT_SK").alias("INCUR_PERD_END_DT_SK"),
        col("MSRMNT_PERD_STRT_DT_SK").alias("MSRMNT_PERD_STRT_DT_SK"),
        col("MSRMNT_PERD_END_DT_SK").alias("MSRMNT_PERD_END_DT_SK"),
        col("MBR_ELIG_STRT_DT_SK").alias("MBR_ELIG_STRT_DT_SK"),
        col("MBR_ELIG_END_DT_SK").alias("MBR_ELIG_END_DT_SK"),
        col("PRCS_CYC_YR_MO_SK").alias("PRCS_CYC_YR_MO_SK"),
        col("SETL_DT_SK").alias("SETL_DT_SK"),
        col("ACES_FEE_ADJ_AMT").alias("ACES_FEE_ADJ_AMT"),
        col("CBF_SETL_RATE_AMT").alias("CBF_SETL_RATE_AMT"),
        col("MBR_LVL_CHRG_AMT").alias("MBR_LVL_CHRG_AMT"),
        col("ATRBD_PROV_ID").alias("ATRBD_PROV_ID"),
        col("ATRBD_PROV_NTNL_PROV_ID").alias("ATRBD_PROV_NTNL_PROV_ID"),
        col("ATTRBTN_PROV_PGM_NM").alias("ATTRBTN_PROV_PGM_NM"),
        col("BCBSA_MMI_ID").alias("BCBSA_MMI_ID"),
        col("CONSIS_MBR_ID").alias("CONSIS_MBR_ID"),
        col("CBF_SCCF_NO").alias("CBF_SCCF_NO"),
        col("GRP_ID").alias("GRP_ID"),
        col("HOME_PLN_MBR_ID").alias("HOME_PLN_MBR_ID"),
        col("ITS_SUB_ID").alias("ITS_SUB_ID"),
        col("ORIG_INTER_PLN_BILL_DTL_SRL_NO").alias("ORIG_INTER_PLN_BILL_DTL_SRL_NO"),
        col("ORIG_ITS_CLM_SCCF_NO").alias("ORIG_ITS_CLM_SCCF_NO"),
        col("PROV_GRP_NM").alias("PROV_GRP_NM"),
        col("VRNC_ACCT_ID").alias("VRNC_ACCT_ID"),
        col("BTCH_STTUS_CD_TX").alias("BTCH_STTUS_CD_TX"),
        col("STTUS_CD_TX").alias("STTUS_CD_TX"),
        col("ERR_CD_TX").alias("ERR_CD_TX"),
        col("POST_AS_EXP_IN").alias("POST_AS_EXP_IN"),
        col("PRCS_CYC_DT_SK").alias("PRCS_CYC_DT_SK"),
        col("VAL_BASED_PGM_ID").alias("VAL_BASED_PGM_ID"),
        col("DSPTD_RCRD_CD").alias("DSPTD_RCRD_CD"),
        col("HOME_PLN_DSPT_ACTN_CD").alias("HOME_PLN_DSPT_ACTN_CD"),
        col("CMNT_TX").alias("CMNT_TX"),
        col("HOST_PLN_DSPT_ACTN_CD").alias("HOST_PLN_DSPT_ACTN_CD"),
        col("LOCAL_PLN_CTL_NO").alias("LOCAL_PLN_CTL_NO"),
        col("PRCS_SITE_CTL_NO").alias("PRCS_SITE_CTL_NO"),
        col("BILL_DTL_FMT_RCRD_TYP_CD").alias("BILL_DTL_FMT_RCRD_TYP_CD"),
        col("ROWNUM").alias("ROWNUM")
    )
)

df_copy_dup_DSLink14 = df_Trans_dup_DSLink9.select(
    col("INTER_PLN_BILL_DTL_SK").alias("INTER_PLN_BILL_DTL_SK"),
    col("INTER_PLN_BILL_DTL_ID").alias("INTER_PLN_BILL_DTL_ID"),
    col("BUS_OWNER_ID").alias("BUS_OWNER_ID"),
    col("SRC_SYS_CD_SK").alias("SRC_SYS_CD_SK"),
    col("CRT_RUN_CYC_EXCTN_SK").alias("CRT_RUN_CYC_EXCTN_SK"),
    col("LAST_UPDT_RUN_CYC_EXCTN_SK").alias("LAST_UPDT_RUN_CYC_EXCTN_SK"),
    col("MBR_SK").alias("MBR_SK"),
    col("ATTRBTN_PGM_CD_SK").alias("ATTRBTN_PGM_CD_SK"),
    col("CFA_RMBRMT_TYP_CD_SK").alias("CFA_RMBRMT_TYP_CD_SK"),
    col("CFA_TRANS_TYP_CD_SK").alias("CFA_TRANS_TYP_CD_SK"),
    col("CTL_PLN_CD_SK").alias("CTL_PLN_CD_SK"),
    col("EPSD_TYP_CD_SK").alias("EPSD_TYP_CD_SK"),
    col("HOME_CORP_PLN_CD_SK").alias("HOME_CORP_PLN_CD_SK"),
    col("HOME_PLN_CD_SK").alias("HOME_PLN_CD_SK"),
    col("HOST_CORP_PLN_CD_SK").alias("HOST_CORP_PLN_CD_SK"),
    col("HOST_PLN_CD_SK").alias("HOST_PLN_CD_SK"),
    col("LOCAL_PLN_CD_SK").alias("LOCAL_PLN_CD_SK"),
    col("VAL_BASED_PGM_CD_SK").alias("VAL_BASED_PGM_CD_SK"),
    col("VAL_BASED_PGM_PAYMT_TYP_CD_SK").alias("VAL_BASED_PGM_PAYMT_TYP_CD_SK"),
    col("BTCH_CRT_DT_SK").alias("BTCH_CRT_DT_SK"),
    col("CBF_SETL_STRT_DT_SK").alias("CBF_SETL_STRT_DT_SK"),
    col("CBF_SETL_BILL_END_DT_SK").alias("CBF_SETL_BILL_END_DT_SK"),
    col("CFA_DISP_DT_SK").alias("CFA_DISP_DT_SK"),
    col("CFA_PRCS_DT_SK").alias("CFA_PRCS_DT_SK"),
    col("HOME_AUTH_DENIAL_DT_SK").alias("HOME_AUTH_DENIAL_DT_SK"),
    col("INCUR_PERD_STRT_DT_SK").alias("INCUR_PERD_STRT_DT_SK"),
    col("INCUR_PERD_END_DT_SK").alias("INCUR_PERD_END_DT_SK"),
    col("MSRMNT_PERD_STRT_DT_SK").alias("MSRMNT_PERD_STRT_DT_SK"),
    col("MSRMNT_PERD_END_DT_SK").alias("MSRMNT_PERD_END_DT_SK"),
    col("MBR_ELIG_STRT_DT_SK").alias("MBR_ELIG_STRT_DT_SK"),
    col("MBR_ELIG_END_DT_SK").alias("MBR_ELIG_END_DT_SK"),
    col("PRCS_CYC_YR_MO_SK").alias("PRCS_CYC_YR_MO_SK"),
    col("SETL_DT_SK").alias("SETL_DT_SK"),
    col("ACES_FEE_ADJ_AMT").alias("ACES_FEE_ADJ_AMT"),
    col("CBF_SETL_RATE_AMT").alias("CBF_SETL_RATE_AMT"),
    col("MBR_LVL_CHRG_AMT").alias("MBR_LVL_CHRG_AMT"),
    col("ATRBD_PROV_ID").alias("ATRBD_PROV_ID"),
    col("ATRBD_PROV_NTNL_PROV_ID").alias("ATRBD_PROV_NTNL_PROV_ID"),
    col("ATTRBTN_PROV_PGM_NM").alias("ATTRBTN_PROV_PGM_NM"),
    col("BCBSA_MMI_ID").alias("BCBSA_MMI_ID"),
    col("CONSIS_MBR_ID").alias("CONSIS_MBR_ID"),
    col("CBF_SCCF_NO").alias("CBF_SCCF_NO"),
    col("GRP_ID").alias("GRP_ID"),
    col("HOME_PLN_MBR_ID").alias("HOME_PLN_MBR_ID"),
    col("ITS_SUB_ID").alias("ITS_SUB_ID"),
    col("ORIG_INTER_PLN_BILL_DTL_SRL_NO").alias("ORIG_INTER_PLN_BILL_DTL_SRL_NO"),
    col("ORIG_ITS_CLM_SCCF_NO").alias("ORIG_ITS_CLM_SCCF_NO"),
    col("PROV_GRP_NM").alias("PROV_GRP_NM"),
    col("VRNC_ACCT_ID").alias("VRNC_ACCT_ID"),
    col("BTCH_STTUS_CD_TX").alias("BTCH_STTUS_CD_TX"),
    col("STTUS_CD_TX").alias("STTUS_CD_TX"),
    col("ERR_CD_TX").alias("ERR_CD_TX"),
    col("POST_AS_EXP_IN").alias("POST_AS_EXP_IN"),
    col("PRCS_CYC_DT_SK").alias("PRCS_CYC_DT_SK"),
    col("VAL_BASED_PGM_ID").alias("VAL_BASED_PGM_ID"),
    col("DSPTD_RCRD_CD").alias("DSPTD_RCRD_CD"),
    col("HOME_PLN_DSPT_ACTN_CD").alias("HOME_PLN_DSPT_ACTN_CD"),
    col("CMNT_TX").alias("CMNT_TX"),
    col("HOST_PLN_DSPT_ACTN_CD").alias("HOST_PLN_DSPT_ACTN_CD"),
    col("LOCAL_PLN_CTL_NO").alias("LOCAL_PLN_CTL_NO"),
    col("PRCS_SITE_CTL_NO").alias("PRCS_SITE_CTL_NO"),
    col("BILL_DTL_FMT_RCRD_TYP_CD").alias("BILL_DTL_FMT_RCRD_TYP_CD"),
    col("ROWNUM").alias("ROWNUM")
)

df_copy_dup_lnk_dup_recds = df_Trans_dup_DSLink9.select(
    col("VAL_BASED_PGM_PAYMT_TYP_CD_SK").alias("VAL_BASED_PGM_PAYMT_TYP_CD_SK"),
    col("INCUR_PERD_STRT_DT_SK").alias("INCUR_PERD_STRT_DT_SK"),
    col("CONSIS_MBR_ID").alias("CONSIS_MBR_ID"),
    col("INTER_PLN_BILL_DTL_SK").alias("INTER_PLN_BILL_DTL_SK"),
    col("INTER_PLN_BILL_DTL_ID").alias("INTER_PLN_BILL_DTL_ID"),
    col("BUS_OWNER_ID").alias("BUS_OWNER_ID"),
    col("SRC_SYS_CD_SK").alias("SRC_SYS_CD_SK"),
    col("CRT_RUN_CYC_EXCTN_SK").alias("CRT_RUN_CYC_EXCTN_SK"),
    col("LAST_UPDT_RUN_CYC_EXCTN_SK").alias("LAST_UPDT_RUN_CYC_EXCTN_SK"),
    col("MBR_SK").alias("MBR_SK"),
    col("ATTRBTN_PGM_CD_SK").alias("ATTRBTN_PGM_CD_SK"),
    col("CFA_RMBRMT_TYP_CD_SK").alias("CFA_RMBRMT_TYP_CD_SK"),
    col("CFA_TRANS_TYP_CD_SK").alias("CFA_TRANS_TYP_CD_SK"),
    col("CTL_PLN_CD_SK").alias("CTL_PLN_CD_SK"),
    col("EPSD_TYP_CD_SK").alias("EPSD_TYP_CD_SK"),
    col("HOME_CORP_PLN_CD_SK").alias("HOME_CORP_PLN_CD_SK"),
    col("HOME_PLN_CD_SK").alias("HOME_PLN_CD_SK"),
    col("HOST_CORP_PLN_CD_SK").alias("HOST_CORP_PLN_CD_SK"),
    col("HOST_PLN_CD_SK").alias("HOST_PLN_CD_SK"),
    col("LOCAL_PLN_CD_SK").alias("LOCAL_PLN_CD_SK"),
    col("VAL_BASED_PGM_CD_SK").alias("VAL_BASED_PGM_CD_SK"),
    col("BTCH_CRT_DT_SK").alias("BTCH_CRT_DT_SK"),
    col("CBF_SETL_STRT_DT_SK").alias("CBF_SETL_STRT_DT_SK"),
    col("CBF_SETL_BILL_END_DT_SK").alias("CBF_SETL_BILL_END_DT_SK"),
    col("CFA_DISP_DT_SK").alias("CFA_DISP_DT_SK"),
    col("CFA_PRCS_DT_SK").alias("CFA_PRCS_DT_SK"),
    col("HOME_AUTH_DENIAL_DT_SK").alias("HOME_AUTH_DENIAL_DT_SK"),
    col("INCUR_PERD_END_DT_SK").alias("INCUR_PERD_END_DT_SK"),
    col("MSRMNT_PERD_STRT_DT_SK").alias("MSRMNT_PERD_STRT_DT_SK"),
    col("MSRMNT_PERD_END_DT_SK").alias("MSRMNT_PERD_END_DT_SK"),
    col("MBR_ELIG_STRT_DT_SK").alias("MBR_ELIG_STRT_DT_SK"),
    col("MBR_ELIG_END_DT_SK").alias("MBR_ELIG_END_DT_SK"),
    col("PRCS_CYC_YR_MO_SK").alias("PRCS_CYC_YR_MO_SK"),
    col("SETL_DT_SK").alias("SETL_DT_SK"),
    col("ACES_FEE_ADJ_AMT").alias("ACES_FEE_ADJ_AMT"),
    col("CBF_SETL_RATE_AMT").alias("CBF_SETL_RATE_AMT"),
    col("MBR_LVL_CHRG_AMT").alias("MBR_LVL_CHRG_AMT"),
    col("ATRBD_PROV_ID").alias("ATRBD_PROV_ID"),
    col("ATRBD_PROV_NTNL_PROV_ID").alias("ATRBD_PROV_NTNL_PROV_ID"),
    col("ATTRBTN_PROV_PGM_NM").alias("ATTRBTN_PROV_PGM_NM"),
    col("BCBSA_MMI_ID").alias("BCBSA_MMI_ID"),
    col("CBF_SCCF_NO").alias("CBF_SCCF_NO"),
    col("GRP_ID").alias("GRP_ID"),
    col("HOME_PLN_MBR_ID").alias("HOME_PLN_MBR_ID"),
    col("ITS_SUB_ID").alias("ITS_SUB_ID"),
    col("ORIG_INTER_PLN_BILL_DTL_SRL_NO").alias("ORIG_INTER_PLN_BILL_DTL_SRL_NO"),
    col("ORIG_ITS_CLM_SCCF_NO").alias("ORIG_ITS_CLM_SCCF_NO"),
    col("PROV_GRP_NM").alias("PROV_GRP_NM"),
    col("VRNC_ACCT_ID").alias("VRNC_ACCT_ID"),
    col("BTCH_STTUS_CD_TX").alias("BTCH_STTUS_CD_TX"),
    col("STTUS_CD_TX").alias("STTUS_CD_TX"),
    col("ERR_CD_TX").alias("ERR_CD_TX"),
    col("POST_AS_EXP_IN").alias("POST_AS_EXP_IN"),
    col("PRCS_CYC_DT_SK").alias("PRCS_CYC_DT_SK"),
    col("VAL_BASED_PGM_ID").alias("VAL_BASED_PGM_ID"),
    col("DSPTD_RCRD_CD").alias("DSPTD_RCRD_CD"),
    col("HOME_PLN_DSPT_ACTN_CD").alias("HOME_PLN_DSPT_ACTN_CD"),
    col("CMNT_TX").alias("CMNT_TX"),
    col("HOST_PLN_DSPT_ACTN_CD").alias("HOST_PLN_DSPT_ACTN_CD"),
    col("LOCAL_PLN_CTL_NO").alias("LOCAL_PLN_CTL_NO"),
    col("PRCS_SITE_CTL_NO").alias("PRCS_SITE_CTL_NO"),
    col("ROWNUM").alias("ROWNUM")
)

df_Transformer_15_DSLink17 = df_copy_dup_DSLink14.select(
    col("INTER_PLN_BILL_DTL_SK").alias("INTER_PLN_BILL_DTL_SK"),
    col("INTER_PLN_BILL_DTL_ID").alias("INTER_PLN_BILL_DTL_ID"),
    col("BUS_OWNER_ID").alias("BUS_OWNER_ID"),
    col("SRC_SYS_CD_SK").alias("SRC_SYS_CD_SK"),
    col("CRT_RUN_CYC_EXCTN_SK").alias("CRT_RUN_CYC_EXCTN_SK"),
    col("LAST_UPDT_RUN_CYC_EXCTN_SK").alias("LAST_UPDT_RUN_CYC_EXCTN_SK"),
    col("MBR_SK").alias("MBR_SK"),
    col("ATTRBTN_PGM_CD_SK").alias("ATTRBTN_PGM_CD_SK"),
    col("CFA_RMBRMT_TYP_CD_SK").alias("CFA_RMBRMT_TYP_CD_SK"),
    col("CFA_TRANS_TYP_CD_SK").alias("CFA_TRANS_TYP_CD_SK"),
    col("CTL_PLN_CD_SK").alias("CTL_PLN_CD_SK"),
    col("EPSD_TYP_CD_SK").alias("EPSD_TYP_CD_SK"),
    col("HOME_CORP_PLN_CD_SK").alias("HOME_CORP_PLN_CD_SK"),
    col("HOME_PLN_CD_SK").alias("HOME_PLN_CD_SK"),
    col("HOST_CORP_PLN_CD_SK").alias("HOST_CORP_PLN_CD_SK"),
    col("HOST_PLN_CD_SK").alias("HOST_PLN_CD_SK"),
    col("LOCAL_PLN_CD_SK").alias("LOCAL_PLN_CD_SK"),
    col("VAL_BASED_PGM_CD_SK").alias("VAL_BASED_PGM_CD_SK"),
    col("VAL_BASED_PGM_PAYMT_TYP_CD_SK").alias("VAL_BASED_PGM_PAYMT_TYP_CD_SK"),
    col("BTCH_CRT_DT_SK").alias("BTCH_CRT_DT_SK"),
    col("CBF_SETL_STRT_DT_SK").alias("CBF_SETL_STRT_DT_SK"),
    col("CBF_SETL_BILL_END_DT_SK").alias("CBF_SETL_BILL_END_DT_SK"),
    col("CFA_DISP_DT_SK").alias("CFA_DISP_DT_SK"),
    col("CFA_PRCS_DT_SK").alias("CFA_PRCS_DT_SK"),
    col("HOME_AUTH_DENIAL_DT_SK").alias("HOME_AUTH_DENIAL_DT_SK"),
    col("INCUR_PERD_STRT_DT_SK").alias("INCUR_PERD_STRT_DT_SK"),
    col("INCUR_PERD_END_DT_SK").alias("INCUR_PERD_END_DT_SK"),
    col("MSRMNT_PERD_STRT_DT_SK").alias("MSRMNT_PERD_STRT_DT_SK"),
    col("MSRMNT_PERD_END_DT_SK").alias("MSRMNT_PERD_END_DT_SK"),
    col("MBR_ELIG_STRT_DT_SK").alias("MBR_ELIG_STRT_DT_SK"),
    col("MBR_ELIG_END_DT_SK").alias("MBR_ELIG_END_DT_SK"),
    lit('175301').alias("PRCS_CYC_YR_MO_SK"),
    col("SETL_DT_SK").alias("SETL_DT_SK"),
    col("ACES_FEE_ADJ_AMT").alias("ACES_FEE_ADJ_AMT"),
    col("CBF_SETL_RATE_AMT").alias("CBF_SETL_RATE_AMT"),
    col("MBR_LVL_CHRG_AMT").alias("MBR_LVL_CHRG_AMT"),
    col("ATRBD_PROV_ID").alias("ATRBD_PROV_ID"),
    col("ATRBD_PROV_NTNL_PROV_ID").alias("ATRBD_PROV_NTNL_PROV_ID"),
    col("ATTRBTN_PROV_PGM_NM").alias("ATTRBTN_PROV_PGM_NM"),
    col("BCBSA_MMI_ID").alias("BCBSA_MMI_ID"),
    col("CONSIS_MBR_ID").alias("CONSIS_MBR_ID"),
    col("CBF_SCCF_NO").alias("CBF_SCCF_NO"),
    col("GRP_ID").alias("GRP_ID"),
    col("HOME_PLN_MBR_ID").alias("HOME_PLN_MBR_ID"),
    col("ITS_SUB_ID").alias("ITS_SUB_ID"),
    col("ORIG_INTER_PLN_BILL_DTL_SRL_NO").alias("ORIG_INTER_PLN_BILL_DTL_SRL_NO"),
    col("ORIG_ITS_CLM_SCCF_NO").alias("ORIG_ITS_CLM_SCCF_NO"),
    col("PROV_GRP_NM").alias("PROV_GRP_NM"),
    col("VRNC_ACCT_ID").alias("VRNC_ACCT_ID"),
    col("BTCH_STTUS_CD_TX").alias("BTCH_STTUS_CD_TX"),
    col("STTUS_CD_TX").alias("STTUS_CD_TX"),
    col("ERR_CD_TX").alias("ERR_CD_TX"),
    col("POST_AS_EXP_IN").alias("POST_AS_EXP_IN"),
    lit('1753-01-01').alias("PRCS_CYC_DT_SK"),
    col("VAL_BASED_PGM_ID").alias("VAL_BASED_PGM_ID"),
    col("DSPTD_RCRD_CD").alias("DSPTD_RCRD_CD"),
    col("HOME_PLN_DSPT_ACTN_CD").alias("HOME_PLN_DSPT_ACTN_CD"),
    col("CMNT_TX").alias("CMNT_TX"),
    col("HOST_PLN_DSPT_ACTN_CD").alias("HOST_PLN_DSPT_ACTN_CD"),
    col("LOCAL_PLN_CTL_NO").alias("LOCAL_PLN_CTL_NO"),
    col("PRCS_SITE_CTL_NO").alias("PRCS_SITE_CTL_NO"),
    col("BILL_DTL_FMT_RCRD_TYP_CD").alias("BILL_DTL_FMT_RCRD_TYP_CD")
)

df_Transformer_15_DSLink17_final = df_Transformer_15_DSLink17.select(
    col("INTER_PLN_BILL_DTL_SK"),
    col("INTER_PLN_BILL_DTL_ID"),
    col("BUS_OWNER_ID"),
    col("SRC_SYS_CD_SK"),
    col("CRT_RUN_CYC_EXCTN_SK"),
    col("LAST_UPDT_RUN_CYC_EXCTN_SK"),
    col("MBR_SK"),
    col("ATTRBTN_PGM_CD_SK"),
    col("CFA_RMBRMT_TYP_CD_SK"),
    col("CFA_TRANS_TYP_CD_SK"),
    col("CTL_PLN_CD_SK"),
    col("EPSD_TYP_CD_SK"),
    col("HOME_CORP_PLN_CD_SK"),
    col("HOME_PLN_CD_SK"),
    col("HOST_CORP_PLN_CD_SK"),
    col("HOST_PLN_CD_SK"),
    col("LOCAL_PLN_CD_SK"),
    col("VAL_BASED_PGM_CD_SK"),
    col("VAL_BASED_PGM_PAYMT_TYP_CD_SK"),
    col("BTCH_CRT_DT_SK"),
    col("CBF_SETL_STRT_DT_SK"),
    col("CBF_SETL_BILL_END_DT_SK"),
    col("CFA_DISP_DT_SK"),
    col("CFA_PRCS_DT_SK"),
    col("HOME_AUTH_DENIAL_DT_SK"),
    col("INCUR_PERD_STRT_DT_SK"),
    col("INCUR_PERD_END_DT_SK"),
    col("MSRMNT_PERD_STRT_DT_SK"),
    col("MSRMNT_PERD_END_DT_SK"),
    col("MBR_ELIG_STRT_DT_SK"),
    col("MBR_ELIG_END_DT_SK"),
    col("PRCS_CYC_YR_MO_SK"),
    col("SETL_DT_SK"),
    col("ACES_FEE_ADJ_AMT"),
    col("CBF_SETL_RATE_AMT"),
    col("MBR_LVL_CHRG_AMT"),
    col("ATRBD_PROV_ID"),
    col("ATRBD_PROV_NTNL_PROV_ID"),
    col("ATTRBTN_PROV_PGM_NM"),
    col("BCBSA_MMI_ID"),
    col("CONSIS_MBR_ID"),
    col("CBF_SCCF_NO"),
    col("GRP_ID"),
    col("HOME_PLN_MBR_ID"),
    col("ITS_SUB_ID"),
    col("ORIG_INTER_PLN_BILL_DTL_SRL_NO"),
    col("ORIG_ITS_CLM_SCCF_NO"),
    col("PROV_GRP_NM"),
    col("VRNC_ACCT_ID"),
    col("BTCH_STTUS_CD_TX"),
    col("STTUS_CD_TX"),
    col("ERR_CD_TX"),
    col("POST_AS_EXP_IN"),
    col("PRCS_CYC_DT_SK"),
    col("VAL_BASED_PGM_ID"),
    col("DSPTD_RCRD_CD"),
    col("HOME_PLN_DSPT_ACTN_CD"),
    col("CMNT_TX"),
    col("HOST_PLN_DSPT_ACTN_CD"),
    col("LOCAL_PLN_CTL_NO"),
    col("PRCS_SITE_CTL_NO"),
    col("BILL_DTL_FMT_RCRD_TYP_CD")
)

df_seq_dups_load_write = df_Transformer_15_DSLink17_final
char_cols_dups = {
    "BTCH_CRT_DT_SK":10,"CBF_SETL_STRT_DT_SK":10,"CBF_SETL_BILL_END_DT_SK":10,"CFA_DISP_DT_SK":10,"CFA_PRCS_DT_SK":10,
    "HOME_AUTH_DENIAL_DT_SK":10,"INCUR_PERD_STRT_DT_SK":10,"INCUR_PERD_END_DT_SK":10,"MSRMNT_PERD_STRT_DT_SK":10,
    "MSRMNT_PERD_END_DT_SK":10,"MBR_ELIG_STRT_DT_SK":10,"MBR_ELIG_END_DT_SK":10,"PRCS_CYC_YR_MO_SK":6,"SETL_DT_SK":10,
    "POST_AS_EXP_IN":1,"PRCS_CYC_DT_SK":10
}
df_seq_dups_load_rpad = df_seq_dups_load_write
for c, length in char_cols_dups.items():
    df_seq_dups_load_rpad = df_seq_dups_load_rpad.withColumn(c, rpad(col(c), length, " "))

write_files(
    df_seq_dups_load_rpad,
    f"{adls_path_publish}/external/INTER_PLN_BILL_DTL_dup.dat",
    delimiter=",",
    mode="overwrite",
    is_pqruet=False,
    header=False,
    quote="|",
    nullValue=None
)

df_Lkp_unique = (
    df_Trans_dup_DSLink6.alias("DSLink6")
    .join(
        df_copy_dup_lnk_dup_recds.alias("lnk_dup_recds"),
        [
            col("DSLink6.VAL_BASED_PGM_PAYMT_TYP_CD_SK") == col("lnk_dup_recds.VAL_BASED_PGM_PAYMT_TYP_CD_SK"),
            col("DSLink6.INCUR_PERD_STRT_DT_SK") == col("lnk_dup_recds.INCUR_PERD_STRT_DT_SK"),
            col("DSLink6.CONSIS_MBR_ID") == col("lnk_dup_recds.CONSIS_MBR_ID")
        ],
        "left"
    )
    .select(
        col("DSLink6.INTER_PLN_BILL_DTL_SK").alias("INTER_PLN_BILL_DTL_SK"),
        col("DSLink6.INTER_PLN_BILL_DTL_ID").alias("INTER_PLN_BILL_DTL_ID"),
        col("DSLink6.BUS_OWNER_ID").alias("BUS_OWNER_ID"),
        col("DSLink6.SRC_SYS_CD_SK").alias("SRC_SYS_CD_SK"),
        col("DSLink6.CRT_RUN_CYC_EXCTN_SK").alias("CRT_RUN_CYC_EXCTN_SK"),
        col("DSLink6.LAST_UPDT_RUN_CYC_EXCTN_SK").alias("LAST_UPDT_RUN_CYC_EXCTN_SK"),
        col("DSLink6.MBR_SK").alias("MBR_SK"),
        col("DSLink6.ATTRBTN_PGM_CD_SK").alias("ATTRBTN_PGM_CD_SK"),
        col("DSLink6.CFA_RMBRMT_TYP_CD_SK").alias("CFA_RMBRMT_TYP_CD_SK"),
        col("DSLink6.CFA_TRANS_TYP_CD_SK").alias("CFA_TRANS_TYP_CD_SK"),
        col("DSLink6.CTL_PLN_CD_SK").alias("CTL_PLN_CD_SK"),
        col("DSLink6.EPSD_TYP_CD_SK").alias("EPSD_TYP_CD_SK"),
        col("DSLink6.HOME_CORP_PLN_CD_SK").alias("HOME_CORP_PLN_CD_SK"),
        col("DSLink6.HOME_PLN_CD_SK").alias("HOME_PLN_CD_SK"),
        col("DSLink6.HOST_CORP_PLN_CD_SK").alias("HOST_CORP_PLN_CD_SK"),
        col("DSLink6.HOST_PLN_CD_SK").alias("HOST_PLN_CD_SK"),
        col("DSLink6.LOCAL_PLN_CD_SK").alias("LOCAL_PLN_CD_SK"),
        col("DSLink6.VAL_BASED_PGM_CD_SK").alias("VAL_BASED_PGM_CD_SK"),
        col("DSLink6.VAL_BASED_PGM_PAYMT_TYP_CD_SK").alias("VAL_BASED_PGM_PAYMT_TYP_CD_SK"),
        col("DSLink6.BTCH_CRT_DT_SK").alias("BTCH_CRT_DT_SK"),
        col("DSLink6.CBF_SETL_STRT_DT_SK").alias("CBF_SETL_STRT_DT_SK"),
        col("DSLink6.CBF_SETL_BILL_END_DT_SK").alias("CBF_SETL_BILL_END_DT_SK"),
        col("DSLink6.CFA_DISP_DT_SK").alias("CFA_DISP_DT_SK"),
        col("DSLink6.CFA_PRCS_DT_SK").alias("CFA_PRCS_DT_SK"),
        col("DSLink6.HOME_AUTH_DENIAL_DT_SK").alias("HOME_AUTH_DENIAL_DT_SK"),
        col("DSLink6.INCUR_PERD_STRT_DT_SK").alias("INCUR_PERD_STRT_DT_SK"),
        col("DSLink6.INCUR_PERD_END_DT_SK").alias("INCUR_PERD_END_DT_SK"),
        col("DSLink6.MSRMNT_PERD_STRT_DT_SK").alias("MSRMNT_PERD_STRT_DT_SK"),
        col("DSLink6.MSRMNT_PERD_END_DT_SK").alias("MSRMNT_PERD_END_DT_SK"),
        col("DSLink6.MBR_ELIG_STRT_DT_SK").alias("MBR_ELIG_STRT_DT_SK"),
        col("DSLink6.MBR_ELIG_END_DT_SK").alias("MBR_ELIG_END_DT_SK"),
        col("DSLink6.PRCS_CYC_YR_MO_SK").alias("PRCS_CYC_YR_MO_SK"),
        col("DSLink6.SETL_DT_SK").alias("SETL_DT_SK"),
        col("DSLink6.ACES_FEE_ADJ_AMT").alias("ACES_FEE_ADJ_AMT"),
        col("DSLink6.CBF_SETL_RATE_AMT").alias("CBF_SETL_RATE_AMT"),
        col("DSLink6.MBR_LVL_CHRG_AMT").alias("MBR_LVL_CHRG_AMT"),
        col("DSLink6.ATRBD_PROV_ID").alias("ATRBD_PROV_ID"),
        col("DSLink6.ATRBD_PROV_NTNL_PROV_ID").alias("ATRBD_PROV_NTNL_PROV_ID"),
        col("DSLink6.ATTRBTN_PROV_PGM_NM").alias("ATTRBTN_PROV_PGM_NM"),
        col("DSLink6.BCBSA_MMI_ID").alias("BCBSA_MMI_ID"),
        col("DSLink6.CONSIS_MBR_ID").alias("CONSIS_MBR_ID"),
        col("DSLink6.CBF_SCCF_NO").alias("CBF_SCCF_NO"),
        col("DSLink6.GRP_ID").alias("GRP_ID"),
        col("DSLink6.HOME_PLN_MBR_ID").alias("HOME_PLN_MBR_ID"),
        col("DSLink6.ITS_SUB_ID").alias("ITS_SUB_ID"),
        col("DSLink6.ORIG_INTER_PLN_BILL_DTL_SRL_NO").alias("ORIG_INTER_PLN_BILL_DTL_SRL_NO"),
        col("DSLink6.ORIG_ITS_CLM_SCCF_NO").alias("ORIG_ITS_CLM_SCCF_NO"),
        col("DSLink6.PROV_GRP_NM").alias("PROV_GRP_NM"),
        col("DSLink6.VRNC_ACCT_ID").alias("VRNC_ACCT_ID"),
        col("DSLink6.BTCH_STTUS_CD_TX").alias("BTCH_STTUS_CD_TX"),
        col("DSLink6.STTUS_CD_TX").alias("STTUS_CD_TX"),
        col("DSLink6.ERR_CD_TX").alias("ERR_CD_TX"),
        col("DSLink6.POST_AS_EXP_IN").alias("POST_AS_EXP_IN"),
        col("DSLink6.PRCS_CYC_DT_SK").alias("PRCS_CYC_DT_SK"),
        col("DSLink6.VAL_BASED_PGM_ID").alias("VAL_BASED_PGM_ID"),
        col("DSLink6.DSPTD_RCRD_CD").alias("DSPTD_RCRD_CD"),
        col("DSLink6.HOME_PLN_DSPT_ACTN_CD").alias("HOME_PLN_DSPT_ACTN_CD"),
        col("DSLink6.CMNT_TX").alias("CMNT_TX"),
        col("DSLink6.HOST_PLN_DSPT_ACTN_CD").alias("HOST_PLN_DSPT_ACTN_CD"),
        col("DSLink6.LOCAL_PLN_CTL_NO").alias("LOCAL_PLN_CTL_NO"),
        col("DSLink6.PRCS_SITE_CTL_NO").alias("PRCS_SITE_CTL_NO"),
        col("DSLink6.BILL_DTL_FMT_RCRD_TYP_CD").alias("BILL_DTL_FMT_RCRD_TYP_CD"),
        col("DSLink6.ROWNUM").alias("ROWNUM"),
        col("lnk_dup_recds.INTER_PLN_BILL_DTL_SK").alias("Right_INTER_PLN_BILL_DTL_SK"),
        col("lnk_dup_recds.MBR_LVL_CHRG_AMT").alias("Right_MBR_LVL_CHRG_AMT")
    )
)

df_Trans_final_recds_Lnk_seq = (
    df_Lkp_unique
    .withColumn(
        "MBR_LVL_CHRG_AMT",
        when(
            col("Right_INTER_PLN_BILL_DTL_SK").isNull(),
            col("MBR_LVL_CHRG_AMT")
        ).otherwise(col("MBR_LVL_CHRG_AMT") + col("Right_MBR_LVL_CHRG_AMT"))
    )
    .withColumn("POST_AS_EXP_IN", trim(col("POST_AS_EXP_IN")))
    .withColumn("PRCS_CYC_YR_MO_SK", lit(PrcsYrMo))
    .withColumn("PRCS_CYC_DT_SK", lit(PrcsYrMoDt))
    .select(
        col("INTER_PLN_BILL_DTL_SK").alias("INTER_PLN_BILL_DTL_SK"),
        col("INTER_PLN_BILL_DTL_ID").alias("INTER_PLN_BILL_DTL_ID"),
        col("BUS_OWNER_ID").alias("BUS_OWNER_ID"),
        col("SRC_SYS_CD_SK").alias("SRC_SYS_CD_SK"),
        col("CRT_RUN_CYC_EXCTN_SK").alias("CRT_RUN_CYC_EXCTN_SK"),
        col("LAST_UPDT_RUN_CYC_EXCTN_SK").alias("LAST_UPDT_RUN_CYC_EXCTN_SK"),
        col("MBR_SK").alias("MBR_SK"),
        col("ATTRBTN_PGM_CD_SK").alias("ATTRBTN_PGM_CD_SK"),
        col("CFA_RMBRMT_TYP_CD_SK").alias("CFA_RMBRMT_TYP_CD_SK"),
        col("CFA_TRANS_TYP_CD_SK").alias("CFA_TRANS_TYP_CD_SK"),
        col("CTL_PLN_CD_SK").alias("CTL_PLN_CD_SK"),
        col("EPSD_TYP_CD_SK").alias("EPSD_TYP_CD_SK"),
        col("HOME_CORP_PLN_CD_SK").alias("HOME_CORP_PLN_CD_SK"),
        col("HOME_PLN_CD_SK").alias("HOME_PLN_CD_SK"),
        col("HOST_CORP_PLN_CD_SK").alias("HOST_CORP_PLN_CD_SK"),
        col("HOST_PLN_CD_SK").alias("HOST_PLN_CD_SK"),
        col("LOCAL_PLN_CD_SK").alias("LOCAL_PLN_CD_SK"),
        col("VAL_BASED_PGM_CD_SK").alias("VAL_BASED_PGM_CD_SK"),
        col("VAL_BASED_PGM_PAYMT_TYP_CD_SK").alias("VAL_BASED_PGM_PAYMT_TYP_CD_SK"),
        col("BTCH_CRT_DT_SK").alias("BTCH_CRT_DT_SK"),
        col("CBF_SETL_STRT_DT_SK").alias("CBF_SETL_STRT_DT_SK"),
        col("CBF_SETL_BILL_END_DT_SK").alias("CBF_SETL_BILL_END_DT_SK"),
        col("CFA_DISP_DT_SK").alias("CFA_DISP_DT_SK"),
        col("CFA_PRCS_DT_SK").alias("CFA_PRCS_DT_SK"),
        col("HOME_AUTH_DENIAL_DT_SK").alias("HOME_AUTH_DENIAL_DT_SK"),
        col("INCUR_PERD_STRT_DT_SK").alias("INCUR_PERD_STRT_DT_SK"),
        col("INCUR_PERD_END_DT_SK").alias("INCUR_PERD_END_DT_SK"),
        col("MSRMNT_PERD_STRT_DT_SK").alias("MSRMNT_PERD_STRT_DT_SK"),
        col("MSRMNT_PERD_END_DT_SK").alias("MSRMNT_PERD_END_DT_SK"),
        col("MBR_ELIG_STRT_DT_SK").alias("MBR_ELIG_STRT_DT_SK"),
        col("MBR_ELIG_END_DT_SK").alias("MBR_ELIG_END_DT_SK"),
        col("PRCS_CYC_YR_MO_SK").alias("PRCS_CYC_YR_MO_SK"),
        col("SETL_DT_SK").alias("SETL_DT_SK"),
        col("ACES_FEE_ADJ_AMT").alias("ACES_FEE_ADJ_AMT"),
        col("CBF_SETL_RATE_AMT").alias("CBF_SETL_RATE_AMT"),
        col("MBR_LVL_CHRG_AMT").alias("MBR_LVL_CHRG_AMT"),
        col("ATRBD_PROV_ID").alias("ATRBD_PROV_ID"),
        col("ATRBD_PROV_NTNL_PROV_ID").alias("ATRBD_PROV_NTNL_PROV_ID"),
        col("ATTRBTN_PROV_PGM_NM").alias("ATTRBTN_PROV_PGM_NM"),
        col("BCBSA_MMI_ID").alias("BCBSA_MMI_ID"),
        col("CONSIS_MBR_ID").alias("CONSIS_MBR_ID"),
        col("CBF_SCCF_NO").alias("CBF_SCCF_NO"),
        col("GRP_ID").alias("GRP_ID"),
        col("HOME_PLN_MBR_ID").alias("HOME_PLN_MBR_ID"),
        col("ITS_SUB_ID").alias("ITS_SUB_ID"),
        col("ORIG_INTER_PLN_BILL_DTL_SRL_NO").alias("ORIG_INTER_PLN_BILL_DTL_SRL_NO"),
        col("ORIG_ITS_CLM_SCCF_NO").alias("ORIG_ITS_CLM_SCCF_NO"),
        col("PROV_GRP_NM").alias("PROV_GRP_NM"),
        col("VRNC_ACCT_ID").alias("VRNC_ACCT_ID"),
        col("BTCH_STTUS_CD_TX").alias("BTCH_STTUS_CD_TX"),
        col("STTUS_CD_TX").alias("STTUS_CD_TX"),
        col("ERR_CD_TX").alias("ERR_CD_TX"),
        col("POST_AS_EXP_IN").alias("POST_AS_EXP_IN"),
        col("PRCS_CYC_DT_SK").alias("PRCS_CYC_DT_SK"),
        col("VAL_BASED_PGM_ID").alias("VAL_BASED_PGM_ID"),
        col("DSPTD_RCRD_CD").alias("DSPTD_RCRD_CD"),
        col("HOME_PLN_DSPT_ACTN_CD").alias("HOME_PLN_DSPT_ACTN_CD"),
        col("CMNT_TX").alias("CMNT_TX"),
        col("HOST_PLN_DSPT_ACTN_CD").alias("HOST_PLN_DSPT_ACTN_CD"),
        col("LOCAL_PLN_CTL_NO").alias("LOCAL_PLN_CTL_NO"),
        col("PRCS_SITE_CTL_NO").alias("PRCS_SITE_CTL_NO"),
        col("BILL_DTL_FMT_RCRD_TYP_CD").alias("BILL_DTL_FMT_RCRD_TYP_CD")
    )
)

df_Seq_unique_recds_write = df_Trans_final_recds_Lnk_seq
char_cols_unique = {
    "BTCH_CRT_DT_SK":10,"CBF_SETL_STRT_DT_SK":10,"CBF_SETL_BILL_END_DT_SK":10,"CFA_DISP_DT_SK":10,"CFA_PRCS_DT_SK":10,
    "HOME_AUTH_DENIAL_DT_SK":10,"INCUR_PERD_STRT_DT_SK":10,"INCUR_PERD_END_DT_SK":10,"MSRMNT_PERD_STRT_DT_SK":10,
    "MSRMNT_PERD_END_DT_SK":10,"MBR_ELIG_STRT_DT_SK":10,"MBR_ELIG_END_DT_SK":10,"PRCS_CYC_YR_MO_SK":6,"SETL_DT_SK":10,
    "POST_AS_EXP_IN":1,"PRCS_CYC_DT_SK":10,"VAL_BASED_PGM_ID":7
}
df_Seq_unique_recds_rpad = df_Seq_unique_recds_write
for c, length in char_cols_unique.items():
    df_Seq_unique_recds_rpad = df_Seq_unique_recds_rpad.withColumn(c, rpad(col(c), length, " "))

write_files(
    df_Seq_unique_recds_rpad,
    f"{adls_path_publish}/external/INTER_PLN_BILL_DTL_uniq.dat",
    delimiter=",",
    mode="overwrite",
    is_pqruet=False,
    header=False,
    quote="|",
    nullValue=None
)