# Databricks notebook source
# MAGIC %md
# MAGIC **Date:** 2025-08-24
# MAGIC """
# MAGIC COPYRIGHT 2009 - 2011 BLUE CROSS/BLUE SHIELD OF KANSAS CITY 
# MAGIC 
# MAGIC 
# MAGIC DESCRIPTION:  Load the unque and duplicates with updated cycle year month.
# MAGIC       
# MAGIC 
# MAGIC MODIFICATIONS:
# MAGIC Developer	Date		Project/Altiris #		Change Description				Development Project	Code Reviewer	Date Reviewed
# MAGIC =====================================================================================================================================================
# MAGIC kishore Goud	2019-09-18	141541			Original Devlopment				IntegrateDev2	Kalyan Neelam	2019-09-20


# MAGIC """
# COMMAND ----------
# MAGIC %run ../../../../../Routine_Functions
# COMMAND ----------
# Using the below functions as UDF(inherited from Routine_Functions notebook) instead of pyspark function
# 1) current_timestamp, current_date - To convert to CST timezone.
# 2) trim - To mimic Datastage behavior in trimming spaces within the string (Not leading or trailing spaces)
# COMMAND ----------
from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    StringType,
    DecimalType
)
from pyspark.sql import functions as F
# COMMAND ----------
# MAGIC %run ../../../../../Utility_Integrate
# COMMAND ----------


IDSOwner = get_widget_value('IDSOwner','')
ids_secret_name = get_widget_value('ids_secret_name','')

# Schema for seq_unique_recds (PxSequentialFile)
schema_seq_unique_recds = StructType([
    StructField("INTER_PLN_BILL_DTL_SK", IntegerType(), False),
    StructField("INTER_PLN_BILL_DTL_ID", StringType(), False),
    StructField("BUS_OWNER_ID", StringType(), False),
    StructField("SRC_SYS_CD_SK", IntegerType(), False),
    StructField("CRT_RUN_CYC_EXCTN_SK", IntegerType(), False),
    StructField("LAST_UPDT_RUN_CYC_EXCTN_SK", IntegerType(), False),
    StructField("MBR_SK", IntegerType(), False),
    StructField("ATTRBTN_PGM_CD_SK", IntegerType(), False),
    StructField("CFA_RMBRMT_TYP_CD_SK", IntegerType(), False),
    StructField("CFA_TRANS_TYP_CD_SK", IntegerType(), False),
    StructField("CTL_PLN_CD_SK", IntegerType(), False),
    StructField("EPSD_TYP_CD_SK", IntegerType(), False),
    StructField("HOME_CORP_PLN_CD_SK", IntegerType(), False),
    StructField("HOME_PLN_CD_SK", IntegerType(), False),
    StructField("HOST_CORP_PLN_CD_SK", IntegerType(), False),
    StructField("HOST_PLN_CD_SK", IntegerType(), False),
    StructField("LOCAL_PLN_CD_SK", IntegerType(), False),
    StructField("VAL_BASED_PGM_CD_SK", IntegerType(), False),
    StructField("VAL_BASED_PGM_PAYMT_TYP_CD_SK", IntegerType(), False),
    StructField("BTCH_CRT_DT_SK", StringType(), False),
    StructField("CBF_SETL_STRT_DT_SK", StringType(), False),
    StructField("CBF_SETL_BILL_END_DT_SK", StringType(), False),
    StructField("CFA_DISP_DT_SK", StringType(), False),
    StructField("CFA_PRCS_DT_SK", StringType(), False),
    StructField("HOME_AUTH_DENIAL_DT_SK", StringType(), False),
    StructField("INCUR_PERD_STRT_DT_SK", StringType(), False),
    StructField("INCUR_PERD_END_DT_SK", StringType(), False),
    StructField("MSRMNT_PERD_STRT_DT_SK", StringType(), False),
    StructField("MSRMNT_PERD_END_DT_SK", StringType(), False),
    StructField("MBR_ELIG_STRT_DT_SK", StringType(), False),
    StructField("MBR_ELIG_END_DT_SK", StringType(), False),
    StructField("PRCS_CYC_YR_MO_SK", StringType(), False),
    StructField("SETL_DT_SK", StringType(), False),
    StructField("ACES_FEE_ADJ_AMT", DecimalType(38,10), False),
    StructField("CBF_SETL_RATE_AMT", DecimalType(38,10), False),
    StructField("MBR_LVL_CHRG_AMT", DecimalType(38,10), False),
    StructField("ATRBD_PROV_ID", StringType(), False),
    StructField("ATRBD_PROV_NTNL_PROV_ID", StringType(), False),
    StructField("ATTRBTN_PROV_PGM_NM", StringType(), False),
    StructField("BCBSA_MMI_ID", StringType(), False),
    StructField("CONSIS_MBR_ID", StringType(), False),
    StructField("CBF_SCCF_NO", StringType(), False),
    StructField("GRP_ID", StringType(), False),
    StructField("HOME_PLN_MBR_ID", StringType(), False),
    StructField("ITS_SUB_ID", StringType(), False),
    StructField("ORIG_INTER_PLN_BILL_DTL_SRL_NO", StringType(), False),
    StructField("ORIG_ITS_CLM_SCCF_NO", StringType(), False),
    StructField("PROV_GRP_NM", StringType(), True),
    StructField("VRNC_ACCT_ID", StringType(), False),
    StructField("BTCH_STTUS_CD_TX", StringType(), False),
    StructField("STTUS_CD_TX", StringType(), False),
    StructField("ERR_CD_TX", StringType(), False),
    StructField("POST_AS_EXP_IN", StringType(), False),
    StructField("PRCS_CYC_DT_SK", StringType(), False),
    StructField("VAL_BASED_PGM_ID", StringType(), True),
    StructField("DSPTD_RCRD_CD", StringType(), True),
    StructField("HOME_PLN_DSPT_ACTN_CD", StringType(), True),
    StructField("CMNT_TX", StringType(), True),
    StructField("HOST_PLN_DSPT_ACTN_CD", StringType(), True),
    StructField("LOCAL_PLN_CTL_NO", StringType(), True),
    StructField("PRCS_SITE_CTL_NO", StringType(), True),
    StructField("BILL_DTL_FMT_RCRD_TYP_CD", StringType(), True)
])

df_seq_unique_recds = (
    spark.read.format("csv")
    .option("header", "false")
    .option("delimiter", ",")
    .option("quote", "|")
    .option("nullValue", None)
    .schema(schema_seq_unique_recds)
    .load(f"{adls_path_publish}/external/INTER_PLN_BILL_DTL_uniq.dat")
)

df_Cp_recds = df_seq_unique_recds.alias("DSLink9").select(
    F.col("DSLink9.INTER_PLN_BILL_DTL_SK").alias("INTER_PLN_BILL_DTL_SK"),
    F.col("DSLink9.INTER_PLN_BILL_DTL_ID").alias("INTER_PLN_BILL_DTL_ID"),
    F.col("DSLink9.BUS_OWNER_ID").alias("BUS_OWNER_ID"),
    F.col("DSLink9.SRC_SYS_CD_SK").alias("SRC_SYS_CD_SK"),
    F.col("DSLink9.CRT_RUN_CYC_EXCTN_SK").alias("CRT_RUN_CYC_EXCTN_SK"),
    F.col("DSLink9.LAST_UPDT_RUN_CYC_EXCTN_SK").alias("LAST_UPDT_RUN_CYC_EXCTN_SK"),
    F.col("DSLink9.MBR_SK").alias("MBR_SK"),
    F.col("DSLink9.ATTRBTN_PGM_CD_SK").alias("ATTRBTN_PGM_CD_SK"),
    F.col("DSLink9.CFA_RMBRMT_TYP_CD_SK").alias("CFA_RMBRMT_TYP_CD_SK"),
    F.col("DSLink9.CFA_TRANS_TYP_CD_SK").alias("CFA_TRANS_TYP_CD_SK"),
    F.col("DSLink9.CTL_PLN_CD_SK").alias("CTL_PLN_CD_SK"),
    F.col("DSLink9.EPSD_TYP_CD_SK").alias("EPSD_TYP_CD_SK"),
    F.col("DSLink9.HOME_CORP_PLN_CD_SK").alias("HOME_CORP_PLN_CD_SK"),
    F.col("DSLink9.HOME_PLN_CD_SK").alias("HOME_PLN_CD_SK"),
    F.col("DSLink9.HOST_CORP_PLN_CD_SK").alias("HOST_CORP_PLN_CD_SK"),
    F.col("DSLink9.HOST_PLN_CD_SK").alias("HOST_PLN_CD_SK"),
    F.col("DSLink9.LOCAL_PLN_CD_SK").alias("LOCAL_PLN_CD_SK"),
    F.col("DSLink9.VAL_BASED_PGM_CD_SK").alias("VAL_BASED_PGM_CD_SK"),
    F.col("DSLink9.VAL_BASED_PGM_PAYMT_TYP_CD_SK").alias("VAL_BASED_PGM_PAYMT_TYP_CD_SK"),
    F.col("DSLink9.BTCH_CRT_DT_SK").alias("BTCH_CRT_DT_SK"),
    F.col("DSLink9.CBF_SETL_STRT_DT_SK").alias("CBF_SETL_STRT_DT_SK"),
    F.col("DSLink9.CBF_SETL_BILL_END_DT_SK").alias("CBF_SETL_BILL_END_DT_SK"),
    F.col("DSLink9.CFA_DISP_DT_SK").alias("CFA_DISP_DT_SK"),
    F.col("DSLink9.CFA_PRCS_DT_SK").alias("CFA_PRCS_DT_SK"),
    F.col("DSLink9.HOME_AUTH_DENIAL_DT_SK").alias("HOME_AUTH_DENIAL_DT_SK"),
    F.col("DSLink9.INCUR_PERD_STRT_DT_SK").alias("INCUR_PERD_STRT_DT_SK"),
    F.col("DSLink9.INCUR_PERD_END_DT_SK").alias("INCUR_PERD_END_DT_SK"),
    F.col("DSLink9.MSRMNT_PERD_STRT_DT_SK").alias("MSRMNT_PERD_STRT_DT_SK"),
    F.col("DSLink9.MSRMNT_PERD_END_DT_SK").alias("MSRMNT_PERD_END_DT_SK"),
    F.col("DSLink9.MBR_ELIG_STRT_DT_SK").alias("MBR_ELIG_STRT_DT_SK"),
    F.col("DSLink9.MBR_ELIG_END_DT_SK").alias("MBR_ELIG_END_DT_SK"),
    F.col("DSLink9.PRCS_CYC_YR_MO_SK").alias("PRCS_CYC_YR_MO_SK"),
    F.col("DSLink9.SETL_DT_SK").alias("SETL_DT_SK"),
    F.col("DSLink9.ACES_FEE_ADJ_AMT").alias("ACES_FEE_ADJ_AMT"),
    F.col("DSLink9.CBF_SETL_RATE_AMT").alias("CBF_SETL_RATE_AMT"),
    F.col("DSLink9.MBR_LVL_CHRG_AMT").alias("MBR_LVL_CHRG_AMT"),
    F.col("DSLink9.ATRBD_PROV_ID").alias("ATRBD_PROV_ID"),
    F.col("DSLink9.ATRBD_PROV_NTNL_PROV_ID").alias("ATRBD_PROV_NTNL_PROV_ID"),
    F.col("DSLink9.ATTRBTN_PROV_PGM_NM").alias("ATTRBTN_PROV_PGM_NM"),
    F.col("DSLink9.BCBSA_MMI_ID").alias("BCBSA_MMI_ID"),
    F.col("DSLink9.CONSIS_MBR_ID").alias("CONSIS_MBR_ID"),
    F.col("DSLink9.CBF_SCCF_NO").alias("CBF_SCCF_NO"),
    F.col("DSLink9.GRP_ID").alias("GRP_ID"),
    F.col("DSLink9.HOME_PLN_MBR_ID").alias("HOME_PLN_MBR_ID"),
    F.col("DSLink9.ITS_SUB_ID").alias("ITS_SUB_ID"),
    F.col("DSLink9.ORIG_INTER_PLN_BILL_DTL_SRL_NO").alias("ORIG_INTER_PLN_BILL_DTL_SRL_NO"),
    F.col("DSLink9.ORIG_ITS_CLM_SCCF_NO").alias("ORIG_ITS_CLM_SCCF_NO"),
    F.col("DSLink9.PROV_GRP_NM").alias("PROV_GRP_NM"),
    F.col("DSLink9.VRNC_ACCT_ID").alias("VRNC_ACCT_ID"),
    F.col("DSLink9.BTCH_STTUS_CD_TX").alias("BTCH_STTUS_CD_TX"),
    F.col("DSLink9.STTUS_CD_TX").alias("STTUS_CD_TX"),
    F.col("DSLink9.ERR_CD_TX").alias("ERR_CD_TX"),
    F.col("DSLink9.POST_AS_EXP_IN").alias("POST_AS_EXP_IN"),
    F.col("DSLink9.PRCS_CYC_DT_SK").alias("PRCS_CYC_DT_SK"),
    F.col("DSLink9.VAL_BASED_PGM_ID").alias("VAL_BASED_PGM_ID"),
    F.col("DSLink9.DSPTD_RCRD_CD").alias("DSPTD_RCRD_CD"),
    F.col("DSLink9.HOME_PLN_DSPT_ACTN_CD").alias("HOME_PLN_DSPT_ACTN_CD"),
    F.col("DSLink9.CMNT_TX").alias("CMNT_TX"),
    F.col("DSLink9.HOST_PLN_DSPT_ACTN_CD").alias("HOST_PLN_DSPT_ACTN_CD"),
    F.col("DSLink9.LOCAL_PLN_CTL_NO").alias("LOCAL_PLN_CTL_NO"),
    F.col("DSLink9.PRCS_SITE_CTL_NO").alias("PRCS_SITE_CTL_NO"),
    F.col("DSLink9.BILL_DTL_FMT_RCRD_TYP_CD").alias("BILL_DTL_FMT_RCRD_TYP_CD")
)

df_inter_plan_load = df_Cp_recds.select(
    "INTER_PLN_BILL_DTL_SK",
    "INTER_PLN_BILL_DTL_ID",
    "BUS_OWNER_ID",
    "SRC_SYS_CD_SK",
    "CRT_RUN_CYC_EXCTN_SK",
    "LAST_UPDT_RUN_CYC_EXCTN_SK",
    "MBR_SK",
    "ATTRBTN_PGM_CD_SK",
    "CFA_RMBRMT_TYP_CD_SK",
    "CFA_TRANS_TYP_CD_SK",
    "CTL_PLN_CD_SK",
    "EPSD_TYP_CD_SK",
    "HOME_CORP_PLN_CD_SK",
    "HOME_PLN_CD_SK",
    "HOST_CORP_PLN_CD_SK",
    "HOST_PLN_CD_SK",
    "LOCAL_PLN_CD_SK",
    "VAL_BASED_PGM_CD_SK",
    "VAL_BASED_PGM_PAYMT_TYP_CD_SK",
    "BTCH_CRT_DT_SK",
    "CBF_SETL_STRT_DT_SK",
    "CBF_SETL_BILL_END_DT_SK",
    "CFA_DISP_DT_SK",
    "CFA_PRCS_DT_SK",
    "HOME_AUTH_DENIAL_DT_SK",
    "INCUR_PERD_STRT_DT_SK",
    "INCUR_PERD_END_DT_SK",
    "MSRMNT_PERD_STRT_DT_SK",
    "MSRMNT_PERD_END_DT_SK",
    "MBR_ELIG_STRT_DT_SK",
    "MBR_ELIG_END_DT_SK",
    "PRCS_CYC_YR_MO_SK",
    "SETL_DT_SK",
    "ACES_FEE_ADJ_AMT",
    "CBF_SETL_RATE_AMT",
    "MBR_LVL_CHRG_AMT",
    "ATRBD_PROV_ID",
    "ATRBD_PROV_NTNL_PROV_ID",
    "ATTRBTN_PROV_PGM_NM",
    "BCBSA_MMI_ID",
    "CONSIS_MBR_ID",
    "CBF_SCCF_NO",
    "GRP_ID",
    "HOME_PLN_MBR_ID",
    "ITS_SUB_ID",
    "ORIG_INTER_PLN_BILL_DTL_SRL_NO",
    "ORIG_ITS_CLM_SCCF_NO",
    "PROV_GRP_NM",
    "VRNC_ACCT_ID",
    "BTCH_STTUS_CD_TX",
    "STTUS_CD_TX",
    "ERR_CD_TX",
    "POST_AS_EXP_IN",
    "PRCS_CYC_DT_SK",
    "VAL_BASED_PGM_ID",
    "DSPTD_RCRD_CD",
    "HOME_PLN_DSPT_ACTN_CD",
    "CMNT_TX",
    "HOST_PLN_DSPT_ACTN_CD",
    "LOCAL_PLN_CTL_NO",
    "PRCS_SITE_CTL_NO",
    "BILL_DTL_FMT_RCRD_TYP_CD"
)

char_columns_inter_plan_load = {
    "BTCH_CRT_DT_SK":10,
    "CBF_SETL_STRT_DT_SK":10,
    "CBF_SETL_BILL_END_DT_SK":10,
    "CFA_DISP_DT_SK":10,
    "CFA_PRCS_DT_SK":10,
    "HOME_AUTH_DENIAL_DT_SK":10,
    "INCUR_PERD_STRT_DT_SK":10,
    "INCUR_PERD_END_DT_SK":10,
    "MSRMNT_PERD_STRT_DT_SK":10,
    "MSRMNT_PERD_END_DT_SK":10,
    "MBR_ELIG_STRT_DT_SK":10,
    "MBR_ELIG_END_DT_SK":10,
    "PRCS_CYC_YR_MO_SK":6,
    "SETL_DT_SK":10,
    "POST_AS_EXP_IN":1,
    "PRCS_CYC_DT_SK":10,
    "VAL_BASED_PGM_ID":7
}

df_inter_plan_load_rpad = df_inter_plan_load
for c in df_inter_plan_load_rpad.columns:
    field_type = df_inter_plan_load_rpad.schema[c].dataType
    if c in char_columns_inter_plan_load:
        df_inter_plan_load_rpad = df_inter_plan_load_rpad.withColumn(c, F.rpad(F.col(c), char_columns_inter_plan_load[c], " "))
    elif isinstance(field_type, StringType):
        df_inter_plan_load_rpad = df_inter_plan_load_rpad.withColumn(c, F.rpad(F.col(c), 255, " "))

jdbc_url_ids, jdbc_props_ids = get_db_config(ids_secret_name)

execute_dml(f"DROP TABLE IF EXISTS STAGING.IntrPlnBllDtlCapUpdtPrcsDtLoad_inter_plan_load_temp", jdbc_url_ids, jdbc_props_ids)

df_inter_plan_load_rpad.write \
    .format("jdbc") \
    .option("url", jdbc_url_ids) \
    .options(**jdbc_props_ids) \
    .option("dbtable", "STAGING.IntrPlnBllDtlCapUpdtPrcsDtLoad_inter_plan_load_temp") \
    .mode("overwrite") \
    .save()

merge_sql_inter_plan_load = """
MERGE INTO {owner}.INTER_PLN_BILL_DTL AS target
USING STAGING.IntrPlnBllDtlCapUpdtPrcsDtLoad_inter_plan_load_temp AS source
ON target.INTER_PLN_BILL_DTL_SK = source.INTER_PLN_BILL_DTL_SK
WHEN MATCHED THEN UPDATE SET
    target.INTER_PLN_BILL_DTL_ID = source.INTER_PLN_BILL_DTL_ID,
    target.BUS_OWNER_ID = source.BUS_OWNER_ID,
    target.SRC_SYS_CD_SK = source.SRC_SYS_CD_SK,
    target.CRT_RUN_CYC_EXCTN_SK = source.CRT_RUN_CYC_EXCTN_SK,
    target.LAST_UPDT_RUN_CYC_EXCTN_SK = source.LAST_UPDT_RUN_CYC_EXCTN_SK,
    target.MBR_SK = source.MBR_SK,
    target.ATTRBTN_PGM_CD_SK = source.ATTRBTN_PGM_CD_SK,
    target.CFA_RMBRMT_TYP_CD_SK = source.CFA_RMBRMT_TYP_CD_SK,
    target.CFA_TRANS_TYP_CD_SK = source.CFA_TRANS_TYP_CD_SK,
    target.CTL_PLN_CD_SK = source.CTL_PLN_CD_SK,
    target.EPSD_TYP_CD_SK = source.EPSD_TYP_CD_SK,
    target.HOME_CORP_PLN_CD_SK = source.HOME_CORP_PLN_CD_SK,
    target.HOME_PLN_CD_SK = source.HOME_PLN_CD_SK,
    target.HOST_CORP_PLN_CD_SK = source.HOST_CORP_PLN_CD_SK,
    target.HOST_PLN_CD_SK = source.HOST_PLN_CD_SK,
    target.LOCAL_PLN_CD_SK = source.LOCAL_PLN_CD_SK,
    target.VAL_BASED_PGM_CD_SK = source.VAL_BASED_PGM_CD_SK,
    target.VAL_BASED_PGM_PAYMT_TYP_CD_SK = source.VAL_BASED_PGM_PAYMT_TYP_CD_SK,
    target.BTCH_CRT_DT_SK = source.BTCH_CRT_DT_SK,
    target.CBF_SETL_STRT_DT_SK = source.CBF_SETL_STRT_DT_SK,
    target.CBF_SETL_BILL_END_DT_SK = source.CBF_SETL_BILL_END_DT_SK,
    target.CFA_DISP_DT_SK = source.CFA_DISP_DT_SK,
    target.CFA_PRCS_DT_SK = source.CFA_PRCS_DT_SK,
    target.HOME_AUTH_DENIAL_DT_SK = source.HOME_AUTH_DENIAL_DT_SK,
    target.INCUR_PERD_STRT_DT_SK = source.INCUR_PERD_STRT_DT_SK,
    target.INCUR_PERD_END_DT_SK = source.INCUR_PERD_END_DT_SK,
    target.MSRMNT_PERD_STRT_DT_SK = source.MSRMNT_PERD_STRT_DT_SK,
    target.MSRMNT_PERD_END_DT_SK = source.MSRMNT_PERD_END_DT_SK,
    target.MBR_ELIG_STRT_DT_SK = source.MBR_ELIG_STRT_DT_SK,
    target.MBR_ELIG_END_DT_SK = source.MBR_ELIG_END_DT_SK,
    target.PRCS_CYC_YR_MO_SK = source.PRCS_CYC_YR_MO_SK,
    target.SETL_DT_SK = source.SETL_DT_SK,
    target.ACES_FEE_ADJ_AMT = source.ACES_FEE_ADJ_AMT,
    target.CBF_SETL_RATE_AMT = source.CBF_SETL_RATE_AMT,
    target.MBR_LVL_CHRG_AMT = source.MBR_LVL_CHRG_AMT,
    target.ATRBD_PROV_ID = source.ATRBD_PROV_ID,
    target.ATRBD_PROV_NTNL_PROV_ID = source.ATRBD_PROV_NTNL_PROV_ID,
    target.ATTRBTN_PROV_PGM_NM = source.ATTRBTN_PROV_PGM_NM,
    target.BCBSA_MMI_ID = source.BCBSA_MMI_ID,
    target.CONSIS_MBR_ID = source.CONSIS_MBR_ID,
    target.CBF_SCCF_NO = source.CBF_SCCF_NO,
    target.GRP_ID = source.GRP_ID,
    target.HOME_PLN_MBR_ID = source.HOME_PLN_MBR_ID,
    target.ITS_SUB_ID = source.ITS_SUB_ID,
    target.ORIG_INTER_PLN_BILL_DTL_SRL_NO = source.ORIG_INTER_PLN_BILL_DTL_SRL_NO,
    target.ORIG_ITS_CLM_SCCF_NO = source.ORIG_ITS_CLM_SCCF_NO,
    target.PROV_GRP_NM = source.PROV_GRP_NM,
    target.VRNC_ACCT_ID = source.VRNC_ACCT_ID,
    target.BTCH_STTUS_CD_TX = source.BTCH_STTUS_CD_TX,
    target.STTUS_CD_TX = source.STTUS_CD_TX,
    target.ERR_CD_TX = source.ERR_CD_TX,
    target.POST_AS_EXP_IN = source.POST_AS_EXP_IN,
    target.PRCS_CYC_DT_SK = source.PRCS_CYC_DT_SK,
    target.VAL_BASED_PGM_ID = source.VAL_BASED_PGM_ID,
    target.DSPTD_RCRD_CD = source.DSPTD_RCRD_CD,
    target.HOME_PLN_DSPT_ACTN_CD = source.HOME_PLN_DSPT_ACTN_CD,
    target.CMNT_TX = source.CMNT_TX,
    target.HOST_PLN_DSPT_ACTN_CD = source.HOST_PLN_DSPT_ACTN_CD,
    target.LOCAL_PLN_CTL_NO = source.LOCAL_PLN_CTL_NO,
    target.PRCS_SITE_CTL_NO = source.PRCS_SITE_CTL_NO,
    target.BILL_DTL_FMT_RCRD_TYP_CD = source.BILL_DTL_FMT_RCRD_TYP_CD
WHEN NOT MATCHED THEN INSERT (
    INTER_PLN_BILL_DTL_SK,
    INTER_PLN_BILL_DTL_ID,
    BUS_OWNER_ID,
    SRC_SYS_CD_SK,
    CRT_RUN_CYC_EXCTN_SK,
    LAST_UPDT_RUN_CYC_EXCTN_SK,
    MBR_SK,
    ATTRBTN_PGM_CD_SK,
    CFA_RMBRMT_TYP_CD_SK,
    CFA_TRANS_TYP_CD_SK,
    CTL_PLN_CD_SK,
    EPSD_TYP_CD_SK,
    HOME_CORP_PLN_CD_SK,
    HOME_PLN_CD_SK,
    HOST_CORP_PLN_CD_SK,
    HOST_PLN_CD_SK,
    LOCAL_PLN_CD_SK,
    VAL_BASED_PGM_CD_SK,
    VAL_BASED_PGM_PAYMT_TYP_CD_SK,
    BTCH_CRT_DT_SK,
    CBF_SETL_STRT_DT_SK,
    CBF_SETL_BILL_END_DT_SK,
    CFA_DISP_DT_SK,
    CFA_PRCS_DT_SK,
    HOME_AUTH_DENIAL_DT_SK,
    INCUR_PERD_STRT_DT_SK,
    INCUR_PERD_END_DT_SK,
    MSRMNT_PERD_STRT_DT_SK,
    MSRMNT_PERD_END_DT_SK,
    MBR_ELIG_STRT_DT_SK,
    MBR_ELIG_END_DT_SK,
    PRCS_CYC_YR_MO_SK,
    SETL_DT_SK,
    ACES_FEE_ADJ_AMT,
    CBF_SETL_RATE_AMT,
    MBR_LVL_CHRG_AMT,
    ATRBD_PROV_ID,
    ATRBD_PROV_NTNL_PROV_ID,
    ATTRBTN_PROV_PGM_NM,
    BCBSA_MMI_ID,
    CONSIS_MBR_ID,
    CBF_SCCF_NO,
    GRP_ID,
    HOME_PLN_MBR_ID,
    ITS_SUB_ID,
    ORIG_INTER_PLN_BILL_DTL_SRL_NO,
    ORIG_ITS_CLM_SCCF_NO,
    PROV_GRP_NM,
    VRNC_ACCT_ID,
    BTCH_STTUS_CD_TX,
    STTUS_CD_TX,
    ERR_CD_TX,
    POST_AS_EXP_IN,
    PRCS_CYC_DT_SK,
    VAL_BASED_PGM_ID,
    DSPTD_RCRD_CD,
    HOME_PLN_DSPT_ACTN_CD,
    CMNT_TX,
    HOST_PLN_DSPT_ACTN_CD,
    LOCAL_PLN_CTL_NO,
    PRCS_SITE_CTL_NO,
    BILL_DTL_FMT_RCRD_TYP_CD
) VALUES (
    source.INTER_PLN_BILL_DTL_SK,
    source.INTER_PLN_BILL_DTL_ID,
    source.BUS_OWNER_ID,
    source.SRC_SYS_CD_SK,
    source.CRT_RUN_CYC_EXCTN_SK,
    source.LAST_UPDT_RUN_CYC_EXCTN_SK,
    source.MBR_SK,
    source.ATTRBTN_PGM_CD_SK,
    source.CFA_RMBRMT_TYP_CD_SK,
    source.CFA_TRANS_TYP_CD_SK,
    source.CTL_PLN_CD_SK,
    source.EPSD_TYP_CD_SK,
    source.HOME_CORP_PLN_CD_SK,
    source.HOME_PLN_CD_SK,
    source.HOST_CORP_PLN_CD_SK,
    source.HOST_PLN_CD_SK,
    source.LOCAL_PLN_CD_SK,
    source.VAL_BASED_PGM_CD_SK,
    source.VAL_BASED_PGM_PAYMT_TYP_CD_SK,
    source.BTCH_CRT_DT_SK,
    source.CBF_SETL_STRT_DT_SK,
    source.CBF_SETL_BILL_END_DT_SK,
    source.CFA_DISP_DT_SK,
    source.CFA_PRCS_DT_SK,
    source.HOME_AUTH_DENIAL_DT_SK,
    source.INCUR_PERD_STRT_DT_SK,
    source.INCUR_PERD_END_DT_SK,
    source.MSRMNT_PERD_STRT_DT_SK,
    source.MSRMNT_PERD_END_DT_SK,
    source.MBR_ELIG_STRT_DT_SK,
    source.MBR_ELIG_END_DT_SK,
    source.PRCS_CYC_YR_MO_SK,
    source.SETL_DT_SK,
    source.ACES_FEE_ADJ_AMT,
    source.CBF_SETL_RATE_AMT,
    source.MBR_LVL_CHRG_AMT,
    source.ATRBD_PROV_ID,
    source.ATRBD_PROV_NTNL_PROV_ID,
    source.ATTRBTN_PROV_PGM_NM,
    source.BCBSA_MMI_ID,
    source.CONSIS_MBR_ID,
    source.CBF_SCCF_NO,
    source.GRP_ID,
    source.HOME_PLN_MBR_ID,
    source.ITS_SUB_ID,
    source.ORIG_INTER_PLN_BILL_DTL_SRL_NO,
    source.ORIG_ITS_CLM_SCCF_NO,
    source.PROV_GRP_NM,
    source.VRNC_ACCT_ID,
    source.BTCH_STTUS_CD_TX,
    source.STTUS_CD_TX,
    source.ERR_CD_TX,
    source.POST_AS_EXP_IN,
    source.PRCS_CYC_DT_SK,
    source.VAL_BASED_PGM_ID,
    source.DSPTD_RCRD_CD,
    source.HOME_PLN_DSPT_ACTN_CD,
    source.CMNT_TX,
    source.HOST_PLN_DSPT_ACTN_CD,
    source.LOCAL_PLN_CTL_NO,
    source.PRCS_SITE_CTL_NO,
    source.BILL_DTL_FMT_RCRD_TYP_CD
);
""".format(owner=IDSOwner)

execute_dml(merge_sql_inter_plan_load, jdbc_url_ids, jdbc_props_ids)

# Schema for Seq_dup_recds (PxSequentialFile)
schema_seq_dup_recds = StructType([
    StructField("INTER_PLN_BILL_DTL_SK", IntegerType(), False),
    StructField("INTER_PLN_BILL_DTL_ID", StringType(), False),
    StructField("BUS_OWNER_ID", StringType(), False),
    StructField("SRC_SYS_CD_SK", IntegerType(), False),
    StructField("CRT_RUN_CYC_EXCTN_SK", IntegerType(), False),
    StructField("LAST_UPDT_RUN_CYC_EXCTN_SK", IntegerType(), False),
    StructField("MBR_SK", IntegerType(), False),
    StructField("ATTRBTN_PGM_CD_SK", IntegerType(), False),
    StructField("CFA_RMBRMT_TYP_CD_SK", IntegerType(), False),
    StructField("CFA_TRANS_TYP_CD_SK", IntegerType(), False),
    StructField("CTL_PLN_CD_SK", IntegerType(), False),
    StructField("EPSD_TYP_CD_SK", IntegerType(), False),
    StructField("HOME_CORP_PLN_CD_SK", IntegerType(), False),
    StructField("HOME_PLN_CD_SK", IntegerType(), False),
    StructField("HOST_CORP_PLN_CD_SK", IntegerType(), False),
    StructField("HOST_PLN_CD_SK", IntegerType(), False),
    StructField("LOCAL_PLN_CD_SK", IntegerType(), False),
    StructField("VAL_BASED_PGM_CD_SK", IntegerType(), False),
    StructField("VAL_BASED_PGM_PAYMT_TYP_CD_SK", IntegerType(), False),
    StructField("BTCH_CRT_DT_SK", StringType(), False),
    StructField("CBF_SETL_STRT_DT_SK", StringType(), False),
    StructField("CBF_SETL_BILL_END_DT_SK", StringType(), False),
    StructField("CFA_DISP_DT_SK", StringType(), False),
    StructField("CFA_PRCS_DT_SK", StringType(), False),
    StructField("HOME_AUTH_DENIAL_DT_SK", StringType(), False),
    StructField("INCUR_PERD_STRT_DT_SK", StringType(), False),
    StructField("INCUR_PERD_END_DT_SK", StringType(), False),
    StructField("MSRMNT_PERD_STRT_DT_SK", StringType(), False),
    StructField("MSRMNT_PERD_END_DT_SK", StringType(), False),
    StructField("MBR_ELIG_STRT_DT_SK", StringType(), False),
    StructField("MBR_ELIG_END_DT_SK", StringType(), False),
    StructField("PRCS_CYC_YR_MO_SK", StringType(), False),
    StructField("SETL_DT_SK", StringType(), False),
    StructField("ACES_FEE_ADJ_AMT", DecimalType(38,10), False),
    StructField("CBF_SETL_RATE_AMT", DecimalType(38,10), False),
    StructField("MBR_LVL_CHRG_AMT", DecimalType(38,10), False),
    StructField("ATRBD_PROV_ID", StringType(), False),
    StructField("ATRBD_PROV_NTNL_PROV_ID", StringType(), False),
    StructField("ATTRBTN_PROV_PGM_NM", StringType(), False),
    StructField("BCBSA_MMI_ID", StringType(), False),
    StructField("CONSIS_MBR_ID", StringType(), False),
    StructField("CBF_SCCF_NO", StringType(), False),
    StructField("GRP_ID", StringType(), False),
    StructField("HOME_PLN_MBR_ID", StringType(), False),
    StructField("ITS_SUB_ID", StringType(), False),
    StructField("ORIG_INTER_PLN_BILL_DTL_SRL_NO", StringType(), False),
    StructField("ORIG_ITS_CLM_SCCF_NO", StringType(), False),
    StructField("PROV_GRP_NM", StringType(), True),
    StructField("VRNC_ACCT_ID", StringType(), False),
    StructField("BTCH_STTUS_CD_TX", StringType(), False),
    StructField("STTUS_CD_TX", StringType(), False),
    StructField("ERR_CD_TX", StringType(), False),
    StructField("POST_AS_EXP_IN", StringType(), False),
    StructField("PRCS_CYC_DT_SK", StringType(), False),
    StructField("VAL_BASED_PGM_ID", StringType(), True),
    StructField("DSPTD_RCRD_CD", StringType(), True),
    StructField("HOME_PLN_DSPT_ACTN_CD", StringType(), True),
    StructField("CMNT_TX", StringType(), True),
    StructField("HOST_PLN_DSPT_ACTN_CD", StringType(), True),
    StructField("LOCAL_PLN_CTL_NO", StringType(), True),
    StructField("PRCS_SITE_CTL_NO", StringType(), True),
    StructField("BILL_DTL_FMT_RCRD_TYP_CD", StringType(), True)
])

df_Seq_dup_recds = (
    spark.read.format("csv")
    .option("header", "false")
    .option("delimiter", ",")
    .option("quote", "|")
    .option("nullValue", None)
    .schema(schema_seq_dup_recds)
    .load(f"{adls_path_publish}/external/INTER_PLN_BILL_DTL_dup.dat")
)

df_Cp_Dup_recds = df_Seq_dup_recds.alias("DSLink9").select(
    F.col("DSLink9.INTER_PLN_BILL_DTL_SK").alias("INTER_PLN_BILL_DTL_SK"),
    F.col("DSLink9.INTER_PLN_BILL_DTL_ID").alias("INTER_PLN_BILL_DTL_ID"),
    F.col("DSLink9.BUS_OWNER_ID").alias("BUS_OWNER_ID"),
    F.col("DSLink9.SRC_SYS_CD_SK").alias("SRC_SYS_CD_SK"),
    F.col("DSLink9.CRT_RUN_CYC_EXCTN_SK").alias("CRT_RUN_CYC_EXCTN_SK"),
    F.col("DSLink9.LAST_UPDT_RUN_CYC_EXCTN_SK").alias("LAST_UPDT_RUN_CYC_EXCTN_SK"),
    F.col("DSLink9.MBR_SK").alias("MBR_SK"),
    F.col("DSLink9.ATTRBTN_PGM_CD_SK").alias("ATTRBTN_PGM_CD_SK"),
    F.col("DSLink9.CFA_RMBRMT_TYP_CD_SK").alias("CFA_RMBRMT_TYP_CD_SK"),
    F.col("DSLink9.CFA_TRANS_TYP_CD_SK").alias("CFA_TRANS_TYP_CD_SK"),
    F.col("DSLink9.CTL_PLN_CD_SK").alias("CTL_PLN_CD_SK"),
    F.col("DSLink9.EPSD_TYP_CD_SK").alias("EPSD_TYP_CD_SK"),
    F.col("DSLink9.HOME_CORP_PLN_CD_SK").alias("HOME_CORP_PLN_CD_SK"),
    F.col("DSLink9.HOME_PLN_CD_SK").alias("HOME_PLN_CD_SK"),
    F.col("DSLink9.HOST_CORP_PLN_CD_SK").alias("HOST_CORP_PLN_CD_SK"),
    F.col("DSLink9.HOST_PLN_CD_SK").alias("HOST_PLN_CD_SK"),
    F.col("DSLink9.LOCAL_PLN_CD_SK").alias("LOCAL_PLN_CD_SK"),
    F.col("DSLink9.VAL_BASED_PGM_CD_SK").alias("VAL_BASED_PGM_CD_SK"),
    F.col("DSLink9.VAL_BASED_PGM_PAYMT_TYP_CD_SK").alias("VAL_BASED_PGM_PAYMT_TYP_CD_SK"),
    F.col("DSLink9.BTCH_CRT_DT_SK").alias("BTCH_CRT_DT_SK"),
    F.col("DSLink9.CBF_SETL_STRT_DT_SK").alias("CBF_SETL_STRT_DT_SK"),
    F.col("DSLink9.CBF_SETL_BILL_END_DT_SK").alias("CBF_SETL_BILL_END_DT_SK"),
    F.col("DSLink9.CFA_DISP_DT_SK").alias("CFA_DISP_DT_SK"),
    F.col("DSLink9.CFA_PRCS_DT_SK").alias("CFA_PRCS_DT_SK"),
    F.col("DSLink9.HOME_AUTH_DENIAL_DT_SK").alias("HOME_AUTH_DENIAL_DT_SK"),
    F.col("DSLink9.INCUR_PERD_STRT_DT_SK").alias("INCUR_PERD_STRT_DT_SK"),
    F.col("DSLink9.INCUR_PERD_END_DT_SK").alias("INCUR_PERD_END_DT_SK"),
    F.col("DSLink9.MSRMNT_PERD_STRT_DT_SK").alias("MSRMNT_PERD_STRT_DT_SK"),
    F.col("DSLink9.MSRMNT_PERD_END_DT_SK").alias("MSRMNT_PERD_END_DT_SK"),
    F.col("DSLink9.MBR_ELIG_STRT_DT_SK").alias("MBR_ELIG_STRT_DT_SK"),
    F.col("DSLink9.MBR_ELIG_END_DT_SK").alias("MBR_ELIG_END_DT_SK"),
    F.col("DSLink9.PRCS_CYC_YR_MO_SK").alias("PRCS_CYC_YR_MO_SK"),
    F.col("DSLink9.SETL_DT_SK").alias("SETL_DT_SK"),
    F.col("DSLink9.ACES_FEE_ADJ_AMT").alias("ACES_FEE_ADJ_AMT"),
    F.col("DSLink9.CBF_SETL_RATE_AMT").alias("CBF_SETL_RATE_AMT"),
    F.col("DSLink9.MBR_LVL_CHRG_AMT").alias("MBR_LVL_CHRG_AMT"),
    F.col("DSLink9.ATRBD_PROV_ID").alias("ATRBD_PROV_ID"),
    F.col("DSLink9.ATRBD_PROV_NTNL_PROV_ID").alias("ATRBD_PROV_NTNL_PROV_ID"),
    F.col("DSLink9.ATTRBTN_PROV_PGM_NM").alias("ATTRBTN_PROV_PGM_NM"),
    F.col("DSLink9.BCBSA_MMI_ID").alias("BCBSA_MMI_ID"),
    F.col("DSLink9.CONSIS_MBR_ID").alias("CONSIS_MBR_ID"),
    F.col("DSLink9.CBF_SCCF_NO").alias("CBF_SCCF_NO"),
    F.col("DSLink9.GRP_ID").alias("GRP_ID"),
    F.col("DSLink9.HOME_PLN_MBR_ID").alias("HOME_PLN_MBR_ID"),
    F.col("DSLink9.ITS_SUB_ID").alias("ITS_SUB_ID"),
    F.col("DSLink9.ORIG_INTER_PLN_BILL_DTL_SRL_NO").alias("ORIG_INTER_PLN_BILL_DTL_SRL_NO"),
    F.col("DSLink9.ORIG_ITS_CLM_SCCF_NO").alias("ORIG_ITS_CLM_SCCF_NO"),
    F.col("DSLink9.PROV_GRP_NM").alias("PROV_GRP_NM"),
    F.col("DSLink9.VRNC_ACCT_ID").alias("VRNC_ACCT_ID"),
    F.col("DSLink9.BTCH_STTUS_CD_TX").alias("BTCH_STTUS_CD_TX"),
    F.col("DSLink9.STTUS_CD_TX").alias("STTUS_CD_TX"),
    F.col("DSLink9.ERR_CD_TX").alias("ERR_CD_TX"),
    F.col("DSLink9.POST_AS_EXP_IN").alias("POST_AS_EXP_IN"),
    F.col("DSLink9.PRCS_CYC_DT_SK").alias("PRCS_CYC_DT_SK"),
    F.col("DSLink9.VAL_BASED_PGM_ID").alias("VAL_BASED_PGM_ID"),
    F.col("DSLink9.DSPTD_RCRD_CD").alias("DSPTD_RCRD_CD"),
    F.col("DSLink9.HOME_PLN_DSPT_ACTN_CD").alias("HOME_PLN_DSPT_ACTN_CD"),
    F.col("DSLink9.CMNT_TX").alias("CMNT_TX"),
    F.col("DSLink9.HOST_PLN_DSPT_ACTN_CD").alias("HOST_PLN_DSPT_ACTN_CD"),
    F.col("DSLink9.LOCAL_PLN_CTL_NO").alias("LOCAL_PLN_CTL_NO"),
    F.col("DSLink9.PRCS_SITE_CTL_NO").alias("PRCS_SITE_CTL_NO"),
    F.col("DSLink9.BILL_DTL_FMT_RCRD_TYP_CD").alias("BILL_DTL_FMT_RCRD_TYP_CD")
)

df_interplan_dup_load = df_Cp_Dup_recds.select(
    "INTER_PLN_BILL_DTL_SK",
    "INTER_PLN_BILL_DTL_ID",
    "BUS_OWNER_ID",
    "SRC_SYS_CD_SK",
    "CRT_RUN_CYC_EXCTN_SK",
    "LAST_UPDT_RUN_CYC_EXCTN_SK",
    "MBR_SK",
    "ATTRBTN_PGM_CD_SK",
    "CFA_RMBRMT_TYP_CD_SK",
    "CFA_TRANS_TYP_CD_SK",
    "CTL_PLN_CD_SK",
    "EPSD_TYP_CD_SK",
    "HOME_CORP_PLN_CD_SK",
    "HOME_PLN_CD_SK",
    "HOST_CORP_PLN_CD_SK",
    "HOST_PLN_CD_SK",
    "LOCAL_PLN_CD_SK",
    "VAL_BASED_PGM_CD_SK",
    "VAL_BASED_PGM_PAYMT_TYP_CD_SK",
    "BTCH_CRT_DT_SK",
    "CBF_SETL_STRT_DT_SK",
    "CBF_SETL_BILL_END_DT_SK",
    "CFA_DISP_DT_SK",
    "CFA_PRCS_DT_SK",
    "HOME_AUTH_DENIAL_DT_SK",
    "INCUR_PERD_STRT_DT_SK",
    "INCUR_PERD_END_DT_SK",
    "MSRMNT_PERD_STRT_DT_SK",
    "MSRMNT_PERD_END_DT_SK",
    "MBR_ELIG_STRT_DT_SK",
    "MBR_ELIG_END_DT_SK",
    "PRCS_CYC_YR_MO_SK",
    "SETL_DT_SK",
    "ACES_FEE_ADJ_AMT",
    "CBF_SETL_RATE_AMT",
    "MBR_LVL_CHRG_AMT",
    "ATRBD_PROV_ID",
    "ATRBD_PROV_NTNL_PROV_ID",
    "ATTRBTN_PROV_PGM_NM",
    "BCBSA_MMI_ID",
    "CONSIS_MBR_ID",
    "CBF_SCCF_NO",
    "GRP_ID",
    "HOME_PLN_MBR_ID",
    "ITS_SUB_ID",
    "ORIG_INTER_PLN_BILL_DTL_SRL_NO",
    "ORIG_ITS_CLM_SCCF_NO",
    "PROV_GRP_NM",
    "VRNC_ACCT_ID",
    "BTCH_STTUS_CD_TX",
    "STTUS_CD_TX",
    "ERR_CD_TX",
    "POST_AS_EXP_IN",
    "PRCS_CYC_DT_SK",
    "VAL_BASED_PGM_ID",
    "DSPTD_RCRD_CD",
    "HOME_PLN_DSPT_ACTN_CD",
    "CMNT_TX",
    "HOST_PLN_DSPT_ACTN_CD",
    "LOCAL_PLN_CTL_NO",
    "PRCS_SITE_CTL_NO",
    "BILL_DTL_FMT_RCRD_TYP_CD"
)

char_columns_interplan_dup_load = {
    "BTCH_CRT_DT_SK":10,
    "CBF_SETL_STRT_DT_SK":10,
    "CBF_SETL_BILL_END_DT_SK":10,
    "CFA_DISP_DT_SK":10,
    "CFA_PRCS_DT_SK":10,
    "HOME_AUTH_DENIAL_DT_SK":10,
    "INCUR_PERD_STRT_DT_SK":10,
    "INCUR_PERD_END_DT_SK":10,
    "MSRMNT_PERD_STRT_DT_SK":10,
    "MSRMNT_PERD_END_DT_SK":10,
    "MBR_ELIG_STRT_DT_SK":10,
    "MBR_ELIG_END_DT_SK":10,
    "PRCS_CYC_YR_MO_SK":6,
    "SETL_DT_SK":10,
    "POST_AS_EXP_IN":1,
    "PRCS_CYC_DT_SK":10,
    "VAL_BASED_PGM_ID":7
}

df_interplan_dup_load_rpad = df_interplan_dup_load
for c in df_interplan_dup_load_rpad.columns:
    field_type = df_interplan_dup_load_rpad.schema[c].dataType
    if c in char_columns_interplan_dup_load:
        df_interplan_dup_load_rpad = df_interplan_dup_load_rpad.withColumn(c, F.rpad(F.col(c), char_columns_interplan_dup_load[c], " "))
    elif isinstance(field_type, StringType):
        df_interplan_dup_load_rpad = df_interplan_dup_load_rpad.withColumn(c, F.rpad(F.col(c), 255, " "))

execute_dml(f"DROP TABLE IF EXISTS STAGING.IntrPlnBllDtlCapUpdtPrcsDtLoad_interplan_dup_load_temp", jdbc_url_ids, jdbc_props_ids)

df_interplan_dup_load_rpad.write \
    .format("jdbc") \
    .option("url", jdbc_url_ids) \
    .options(**jdbc_props_ids) \
    .option("dbtable", "STAGING.IntrPlnBllDtlCapUpdtPrcsDtLoad_interplan_dup_load_temp") \
    .mode("overwrite") \
    .save()

merge_sql_interplan_dup_load = """
MERGE INTO {owner}.INTER_PLN_BILL_DTL AS target
USING STAGING.IntrPlnBllDtlCapUpdtPrcsDtLoad_interplan_dup_load_temp AS source
ON target.INTER_PLN_BILL_DTL_SK = source.INTER_PLN_BILL_DTL_SK
WHEN MATCHED THEN UPDATE SET
    target.INTER_PLN_BILL_DTL_ID = source.INTER_PLN_BILL_DTL_ID,
    target.BUS_OWNER_ID = source.BUS_OWNER_ID,
    target.SRC_SYS_CD_SK = source.SRC_SYS_CD_SK,
    target.CRT_RUN_CYC_EXCTN_SK = source.CRT_RUN_CYC_EXCTN_SK,
    target.LAST_UPDT_RUN_CYC_EXCTN_SK = source.LAST_UPDT_RUN_CYC_EXCTN_SK,
    target.MBR_SK = source.MBR_SK,
    target.ATTRBTN_PGM_CD_SK = source.ATTRBTN_PGM_CD_SK,
    target.CFA_RMBRMT_TYP_CD_SK = source.CFA_RMBRMT_TYP_CD_SK,
    target.CFA_TRANS_TYP_CD_SK = source.CFA_TRANS_TYP_CD_SK,
    target.CTL_PLN_CD_SK = source.CTL_PLN_CD_SK,
    target.EPSD_TYP_CD_SK = source.EPSD_TYP_CD_SK,
    target.HOME_CORP_PLN_CD_SK = source.HOME_CORP_PLN_CD_SK,
    target.HOME_PLN_CD_SK = source.HOME_PLN_CD_SK,
    target.HOST_CORP_PLN_CD_SK = source.HOST_CORP_PLN_CD_SK,
    target.HOST_PLN_CD_SK = source.HOST_PLN_CD_SK,
    target.LOCAL_PLN_CD_SK = source.LOCAL_PLN_CD_SK,
    target.VAL_BASED_PGM_CD_SK = source.VAL_BASED_PGM_CD_SK,
    target.VAL_BASED_PGM_PAYMT_TYP_CD_SK = source.VAL_BASED_PGM_PAYMT_TYP_CD_SK,
    target.BTCH_CRT_DT_SK = source.BTCH_CRT_DT_SK,
    target.CBF_SETL_STRT_DT_SK = source.CBF_SETL_STRT_DT_SK,
    target.CBF_SETL_BILL_END_DT_SK = source.CBF_SETL_BILL_END_DT_SK,
    target.CFA_DISP_DT_SK = source.CFA_DISP_DT_SK,
    target.CFA_PRCS_DT_SK = source.CFA_PRCS_DT_SK,
    target.HOME_AUTH_DENIAL_DT_SK = source.HOME_AUTH_DENIAL_DT_SK,
    target.INCUR_PERD_STRT_DT_SK = source.INCUR_PERD_STRT_DT_SK,
    target.INCUR_PERD_END_DT_SK = source.INCUR_PERD_END_DT_SK,
    target.MSRMNT_PERD_STRT_DT_SK = source.MSRMNT_PERD_STRT_DT_SK,
    target.MSRMNT_PERD_END_DT_SK = source.MSRMNT_PERD_END_DT_SK,
    target.MBR_ELIG_STRT_DT_SK = source.MBR_ELIG_STRT_DT_SK,
    target.MBR_ELIG_END_DT_SK = source.MBR_ELIG_END_DT_SK,
    target.PRCS_CYC_YR_MO_SK = source.PRCS_CYC_YR_MO_SK,
    target.SETL_DT_SK = source.SETL_DT_SK,
    target.ACES_FEE_ADJ_AMT = source.ACES_FEE_ADJ_AMT,
    target.CBF_SETL_RATE_AMT = source.CBF_SETL_RATE_AMT,
    target.MBR_LVL_CHRG_AMT = source.MBR_LVL_CHRG_AMT,
    target.ATRBD_PROV_ID = source.ATRBD_PROV_ID,
    target.ATRBD_PROV_NTNL_PROV_ID = source.ATRBD_PROV_NTNL_PROV_ID,
    target.ATTRBTN_PROV_PGM_NM = source.ATTRBTN_PROV_PGM_NM,
    target.BCBSA_MMI_ID = source.BCBSA_MMI_ID,
    target.CONSIS_MBR_ID = source.CONSIS_MBR_ID,
    target.CBF_SCCF_NO = source.CBF_SCCF_NO,
    target.GRP_ID = source.GRP_ID,
    target.HOME_PLN_MBR_ID = source.HOME_PLN_MBR_ID,
    target.ITS_SUB_ID = source.ITS_SUB_ID,
    target.ORIG_INTER_PLN_BILL_DTL_SRL_NO = source.ORIG_INTER_PLN_BILL_DTL_SRL_NO,
    target.ORIG_ITS_CLM_SCCF_NO = source.ORIG_ITS_CLM_SCCF_NO,
    target.PROV_GRP_NM = source.PROV_GRP_NM,
    target.VRNC_ACCT_ID = source.VRNC_ACCT_ID,
    target.BTCH_STTUS_CD_TX = source.BTCH_STTUS_CD_TX,
    target.STTUS_CD_TX = source.STTUS_CD_TX,
    target.ERR_CD_TX = source.ERR_CD_TX,
    target.POST_AS_EXP_IN = source.POST_AS_EXP_IN,
    target.PRCS_CYC_DT_SK = source.PRCS_CYC_DT_SK,
    target.VAL_BASED_PGM_ID = source.VAL_BASED_PGM_ID,
    target.DSPTD_RCRD_CD = source.DSPTD_RCRD_CD,
    target.HOME_PLN_DSPT_ACTN_CD = source.HOME_PLN_DSPT_ACTN_CD,
    target.CMNT_TX = source.CMNT_TX,
    target.HOST_PLN_DSPT_ACTN_CD = source.HOST_PLN_DSPT_ACTN_CD,
    target.LOCAL_PLN_CTL_NO = source.LOCAL_PLN_CTL_NO,
    target.PRCS_SITE_CTL_NO = source.PRCS_SITE_CTL_NO,
    target.BILL_DTL_FMT_RCRD_TYP_CD = source.BILL_DTL_FMT_RCRD_TYP_CD
WHEN NOT MATCHED THEN INSERT (
    INTER_PLN_BILL_DTL_SK,
    INTER_PLN_BILL_DTL_ID,
    BUS_OWNER_ID,
    SRC_SYS_CD_SK,
    CRT_RUN_CYC_EXCTN_SK,
    LAST_UPDT_RUN_CYC_EXCTN_SK,
    MBR_SK,
    ATTRBTN_PGM_CD_SK,
    CFA_RMBRMT_TYP_CD_SK,
    CFA_TRANS_TYP_CD_SK,
    CTL_PLN_CD_SK,
    EPSD_TYP_CD_SK,
    HOME_CORP_PLN_CD_SK,
    HOME_PLN_CD_SK,
    HOST_CORP_PLN_CD_SK,
    HOST_PLN_CD_SK,
    LOCAL_PLN_CD_SK,
    VAL_BASED_PGM_CD_SK,
    VAL_BASED_PGM_PAYMT_TYP_CD_SK,
    BTCH_CRT_DT_SK,
    CBF_SETL_STRT_DT_SK,
    CBF_SETL_BILL_END_DT_SK,
    CFA_DISP_DT_SK,
    CFA_PRCS_DT_SK,
    HOME_AUTH_DENIAL_DT_SK,
    INCUR_PERD_STRT_DT_SK,
    INCUR_PERD_END_DT_SK,
    MSRMNT_PERD_STRT_DT_SK,
    MSRMNT_PERD_END_DT_SK,
    MBR_ELIG_STRT_DT_SK,
    MBR_ELIG_END_DT_SK,
    PRCS_CYC_YR_MO_SK,
    SETL_DT_SK,
    ACES_FEE_ADJ_AMT,
    CBF_SETL_RATE_AMT,
    MBR_LVL_CHRG_AMT,
    ATRBD_PROV_ID,
    ATRBD_PROV_NTNL_PROV_ID,
    ATTRBTN_PROV_PGM_NM,
    BCBSA_MMI_ID,
    CONSIS_MBR_ID,
    CBF_SCCF_NO,
    GRP_ID,
    HOME_PLN_MBR_ID,
    ITS_SUB_ID,
    ORIG_INTER_PLN_BILL_DTL_SRL_NO,
    ORIG_ITS_CLM_SCCF_NO,
    PROV_GRP_NM,
    VRNC_ACCT_ID,
    BTCH_STTUS_CD_TX,
    STTUS_CD_TX,
    ERR_CD_TX,
    POST_AS_EXP_IN,
    PRCS_CYC_DT_SK,
    VAL_BASED_PGM_ID,
    DSPTD_RCRD_CD,
    HOME_PLN_DSPT_ACTN_CD,
    CMNT_TX,
    HOST_PLN_DSPT_ACTN_CD,
    LOCAL_PLN_CTL_NO,
    PRCS_SITE_CTL_NO,
    BILL_DTL_FMT_RCRD_TYP_CD
) VALUES (
    source.INTER_PLN_BILL_DTL_SK,
    source.INTER_PLN_BILL_DTL_ID,
    source.BUS_OWNER_ID,
    source.SRC_SYS_CD_SK,
    source.CRT_RUN_CYC_EXCTN_SK,
    source.LAST_UPDT_RUN_CYC_EXCTN_SK,
    source.MBR_SK,
    source.ATTRBTN_PGM_CD_SK,
    source.CFA_RMBRMT_TYP_CD_SK,
    source.CFA_TRANS_TYP_CD_SK,
    source.CTL_PLN_CD_SK,
    source.EPSD_TYP_CD_SK,
    source.HOME_CORP_PLN_CD_SK,
    source.HOME_PLN_CD_SK,
    source.HOST_CORP_PLN_CD_SK,
    source.HOST_PLN_CD_SK,
    source.LOCAL_PLN_CD_SK,
    source.VAL_BASED_PGM_CD_SK,
    source.VAL_BASED_PGM_PAYMT_TYP_CD_SK,
    source.BTCH_CRT_DT_SK,
    source.CBF_SETL_STRT_DT_SK,
    source.CBF_SETL_BILL_END_DT_SK,
    source.CFA_DISP_DT_SK,
    source.CFA_PRCS_DT_SK,
    source.HOME_AUTH_DENIAL_DT_SK,
    source.INCUR_PERD_STRT_DT_SK,
    source.INCUR_PERD_END_DT_SK,
    source.MSRMNT_PERD_STRT_DT_SK,
    source.MSRMNT_PERD_END_DT_SK,
    source.MBR_ELIG_STRT_DT_SK,
    source.MBR_ELIG_END_DT_SK,
    source.PRCS_CYC_YR_MO_SK,
    source.SETL_DT_SK,
    source.ACES_FEE_ADJ_AMT,
    source.CBF_SETL_RATE_AMT,
    source.MBR_LVL_CHRG_AMT,
    source.ATRBD_PROV_ID,
    source.ATRBD_PROV_NTNL_PROV_ID,
    source.ATTRBTN_PROV_PGM_NM,
    source.BCBSA_MMI_ID,
    source.CONSIS_MBR_ID,
    source.CBF_SCCF_NO,
    source.GRP_ID,
    source.HOME_PLN_MBR_ID,
    source.ITS_SUB_ID,
    source.ORIG_INTER_PLN_BILL_DTL_SRL_NO,
    source.ORIG_ITS_CLM_SCCF_NO,
    source.PROV_GRP_NM,
    source.VRNC_ACCT_ID,
    source.BTCH_STTUS_CD_TX,
    source.STTUS_CD_TX,
    source.ERR_CD_TX,
    source.POST_AS_EXP_IN,
    source.PRCS_CYC_DT_SK,
    source.VAL_BASED_PGM_ID,
    source.DSPTD_RCRD_CD,
    source.HOME_PLN_DSPT_ACTN_CD,
    source.CMNT_TX,
    source.HOST_PLN_DSPT_ACTN_CD,
    source.LOCAL_PLN_CTL_NO,
    source.PRCS_SITE_CTL_NO,
    source.BILL_DTL_FMT_RCRD_TYP_CD
);
""".format(owner=IDSOwner)

execute_dml(merge_sql_interplan_dup_load, jdbc_url_ids, jdbc_props_ids)