# Databricks notebook source
# MAGIC %md
# MAGIC **Date:** 2025-08-23
# MAGIC """
# MAGIC Â© Copyright 2021 Blue Cross and Blue Shield of Kansas City
# MAGIC 
# MAGIC Called by: IdsProviderMbrBioMesrRsltExtrSeq
# MAGIC                    
# MAGIC Job Name: CommonIdsLabSecondaryMbrMatch
# MAGIC Called By: CommonIdsLabRsltCntl
# MAGIC Purpose: This job takes the FORMAT.*.LAB*.TXT  file created by the CommonIdsLabRsltExtrFormatData job, does member matching logic compared to the IDS MBR table, and generates and updated version of the FORMAT.*.LAB*.TXT file to be read by the CommonIdsLabRsltExtr job.
# MAGIC                     
# MAGIC 
# MAGIC Control Job Rerun Information: 
# MAGIC                     Previous Run Successful:  Restore the source file before re-running the job
# MAGIC                     Previous Run Aborted: Restart, no other steps necessary  
# MAGIC Modifications:                        
# MAGIC \(9)\(9)\(9)\(9)\(9)PROJECT/\(9)\(9)\(9)\(9)\(9)\(9)\(9)\(9)\(9)DEVELOPMENT\(9)\(9)
# MAGIC DEVELOPER\(9)\(9)DATE\(9)\(9)STORY#\(9)\(9)CHANGE DESCRIPTION\(9)\(9)\(9)\(9)\(9)\(9)PROJECT\(9)\(9)\(9)CODE REVIEWER\(9)\(9)DATE REVIEWED
# MAGIC ==============================================================================================================================================================================================
# MAGIC Ken Bradmon\(9)\(9)2021-12-15\(9)us474125\(9)\(9)Original programming\(9)\(9)\(9)\(9)\(9)\(9)IntegrateDev2\(9)\(9)\(9)Abhiram Dasarathy\(9)\(9)2022-02-08
# MAGIC Ken Bradmon\(9)\(9)2021-12-15\(9)us474125\(9)\(9)Changed the name of the file read, and the file\(9)\(9)\(9)\(9)IntegrateDev2\(9)\(9)\(9)Abhiram Dasarathy\(9)\(9)2022-02-24
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)generated by this job.  Also changed the sizes of 
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)several columns so this job won't throw warnings if
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)a lab sends us a file with a value that is too long.  That
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)already gets handled by downstream job 
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)CommonIdsLabRsltExtrFormatData.
# MAGIC Ken Bradmon\(9)\(9)2023-07-07\(9)us542805\(9)\(9)Added MBR_UNIQ_KEY column to the output
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)file, as it is now needed by the CommonIdsLabRsltExtrFormatData job.\(9)\(9)IntegrateDev2\(9)\(9)\(9)Harsha Ravuri\(9)\(9)2023-08-03\(9)
# MAGIC Ken Bradmon\(9)\(9)2024-02-09\(9)us610327\(9)\(9)Removed member match levels 4, 5, 6, and 7.  Also added another column\(9)IntegrateDev2\(9)\(9)\(9)Harsha Ravuri\(9)\(9)2024-02-23\(9)\(9)
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)to the output file that tracks whether the member match was made at level 1,
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)level 2, or level 3 for every record.\(9)\(9)
# MAGIC Ken Bradmon\(9)\(9)2024-05-03\(9)us616253\(9)\(9)Added MBR_UNIQ_KEY to the stage variable svIsDuplicateRow.  This\(9)\(9)IntegrateDev2\(9)\(9)\(9)Harsha Ravuri\(9)\(9)2024-06-05
# MAGIC \(9)\(9)\(9)\(9)\(9)\(9)\(9)eliminates FALSE "too many member matches" errors.\(9)

# MAGIC Job Name: CommonIdsLabSecondaryMbrMatch
# MAGIC Called By: CommonIdsLabRsltCntl
# MAGIC Purpose: This job takes the Lab v4.3 file sent to us by the Providers, does member matching logic compared to the IDS MBR table, and generates and updated version of the Lab v4.3 file to be read by the CommonIdsLabRsltExtrFormatData job.
# MAGIC In this case we don't want the ones that match in the lookup, so \"rejects\" are good.  The records that matched by the Lookup stage are duplicates.
# MAGIC This is a original source LAB file from the provider.
# MAGIC The DeDupe stage removes duplicates based on:
# MAGIC + ACESION_NO
# MAGIC + POL_NO
# MAGIC + RSLT_DT
# MAGIC + PATN_LAST_NM
# MAGIC + PATN_FIRST_NM
# MAGIC + DOB
# MAGIC + LOINC_CD
# MAGIC + RSLT_NM
# MAGIC + RSLT_VAL_NUM
# MAGIC + RSLT_VAL_TXT
# MAGIC The member's first and last names need to be converted to 50 characters each, to match the FORMAT.*.LAB* file.
# MAGIC One row, per patient
# MAGIC This is the edited source LAB file:
# MAGIC /ids/prod/landing
# MAGIC <PROVIDER>.LAB.CCYYMMDDhhmmss.TXTMBRMATCHFINAL
# MAGIC /ids/prod/verified/
# MAGIC LAB.MEMBER_MATCH_ERRORS.CCYYMMhhmmss.TXT
# MAGIC There are 3 scenarios for Member Matching, to maximize the number of Lab records successfully matched to a single Member record from MBR_D.
# MAGIC Lab records that fail to match get sent to the Error file. Lab records that match more than one record from MBR_D also get sent to the Error file.
# MAGIC These are the source file records where all of the member matching levels 1 - 3 failed.
# MAGIC If we have more than one record "matched" from the MBR table, we want to sent ALL of those records written to the error file, not just one of them.
# MAGIC So the "IdentifyDuplicates" stage sends the dupes to the "Duplicates" stage, then the "LookupDupes" only sends the REJECTED (non-matching) rows to the "ClenseOutput" stage, and all the matches go to the "TooManyMatches" stage, and then the ErrorFile.
# MAGIC Unlike the first remove dupes step, this one does not include First Name, Last Name, or DOB, because the names might not match (like for example, twin babies).
# MAGIC These are records where the POL_NO does not match any SUB_ID in our IDS SUB table.
# MAGIC """
# COMMAND ----------
# MAGIC %run ../../../../../Routine_Functions
# COMMAND ----------
# Using the below functions as UDF(inherited from Routine_Functions notebook) instead of pyspark function
# 1) current_timestamp, current_date - To convert to CST timezone.
# 2) trim - To mimic Datastage behavior in trimming spaces within the string (Not leading or trailing spaces)
# COMMAND ----------
from pyspark.sql import functions as F
from pyspark.sql.types import StructType, StructField, StringType
from pyspark.sql.window import Window
# COMMAND ----------
# MAGIC %run ../../../../../Utility_Integrate
# COMMAND ----------


InFile = get_widget_value('InFile','')
ProviderName = get_widget_value('ProviderName','')
IDSOwner = get_widget_value('IDSOwner','')
RunID = get_widget_value('RunID','')
ids_secret_name = get_widget_value('ids_secret_name','')

# DB2ConnectorPX: SUB (Read from IDS)
jdbc_url_SUB, jdbc_props_SUB = get_db_config(ids_secret_name)
extract_query_SUB = f"SELECT upper(sub.SUB_ID) as SUB_ID\nFROM {IDSOwner}.SUB sub\n"
df_SUB = (
    spark.read.format("jdbc")
    .option("url", jdbc_url_SUB)
    .options(**jdbc_props_SUB)
    .option("query", extract_query_SUB)
    .load()
)

# PxSequentialFile: Raw_Lab_original
schema_Raw_Lab_original = StructType([
    StructField("RSLT_DT", StringType(), True),
    StructField("ACESION_NO", StringType(), True),
    StructField("LAB_CD", StringType(), True),
    StructField("PATN_LAST_NM", StringType(), True),
    StructField("PATN_FIRST_NM", StringType(), True),
    StructField("PATN_MID_NM", StringType(), True),
    StructField("DOB", StringType(), True),
    StructField("PATN_AGE", StringType(), True),
    StructField("GNDR", StringType(), True),
    StructField("VNDR_BILL_ID", StringType(), True),
    StructField("POL_NO", StringType(), True),
    StructField("ORDER_NTNL_PROV_ID", StringType(), True),
    StructField("ORDER_ACCT_NM", StringType(), True),
    StructField("RNDR_NTNL_PROV_ID", StringType(), True),
    StructField("ICD_VRSN", StringType(), True),
    StructField("DIAG_CD", StringType(), True),
    StructField("DIAG_CD_2", StringType(), True),
    StructField("DIAG_CD_3", StringType(), True),
    StructField("ORDER_NM", StringType(), True),
    StructField("LOCAL_ORDER_CD", StringType(), True),
    StructField("LOINC_CD", StringType(), True),
    StructField("RSLT_NM", StringType(), True),
    StructField("LOCAL_RSLT_CD", StringType(), True),
    StructField("RSLT_VAL_NUM", StringType(), True),
    StructField("RSLT_VAL_TEXT", StringType(), True),
    StructField("RSLT_UNIT", StringType(), True),
    StructField("ABNORM_FLAG", StringType(), True),
    StructField("MRN_ID", StringType(), True),
    StructField("SOURCE_ID", StringType(), True)
])

df_Raw_Lab_original = (
    spark.read.format("csv")
    .option("header", True)
    .option("delimiter", "|")
    .schema(schema_Raw_Lab_original)
    .load(f"{adls_path_raw}/landing/{InFile}")
)

# CTransformerStage: Cleanse
df_Cleanse = df_Raw_Lab_original \
    .withColumn(
        "RSLT_DT",
        F.when(
            (F.length(trim(F.col("RSLT_DT"))) == 0) | (F.col("RSLT_DT").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("RSLT_DT")))
    ).withColumn(
        "ACESION_NO",
        F.when(
            (F.length(trim(F.col("ACESION_NO"))) == 0) | (F.col("ACESION_NO").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("ACESION_NO")))
    ).withColumn(
        "LAB_CD",
        F.when(
            (F.length(trim(F.col("LAB_CD"))) == 0) | (F.col("LAB_CD").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("LAB_CD"))))
    ).withColumn(
        "PATN_LAST_NM",
        F.when(
            (F.length(trim(F.col("PATN_LAST_NM"))) == 0) | (F.col("PATN_LAST_NM").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("PATN_LAST_NM"))))
    ).withColumn(
        "PATN_FIRST_NM",
        F.when(
            (F.length(trim(F.col("PATN_FIRST_NM"))) == 0) | (F.col("PATN_FIRST_NM").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("PATN_FIRST_NM"))))
    ).withColumn(
        "PATN_MID_NM",
        F.when(
            (F.length(trim(F.col("PATN_MID_NM"))) == 0) | (F.col("PATN_MID_NM").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("PATN_MID_NM"))))
    ).withColumn(
        "DOB",
        F.when(
            (F.length(trim(F.col("DOB"))) == 0) | (F.col("DOB").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("DOB")))
    ).withColumn(
        "PATN_AGE",
        F.when(
            (F.length(trim(F.col("PATN_AGE"))) == 0) | (F.col("PATN_AGE").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("PATN_AGE")))
    ).withColumn(
        "GNDR",
        F.when(
            (F.length(trim(F.col("GNDR"))) == 0) | (F.col("GNDR").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("GNDR"))))
    ).withColumn(
        "VNDR_BILL_ID",
        F.when(
            (F.length(trim(F.col("VNDR_BILL_ID"))) == 0) | (F.col("VNDR_BILL_ID").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("VNDR_BILL_ID"))))
    ).withColumn(
        "POL_NO",
        F.when(
            (F.length(trim(F.col("POL_NO"))) == 0) | (F.col("POL_NO").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("POL_NO"))))
    ).withColumn(
        "ORDER_NTNL_PROV_ID",
        F.when(
            (F.length(trim(F.col("ORDER_NTNL_PROV_ID"))) == 0) | (F.col("ORDER_NTNL_PROV_ID").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("ORDER_NTNL_PROV_ID")))
    ).withColumn(
        "ORDER_ACCT_NM",
        F.when(
            (F.length(trim(F.col("ORDER_ACCT_NM"))) == 0) | (F.col("ORDER_ACCT_NM").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.regexp_replace(F.col("ORDER_ACCT_NM"), '"', ''))))
    ).withColumn(
        "RNDR_NTNL_PROV_ID",
        F.when(
            (F.length(trim(F.col("RNDR_NTNL_PROV_ID"))) == 0) | (F.col("RNDR_NTNL_PROV_ID").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("RNDR_NTNL_PROV_ID")))
    ).withColumn(
        "ICD_VRSN",
        F.when(
            (F.length(trim(F.col("ICD_VRSN"))) == 0) | (F.col("ICD_VRSN").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("ICD_VRSN"))))
    ).withColumn(
        "DIAG_CD",
        F.when(
            (F.length(trim(F.col("DIAG_CD"))) == 0) | (F.col("DIAG_CD").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("DIAG_CD"))))
    ).withColumn(
        "DIAG_CD_2",
        F.when(
            (F.length(trim(F.col("DIAG_CD_2"))) == 0) | (F.col("DIAG_CD_2").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("DIAG_CD_2"))))
    ).withColumn(
        "DIAG_CD_3",
        F.when(
            (F.length(trim(F.col("DIAG_CD_3"))) == 0) | (F.col("DIAG_CD_3").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("DIAG_CD_3"))))
    ).withColumn(
        "ORDER_NM",
        F.when(
            (F.length(trim(F.col("ORDER_NM"))) == 0) | (F.col("ORDER_NM").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("ORDER_NM")))
    ).withColumn(
        "LOCAL_ORDER_CD",
        F.when(
            (F.length(trim(F.col("LOCAL_ORDER_CD"))) == 0) | (F.col("LOCAL_ORDER_CD").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("LOCAL_ORDER_CD")))
    ).withColumn(
        "LOINC_CD",
        F.when(
            (F.length(trim(F.col("LOINC_CD"))) == 0) | (F.col("LOINC_CD").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("LOINC_CD")))
    ).withColumn(
        "RSLT_NM",
        F.when(
            (F.length(trim(F.col("RSLT_NM"))) == 0) | (F.col("RSLT_NM").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("RSLT_NM")))
    ).withColumn(
        "LOCAL_RSLT_CD",
        F.when(
            (F.length(trim(F.col("LOCAL_RSLT_CD"))) == 0) | (F.col("LOCAL_RSLT_CD").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("LOCAL_RSLT_CD"))))
    ).withColumn(
        "RSLT_VAL_NUM",
        F.when(
            (F.length(trim(F.col("RSLT_VAL_NUM"))) == 0) | (F.col("RSLT_VAL_NUM").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("RSLT_VAL_NUM"))))
    ).withColumn(
        "RSLT_VAL_TEXT",
        F.when(
            (F.length(trim(F.col("RSLT_VAL_TEXT"))) == 0) | (F.col("RSLT_VAL_TEXT").isNull()),
            F.lit("")
        ).otherwise(F.col("RSLT_VAL_TEXT").substr(1, 18))
    ).withColumn(
        "RSLT_UNIT",
        F.when(
            (F.length(trim(F.col("RSLT_UNIT"))) == 0) | (F.col("RSLT_UNIT").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("RSLT_UNIT")))
    ).withColumn(
        "ABNORM_FLAG",
        F.when(
            (F.length(trim(F.col("ABNORM_FLAG"))) == 0) | (F.col("ABNORM_FLAG").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("ABNORM_FLAG"))))
    ).withColumn(
        "MRN_ID",
        F.when(
            (F.length(trim(F.col("MRN_ID"))) == 0) | (F.col("MRN_ID").isNull()),
            F.lit("")
        ).otherwise(trim(F.col("MRN_ID")))
    ).withColumn(
        "SOURCE_ID",
        F.when(
            (F.length(trim(F.col("SOURCE_ID"))) == 0) | (F.col("SOURCE_ID").isNull()),
            F.lit("")
        ).otherwise(F.upper(trim(F.col("SOURCE_ID"))))
    )

# PxLookup: LookupSub (left join between Cleanse (primary) and SUB (lookup))
df_LookupSub_temp = df_Cleanse.alias("source").join(
    df_SUB.alias("IdsSub"),
    F.col("source.POL_NO") == F.col("IdsSub.SUB_ID"),
    "left"
)

df_LookupSub_match = df_LookupSub_temp.filter(F.col("IdsSub.SUB_ID").isNotNull())
df_NotOurMembers = df_LookupSub_temp.filter(F.col("IdsSub.SUB_ID").isNull())

df_LookupSub_sort = df_LookupSub_match.select(
    F.col("source.RSLT_DT").alias("RSLT_DT"),
    F.col("source.ACESION_NO").alias("ACESION_NO"),
    F.col("source.LAB_CD").alias("LAB_CD"),
    F.col("source.PATN_LAST_NM").alias("PATN_LAST_NM"),
    F.col("source.PATN_FIRST_NM").alias("PATN_FIRST_NM"),
    F.col("source.PATN_MID_NM").alias("PATN_MID_NM"),
    F.col("source.DOB").alias("DOB"),
    F.col("source.PATN_AGE").alias("PATN_AGE"),
    F.col("source.GNDR").alias("GNDR"),
    F.col("source.VNDR_BILL_ID").alias("VNDR_BILL_ID"),
    F.col("source.POL_NO").alias("POL_NO"),
    F.col("source.ORDER_NTNL_PROV_ID").alias("ORDER_NTNL_PROV_ID"),
    F.col("source.ORDER_ACCT_NM").alias("ORDER_ACCT_NM"),
    F.col("source.RNDR_NTNL_PROV_ID").alias("RNDR_NTNL_PROV_ID"),
    F.col("source.ICD_VRSN").alias("ICD_VRSN"),
    F.col("source.DIAG_CD").alias("DIAG_CD"),
    F.col("source.DIAG_CD_2").alias("DIAG_CD_2"),
    F.col("source.DIAG_CD_3").alias("DIAG_CD_3"),
    F.col("source.ORDER_NM").alias("ORDER_NM"),
    F.col("source.LOCAL_ORDER_CD").alias("LOCAL_ORDER_CD"),
    F.col("source.LOINC_CD").alias("LOINC_CD"),
    F.col("source.RSLT_NM").alias("RSLT_NM"),
    F.col("source.LOCAL_RSLT_CD").alias("LOCAL_RSLT_CD"),
    F.col("source.RSLT_VAL_NUM").alias("RSLT_VAL_NUM"),
    F.col("source.RSLT_VAL_TEXT").alias("RSLT_VAL_TEXT"),
    F.col("source.RSLT_UNIT").alias("RSLT_UNIT"),
    F.col("source.ABNORM_FLAG").alias("ABNORM_FLAG"),
    F.col("source.MRN_ID").alias("MRN_ID"),
    F.col("source.SOURCE_ID").alias("SOURCE_ID")
)

df_NotOurMembers_out = df_NotOurMembers.select(
    F.col("source.RSLT_DT"),
    F.col("source.ACESION_NO"),
    F.col("source.LAB_CD"),
    F.col("source.PATN_LAST_NM"),
    F.col("source.PATN_FIRST_NM"),
    F.col("source.PATN_MID_NM"),
    F.col("source.DOB"),
    F.col("source.PATN_AGE"),
    F.col("source.GNDR"),
    F.col("source.VNDR_BILL_ID"),
    F.col("source.POL_NO"),
    F.col("source.ORDER_NTNL_PROV_ID"),
    F.col("source.ORDER_ACCT_NM"),
    F.col("source.RNDR_NTNL_PROV_ID"),
    F.col("source.ICD_VRSN"),
    F.col("source.DIAG_CD"),
    F.col("source.DIAG_CD_2"),
    F.col("source.DIAG_CD_3"),
    F.col("source.ORDER_NM"),
    F.col("source.LOCAL_ORDER_CD"),
    F.col("source.LOINC_CD"),
    F.col("source.RSLT_NM"),
    F.col("source.LOCAL_RSLT_CD"),
    F.col("source.RSLT_VAL_NUM"),
    F.col("source.RSLT_VAL_TEXT"),
    F.col("source.RSLT_UNIT"),
    F.col("source.ABNORM_FLAG"),
    F.col("source.MRN_ID"),
    F.col("source.SOURCE_ID")
)

write_files(
    df_NotOurMembers_out,
    f"{adls_path}/verified/{ProviderName}.LAB.Member_Sub_IDs_Not_Found.{RunID}.TXT",
    delimiter="|",
    mode="overwrite",
    is_pqruet=False,
    header=True,
    quote='"',
    nullValue=None
)

# PxSort: SortFileRecords
df_SortFileRecords = df_LookupSub_sort.sort(
    "ACESION_NO", "POL_NO", "RSLT_DT", "PATN_LAST_NM", "PATN_FIRST_NM", "DOB", "LOINC_CD", "RSLT_NM", "RSLT_VAL_NUM", "RSLT_VAL_TEXT"
)

# CTransformerStage: DeDupe
# Implement row-by-row check with a window
w_DeDupe = Window.orderBy(
    "ACESION_NO", "POL_NO", "RSLT_DT", "PATN_LAST_NM", "PATN_FIRST_NM", "DOB", "LOINC_CD", "RSLT_NM", "RSLT_VAL_NUM", "RSLT_VAL_TEXT"
)
df_DeDupe_vars = df_SortFileRecords \
    .withColumn("prev_ACESION_NO", F.lag(F.col("ACESION_NO")).over(w_DeDupe)) \
    .withColumn("prev_POL_NO", F.lag(F.col("POL_NO")).over(w_DeDupe)) \
    .withColumn("prev_RSLT_DT", F.lag(F.col("RSLT_DT")).over(w_DeDupe)) \
    .withColumn("prev_PATN_LAST_NM", F.lag(F.col("PATN_LAST_NM")).over(w_DeDupe)) \
    .withColumn("prev_PATN_FIRST_NM", F.lag(F.col("PATN_FIRST_NM")).over(w_DeDupe)) \
    .withColumn("prev_DOB", F.lag(F.col("DOB")).over(w_DeDupe)) \
    .withColumn("prev_LOINC_CD", F.lag(F.col("LOINC_CD")).over(w_DeDupe)) \
    .withColumn("prev_RSLT_NM", F.lag(F.col("RSLT_NM")).over(w_DeDupe)) \
    .withColumn("prev_RSLT_VAL_NUM", F.lag(F.col("RSLT_VAL_NUM")).over(w_DeDupe)) \
    .withColumn("prev_RSLT_VAL_TEXT", F.lag(F.col("RSLT_VAL_TEXT")).over(w_DeDupe))

df_DeDupe_mark = df_DeDupe_vars.withColumn(
    "svIsDupeRow",
    F.when(
        (F.col("ACESION_NO") == F.col("prev_ACESION_NO")) &
        (F.col("POL_NO") == F.col("prev_POL_NO")) &
        (F.col("RSLT_DT") == F.col("prev_RSLT_DT")) &
        (F.col("PATN_LAST_NM") == F.col("prev_PATN_LAST_NM")) &
        (F.col("PATN_FIRST_NM") == F.col("prev_PATN_FIRST_NM")) &
        (F.col("DOB") == F.col("prev_DOB")) &
        (F.col("LOINC_CD") == F.col("prev_LOINC_CD")) &
        (F.col("RSLT_NM") == F.col("prev_RSLT_NM")) &
        (F.col("RSLT_VAL_NUM") == F.col("prev_RSLT_VAL_NUM")) &
        (F.col("RSLT_VAL_TEXT") == F.col("prev_RSLT_VAL_TEXT")),
        F.lit("Y")
    ).otherwise(F.lit("N"))
)

# Stage variables for DeDupe
df_DeDupe_withVars = df_DeDupe_mark \
    .withColumn("svLastNameTrunc", F.col("PATN_LAST_NM").substr(1, 3)) \
    .withColumn("svFirstNameTrunc", F.col("PATN_FIRST_NM").substr(1, 3)) \
    .withColumn("svFirstInitial", F.col("PATN_FIRST_NM").substr(1, 1)) \
    .withColumn(
        "svYearOfBirth",
        F.when(F.length(F.col("DOB")) == 0, F.lit("")).otherwise(F.col("DOB").substr(1, 4))
    )

df_DeDupe_cleansed = df_DeDupe_withVars.filter(F.col("svIsDupeRow") == "N")
df_DeDupe_dupeRows = df_DeDupe_withVars.filter(F.col("svIsDupeRow") == "Y")

df_DeDupe_cleansed_out = df_DeDupe_cleansed.select(
    F.col("RSLT_DT"),
    F.col("ACESION_NO"),
    F.col("LAB_CD"),
    F.col("PATN_LAST_NM").substr(1,75).alias("LoadFile_PATN_LAST_NM"),
    F.col("PATN_FIRST_NM").substr(1,35).alias("LoadFile_PATN_FIRST_NM"),
    F.col("PATN_MID_NM").substr(1,50).alias("LoadFile_PATN_MID_NM"),
    F.col("DOB").alias("LoadFile_DOB"),
    F.col("PATN_AGE"),
    F.col("GNDR").alias("LoadFile_GNDR"),
    F.col("VNDR_BILL_ID"),
    F.col("POL_NO").alias("LoadFile_POL_NO"),
    F.col("ORDER_NTNL_PROV_ID"),
    F.col("ORDER_ACCT_NM"),
    F.col("RNDR_NTNL_PROV_ID"),
    F.col("ICD_VRSN"),
    F.col("DIAG_CD"),
    F.col("DIAG_CD_2"),
    F.col("DIAG_CD_3"),
    F.col("ORDER_NM"),
    F.col("LOCAL_ORDER_CD"),
    F.col("LOINC_CD"),
    F.col("RSLT_NM"),
    F.col("LOCAL_RSLT_CD"),
    F.col("RSLT_VAL_NUM"),
    F.col("RSLT_VAL_TEXT"),
    F.col("RSLT_UNIT"),
    F.col("ABNORM_FLAG"),
    F.col("MRN_ID"),
    F.col("svFirstNameTrunc").alias("LoadFile_FirstNameTrunc"),
    F.col("svLastNameTrunc").alias("LoadFile_LastNameTrunc"),
    F.col("svFirstInitial").alias("LoadFile_FirstInitial"),
    F.col("svYearOfBirth").alias("LoadFile_YearOfBirth"),
    F.col("SOURCE_ID").alias("LoadFile_SOURCE_ID")
)

df_DeDupe_dupeRows_out = df_DeDupe_dupeRows.select(
    F.col("RSLT_DT"),
    F.col("ACESION_NO"),
    F.col("LAB_CD"),
    F.when(
        (F.length(trim(F.col("PATN_LAST_NM"))) == 0),
        F.lit("")
    ).otherwise(F.upper(trim(F.col("PATN_LAST_NM")))).alias("PATN_LAST_NM"),
    F.when(
        (F.length(trim(F.col("PATN_FIRST_NM"))) == 0),
        F.lit("")
    ).otherwise(F.upper(trim(F.col("PATN_FIRST_NM").substr(1,35)))).alias("PATN_FIRST_NM"),
    F.upper(F.col("PATN_MID_NM")).alias("PATN_MID_NM"),
    F.when(
        (F.length(trim(F.col("DOB"))) == 0),
        F.lit("")
    ).otherwise(trim(F.col("DOB"))).alias("DOB"),
    F.col("PATN_AGE"),
    F.col("GNDR"),
    F.col("VNDR_BILL_ID"),
    F.col("POL_NO"),
    F.col("ORDER_NTNL_PROV_ID"),
    F.col("ORDER_ACCT_NM"),
    F.col("RNDR_NTNL_PROV_ID"),
    F.col("ICD_VRSN"),
    F.col("DIAG_CD"),
    F.col("DIAG_CD_2"),
    F.col("DIAG_CD_3"),
    F.col("ORDER_NM"),
    F.col("LOCAL_ORDER_CD"),
    F.col("LOINC_CD"),
    F.col("RSLT_NM"),
    F.col("LOCAL_RSLT_CD"),
    F.col("RSLT_VAL_NUM"),
    F.col("RSLT_VAL_TEXT"),
    F.col("RSLT_UNIT"),
    F.col("ABNORM_FLAG"),
    F.col("MRN_ID"),
    F.col("SOURCE_ID")
)

# PxSequentialFile: DupeRowsFile
write_files(
    df_DeDupe_dupeRows_out,
    f"{adls_path}/verified/{ProviderName}.LAB.Duplicate_Rows_In_Source_File.{RunID}.TXT",
    delimiter="|",
    mode="overwrite",
    is_pqruet=False,
    header=True,
    quote='"',
    nullValue=None
)

# DB2ConnectorPX: MBR (Read from IDS)
jdbc_url_MBR, jdbc_props_MBR = get_db_config(ids_secret_name)
extract_query_MBR = (
    f"SELECT DISTINCT \n   upper(sub.SUB_ID) as SUB_ID\n   ,upper(mbr.LAST_NM) as LAST_NM\n   ,upper(mbr.FIRST_NM) as FIRST_NM\n   ,mbr.BRTH_DT_SK\n   ,mbr.MBR_UNIQ_KEY\n"
    f"FROM {IDSOwner}.MBR mbr,\n              {IDSOwner}.SUB sub\n"
    f"WHERE mbr.SUB_SK = sub.SUB_SK\n-- *** this is only for testing ***\n--AND sub.SUB_ID = '05K034881'\n"
)
df_MBR = (
    spark.read.format("jdbc")
    .option("url", jdbc_url_MBR)
    .options(**jdbc_props_MBR)
    .option("query", extract_query_MBR)
    .load()
)

# CTransformerStage: TruncNames
df_TruncNames_vars = df_MBR \
    .withColumn("svLastNameTrunc", F.upper(trim(F.col("LAST_NM"))).substr(1,3)) \
    .withColumn("svFirstNameTrunc", F.upper(trim(F.col("FIRST_NM"))).substr(1,3)) \
    .withColumn("svFirstInitial", F.upper(trim(F.col("FIRST_NM"))).substr(1,1)) \
    .withColumn(
        "svYearOfBirth",
        F.col("BRTH_DT_SK").substr(1,4)
    ) \
    .withColumn(
        "svDOB",
        F.when(
            trim(F.col("BRTH_DT_SK")) == F.lit("NA"),
            F.lit("")
        ).otherwise(
            F.when(
                trim(F.col("BRTH_DT_SK")) == F.lit("UNK"),
                F.lit("")
            ).otherwise(
                F.regexp_replace(trim(F.col("BRTH_DT_SK")), "-", "")
            )
        )
    )

df_TruncNames_Level1 = df_TruncNames_vars.select(
    F.when(F.length(F.col("SUB_ID")) == 0, F.lit("")).otherwise(F.col("SUB_ID")).alias("MBR_SUB_ID"),
    F.col("LAST_NM").substr(1,50).alias("MBR_LAST_NM"),
    F.col("FIRST_NM").alias("MBR_FIRST_NM"),
    F.col("svDOB").alias("MBR_BRTH_DT_SK"),
    F.col("MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY")
)

df_TruncNames_Level2 = df_TruncNames_vars.select(
    F.when(F.length(F.col("SUB_ID")) == 0, F.lit("")).otherwise(F.col("SUB_ID")).alias("MBR_SUB_ID"),
    F.col("LAST_NM").substr(1,50).alias("MBR_LAST_NM"),
    F.col("FIRST_NM").alias("MBR_FIRST_NM"),
    F.col("svDOB").alias("MBR_BRTH_DT_SK"),
    F.col("svFirstNameTrunc").alias("MBR_FirstNameTrunc"),
    F.col("MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY")
)

df_TruncNames_Level3 = df_TruncNames_vars.select(
    F.when(F.length(F.col("SUB_ID")) == 0, F.lit("")).otherwise(F.col("SUB_ID")).alias("MBR_SUB_ID"),
    F.col("LAST_NM").substr(1,50).alias("MBR_LAST_NM"),
    F.col("FIRST_NM").alias("MBR_FIRST_NM"),
    F.col("svDOB").alias("MBR_BRTH_DT_SK"),
    F.col("svLastNameTrunc").alias("MBR_LastNameTrunc"),
    F.col("svFirstNameTrunc").alias("MBR_FirstNameTrunc"),
    F.col("MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY")
)

# Lookup1: left join primary = df_DeDupe_cleansed_out as cleansed, ref = df_TruncNames_Level1 as Level1
df_Lookup1_temp = df_DeDupe_cleansed_out.alias("cleansed").join(
    df_TruncNames_Level1.alias("Level1"),
    (
        (F.col("cleansed.LoadFile_POL_NO") == F.col("Level1.MBR_SUB_ID")) &
        (F.col("cleansed.LoadFile_PATN_LAST_NM") == F.col("Level1.MBR_LAST_NM")) &
        (F.col("cleansed.LoadFile_PATN_FIRST_NM") == F.col("Level1.MBR_FIRST_NM")) &
        (F.col("cleansed.LoadFile_DOB") == F.col("Level1.MBR_BRTH_DT_SK"))
    ),
    "left"
)

# matched => "lookup1", unmatched => "rej1"
df_Lookup1_match = df_Lookup1_temp.filter(F.col("Level1.MBR_SUB_ID").isNotNull())
df_Lookup1_rej = df_Lookup1_temp.filter(F.col("Level1.MBR_SUB_ID").isNull())

df_Lookup1 = df_Lookup1_match.select(
    F.col("cleansed.RSLT_DT").alias("RSLT_DT"),
    F.col("cleansed.ACESION_NO").alias("ACESION_NO"),
    F.col("cleansed.LAB_CD").alias("LAB_CD"),
    F.col("Level1.MBR_LAST_NM").alias("PATN_LAST_NM"),
    F.col("Level1.MBR_FIRST_NM").alias("PATN_FIRST_NM"),
    F.col("cleansed.LoadFile_PATN_MID_NM").alias("PATN_MID_NM"),
    F.col("Level1.MBR_BRTH_DT_SK").alias("DOB"),
    F.col("cleansed.PATN_AGE").alias("PATN_AGE"),
    F.col("cleansed.LoadFile_GNDR").alias("GNDR"),
    F.col("cleansed.VNDR_BILL_ID").alias("VNDR_BILL_ID"),
    F.col("cleansed.LoadFile_POL_NO").alias("POL_NO"),
    F.col("cleansed.ORDER_NTNL_PROV_ID").alias("ORDER_NTNL_PROV_ID"),
    F.col("cleansed.ORDER_ACCT_NM").alias("ORDER_ACCT_NM"),
    F.col("cleansed.RNDR_NTNL_PROV_ID").alias("RNDR_NTNL_PROV_ID"),
    F.col("cleansed.ICD_VRSN").alias("ICD_VRSN"),
    F.col("cleansed.DIAG_CD").alias("DIAG_CD"),
    F.col("cleansed.DIAG_CD_2").alias("DIAG_CD_2"),
    F.col("cleansed.DIAG_CD_3").alias("DIAG_CD_3"),
    F.col("cleansed.ORDER_NM").alias("ORDER_NM"),
    F.col("cleansed.LOCAL_ORDER_CD").alias("LOCAL_ORDER_CD"),
    F.col("cleansed.LOINC_CD").alias("LOINC_CD"),
    F.col("cleansed.RSLT_NM").alias("RSLT_NM"),
    F.col("cleansed.LOCAL_RSLT_CD").alias("LOCAL_RSLT_CD"),
    F.col("cleansed.RSLT_VAL_NUM").alias("RSLT_VAL_NUM"),
    F.col("cleansed.RSLT_VAL_TEXT").alias("RSLT_VAL_TEXT"),
    F.col("cleansed.RSLT_UNIT").alias("RSLT_UNIT"),
    F.col("cleansed.ABNORM_FLAG").alias("ABNORM_FLAG"),
    F.col("cleansed.MRN_ID").alias("MRN_ID"),
    F.col("cleansed.LoadFile_FirstNameTrunc").alias("LoadFile_FirstNameTrunc"),
    F.col("cleansed.LoadFile_LastNameTrunc").alias("LoadFile_LastNameTrunc"),
    F.col("cleansed.LoadFile_FirstInitial").alias("LoadFile_FirstInitial"),
    F.col("cleansed.LoadFile_YearOfBirth").alias("LoadFile_YearOfBirth"),
    F.col("cleansed.LoadFile_SOURCE_ID").alias("SOURCE_ID"),
    F.col("Level1.MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY")
)

df_Lookup1_rej_out = df_Lookup1_rej.select(
    F.col("cleansed.RSLT_DT").alias("RSLT_DT"),
    F.col("cleansed.ACESION_NO").alias("ACESION_NO"),
    F.col("cleansed.LAB_CD").alias("LAB_CD"),
    F.col("cleansed.LoadFile_PATN_LAST_NM").substr(1,75).alias("LoadFile_PATN_LAST_NM"),
    F.col("cleansed.LoadFile_PATN_FIRST_NM").substr(1,35).alias("LoadFile_PATN_FIRST_NM"),
    F.col("cleansed.LoadFile_PATN_MID_NM").substr(1,50).alias("LoadFile_PATN_MID_NM"),
    F.col("cleansed.LoadFile_DOB").alias("LoadFile_DOB"),
    F.col("cleansed.PATN_AGE").alias("PATN_AGE"),
    F.col("cleansed.LoadFile_GNDR").alias("LoadFile_GNDR"),
    F.col("cleansed.VNDR_BILL_ID").alias("VNDR_BILL_ID"),
    F.col("cleansed.LoadFile_POL_NO").alias("LoadFile_POL_NO"),
    F.col("cleansed.ORDER_NTNL_PROV_ID").alias("ORDER_NTNL_PROV_ID"),
    F.col("cleansed.ORDER_ACCT_NM").alias("ORDER_ACCT_NM"),
    F.col("cleansed.RNDR_NTNL_PROV_ID").alias("RNDR_NTNL_PROV_ID"),
    F.col("cleansed.ICD_VRSN").alias("ICD_VRSN"),
    F.col("cleansed.DIAG_CD").alias("DIAG_CD"),
    F.col("cleansed.DIAG_CD_2").alias("DIAG_CD_2"),
    F.col("cleansed.DIAG_CD_3").alias("DIAG_CD_3"),
    F.col("cleansed.ORDER_NM").alias("ORDER_NM"),
    F.col("cleansed.LOCAL_ORDER_CD").alias("LOCAL_ORDER_CD"),
    F.col("cleansed.LOINC_CD").alias("LOINC_CD"),
    F.col("cleansed.RSLT_NM").alias("RSLT_NM"),
    F.col("cleansed.LOCAL_RSLT_CD").alias("LOCAL_RSLT_CD"),
    F.col("cleansed.RSLT_VAL_NUM").alias("RSLT_VAL_NUM"),
    F.col("cleansed.RSLT_VAL_TEXT").alias("RSLT_VAL_TEXT"),
    F.col("cleansed.RSLT_UNIT").alias("RSLT_UNIT"),
    F.col("cleansed.ABNORM_FLAG").alias("ABNORM_FLAG"),
    F.col("cleansed.MRN_ID").alias("MRN_ID"),
    F.col("cleansed.LoadFile_FirstNameTrunc").alias("LoadFile_FirstNameTrunc"),
    F.col("cleansed.LoadFile_LastNameTrunc").alias("LoadFile_LastNameTrunc"),
    F.col("cleansed.LoadFile_FirstInitial").alias("LoadFile_FirstInitial"),
    F.col("cleansed.LoadFile_YearOfBirth").alias("LoadFile_YearOfBirth"),
    F.col("cleansed.LoadFile_SOURCE_ID").alias("LoadFile_SOURCE_ID")
)

# Lookup2: left join primary = df_Lookup1_rej_out as rej1, ref = df_TruncNames_Level2 as Level2
df_Lookup2_temp = df_Lookup1_rej_out.alias("rej1").join(
    df_TruncNames_Level2.alias("Level2"),
    (
        (F.col("rej1.LoadFile_POL_NO") == F.col("Level2.MBR_SUB_ID")) &
        (F.col("rej1.LoadFile_PATN_LAST_NM") == F.col("Level2.MBR_LAST_NM")) &
        (F.col("rej1.LoadFile_DOB") == F.col("Level2.MBR_BRTH_DT_SK")) &
        (F.col("rej1.LoadFile_FirstNameTrunc") == F.col("Level2.MBR_FirstNameTrunc"))
    ),
    "left"
)

# matched => "lookup2", unmatched => "rej2"
df_Lookup2_match = df_Lookup2_temp.filter(F.col("Level2.MBR_SUB_ID").isNotNull())
df_Lookup2_rej = df_Lookup2_temp.filter(F.col("Level2.MBR_SUB_ID").isNull())

df_Lookup2 = df_Lookup2_match.select(
    F.col("rej1.RSLT_DT").alias("RSLT_DT"),
    F.col("rej1.ACESION_NO").alias("ACESION_NO"),
    F.col("rej1.LAB_CD").alias("LAB_CD"),
    F.col("Level2.MBR_LAST_NM").alias("PATN_LAST_NM"),
    F.col("Level2.MBR_FIRST_NM").alias("PATN_FIRST_NM"),
    F.col("rej1.LoadFile_PATN_MID_NM").alias("PATN_MID_NM"),
    F.col("Level2.MBR_BRTH_DT_SK").alias("DOB"),
    F.col("rej1.PATN_AGE").alias("PATN_AGE"),
    F.col("rej1.LoadFile_GNDR").alias("GNDR"),
    F.col("rej1.VNDR_BILL_ID").alias("VNDR_BILL_ID"),
    F.col("rej1.LoadFile_POL_NO").alias("POL_NO"),
    F.col("rej1.ORDER_NTNL_PROV_ID").alias("ORDER_NTNL_PROV_ID"),
    F.col("rej1.ORDER_ACCT_NM").alias("ORDER_ACCT_NM"),
    F.col("rej1.RNDR_NTNL_PROV_ID").alias("RNDR_NTNL_PROV_ID"),
    F.col("rej1.ICD_VRSN").alias("ICD_VRSN"),
    F.col("rej1.DIAG_CD").alias("DIAG_CD"),
    F.col("rej1.DIAG_CD_2").alias("DIAG_CD_2"),
    F.col("rej1.DIAG_CD_3").alias("DIAG_CD_3"),
    F.col("rej1.ORDER_NM").alias("ORDER_NM"),
    F.col("rej1.LOCAL_ORDER_CD").alias("LOCAL_ORDER_CD"),
    F.col("rej1.LOINC_CD").alias("LOINC_CD"),
    F.col("rej1.RSLT_NM").alias("RSLT_NM"),
    F.col("rej1.LOCAL_RSLT_CD").alias("LOCAL_RSLT_CD"),
    F.col("rej1.RSLT_VAL_NUM").alias("RSLT_VAL_NUM"),
    F.col("rej1.RSLT_VAL_TEXT").alias("RSLT_VAL_TEXT"),
    F.col("rej1.RSLT_UNIT").alias("RSLT_UNIT"),
    F.col("rej1.ABNORM_FLAG").alias("ABNORM_FLAG"),
    F.col("rej1.MRN_ID").alias("MRN_ID"),
    F.col("rej1.LoadFile_FirstNameTrunc").alias("LoadFile_FirstNameTrunc"),
    F.col("rej1.LoadFile_LastNameTrunc").alias("LoadFile_LastNameTrunc"),
    F.col("rej1.LoadFile_FirstInitial").alias("LoadFile_FirstInitial"),
    F.col("rej1.LoadFile_YearOfBirth").alias("LoadFile_YearOfBirth"),
    F.col("rej1.LoadFile_SOURCE_ID").alias("SOURCE_ID"),
    F.col("Level2.MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY")
)

df_Lookup2_rej_out = df_Lookup2_rej.select(
    F.col("rej1.RSLT_DT").alias("RSLT_DT"),
    F.col("rej1.ACESION_NO").alias("ACESION_NO"),
    F.col("rej1.LAB_CD").alias("LAB_CD"),
    F.col("rej1.LoadFile_PATN_LAST_NM").substr(1,75).alias("LoadFile_PATN_LAST_NM"),
    F.col("rej1.LoadFile_PATN_FIRST_NM").substr(1,35).alias("LoadFile_PATN_FIRST_NM"),
    F.col("rej1.LoadFile_PATN_MID_NM").substr(1,50).alias("LoadFile_PATN_MID_NM"),
    F.col("rej1.LoadFile_DOB").alias("LoadFile_DOB"),
    F.col("rej1.PATN_AGE").alias("PATN_AGE"),
    F.col("rej1.LoadFile_GNDR").alias("LoadFile_GNDR"),
    F.col("rej1.VNDR_BILL_ID").alias("VNDR_BILL_ID"),
    F.col("rej1.LoadFile_POL_NO").alias("LoadFile_POL_NO"),
    F.col("rej1.ORDER_NTNL_PROV_ID").alias("ORDER_NTNL_PROV_ID"),
    F.col("rej1.ORDER_ACCT_NM").alias("ORDER_ACCT_NM"),
    F.col("rej1.RNDR_NTNL_PROV_ID").alias("RNDR_NTNL_PROV_ID"),
    F.col("rej1.ICD_VRSN").alias("ICD_VRSN"),
    F.col("rej1.DIAG_CD").alias("DIAG_CD"),
    F.col("rej1.DIAG_CD_2").alias("DIAG_CD_2"),
    F.col("rej1.DIAG_CD_3").alias("DIAG_CD_3"),
    F.col("rej1.ORDER_NM").alias("ORDER_NM"),
    F.col("rej1.LOCAL_ORDER_CD").alias("LOCAL_ORDER_CD"),
    F.col("rej1.LOINC_CD").alias("LOINC_CD"),
    F.col("rej1.RSLT_NM").alias("RSLT_NM"),
    F.col("rej1.LOCAL_RSLT_CD").alias("LOCAL_RSLT_CD"),
    F.col("rej1.RSLT_VAL_NUM").alias("RSLT_VAL_NUM"),
    F.col("rej1.RSLT_VAL_TEXT").alias("RSLT_VAL_TEXT"),
    F.col("rej1.RSLT_UNIT").alias("RSLT_UNIT"),
    F.col("rej1.ABNORM_FLAG").alias("ABNORM_FLAG"),
    F.col("rej1.MRN_ID").alias("MRN_ID"),
    F.col("rej1.LoadFile_FirstNameTrunc").alias("LoadFile_FirstNameTrunc"),
    F.col("rej1.LoadFile_LastNameTrunc").alias("LoadFile_LastNameTrunc"),
    F.col("rej1.LoadFile_FirstInitial").alias("LoadFile_FirstInitial"),
    F.col("rej1.LoadFile_YearOfBirth").alias("LoadFile_YearOfBirth"),
    F.col("rej1.LoadFile_SOURCE_ID").alias("LoadFile_SOURCE_ID")
)

# Lookup3: left join primary = df_Lookup2_rej_out as rej2, ref = df_TruncNames_Level3 as Level3
df_Lookup3_temp = df_Lookup2_rej_out.alias("rej2").join(
    df_TruncNames_Level3.alias("Level3"),
    (
        (F.col("rej2.LoadFile_POL_NO") == F.col("Level3.MBR_SUB_ID")) &
        (F.col("rej2.LoadFile_DOB") == F.col("Level3.MBR_BRTH_DT_SK")) &
        (F.col("rej2.LoadFile_LastNameTrunc") == F.col("Level3.MBR_LastNameTrunc")) &
        (F.col("rej2.LoadFile_FirstNameTrunc") == F.col("Level3.MBR_FirstNameTrunc"))
    ),
    "left"
)

# matched => "lookup3", unmatched => "rej3"
df_Lookup3_match = df_Lookup3_temp.filter(F.col("Level3.MBR_SUB_ID").isNotNull())
df_Lookup3_rej = df_Lookup3_temp.filter(F.col("Level3.MBR_SUB_ID").isNull())

df_Lookup3 = df_Lookup3_match.select(
    F.col("rej2.RSLT_DT").alias("RSLT_DT"),
    F.col("rej2.ACESION_NO").alias("ACESION_NO"),
    F.col("rej2.LAB_CD").alias("LAB_CD"),
    F.col("Level3.MBR_LAST_NM").alias("PATN_LAST_NM"),
    F.col("Level3.MBR_FIRST_NM").alias("PATN_FIRST_NM"),
    F.col("rej2.LoadFile_PATN_MID_NM").alias("PATN_MID_NM"),
    F.col("Level3.MBR_BRTH_DT_SK").alias("DOB"),
    F.col("rej2.PATN_AGE").alias("PATN_AGE"),
    F.col("rej2.LoadFile_GNDR").alias("GNDR"),
    F.col("rej2.VNDR_BILL_ID").alias("VNDR_BILL_ID"),
    F.col("rej2.LoadFile_POL_NO").alias("POL_NO"),
    F.col("rej2.ORDER_NTNL_PROV_ID").alias("ORDER_NTNL_PROV_ID"),
    F.col("rej2.ORDER_ACCT_NM").alias("ORDER_ACCT_NM"),
    F.col("rej2.RNDR_NTNL_PROV_ID").alias("RNDR_NTNL_PROV_ID"),
    F.col("rej2.ICD_VRSN").alias("ICD_VRSN"),
    F.col("rej2.DIAG_CD").alias("DIAG_CD"),
    F.col("rej2.DIAG_CD_2").alias("DIAG_CD_2"),
    F.col("rej2.DIAG_CD_3").alias("DIAG_CD_3"),
    F.col("rej2.ORDER_NM").alias("ORDER_NM"),
    F.col("rej2.LOCAL_ORDER_CD").alias("LOCAL_ORDER_CD"),
    F.col("rej2.LOINC_CD").alias("LOINC_CD"),
    F.col("rej2.RSLT_NM").alias("RSLT_NM"),
    F.col("rej2.LOCAL_RSLT_CD").alias("LOCAL_RSLT_CD"),
    F.col("rej2.RSLT_VAL_NUM").alias("RSLT_VAL_NUM"),
    F.col("rej2.RSLT_VAL_TEXT").alias("RSLT_VAL_TEXT"),
    F.col("rej2.RSLT_UNIT").alias("RSLT_UNIT"),
    F.col("rej2.ABNORM_FLAG").alias("ABNORM_FLAG"),
    F.col("rej2.MRN_ID").alias("MRN_ID"),
    F.col("rej2.LoadFile_FirstNameTrunc").alias("LoadFile_FirstNameTrunc"),
    F.col("rej2.LoadFile_LastNameTrunc").alias("LoadFile_LastNameTrunc"),
    F.col("rej2.LoadFile_FirstInitial").alias("LoadFile_FirstInitial"),
    F.col("rej2.LoadFile_YearOfBirth").alias("LoadFile_YearOfBirth"),
    F.col("rej2.LoadFile_SOURCE_ID").alias("SOURCE_ID"),
    F.col("Level3.MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY")
)

df_Lookup3_rej_out = df_Lookup3_rej.select(
    F.col("rej2.LoadFile_POL_NO").alias("POL_NO"),
    F.col("rej2.LoadFile_PATN_LAST_NM").alias("PATN_LAST_NM"),
    F.col("rej2.LoadFile_PATN_FIRST_NM").alias("PATN_FIRST_NM"),
    F.col("rej2.LoadFile_DOB").alias("DOB"),
    F.lit("All Member Matches Failed").alias("ErrorReason"),
    F.lit("None").alias("MemberMatchLevel")
)

# RejReason3 => pass df_Lookup3_rej_out
df_RejReason3 = df_Lookup3_rej_out.select(
    F.col("POL_NO"),
    F.col("PATN_LAST_NM"),
    F.col("PATN_FIRST_NM"),
    F.col("DOB"),
    F.col("ErrorReason").alias("ErrorReason"),
    F.col("MemberMatchLevel").alias("MemberMatchLevel")
)

# Transformer1 => just adds "MemberMatchLevel" = 'Level One'
df_Transformer1 = df_Lookup1.select(
    "*",
    F.lit("Level One").alias("MemberMatchLevel")
)

# Transformer2 => just adds "MemberMatchLevel" = 'Level Two'
df_Transformer2 = df_Lookup2.select(
    "*",
    F.lit("Level Two").alias("MemberMatchLevel")
)

# Transformer3 => just adds "MemberMatchLevel" = 'Level Three'
df_Transformer3 = df_Lookup3.select(
    "*",
    F.lit("Level Three").alias("MemberMatchLevel")
)

# FunnelMatches => union of levelOne, levelTwo, levelThree
df_FunnelMatches = df_Transformer1.unionByName(df_Transformer2).unionByName(df_Transformer3)

# SortFunRecs => sort by: ACESION_NO, POL_NO, MBR_UNIQ_KEY, RSLT_DT, LOINC_CD, RSLT_NM, RSLT_VAL_NUM, RSLT_VAL_TEXT
df_SortFunRecs = df_FunnelMatches.sort(
    "ACESION_NO","POL_NO","MBR_UNIQ_KEY","RSLT_DT","LOINC_CD","RSLT_NM","RSLT_VAL_NUM","RSLT_VAL_TEXT"
)

# Next => passes all columns forward => rename as df_CountRows_input
df_CountRows_input = df_SortFunRecs

# CountRows => row-by-row check for duplicates
w_CountRows = Window.orderBy("ACESION_NO","POL_NO","MBR_UNIQ_KEY","RSLT_DT","LOINC_CD","RSLT_NM","RSLT_VAL_NUM","RSLT_VAL_TEXT")
df_CountRows_vars = df_CountRows_input \
    .withColumn("prev_ACESION_NO", F.lag(F.col("ACESION_NO")).over(w_CountRows)) \
    .withColumn("prev_POL_NO", F.lag(F.col("POL_NO")).over(w_CountRows)) \
    .withColumn("prev_MBR_UNIQ_KEY", F.lag(F.col("MBR_UNIQ_KEY")).over(w_CountRows)) \
    .withColumn("prev_RSLT_DT", F.lag(F.col("RSLT_DT")).over(w_CountRows)) \
    .withColumn("prev_LOINC_CD", F.lag(F.col("LOINC_CD")).over(w_CountRows)) \
    .withColumn("prev_RSLT_NM", F.lag(F.col("RSLT_NM")).over(w_CountRows)) \
    .withColumn("prev_RSLT_VAL_NUM", F.lag(F.col("RSLT_VAL_NUM")).over(w_CountRows)) \
    .withColumn("prev_RSLT_VAL_TEXT", F.lag(F.col("RSLT_VAL_TEXT")).over(w_CountRows))

df_CountRows_mark = df_CountRows_vars.withColumn(
    "svIsDuplicateRow",
    F.when(
        (F.col("ACESION_NO") == F.col("prev_ACESION_NO")) &
        (F.col("POL_NO") == F.col("prev_POL_NO")) &
        (F.col("MBR_UNIQ_KEY") == F.col("prev_MBR_UNIQ_KEY")) &
        (F.col("RSLT_DT") == F.col("prev_RSLT_DT")) &
        (F.col("LOINC_CD") == F.col("prev_LOINC_CD")) &
        (F.col("RSLT_NM") == F.col("prev_RSLT_NM")) &
        (F.col("RSLT_VAL_NUM") == F.col("prev_RSLT_VAL_NUM")) &
        (F.col("RSLT_VAL_TEXT") == F.col("prev_RSLT_VAL_TEXT")),
        F.lit("Y")
    ).otherwise(F.lit("N"))
)

df_CountRows_out = df_CountRows_mark.select(
    F.col("RSLT_DT"),
    F.col("ACESION_NO"),
    F.col("LAB_CD"),
    F.col("PATN_LAST_NM"),
    F.col("PATN_FIRST_NM"),
    F.col("PATN_MID_NM"),
    F.col("DOB"),
    F.col("PATN_AGE"),
    F.col("GNDR"),
    F.col("VNDR_BILL_ID"),
    F.col("POL_NO"),
    F.col("ORDER_NTNL_PROV_ID"),
    F.col("ORDER_ACCT_NM"),
    F.col("RNDR_NTNL_PROV_ID"),
    F.col("ICD_VRSN"),
    F.col("DIAG_CD"),
    F.col("DIAG_CD_2"),
    F.col("DIAG_CD_3"),
    F.col("ORDER_NM"),
    F.col("LOCAL_ORDER_CD"),
    F.col("LOINC_CD"),
    F.col("RSLT_NM"),
    F.col("LOCAL_RSLT_CD"),
    F.col("RSLT_VAL_NUM"),
    F.col("RSLT_VAL_TEXT"),
    F.col("RSLT_UNIT"),
    F.col("ABNORM_FLAG"),
    F.col("MRN_ID"),
    F.col("SOURCE_ID"),
    F.col("MBR_UNIQ_KEY"),
    F.col("svIsDuplicateRow").alias("IS_DUPLICATE_ROW"),
    F.col("MemberMatchLevel")
)

# IdentifyDuplicates => separate duplicates
df_IdentifyDuplicates_dupes = df_CountRows_out.filter(F.col("IS_DUPLICATE_ROW") == "Y")
df_IdentifyDuplicates_keep = df_CountRows_out.filter(F.col("IS_DUPLICATE_ROW") != "Y")

df_Duplicates_out = df_IdentifyDuplicates_dupes.select(
    F.col("ACESION_NO"),
    F.col("POL_NO"),
    F.col("PATN_LAST_NM"),
    F.col("PATN_FIRST_NM"),
    F.col("DOB")
)

df_SubtractDupes_out = df_IdentifyDuplicates_keep.select(
    F.col("RSLT_DT"),
    F.col("ACESION_NO"),
    F.col("LAB_CD"),
    F.col("PATN_LAST_NM"),
    F.col("PATN_FIRST_NM"),
    F.col("PATN_MID_NM"),
    F.col("DOB"),
    F.col("PATN_AGE"),
    F.col("GNDR"),
    F.col("VNDR_BILL_ID"),
    F.col("POL_NO"),
    F.col("ORDER_NTNL_PROV_ID"),
    F.col("ORDER_ACCT_NM"),
    F.col("RNDR_NTNL_PROV_ID"),
    F.col("ICD_VRSN"),
    F.col("DIAG_CD"),
    F.col("DIAG_CD_2"),
    F.col("DIAG_CD_3"),
    F.col("ORDER_NM"),
    F.col("LOCAL_ORDER_CD"),
    F.col("LOINC_CD"),
    F.col("RSLT_NM"),
    F.col("LOCAL_RSLT_CD"),
    F.col("RSLT_VAL_NUM"),
    F.col("RSLT_VAL_TEXT"),
    F.col("RSLT_UNIT"),
    F.col("ABNORM_FLAG"),
    F.col("MRN_ID"),
    F.col("SOURCE_ID"),
    F.col("MBR_UNIQ_KEY"),
    F.col("MemberMatchLevel")
)

# Duplicates => sort unique -> output all
df_Duplicates_unique = df_Duplicates_out.dropDuplicates(["ACESION_NO","POL_NO"])

# pass forward
df_Duplicates_unique_out = df_Duplicates_unique.select(
    F.col("ACESION_NO").alias("ACESION_NO"),
    F.col("POL_NO").alias("POL_NO"),
    F.col("PATN_LAST_NM"),
    F.col("PATN_FIRST_NM"),
    F.col("DOB")
)

# LookupDupes => left join primary = SubtractDupes, reference = Duplicates
df_LookupDupes_temp = df_SubtractDupes_out.alias("SubtractDupes").join(
    df_Duplicates_unique_out.alias("dupes2"),
    (
        (F.col("SubtractDupes.ACESION_NO") == F.col("dupes2.ACESION_NO")) &
        (F.col("SubtractDupes.POL_NO") == F.col("dupes2.POL_NO"))
    ),
    "left"
)

df_LookupDupes_match = df_LookupDupes_temp.filter(F.col("dupes2.ACESION_NO").isNotNull())
df_LookupDupes_unmatched = df_LookupDupes_temp.filter(F.col("dupes2.ACESION_NO").isNull())

df_LookupDupes_AllTheDupes = df_LookupDupes_match.select(
    F.col("SubtractDupes.RSLT_DT"),
    F.col("SubtractDupes.ACESION_NO"),
    F.col("SubtractDupes.LAB_CD"),
    F.col("SubtractDupes.PATN_LAST_NM"),
    F.col("SubtractDupes.PATN_FIRST_NM"),
    F.col("SubtractDupes.PATN_MID_NM"),
    F.col("SubtractDupes.DOB"),
    F.col("SubtractDupes.PATN_AGE"),
    F.col("SubtractDupes.GNDR"),
    F.col("SubtractDupes.VNDR_BILL_ID"),
    F.col("SubtractDupes.POL_NO"),
    F.col("SubtractDupes.ORDER_NTNL_PROV_ID"),
    F.col("SubtractDupes.ORDER_ACCT_NM"),
    F.col("SubtractDupes.RNDR_NTNL_PROV_ID"),
    F.col("SubtractDupes.ICD_VRSN"),
    F.col("SubtractDupes.DIAG_CD"),
    F.col("SubtractDupes.DIAG_CD_2"),
    F.col("SubtractDupes.DIAG_CD_3"),
    F.col("SubtractDupes.ORDER_NM"),
    F.col("SubtractDupes.LOCAL_ORDER_CD"),
    F.col("SubtractDupes.LOINC_CD"),
    F.col("SubtractDupes.RSLT_NM"),
    F.col("SubtractDupes.LOCAL_RSLT_CD"),
    F.col("SubtractDupes.RSLT_VAL_NUM"),
    F.col("SubtractDupes.RSLT_VAL_TEXT"),
    F.col("SubtractDupes.RSLT_UNIT"),
    F.col("SubtractDupes.ABNORM_FLAG"),
    F.col("SubtractDupes.MRN_ID"),
    F.col("SubtractDupes.SOURCE_ID"),
    F.col("SubtractDupes.MBR_UNIQ_KEY"),
    F.col("SubtractDupes.MemberMatchLevel")
)

df_LookupDupes_output = df_LookupDupes_unmatched.select(
    F.col("SubtractDupes.RSLT_DT").alias("RSLT_DT"),
    F.col("SubtractDupes.ACESION_NO").alias("ACESION_NO"),
    F.col("SubtractDupes.LAB_CD").alias("LAB_CD"),
    F.col("SubtractDupes.PATN_LAST_NM").alias("PATN_LAST_NM"),
    F.col("SubtractDupes.PATN_FIRST_NM").alias("PATN_FIRST_NM"),
    F.col("SubtractDupes.PATN_MID_NM").alias("PATN_MID_NM"),
    F.col("SubtractDupes.DOB").alias("DOB"),
    F.col("SubtractDupes.PATN_AGE").alias("PATN_AGE"),
    F.col("SubtractDupes.GNDR").alias("GNDR"),
    F.col("SubtractDupes.VNDR_BILL_ID").alias("VNDR_BILL_ID"),
    F.col("SubtractDupes.POL_NO").alias("POL_NO"),
    F.col("SubtractDupes.ORDER_NTNL_PROV_ID").alias("ORDER_NTNL_PROV_ID"),
    F.col("SubtractDupes.ORDER_ACCT_NM").alias("ORDER_ACCT_NM"),
    F.col("SubtractDupes.RNDR_NTNL_PROV_ID").alias("RNDR_NTNL_PROV_ID"),
    F.col("SubtractDupes.ICD_VRSN").alias("ICD_VRSN"),
    F.col("SubtractDupes.DIAG_CD").alias("DIAG_CD"),
    F.col("SubtractDupes.DIAG_CD_2").alias("DIAG_CD_2"),
    F.col("SubtractDupes.DIAG_CD_3").alias("DIAG_CD_3"),
    F.col("SubtractDupes.ORDER_NM").alias("ORDER_NM"),
    F.col("SubtractDupes.LOCAL_ORDER_CD").alias("LOCAL_ORDER_CD"),
    F.col("SubtractDupes.LOINC_CD").alias("LOINC_CD"),
    F.col("SubtractDupes.RSLT_NM").alias("RSLT_NM"),
    F.col("SubtractDupes.LOCAL_RSLT_CD").alias("LOCAL_RSLT_CD"),
    F.col("SubtractDupes.RSLT_VAL_NUM").alias("RSLT_VAL_NUM"),
    F.col("SubtractDupes.RSLT_VAL_TEXT").alias("RSLT_VAL_TEXT"),
    F.col("SubtractDupes.RSLT_UNIT").alias("RSLT_UNIT"),
    F.col("SubtractDupes.ABNORM_FLAG").alias("ABNORM_FLAG"),
    F.col("SubtractDupes.MRN_ID").alias("MRN_ID"),
    F.col("SubtractDupes.SOURCE_ID").alias("SOURCE_ID"),
    F.col("SubtractDupes.MBR_UNIQ_KEY").alias("MBR_UNIQ_KEY"),
    F.col("SubtractDupes.MemberMatchLevel").alias("MemberMatchLevel")
)

# TooManyMatches => unique sorted => error link
df_TooManyMatches_unique = df_LookupDupes_AllTheDupes.dropDuplicates(["POL_NO","PATN_LAST_NM","PATN_FIRST_NM","DOB"])
df_TooManyMatches_out = df_TooManyMatches_unique.select(
    F.col("POL_NO"),
    F.col("PATN_LAST_NM"),
    F.col("PATN_FIRST_NM"),
    F.col("DOB"),
    F.lit("Too Many Member Matches").alias("ErrorReason"),
    F.col("MemberMatchLevel")
)

# FunnelErrors => union of TooManyMatches_out and RejReason3
df_FunnelErrors = df_TooManyMatches_out.unionByName(df_RejReason3)

df_FunnelErrors_result = df_FunnelErrors.select(
    F.col("POL_NO").alias("SUB_ID"),
    F.col("PATN_LAST_NM").alias("PATN_LAST_NM"),
    F.col("PATN_FIRST_NM").alias("PATN_FIRST_NM"),
    F.col("DOB").alias("DOB"),
    F.col("ErrorReason").alias("ErrorReason"),
    F.col("MemberMatchLevel").alias("MemberMatchLevel")
)

# PxSequentialFile: ErrorFile
write_files(
    df_FunnelErrors_result,
    f"{adls_path}/verified/{ProviderName}.LAB.MEMBER_MATCH_ERRORS.{RunID}.TXT",
    delimiter="|",
    mode="overwrite",
    is_pqruet=False,
    header=True,
    quote='"',
    nullValue=None
)

# ClenseOutput => pass output to LabFile
df_ClenseOutput = df_LookupDupes_output.select(
    F.col("RSLT_DT"),
    F.col("ACESION_NO"),
    F.col("LAB_CD"),
    F.col("PATN_LAST_NM"),
    F.col("PATN_FIRST_NM"),
    F.col("PATN_MID_NM"),
    F.col("DOB"),
    F.col("PATN_AGE"),
    F.col("GNDR"),
    F.col("VNDR_BILL_ID"),
    F.col("POL_NO"),
    F.col("ORDER_NTNL_PROV_ID"),
    F.col("ORDER_ACCT_NM"),
    F.col("RNDR_NTNL_PROV_ID"),
    F.col("ICD_VRSN"),
    F.col("DIAG_CD"),
    F.col("DIAG_CD_2"),
    F.col("DIAG_CD_3"),
    F.col("ORDER_NM"),
    F.col("LOCAL_ORDER_CD"),
    F.col("LOINC_CD"),
    F.col("RSLT_NM"),
    F.col("LOCAL_RSLT_CD"),
    F.col("RSLT_VAL_NUM"),
    F.col("RSLT_VAL_TEXT"),
    F.col("RSLT_UNIT"),
    F.col("ABNORM_FLAG"),
    F.col("MRN_ID"),
    F.col("SOURCE_ID"),
    F.col("MBR_UNIQ_KEY"),
    F.col("MemberMatchLevel")
)

# PxSequentialFile: LabFile
write_files(
    df_ClenseOutput,
    f"{adls_path_raw}/landing/{InFile}_MBRMATCHFINAL",
    delimiter="|",
    mode="overwrite",
    is_pqruet=False,
    header=True,
    quote='"',
    nullValue=None
)