from: il
to: adf
generateComments: false
translations:
  defaultDb: azure
  expr:
    snow: snow
  exprsql:
    snow: snow
  exprcf:
    snow: snow
  sql:
    teradata2: snow
    mssql: snow
    db2: snow
    plsql: snow
    netezza2: snow

optimize:
  removeProjectLevelParams: true
meta:
  shellActivity:
    useDBNotebook: true

