#!/bin/zsh

src="$1"
base=$(basename "$src")
fn="${base/.dsx/}"
dst="py/$fn.py"
il="il/${base/.dsx/.il}"
logdir=/tmp/bluekc/logs
mkdir -p $logdir
il_log="$logdir/${base/.dsx/.il.log}"
py_log="$logdir/${base/.dsx/.py.log}"
res=adf
mkdir -p adf/json
mkdir model
json_log="$logdir/${base/.dsx/.json.log}"

java -XX:+UseSerialGC -Dlog.level=info -jar $SHIFT_JAR --input "$src" --output "$il" --config.name ../il-config.yml 2>&1 > "$il_log"

java -XX:+UseSerialGC -Dlog.level=info -jar $SHIFT_JAR --input "$il" --output "$dst" --config.name ../adf-config.yml --modelFile "model/$fn.il"  2>&1 > "$py_log"

python3 "$dst" --config ../py-json.config --log=DEBUG --output "$res" 2>"$json_log" > "$json_log"

