import React, { useState, useEffect } from 'react';
import {
  Box,
  Paper,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Button,
  Chip,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Tooltip,
  Card,
  CardContent,
  Grid,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Stack,
  Alert,
  LinearProgress,
  Avatar,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  Divider,
  Badge,
  InputAdornment,
  Tabs,
  Tab,
  Collapse,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  TablePagination,
  Menu,
  MenuList,
  ListItemButton,
} from '@mui/material';
import {
  Add,
  Reply,
  CheckCircle,
  Warning,
  Error as ErrorIcon,
  Search,
  FilterList,
  Assignment,
  Person,
  CalendarToday,
  Download,
  Print,
  Visibility,
  Edit,
  Close as CloseIcon,
  ExpandMore,
  AssignmentTurnedIn,
  HelpOutline,
  Schedule,
  Send,
  History,
  Comment,
  Info,
  PlayArrow,
  Check,
  Block,
  Assessment,
  Group,
  TrendingUp,
  Build,
  LocalHospital,
  Science,
  Refresh,
} from '@mui/icons-material';

interface Query {
  id: string;
  queryId: string;
  studyId: string;
  studyName: string;
  subjectId: string;
  visitName: string;
  formName: string;
  fieldName: string;
  fieldValue: string;
  queryText: string;
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  status: 'OPEN' | 'ASSIGNED' | 'ANSWERED' | 'REVIEWED' | 'CLOSED';
  raisedBy: string;
  raisedByRole: string;
  assignedTo: string;
  assignedToRole: string;
  createdDate: string;
  lastUpdated: string;
  responses: QueryResponse[];
  daysOpen: number;
  isAutoGenerated: boolean;
  closureReason?: string;
}

interface QueryResponse {
  id: string;
  responseText: string;
  respondedBy: string;
  respondedByRole: string;
  responseDate: string;
  responseType: 'RESPONSE' | 'CLOSURE' | 'ASSIGNMENT';
}

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function TabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;
  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`query-tabpanel-${index}`}
      aria-labelledby={`query-tab-${index}`}
      {...other}
    >
      {value === index && <Box sx={{ p: 3 }}>{children}</Box>}
    </div>
  );
}

const QueryManagement: React.FC = () => {
  const [queries, setQueries] = useState<Query[]>([]);
  const [selectedQuery, setSelectedQuery] = useState<Query | null>(null);
  const [detailDialogOpen, setDetailDialogOpen] = useState(false);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [responseDialogOpen, setResponseDialogOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [tabValue, setTabValue] = useState(0);
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(10);
  
  // State for dropdowns
  const [studies, setStudies] = useState<any[]>([]);
  const [subjects, setSubjects] = useState<any[]>([]);
  
  // Filters
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [severityFilter, setSeverityFilter] = useState('all');
  const [studyFilter, setStudyFilter] = useState('all');
  const [raisedByFilter, setRaisedByFilter] = useState('all');

  // New query form
  const [newQuery, setNewQuery] = useState({
    studyId: '',
    subjectId: '',
    visitName: '',
    formName: '',
    fieldName: '',
    queryText: '',
    severity: 'MEDIUM' as const,
    assignedTo: '',
  });

  // Response form
  const [responseText, setResponseText] = useState('');
  const [closureReason, setClosureReason] = useState('');

  // Fetch queries function
  const fetchQueries = async () => {
    try {
      setLoading(true);
      const response = await fetch('/api/queries');
      
      if (!response.ok) {
        throw new Error('Failed to fetch queries');
      }
      
      const data = await response.json();
      
      // Transform API data to match component interface with bulletproof null safety
      const transformedQueries: Query[] = (data.data || []).map((query: any) => ({
        id: String(query?.id || ''),
        queryId: String(query?.id || 'UNKNOWN'),
        studyId: String(query?.study_id || ''),
        studyName: String(query?.edc_studies?.title || 'Unknown Study'),
        siteId: String(query?.site_id || ''),
        siteName: String(query?.edc_sites?.name || 'Unknown Site'),
        subjectId: String(query?.subject_id || ''),
        formName: String(query?.edc_forms?.form_name || 'Unknown Form'),
        fieldName: String(query?.field_name || ''),
        visitName: 'Visit',
        queryType: String(query?.query_type || 'MANUAL'),
        priority: String(query?.priority || 'MEDIUM'),
        status: String(query?.status || 'OPEN'),
        queryText: String(query?.query_text || ''),
        description: String(query?.query_text || 'No description available'),
        raisedBy: String((query?.raised_by_user?.first_name || '') + ' ' + (query?.raised_by_user?.last_name || '')).trim() || 'System',
        assignedTo: String(query?.assigned_to || 'Unassigned'),
        raisedDate: String(query?.created_at || ''),
        dueDate: String(query?.due_date || ''),
        resolvedDate: String(query?.resolved_date || ''),
        responses: [], // Always empty array - no undefined possible
        isAutoGenerated: Boolean(query?.auto_generated || false),
      }));
      
      setQueries(transformedQueries);
    } catch (error) {
      console.error('Error fetching queries:', error);
      setQueries([]);
    } finally {
      setLoading(false);
    }
  };

  // Fetch studies function
  const fetchStudies = async () => {
    try {
      const response = await fetch('/api/studies');
      if (response.ok) {
        const data = await response.json();
        setStudies(data.data || []);
      }
    } catch (error) {
      console.error('Error fetching studies:', error);
      setStudies([]);
    }
  };

  // Fetch subjects function (filtered by study if selected)
  const fetchSubjects = async (studyId?: string) => {
    try {
      const url = studyId ? `/api/subjects?study_id=${studyId}` : '/api/subjects';
      const response = await fetch(url);
      if (response.ok) {
        const data = await response.json();
        setSubjects(data.data || []);
      }
    } catch (error) {
      console.error('Error fetching subjects:', error);
      setSubjects([]);
    }
  };

  useEffect(() => {
    fetchQueries();
    fetchStudies();
    fetchSubjects(); // Fetch all subjects initially
  }, []);

  // When study selection changes, fetch subjects for that study
  const handleStudyChange = (studyId: string) => {
    setNewQuery({ ...newQuery, studyId, subjectId: '' }); // Clear subject selection
    if (studyId) {
      fetchSubjects(studyId);
    } else {
      setSubjects([]);
    }
  };

  // Removed mock data - using only real database queries

  // Get query counts by status
  const getQueryCounts = () => {
    return {
      total: queries.length,
      open: queries.filter(q => q.status === 'OPEN').length,
      assigned: queries.filter(q => q.status === 'ASSIGNED').length,
      answered: queries.filter(q => q.status === 'ANSWERED').length,
      reviewed: queries.filter(q => q.status === 'REVIEWED').length,
      closed: queries.filter(q => q.status === 'CLOSED').length,
    };
  };

  const counts = getQueryCounts();

  // Filter queries
  const filteredQueries = queries.filter(query => {
    const matchesSearch = 
      (query.queryId || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (query.subjectId || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (query.formName || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (query.fieldName || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (query.queryText || '').toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesStatus = statusFilter === 'all' || query.status === statusFilter;
    const matchesSeverity = severityFilter === 'all' || query.severity === severityFilter;
    
    return matchesSearch && matchesStatus && matchesSeverity;
  });

  // Get severity color
  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'CRITICAL': return 'error';
      case 'HIGH': return 'warning';
      case 'MEDIUM': return 'info';
      case 'LOW': return 'default';
      default: return 'default';
    }
  };

  // Get status color
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'OPEN': return 'error';
      case 'ASSIGNED': return 'warning';
      case 'ANSWERED': return 'info';
      case 'REVIEWED': return 'primary';
      case 'CLOSED': return 'success';
      default: return 'default';
    }
  };

  // Handle view query details
  const handleViewQuery = (query: Query) => {
    setSelectedQuery(query);
    setDetailDialogOpen(true);
  };

  // Handle create new query
  const handleCreateQuery = async () => {
    // Create query via API call to database
    try {
      const response = await fetch('/api/queries', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          study_id: newQuery.studyId,
          subject_id: newQuery.subjectId,
          field_name: newQuery.fieldName,
          query_text: newQuery.queryText,
          severity: newQuery.severity,
          priority: 'MEDIUM',
          raised_by: 'b73c7f9f-3802-48b9-9b39-50ab242db83b', // Default user ID for now
          assigned_to: null, // Will implement user dropdown later
          query_type: 'MANUAL'
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to create query');
      }

      const result = await response.json();
      console.log('Query created successfully:', result);
      
      // Refresh queries list to show the new query
      await fetchQueries();
    } catch (error) {
      console.error('Error creating query:', error);
      // Continue with dialog close even if there's an error
    }
    setCreateDialogOpen(false);
    setNewQuery({
      studyId: '',
      subjectId: '',
      visitName: '',
      formName: '',
      fieldName: '',
      queryText: '',
      severity: 'MEDIUM',
      assignedTo: '',
    });
  };

  // Handle respond to query
  const handleRespondToQuery = () => {
    if (!selectedQuery || !responseText.trim()) return;

    const response: QueryResponse = {
      id: `R${(selectedQuery.responses || []).length + 1}`,
      responseText: responseText.trim(),
      respondedBy: 'Current User',
      respondedByRole: 'CRC',
      responseDate: new Date().toISOString(),
      responseType: 'RESPONSE',
    };

    const updatedQuery = {
      ...selectedQuery,
      status: 'ANSWERED' as const,
      responses: [...(selectedQuery.responses || []), response],
      lastUpdated: new Date().toISOString(),
    };

    setQueries(queries.map(q => q.id === selectedQuery.id ? updatedQuery : q));
    setSelectedQuery(updatedQuery);
    setResponseText('');
    setResponseDialogOpen(false);
  };

  // Handle close query
  const handleCloseQuery = () => {
    if (!selectedQuery || !closureReason.trim()) return;

    const response: QueryResponse = {
      id: `R${(selectedQuery.responses || []).length + 1}`,
      responseText: closureReason.trim(),
      respondedBy: 'Current User',
      respondedByRole: 'DM',
      responseDate: new Date().toISOString(),
      responseType: 'CLOSURE',
    };

    const updatedQuery = {
      ...selectedQuery,
      status: 'CLOSED' as const,
      responses: [...(selectedQuery.responses || []), response],
      lastUpdated: new Date().toISOString(),
      closureReason: closureReason.trim(),
    };

    setQueries(queries.map(q => q.id === selectedQuery.id ? updatedQuery : q));
    setSelectedQuery(updatedQuery);
    setClosureReason('');
  };

  if (loading) {
    return (
      <Box sx={{ p: 3 }}>
        <LinearProgress />
        <Typography sx={{ mt: 2 }}>Loading queries...</Typography>
      </Box>
    );
  }

  return (
    <Box>
      {/* Header */}
      <Box sx={{ mb: 3, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Box>
          <Typography variant="h4" gutterBottom>
            Query Management
          </Typography>
          <Typography variant="subtitle1" color="text.secondary">
            Manage data queries, validations, and responses across all studies
          </Typography>
        </Box>
        <Stack direction="row" spacing={2}>
          <Button
            variant="outlined"
            startIcon={<Refresh />}
            onClick={fetchQueries}
          >
            Refresh
          </Button>
          <Button
            variant="contained"
            startIcon={<Add />}
            onClick={() => setCreateDialogOpen(true)}
            sx={{
              background: 'linear-gradient(45deg, #FE6B8B 30%, #FF8E53 90%)',
              boxShadow: '0 3px 5px 2px rgba(255, 105, 135, .3)',
            }}
          >
            Raise Manual Query
          </Button>
        </Stack>
      </Box>

      {/* Statistics Cards */}
      <Grid container spacing={3} sx={{ mb: 3 }}>
        <Grid item xs={12} md={2.4}>
          <Card sx={{ background: 'linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%)', color: 'white' }}>
            <CardContent>
              <Stack direction="row" justifyContent="space-between" alignItems="center">
                <Box>
                  <Typography color="inherit" gutterBottom sx={{ opacity: 0.8 }}>
                    Open
                  </Typography>
                  <Typography variant="h4">{counts.open}</Typography>
                </Box>
                <Avatar sx={{ bgcolor: 'rgba(255,255,255,0.2)' }}>
                  <ErrorIcon />
                </Avatar>
              </Stack>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={2.4}>
          <Card sx={{ background: 'linear-gradient(135deg, #ffa726 0%, #ff9800 100%)', color: 'white' }}>
            <CardContent>
              <Stack direction="row" justifyContent="space-between" alignItems="center">
                <Box>
                  <Typography color="inherit" gutterBottom sx={{ opacity: 0.8 }}>
                    Assigned
                  </Typography>
                  <Typography variant="h4">{counts.assigned}</Typography>
                </Box>
                <Avatar sx={{ bgcolor: 'rgba(255,255,255,0.2)' }}>
                  <PlayArrow />
                </Avatar>
              </Stack>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={2.4}>
          <Card sx={{ background: 'linear-gradient(135deg, #42a5f5 0%, #2196f3 100%)', color: 'white' }}>
            <CardContent>
              <Stack direction="row" justifyContent="space-between" alignItems="center">
                <Box>
                  <Typography color="inherit" gutterBottom sx={{ opacity: 0.8 }}>
                    Answered
                  </Typography>
                  <Typography variant="h4">{counts.answered}</Typography>
                </Box>
                <Avatar sx={{ bgcolor: 'rgba(255,255,255,0.2)' }}>
                  <Reply />
                </Avatar>
              </Stack>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={2.4}>
          <Card sx={{ background: 'linear-gradient(135deg, #ab47bc 0%, #9c27b0 100%)', color: 'white' }}>
            <CardContent>
              <Stack direction="row" justifyContent="space-between" alignItems="center">
                <Box>
                  <Typography color="inherit" gutterBottom sx={{ opacity: 0.8 }}>
                    Reviewed
                  </Typography>
                  <Typography variant="h4">{counts.reviewed}</Typography>
                </Box>
                <Avatar sx={{ bgcolor: 'rgba(255,255,255,0.2)' }}>
                  <Assessment />
                </Avatar>
              </Stack>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={2.4}>
          <Card sx={{ background: 'linear-gradient(135deg, #66bb6a 0%, #4caf50 100%)', color: 'white' }}>
            <CardContent>
              <Stack direction="row" justifyContent="space-between" alignItems="center">
                <Box>
                  <Typography color="inherit" gutterBottom sx={{ opacity: 0.8 }}>
                    Closed
                  </Typography>
                  <Typography variant="h4">{counts.closed}</Typography>
                </Box>
                <Avatar sx={{ bgcolor: 'rgba(255,255,255,0.2)' }}>
                  <CheckCircle />
                </Avatar>
              </Stack>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Filters */}
      <Paper sx={{ p: 2, mb: 3 }}>
        <Grid container spacing={2} alignItems="center">
          <Grid item xs={12} md={3}>
            <TextField
              fullWidth
              size="small"
              placeholder="Search queries..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <Search />
                  </InputAdornment>
                ),
              }}
            />
          </Grid>
          <Grid item xs={12} md={2}>
            <FormControl fullWidth size="small">
              <InputLabel>Status</InputLabel>
              <Select
                value={statusFilter}
                label="Status"
                onChange={(e) => setStatusFilter(e.target.value)}
              >
                <MenuItem value="all">All Status</MenuItem>
                <MenuItem value="OPEN">Open</MenuItem>
                <MenuItem value="ASSIGNED">Assigned</MenuItem>
                <MenuItem value="ANSWERED">Answered</MenuItem>
                <MenuItem value="REVIEWED">Reviewed</MenuItem>
                <MenuItem value="CLOSED">Closed</MenuItem>
              </Select>
            </FormControl>
          </Grid>
          <Grid item xs={12} md={2}>
            <FormControl fullWidth size="small">
              <InputLabel>Severity</InputLabel>
              <Select
                value={severityFilter}
                label="Severity"
                onChange={(e) => setSeverityFilter(e.target.value)}
              >
                <MenuItem value="all">All Severity</MenuItem>
                <MenuItem value="CRITICAL">Critical</MenuItem>
                <MenuItem value="HIGH">High</MenuItem>
                <MenuItem value="MEDIUM">Medium</MenuItem>
                <MenuItem value="LOW">Low</MenuItem>
              </Select>
            </FormControl>
          </Grid>
          <Grid item xs={12} md={2}>
            <FormControl fullWidth size="small">
              <InputLabel>Study</InputLabel>
              <Select
                value={studyFilter}
                label="Study"
                onChange={(e) => setStudyFilter(e.target.value)}
              >
                <MenuItem value="all">All Studies</MenuItem>
                <MenuItem value="CARDIO-2024-001">Cardiovascular Trial</MenuItem>
                <MenuItem value="ONCO-2024-002">Oncology Phase II</MenuItem>
              </Select>
            </FormControl>
          </Grid>
          <Grid item xs={12} md={2}>
            <Stack direction="row" spacing={1}>
              <Button startIcon={<Download />} size="small">Export</Button>
              <Button startIcon={<Print />} size="small">Print</Button>
            </Stack>
          </Grid>
          <Grid item xs={12} md={1}>
            <Typography variant="body2" color="text.secondary" textAlign="center">
              {filteredQueries.length} queries
            </Typography>
          </Grid>
        </Grid>
      </Paper>

      {/* Queries Table */}
      <Paper elevation={2}>
        <TableContainer>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell>Query Details</TableCell>
                <TableCell>Study/Subject</TableCell>
                <TableCell>Form/Field</TableCell>
                <TableCell>Value</TableCell>
                <TableCell>Severity</TableCell>
                <TableCell>Status</TableCell>
                <TableCell>Raised By</TableCell>
                <TableCell>Days Open</TableCell>
                <TableCell align="center">Actions</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {filteredQueries
                .slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
                .map((query) => (
                <TableRow key={query.id} hover>
                  <TableCell>
                    <Box>
                      <Typography variant="subtitle2" fontWeight={600} sx={{ mb: 0.5 }}>
                        {query.queryId}
                      </Typography>
                      <Typography variant="body2" sx={{ mb: 1 }}>
                        {query.queryText.length > 100 
                          ? `${query.queryText.substring(0, 100)}...` 
                          : query.queryText}
                      </Typography>
                      <Stack direction="row" spacing={1} alignItems="center">
                        {query.isAutoGenerated && (
                          <Chip label="Auto" size="small" variant="outlined" />
                        )}
                        <Chip 
                          label={`${(query.responses || []).length} responses`} 
                          size="small" 
                          color={(query.responses || []).length > 0 ? 'primary' : 'default'}
                        />
                      </Stack>
                    </Box>
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2" fontWeight={500}>
                      {query.studyName.substring(0, 25)}...
                    </Typography>
                    <Typography variant="caption" color="primary">
                      {query.subjectId}
                    </Typography>
                    <Typography variant="caption" display="block" color="text.secondary">
                      {query.visitName}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2" fontWeight={500}>
                      {query.formName}
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      {query.fieldName}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2" fontFamily="monospace">
                      {query.fieldValue}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Chip
                      label={query.severity}
                      color={getSeverityColor(query.severity) as any}
                      size="small"
                      icon={query.severity === 'CRITICAL' ? <ErrorIcon /> : 
                            query.severity === 'HIGH' ? <Warning /> : <Info />}
                    />
                  </TableCell>
                  <TableCell>
                    <Chip
                      label={query.status}
                      color={getStatusColor(query.status) as any}
                      size="small"
                    />
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2">
                      {query.raisedBy}
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      {query.raisedByRole}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2" color={query.daysOpen > 7 ? 'error' : 'text.primary'}>
                      {query.daysOpen} days
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Stack direction="row" spacing={1} justifyContent="center">
                      <Tooltip title="View Details">
                        <IconButton
                          size="small"
                          color="primary"
                          onClick={() => handleViewQuery(query)}
                        >
                          <Visibility />
                        </IconButton>
                      </Tooltip>
                      {query.status !== 'CLOSED' && (
                        <Tooltip title="Respond">
                          <IconButton
                            size="small"
                            color="secondary"
                            onClick={() => {
                              setSelectedQuery(query);
                              setResponseDialogOpen(true);
                            }}
                          >
                            <Reply />
                          </IconButton>
                        </Tooltip>
                      )}
                    </Stack>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
        <TablePagination
          rowsPerPageOptions={[5, 10, 25]}
          component="div"
          count={filteredQueries.length}
          rowsPerPage={rowsPerPage}
          page={page}
          onPageChange={(e, newPage) => setPage(newPage)}
          onRowsPerPageChange={(e) => {
            setRowsPerPage(parseInt(e.target.value, 10));
            setPage(0);
          }}
        />
      </Paper>

      {/* Query Detail Dialog */}
      <Dialog open={detailDialogOpen} onClose={() => setDetailDialogOpen(false)} maxWidth="lg" fullWidth>
        <DialogTitle>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <Box>
              <Typography variant="h6">
                Query Details: {selectedQuery?.queryId}
              </Typography>
              <Typography variant="body2" color="text.secondary">
                {selectedQuery?.studyName} | {selectedQuery?.subjectId} | {selectedQuery?.formName}
              </Typography>
            </Box>
            <Stack direction="row" spacing={1}>
              <Chip
                label={selectedQuery?.severity}
                color={getSeverityColor(selectedQuery?.severity || '') as any}
                size="small"
              />
              <Chip
                label={selectedQuery?.status}
                color={getStatusColor(selectedQuery?.status || '') as any}
                size="small"
              />
            </Stack>
          </Box>
        </DialogTitle>
        <DialogContent dividers>
          {selectedQuery && (
            <Grid container spacing={3}>
              <Grid item xs={12} md={8}>
                <Typography variant="h6" sx={{ mb: 2 }}>Query Information</Typography>
                <Card variant="outlined" sx={{ mb: 3 }}>
                  <CardContent>
                    <Typography variant="body1" sx={{ mb: 2 }}>
                      <strong>Query Text:</strong>
                    </Typography>
                    <Typography variant="body2" sx={{ mb: 2, p: 2, bgcolor: 'background.paper', borderRadius: 1 }}>
                      {selectedQuery.queryText}
                    </Typography>
                    <Grid container spacing={2}>
                      <Grid item xs={6}>
                        <Typography variant="body2">
                          <strong>Field Value:</strong> {selectedQuery.fieldValue}
                        </Typography>
                      </Grid>
                      <Grid item xs={6}>
                        <Typography variant="body2">
                          <strong>Days Open:</strong> {selectedQuery.daysOpen} days
                        </Typography>
                      </Grid>
                    </Grid>
                  </CardContent>
                </Card>

                <Typography variant="h6" sx={{ mb: 2 }}>Response History</Typography>
                {(selectedQuery.responses || []).length === 0 ? (
                  <Alert severity="info">No responses yet</Alert>
                ) : (
                  <List>
                    {(selectedQuery.responses || []).map((response, index) => (
                      <ListItem key={response.id} divider={index < (selectedQuery.responses || []).length - 1}>
                        <ListItemIcon>
                          {response.responseType === 'CLOSURE' ? <CheckCircle color="success" /> : <Reply />}
                        </ListItemIcon>
                        <ListItemText
                          primary={
                            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                              <Typography variant="subtitle2">
                                {response.respondedBy} ({response.respondedByRole})
                              </Typography>
                              <Typography variant="caption" color="text.secondary">
                                {new Date(response.responseDate).toLocaleString()}
                              </Typography>
                            </Box>
                          }
                          secondary={
                            <Typography variant="body2" sx={{ mt: 1 }}>
                              {response.responseText}
                            </Typography>
                          }
                        />
                      </ListItem>
                    ))}
                  </List>
                )}
              </Grid>
              <Grid item xs={12} md={4}>
                <Typography variant="h6" sx={{ mb: 2 }}>Context</Typography>
                <Card variant="outlined">
                  <CardContent>
                    <List dense>
                      <ListItem>
                        <ListItemIcon><Science /></ListItemIcon>
                        <ListItemText primary="Study" secondary={selectedQuery.studyName} />
                      </ListItem>
                      <ListItem>
                        <ListItemIcon><Person /></ListItemIcon>
                        <ListItemText primary="Subject" secondary={selectedQuery.subjectId} />
                      </ListItem>
                      <ListItem>
                        <ListItemIcon><CalendarToday /></ListItemIcon>
                        <ListItemText primary="Visit" secondary={selectedQuery.visitName} />
                      </ListItem>
                      <ListItem>
                        <ListItemIcon><Assignment /></ListItemIcon>
                        <ListItemText primary="Form" secondary={selectedQuery.formName} />
                      </ListItem>
                      <ListItem>
                        <ListItemIcon><Edit /></ListItemIcon>
                        <ListItemText primary="Field" secondary={selectedQuery.fieldName} />
                      </ListItem>
                    </List>
                  </CardContent>
                </Card>

                <Typography variant="h6" sx={{ mt: 3, mb: 2 }}>Assignment</Typography>
                <Card variant="outlined">
                  <CardContent>
                    <Typography variant="body2" sx={{ mb: 1 }}>
                      <strong>Raised by:</strong> {selectedQuery.raisedBy} ({selectedQuery.raisedByRole})
                    </Typography>
                    <Typography variant="body2" sx={{ mb: 1 }}>
                      <strong>Assigned to:</strong> {selectedQuery.assignedTo} ({selectedQuery.assignedToRole})
                    </Typography>
                    <Typography variant="body2">
                      <strong>Created:</strong> {new Date(selectedQuery.createdDate).toLocaleString()}
                    </Typography>
                  </CardContent>
                </Card>
              </Grid>
            </Grid>
          )}
        </DialogContent>
        <DialogActions>
          {selectedQuery?.status !== 'CLOSED' && (
            <>
              <Button
                onClick={() => {
                  setResponseDialogOpen(true);
                }}
                startIcon={<Reply />}
                variant="contained"
                color="primary"
              >
                Respond
              </Button>
              <Button
                onClick={() => {
                  setClosureReason('');
                  setDetailDialogOpen(false);
                }}
                startIcon={<CheckCircle />}
                variant="contained"
                color="success"
              >
                Close Query
              </Button>
            </>
          )}
          <Button onClick={() => setDetailDialogOpen(false)}>Close</Button>
        </DialogActions>
      </Dialog>

      {/* Create Query Dialog */}
      <Dialog open={createDialogOpen} onClose={() => setCreateDialogOpen(false)} maxWidth="md" fullWidth>
        <DialogTitle>Raise Manual Query</DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12} md={6}>
              <FormControl fullWidth>
                <InputLabel>Study</InputLabel>
                <Select
                  value={newQuery.studyId}
                  label="Study"
                  onChange={(e) => handleStudyChange(e.target.value)}
                >
                  <MenuItem value="">Select Study</MenuItem>
                  {studies.map((study) => (
                    <MenuItem key={study.id} value={study.id}>
                      {study.title} ({study.protocol_number})
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12} md={6}>
              <FormControl fullWidth>
                <InputLabel>Subject ID</InputLabel>
                <Select
                  value={newQuery.subjectId}
                  label="Subject ID"
                  onChange={(e) => setNewQuery({ ...newQuery, subjectId: e.target.value })}
                  disabled={!newQuery.studyId}
                >
                  <MenuItem value="">Select Subject</MenuItem>
                  {subjects.map((subject) => (
                    <MenuItem key={subject.id} value={subject.id}>
                      {subject.subject_number} - {subject.initials}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Visit Name"
                value={newQuery.visitName}
                onChange={(e) => setNewQuery({ ...newQuery, visitName: e.target.value })}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Form Name"
                value={newQuery.formName}
                onChange={(e) => setNewQuery({ ...newQuery, formName: e.target.value })}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="Field Name"
                value={newQuery.fieldName}
                onChange={(e) => setNewQuery({ ...newQuery, fieldName: e.target.value })}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <FormControl fullWidth>
                <InputLabel>Severity</InputLabel>
                <Select
                  value={newQuery.severity}
                  label="Severity"
                  onChange={(e) => setNewQuery({ ...newQuery, severity: e.target.value as any })}
                >
                  <MenuItem value="LOW">Low</MenuItem>
                  <MenuItem value="MEDIUM">Medium</MenuItem>
                  <MenuItem value="HIGH">High</MenuItem>
                  <MenuItem value="CRITICAL">Critical</MenuItem>
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Query Text"
                multiline
                rows={4}
                value={newQuery.queryText}
                onChange={(e) => setNewQuery({ ...newQuery, queryText: e.target.value })}
                helperText="Provide detailed information about the query"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Assign To"
                value={newQuery.assignedTo}
                onChange={(e) => setNewQuery({ ...newQuery, assignedTo: e.target.value })}
                helperText="Name of the person to assign this query to"
              />
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setCreateDialogOpen(false)}>Cancel</Button>
          <Button
            onClick={handleCreateQuery}
            variant="contained"
            disabled={!newQuery.studyId || !newQuery.subjectId || !newQuery.queryText}
            startIcon={<Send />}
          >
            Raise Query
          </Button>
        </DialogActions>
      </Dialog>

      {/* Response Dialog */}
      <Dialog open={responseDialogOpen} onClose={() => setResponseDialogOpen(false)} maxWidth="md" fullWidth>
        <DialogTitle>
          Respond to Query: {selectedQuery?.queryId}
        </DialogTitle>
        <DialogContent>
          <Alert severity="info" sx={{ mb: 2 }}>
            <Typography variant="body2">
              <strong>Query:</strong> {selectedQuery?.queryText}
            </Typography>
          </Alert>
          <TextField
            fullWidth
            label="Response"
            multiline
            rows={4}
            value={responseText}
            onChange={(e) => setResponseText(e.target.value)}
            placeholder="Enter your response to this query..."
            sx={{ mt: 2 }}
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setResponseDialogOpen(false)}>Cancel</Button>
          <Button
            onClick={handleRespondToQuery}
            variant="contained"
            disabled={!responseText.trim()}
            startIcon={<Send />}
          >
            Submit Response
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default QueryManagement;